### ISSUE TITLE
Knative release image use tag not sha

### ISSUE THREAD

**Issue by lou-lan** [knative/docs#1013]
## What is changing? (Please include as many details as possible.)
fix release yaml
```
gcr.io/knative-releases/github.com/knative/serving/cmd/queue@sha256:e19ca17d2b729904d2662a30b6c5c27cf4b62fd64baef2da4125525a4f9346e5
```
->
```
gcr.io/knative-releases/github.com/knative/serving/cmd/queue@v0.4.0
```

## How will this impact our users?
The speed is not ideal in some areas. 
```
rpc error: code = Unknown desc = Error response from daemon: Get http://gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

## In what release will this take happen (to the best of your knowledge)?
v0.4

**Comment by carieshmarie** [comment]
Looks like this is still an issue in the YAML files, now renamed by component. Ex: serving.yaml.

Marking this as a P3, but feel free to submit a PR to fix this issue. Thanks!
