### ISSUE TITLE
Move the community governance docs to a non-versioned new repo

### ISSUE THREAD

**Issue by rgregg** [knative/docs#1018]
Opening from #1017, to track separately from the core issue.

This will provide a single hub for this content, as well as issues related to the content, that is separate from the technical documentation and sample code that lives in the docs repo today.

As @RichieEscarez mentioned, having a non-versioned single source of truth for our governance and community organization content is another benefit of doing this, and something I strongly believe in as well.

**Comment by rgregg** [comment]
We should hold off on doing this change until #1017 is approved/rejected, so we can keep the history.

**Comment by rgregg** [comment]
Now that #1017 is done, we can proceed.

**Comment by RichieEscarez** [comment]
@rgregg is the focus of this new and separate repo solely focused on community governance?
Or, is this a repository that can also contain other non-versioned content, for example Blog posts? 
/cc @mchmarny

**Comment by rgregg** [comment]
I think we'd want to have a repo just for the community/governance stuff so that we can lock it down to only the steering committee members who have approval access.

For other non-versioned content, like the blog, we'll need to find another place for it.

**Comment by RichieEscarez** [comment]
This should be assigned to a member of Knative Admin. When the new repo is created Im happy to jump in and handle the file movement as well as update the build scripts.

**Comment by rgregg** [comment]
Yep. I've proposed this to the KSC, but we're waiting until we have all the vacant seats filled before we vote on anything new.

**Comment by RichieEscarez** [comment]
https://github.com/knative/community now exists!
