### ISSUE TITLE
broken buildpack Serving Samples (2) - buildpack.yaml 404

### ISSUE THREAD

**Issue by RichieEscarez** [knative/docs#1022]
## Expected Behavior
knative/build-templates/master/buildpack/buildpack.yaml exists

## Actual Behavior
Different files exist in that directory, you get a 404

The files have all been updated and changed:
https://github.com/knative/build-templates/pull/67

## Steps to Reproduce the Problem

Broken Serving samples:
1. https://github.com/knative/docs/tree/master/docs/serving/samples/buildpack-app-dotnet
2. https://github.com/knative/docs/tree/master/docs/serving/samples/buildpack-function-nodejs

**Comment by carieshmarie** [comment]
Jason - do these samples still exist? If so, can you let us know where they are? We're currently linking to the above samples from our docs.

**Comment by ImJasonH** [comment]
The buildpacks yaml was renamed to cnb.yaml: https://github.com/knative/build-templates/blob/master/buildpacks/cnb.yaml
