### ISSUE TITLE
Create "getting started" checklist for code contributors

### ISSUE THREAD

**Issue by samodell** [knative/docs#1032]
**Describe the change you'd like to see**
Create a "getting started" checklist for code contributors that encourages doc participation.

Right now, the contributing guide is a little intimidating; would be nice to pull together an easy path to contributing, and it's a good opportunity to encourage folks to get started with docs, as well as to check out the good-first-issue tags in the repos.

**Comment by RichieEscarez** [comment]
https://knative.dev/help/contributor/gettingstarted/
