### ISSUE TITLE
Eventing Kubernetes Event Source link is broken

### ISSUE THREAD

**Issue by kameshsampath** [knative/docs#1034]
The Kubernetes eventing source eventing sample  README in https://github.com/knative/eventing-sources/tree/master/samples/kubernetes-event-source shows deprecation notice with new url as https://github.com/knative/docs/tree/master/eventing/samples/kubernetes-event-source

## Expected Behavior
the user will be redirected to https://github.com/knative/docs/tree/master/eventing/samples/kubernetes-event-source

## Actual Behavior
HTTP 404 Page not found

## Steps to Reproduce the Problem

1. Open https://github.com/knative/eventing-sources/tree/master/samples/kubernetes-event-source
2. Click the link shown in deprecation notice

**Comment by samodell** [comment]
Umbrella issue for all external links to Docs repo: #1038
