### ISSUE TITLE
Find and correct links from other repos into Docs repo

### ISSUE THREAD

**Issue by samodell** [knative/docs#1038]
With the file restructure for the Docs website, all links pointing to specific pages/samples/etc. in the Docs repo from other Knative repos are now broken. These need to be found and fixed.

Work commenced after PR #1025 merged in.

- [x] Serving https://github.com/knative/serving/pull/3497
- [x] Build https://github.com/knative/build/pull/586
- [x] Eventing https://github.com/knative/eventing/pull/954
- [x] Eventing-sources https://github.com/knative/eventing-sources/pull/276
- [x] Client https://github.com/knative/client/pull/44
- [x] Docs repo #1072 
- [ ] https://github.com/knative/caching

**Comment by RichieEscarez** [comment]
Known file or folder changes:

- Add a "[docs](https://github.com/knative/docs/tree/master/docs)" folder in the root of knative/docs. The following content has been moved into the docs folder ([#1007](https://github.com/knative/docs/pull/1007)):
   - serving
   - build
   - eventing
   - reference
   - images
   - install
- Consolidate hello world samples into a "[hello-world](https://github.com/knative/docs/tree/27ef769fe36747f48ec7fee0cc8b3720bd63502d/docs/serving/samples/hello-world)" folder ([#1025](https://github.com/knative/docs/pull/1025)).
- Remove unnecessary ['fluentd'](https://github.com/knative/docs/pull/1025/commits/e07e6bb6be9e613f91ade810c75d668afdb1a736) folder ([#1025](https://github.com/knative/docs/pull/1025)).
  - Rename README.md to [fluentd-requirements.md](https://github.com/knative/docs/pull/1025/commits/e07e6bb6be9e613f91ade810c75d668afdb1a736#diff-9dde48379a1166eb1e839f87c29a7285)

**Comment by RichieEscarez** [comment]
https://github.com/knative/eventing-sources/pull/265
