### ISSUE TITLE
Proposed navigation for knative.dev/docs

### ISSUE THREAD

**Issue by rgregg** [knative/docs#1050]
**Describe the change you'd like to see**
The navigation for knative.dev/docs today is a bit all over the place (since it's based on the structure of the files). It makes it hard to find and consume the information in a logical order.

I'd recommend we order the content so that browsing the website can help you through the user journey for onboarding and using Knative.

I've created a proposed hierarchy for the content in a [sheet I've put in the team drive](https://docs.google.com/spreadsheets/d/1L3EAeTX7RRdZhcQZeNmxwN4DCncuImCXA5A1_KQvwSk/edit).

**Comment by samodell** [comment]
Related to #986

**Comment by samodell** [comment]
@rgregg -- I have an update on this. The "Information Architecture Task Force" met today to talk about your proposal and to each draft proposals of our own. You can see our [meeting notes here](https://docs.google.com/document/d/1wpEmlTzqtI7_2S5Or2-nbnlJvsFhRvqG_gLUAzgTz5A/), and our proposals were added to the sheet where you drafted yours.

Next, I'm going to consolidate the multiple proposals into one and then post it as an issue in the Docs repo and invite community input, and then once we resolve any community comments, we'll get started on implementing the new structure.

**Comment by RichieEscarez** [comment]
Hi all, 

A [revised "navigation" proposal "Serving V1 proposal"](https://docs.google.com/spreadsheets/d/1L3EAeTX7RRdZhcQZeNmxwN4DCncuImCXA5A1_KQvwSk/edit) has been added to the shared Google Sheets doc in the team drive.

**Request for Action**:
PTAL and provide feedback.

Sometime next week we will begin moving the content around to generate a staged/working copy (and incorporate your feedback). Please try to provide your feedback (in the proposal) before then.

**Comment by abrennan89** [comment]
We're working on this in the WG now as a group. It doesn't make sense really to have an issue tracking this, because it's a huge project with multiple participants, and we will create individual issues for each requirement or user story.
cc @carieshmarie
