### ISSUE TITLE
Empty issue lists for "help wanted" and "good first issue" labels

### ISSUE THREAD

**Issue by samodell** [knative/docs#1066]
On the Contributing home page, the "How can I help" section links out to bug lists in the various components, but all of the links point to empty lists. We should update the links to also include the "good first issue" label, but that label isn't used much either.

https://www.knative.dev/contributing/#how-can-i-help

## Expected Behavior
New contributors will find appropriately tagged issues that are good for getting started.

## Actual Behavior
Currently, all the linked-to issue lists are empty.

Related to #1032

**Comment by mhamwala** [comment]
Sorry @samodell just seen this issue, I created a PR yesterday to fix this issue: https://github.com/knative/docs/pull/1214. I suggest that we should clearly d

**Comment by samodell** [comment]
@mhamwala  I think it's nice to have both -- you're right that everything labled with "good first issue" indicates that help is wanted, but not everything labled with "help wanted" (when we start using the label) will be a good first issue. In theory, something labled with "good first issue" should have the necessary change very clearly documented, and it should be something that someone with little to no familiarity with Knative should be able to get done.

I created a "[kind/help-wanted](https://github.com/knative/docs/labels/kind%2Fhelp-wanted)" label, and we'll start to use that in addition to "kind/good first issue". If you could update your PR so that we're pointing people to the good first issues, as well as to help wanted, that would be excellent!

**Comment by mhamwala** [comment]
Ahh okay i understand! Thanks for clearing that up. We could possibly rename that "kind/help-wanted" label to just "help wanted" so that it's the same as the other Knative folders? I will update my PR tomorrow!

Link: https://github.com/knative/docs/issues/1215

**Comment by mhamwala** [comment]
I believe this can be closed @samodell
