### ISSUE TITLE
Add other medium.com blog content to knative.dev?

### ISSUE THREAD

**Issue by RichieEscarez** [knative/docs#1084]
The following blog posts exist on medium.com/knative, do we want them added to our website too (https://www.knative.dev/blog/articles/)?

@mattmoor : https://medium.com/knative/ko-fast-kubernetes-microservice-development-in-go-f94a934a7240

@josephburnett : https://medium.com/knative/knative-v0-3-autoscaling-a-love-story-d6954279a67a

Ive manually copied over the HTML for the last 0.4 release announcement but copying content out of a web page includes far more CSS and other extra HTML (it took a long time to parse out all the noise).

I think these articles would be a nice addition but they should be "exported" using the medium tooling. We found that only owners of the content can export the .html files.

If you agree that they should be added, feel free to email them to me.

**Comment by mchmarny** [comment]
yes, both should be added, exporting now...

**Comment by mchmarny** [comment]
@RichieEscarez I've sent you the autoscaling one. 
@mattmoor you will have to export the ko one since you published it

**Comment by RichieEscarez** [comment]
Received, thanks! Ill wait for the last file to be sent over and get them into the site some time tomorrow.

**Comment by RichieEscarez** [comment]
Ive manually copied in the remaining posts. PR is awaiting review.
