### ISSUE TITLE
Consolidate helloworld scala app instruction

### ISSUE THREAD

**Issue by chaodaiG** [knative/docs#1086]
**Describe the change you'd like to see**
All instructions for `Helloworld` example apps under `docs/serving/samples/hello-world` are following a consistent pattern, except for Scala. Please consolidate it using the same pattern, or move it to be under `community/samples/serving`.

**Comment by chaodaiG** [comment]
@RichieEscarez fyi

**Comment by chaodaiG** [comment]
I think @viktorklang created this sample app

**Comment by viktorklang** [comment]
@chaodaiG Could you elaborate as to what changes you would like to be made?

**Comment by chaodaiG** [comment]
@viktorklang , a few days ago @RichieEscarez 's PR reorganized samples, and now helloworld Scala sample is under `docs/serving/samples/hello-world`. There are also other helloworld samples for other languages, which follow very similar format, and some implicit naming conventions.
For example:
https://github.com/knative/docs/blob/master/docs/serving/samples/hello-world/helloworld-go/README.md
https://github.com/knative/docs/blob/master/docs/serving/samples/hello-world/helloworld-java/README.md

These 2 are Go and Java examples, they share same structures, and some of the sections are almost identical. Also the Dockerfiles are pretty much the same. 

If you feel the format in current Scala sample README is very important, you can also choose to move it to be under `community/sample/serving`

**Comment by viktorklang** [comment]
@chaodaiG I don't mind having the sample reformatted, as long as it's still correct. I'm happy to review a PR if you are keen on helping out!

**Comment by chaodaiG** [comment]
sounds good

**Comment by samodell** [comment]
Hey @chaodaiG  -- if you still feel up to editing the sample, go for it! Otherwise, you can close this issue if it's not a priority. Assigning to you for now.

**Comment by chaodaiG** [comment]
It doesn't feel like a priority for now, let's close it
/close
