### ISSUE TITLE
Install on Google Kubernetes Engine(docs/install/Knative-with-GKE.md)

### ISSUE THREAD

**Issue by estrellis** [knative/docs#1109]
## Expected Behavior
cut paste of install command from guide failed

## Actual Behavior
bash gcloud container clusters create $CLUSTER_NAME \ --zone=$CLUSTER_ZONE \ --cluster-version=latest \ --machine-type=n1-standard-4 \ --enable-autoscaling --min-nodes=1 --max-nodes=10 \ --enable-autorepair \ --scopes=service-control,service-management,compute-rw,storage-ro,cloud-platform,logging-write,monitoring-write,pubsub,datastore \ --num-nodes=3

## Steps to Reproduce the Problem

see above
1.
1.
1.

## Additional Info

This edited version of the command worked for me.

gcloud container clusters create $CLUSTER_NAME --zone=$CLUSTER_ZONE --cluster-version=latest --machine-type=n1-standard-4 --enable-autoscaling --min-nodes=1 --max-nodes=10 --enable-autorepair --scopes=service-control,service-management,compute-rw,storage-ro,cloud-platform,logging-write,monitoring-write,pubsub,datastore --num-nodes=3
WARNING: In June 2019, node auto-upgrade will be enabled by default for newly created clusters and node pools. To disable it, use the `--no-enable-autoupgrade` flag.
WARNING: Starting in 1.12, new clusters will have basic authentication disabled by default. Basic authentication can be enabled (or disabled) manually using the `--[no-]enable-basic-auth` flag.
WARNING: Starting in 1.12, new clusters will not have a client certificate issued. You can manually enable (or disable) the issuance of the client certificate using the `--[no-]issue-client-certificate` flag.
WARNING: Currently VPC-native is not the default mode during cluster creation. In the future, this will become the default mode and can be disabled using `--no-enable-ip-alias` flag. Use `--[no-]enable-ip-alias` flag to suppress this warning.
WARNING: Starting in 1.12, default node pools in new clusters will have their legacy Compute Engine instance metadata endpoints disabled by default. To create a cluster with legacy instance metadata endpoints disabled in the default node pool, run `clusters create` with the flag `--metadata disable-legacy-endpoints=true`.
This will enable the autorepair feature for nodes. Please see https://cloud.google.com/kubernetes-engine/docs/node-auto-repair for more information on node autorepairs.
Creating cluster knative in us-west1-c... Cluster is being health-checked (master is healthy)...done.
Created [https://container.googleapis.com/v1/projects/egs-test/zones/us-west1-c/clusters/knative].
To inspect the contents of your cluster, go to: https://console.cloud.google.com/kubernetes/workload_/gcloud/us-west1-c/knative?project=egs-test
kubeconfig entry generated for knative.
NAME     LOCATION    MASTER_VERSION  MASTER_IP    MACHINE_TYPE   NODE_VERSION  NUM_NODES  STATUS
knative  us-west1-c  1.12.5-gke.5    35.247.0.62  n1-standard-4  1.12.5-gke.5  3          RUNNING
strellis@chinacat:/google/src/cloud/strellis/wait/google3$ 

**Additional context**

**Install information:**
 - Platform (GKE, IKS, AKS, etc.):
 - Knative Version:

**Comment by sebgoa** [comment]
With the formatting I cannot tell what you changed in the command.

**Comment by sebgoa** [comment]
it is a rendering issue on the website, not in the github page.

**Comment by sebgoa** [comment]
I submitted a fix, but we probably need to have an automatic linter for this.
