### ISSUE TITLE
Fix 'verion' mispelling in check-install-version

### ISSUE THREAD

**Issue by udhos** [knative/docs#1119]
**Describe the change you'd like to see**

At the end of this doc:

https://github.com/knative/docs/blob/master/docs/install/check-install-version.md

Find this mispelling for 'version':

> or whatever verion you have installed

**Comment by sebgoa** [comment]
@udhos why don't you submit a PR for this ? You can simply edit the file in the github interface by clicking on the pen icon, make the change and submit the small patch.

**Comment by samodell** [comment]
Fixed by #1122
