### ISSUE TITLE
Are the hardcoded in-page license statements needed?

### ISSUE THREAD

**Issue by RichieEscarez** [knative/docs#1134]
## What is changing? 

When merged, there will be a footer on the whole Knative.dev site that lists the Knative licenses and also links to the License file in the knative/docs repo: https://github.com/knative/website/pull/24

If the footer shows a license on every page in the website and there exists a License file in the docs repo, do we need the hardcoded license footers in each page in the docs repo? Can the hardcoded text be removed from each of the files in the knative/docs repo? When  https://github.com/knative/website/pull/24 merges, the licenses  will display twice for each page in the site (once in the footer, and other as the hardcoded lines in each doc).

#### Examples
* [Staged changes in knative/website#24](https://deploy-preview-24--knative.netlify.com/)
* Hardcoded license text at the bottom of each file:

---

Except as otherwise noted, the content of this page is licensed under the
[Creative Commons Attribution 4.0 License](https://creativecommons.org/licenses/by/4.0/),
and code samples are licensed under the
[Apache 2.0 License](https://www.apache.org/licenses/LICENSE-2.0).

**Comment by samodell** [comment]
@rgregg Thoughts on this?

**Comment by rgregg** [comment]
We should definitely not have the license repeated twice on every page. Besides eliminating the need for repeating it on every markdown file in the docs repo (an already solved problem) what's pushing for us to add it to the template?

Are there other pages (say, like the governance pages) where the license text does include another license source that was referenced?

**Comment by RichieEscarez** [comment]
When i created the first Kubernetes docs site, I remember the legal team stating that that we must add a license to all pages. This is what they do: https://kubernetes.io/#mc_embed_signup_scroll

**Comment by RichieEscarez** [comment]
@rgregg I just noticed that other sites also include a link to their "Privacy Policy". Which does Knative use?

For example, kubflow.io use/link to the Google Privacy Policy and kubernetes.io uses the Linux Foundation Privacy Policy.

**Comment by RichieEscarez** [comment]
Ive added the Google Privacy Policy re: https://github.com/knative/website/pull/24

Next step: Remove hard coded "in-page" footers

**Comment by RichieEscarez** [comment]
in-page license statements were removed, closing
