### ISSUE TITLE
Create new v0.5 docs release branch and publish to knative.dev

### ISSUE THREAD

**Issue by RichieEscarez** [knative/docs#1138]
After v0.5 docs projects are complete and doc updates have merged:

* Obtain commit number to use for creating new `release-0.5` branch
* Add new '0.5' version to the docs website
* Publish 0.5 to knative.com (switch /docs to 0.5 and move 0.4 to v04.-docs)

Code releases (4/2):
https://github.com/knative/build/releases
https://github.com/knative/eventing/releases
https://github.com/knative/eventing-sources/releases
https://github.com/knative/serving/releases

**Comment by RichieEscarez** [comment]
Required: https://github.com/knative/docs/issues/1139

**Comment by samodell** [comment]
Also required: #994
