### ISSUE TITLE
Istio installation instructions need updating for Serving 0.6

### ISSUE THREAD

**Issue by bbrowning** [knative/docs#1148]
## What is changing? (Please include as many details as possible.)
The way Istio CustomResourceDefinitions are installed is changing in Knative Serving 0.6 that brings in Istio 1.1. Previously, users could just `kubectl apply -f` the istio CRDs and the other bits of Istio. Now, they'll need to apply the CRD yaml, wait until the Kubernetes job that spins up finishes, and then apply the other Istio yaml.

From a user's point-of-view, it's a more complicated install process now.

## How will this impact our users?
Users will not be able to install Istio using the same steps as before. And any vendor/operator code that installs Istio for Knative Serving may need to be updated.

## In what release will this take happen (to the best of your knowledge)?
v0.6

## Context
Link to associated PRs or issues from other repos here.

1. knative/test-infra#672 shows how we had to add a new function in the CI scripts to wait for the Istio Kubernetes Job to finish installing the CRDs before we can install the other bits of Istio.

## Additional info
I don't know the best thing to document for users yet. We'll have to document how they verify the Istio CRD Job is running and known when it's complete before moving on to install the rest of Istio.

**Comment by tcnghia** [comment]
One downside of this new installation is that we can no longer append the CRD installation into the first part of the main manifest.  The kubectl -> init pod -> crd sequence is slower than before, and we will be guaranteed to hit the race condition.

**Comment by sebgoa** [comment]
This is definitely less than ideal. Was the istio team informed ?

**Comment by samodell** [comment]
Related to #1244

**Comment by samodell** [comment]
Fixed by #1314
