### ISSUE TITLE
Knative main documentation site appears to be down

### ISSUE THREAD

**Issue by rakhbari** [knative/docs#1158]
## Expected Behavior

Browsing to [](http://www.knative.dev/docs) should render the documentation page.

## Actual Behavior

Page does not render. Error message is displayed: We can’t connect to the server at www.knative.dev

## Steps to Reproduce the Problem

1. Open browser
2. Attempt to navigate to http://www.knative.dev/docs
3. See error

## Additional Info
`wget` console output if that helps:

```
$ wget http://www.knative.dev/docs
--2019-04-10 10:29:58--  http://www.knative.dev/docs
Resolving www.knative.dev... 104.248.78.24, 2604:a880:2:d0::21e9:c001
Connecting to www.knative.dev|104.248.78.24|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://www.knative.dev/docs [following]
--2019-04-10 10:29:58--  https://www.knative.dev/docs
Connecting to www.knative.dev|104.248.78.24|:443... connected.
OpenSSL: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
Unable to establish SSL connection.
```

**Comment by samodell** [comment]
Hm, @rakhbari , are you still seeing this behavior? The site loads for me.

**Comment by samodell** [comment]
@RichieEscarez  mentioned this might have something to do with attempting to navigate to the http version of the site instead of the https version. For me, it redirects automatically, but that may not be the case for you depending on your browser. Try navigating to https://knative.dev/docs

**Comment by rakhbari** [comment]
For me it also first redirects to [https://www.knative.dev/docs](), but then it fails to render due to the error in my original post.

Same behavior for [https://knative.dev/docs]() 

```
$ wget https://knative.dev/docs
--2019-04-10 11:35:45--  https://knative.dev/docs
Resolving knative.dev... 104.198.14.52
Connecting to knative.dev|104.198.14.52|:443... connected.
OpenSSL: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
Unable to establish SSL connection.
```

**Comment by RichieEscarez** [comment]
Sorry, we are not seeing that error. Do you get the same when you include the www?

Here is what i see:
```
$ wget https://knative.dev/docs
--2019-04-10 11:39:54--  https://knative.dev/docs
Resolving knative.dev (knative.dev)... 104.198.14.52
Connecting to knative.dev (knative.dev)|104.198.14.52|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://www.knative.dev/docs [following]
--2019-04-10 11:39:54--  https://www.knative.dev/docs
Resolving www.knative.dev (www.knative.dev)... 2604:a880:400:d1::8b0:4001, 167.99.4.63
Connecting to www.knative.dev (www.knative.dev)|2604:a880:400:d1::8b0:4001|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: /docs/ [following]
--2019-04-10 11:39:55--  https://www.knative.dev/docs/
Reusing existing connection to [www.knative.dev]:443.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘docs’

docs                         [ <=>                               ]  64.97K  --.-KB/s    in 0.07s   

2019-04-10 11:39:55 (987 KB/s) - ‘docs’ saved [66532]


$ wget https://www.knative.dev/docs
--2019-04-10 11:40:26--  https://www.knative.dev/docs
Resolving www.knative.dev (www.knative.dev)... 2604:a880:400:d1::8b0:4001, 167.99.4.63
Connecting to www.knative.dev (www.knative.dev)|2604:a880:400:d1::8b0:4001|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: /docs/ [following]
--2019-04-10 11:40:27--  https://www.knative.dev/docs/
Connecting to www.knative.dev (www.knative.dev)|2604:a880:400:d1::8b0:4001|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 66532 (65K) [text/html]
Saving to: ‘docs.1’

docs.1                   100%[==================================>]  64.97K  --.-KB/s    in 0.1s    

2019-04-10 11:40:27 (486 KB/s) - ‘docs.1’ saved [66532/66532]

 
$ wget http://knative.dev/docs
URL transformed to HTTPS due to an HSTS policy
--2019-04-10 11:42:58--  https://knative.dev/docs
Resolving knative.dev (knative.dev)... 104.198.14.52
Connecting to knative.dev (knative.dev)|104.198.14.52|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://www.knative.dev/docs [following]
--2019-04-10 11:42:58--  https://www.knative.dev/docs
Resolving www.knative.dev (www.knative.dev)... 2604:a880:400:d1::7ff:b001, 104.248.120.187
Connecting to www.knative.dev (www.knative.dev)|2604:a880:400:d1::7ff:b001|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: /docs/ [following]
--2019-04-10 11:42:59--  https://www.knative.dev/docs/
Reusing existing connection to [www.knative.dev]:443.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘docs.2’

docs.2                       [ <=>                               ]  64.97K  --.-KB/s    in 0.07s   

2019-04-10 11:42:59 (984 KB/s) - ‘docs.2’ saved [66532]
```

**Comment by RichieEscarez** [comment]
This suggests it might have to do with your wget version?

https://stackoverflow.com/questions/28757232/unable-to-establish-ssl-connection-upon-wget-on-ubuntu-14-04-lts

**Comment by rakhbari** [comment]
Yes, the `wget` that failed was on an old server of mine still running CentOS 5. I tried the same thing on another sever of mine running latest/greatest Ubuntu 18.10 with a fresh `apt update;apt upgrade`. On that the `wget` to https://www.knative.dev/docs worked.

But still, none of our desktop PCs at work, whether Windows 10 or Mac can render this site. Tried FireFox and Chrome on both platforms. All failed. And even the `wget` on my old Centos 5 box is able to render just about every other site (https or not) without an issue, so there's definitely something not right with the server of this docs site.

![image-007](https://user-images.githubusercontent.com/5705277/55908380-270a9780-5b8e-11e9-9311-6c9547a061b6.png)

**Comment by RichieEscarez** [comment]
The site is hosted on Netlfiy and their server status page indicates no issues: https://www.netlifystatus.com/

This is the default subdomain: https://knative.netlify.com/
Can you try to hit that URL to see if you get the same error?

**Comment by rakhbari** [comment]
Yes, the Netlify site renders just fine. I have a feeling this is an issue with our DNS at work. Hint being the error in the page: DNS_PROBE_FINISHED_NXDOMAIN

https://kinsta.com/knowledgebase/dns_probe_finished_nxdomain/#dns-domain

When I get home tonight I'm going to try to browse to https://www.knative.dev/docs from my home desktop machines and see if that works. If it does, then I'll have profusely apologize for opening this (non-)issue. I'll report back tonight.

**Comment by RichieEscarez** [comment]
No worries! I just want to make sure that its not anything else.

**Comment by samodell** [comment]
We've had no other reports of this, so closing for now.

**Comment by eaydogan** [comment]
<img width="1241" alt="Screen Shot 2019-04-12 at 20 31 06" src="https://user-images.githubusercontent.com/1244956/56055400-0eeb7180-5d62-11e9-84aa-999d7b0ba0e4.png">

**Comment by RichieEscarez** [comment]
Context please @eaydogan 

Did you try the items above (ie netlify subdomain)? Without more info its impossible to help since we are not seeing these issues ourselves. 

Can you try clicking Advanced to see if the "Proceed anyway" link works?

Here is more info that might help resolve why you get that screen: https://www.google.com/search?q=your+connection+is+not+private+chrome

**Comment by eaydogan** [comment]
@RichieEscarez sorry for false alarm.

It was related active pow.cx

I removed old dev extension from /etc/resolver

now it's ok.

Again, sorry for the false alarm.

**Comment by rakhbari** [comment]
@eaydogan, when I ran into my original issue (which has turned out to be problems with DNS servers at my work) I first checked with an online SSL checker and the SSL certs for www.knative.dev appear to be flawless. No issues that I can see.

https://www.sslshopper.com/ssl-checker.html#hostname=www.knative.dev
