### ISSUE TITLE
Add v0.5 release blog post to knative.dev/blogs

### ISSUE THREAD

**Issue by RichieEscarez** [knative/docs#1166]
@mchmarny can you please export and send me your latest post so that i can add it to the site:
https://medium.com/knative/announcing-knative-v0-5-release-cfe646ca8e30

**Comment by samodell** [comment]
@mchmarny  Ping on this -- can you export the post and send it to Richie, so he can upload it to knative.dev?

**Comment by RichieEscarez** [comment]
@mchmarny friendly ping (a draft of the 0.6 post is being edited and it would be nice to get this up at the same time, if not before)

**Comment by RichieEscarez** [comment]
Blog posts sent over, thanks!
