### ISSUE TITLE
numbers not rendering on the website in some instances

### ISSUE THREAD

**Issue by mhamwala** [knative/docs#1202]
## Expected Behavior
1. first item
2. second item
3. third item

## Actual Behavior
`1.` first item
`1.` second item
`1.` third item

## Steps to Reproduce the Problem
Some numbered bullet points are not rendering on the website but are fine in the github docs, this is the first instance I have seen of this happening, take a look at this Hello world sample app - https://knative.dev/docs/serving/samples/hello-world/helloworld-csharp/index.html

## Additional Info
**Additional context**

**Comment by mhamwala** [comment]
I think what might be happening is that it renders every block after a ```shell block like a new list hence the recurring `1`'s, I cloud be wrong.

**Comment by samodell** [comment]
Thank you for looking into this!

@RichieEscarez  some more website rendering issues.

**Comment by mhamwala** [comment]
I started looking into this, a potential fix could be adding four spaces to indent content between bullet points but I haven't figured out how to confirm that this works by viewing the rendered website.

having the same issue as: https://github.com/knative/docs/issues/1239

**Comment by RichieEscarez** [comment]
Looks like the Hugo markdown processor wants another single space add in front of any content in a nested list (that includes a line break). 

[Here is my test commit](https://github.com/knative/docs/commit/d877bf333da8c1d3643983e8a6eb4ebb4ea4f7a3#diff-cd7cfac5aac40d9955039b3adfbf7978)

which fixes the first bullet in the example topic reference in this issue: https://knative.dev/docs/serving/samples/hello-world/helloworld-csharp/index.html

**Comment by mhamwala** [comment]
Ahh I see, great @RichieEscarez , is this something that we should document or is it possible to change the rules for the Hugo markdown processor?

**Comment by RichieEscarez** [comment]
> is this something that we should document or is it possible to change the rules for the Hugo markdown processor?

Looks like this has been a [known Blackfriday issue](https://github.com/russross/blackfriday/issues/329) for some time and the extra spacing that I found to fix our issue is what has been the "[workaround](https://gohugo.io/content-management/formats/)".

Ill keep an eye out for alternate solutions and will try to document this soon. But even with a set of instructions in our repo it is un-intuitive to indent with "3-4 spaces" (especially if you use the "TAB" button). As far as our library, Ive seen some .md files where the author has either failed to indent all together, while some are indented normally ("1 tab"), and in both cases, its not obvious that there will be an rendering issue on knative.dev, given that the GitHub WYSIWIG renders correctly (and doesnt indicate any type of problem).

**Render Test: "tabs vs spaces"**


- list

    - nested (4 spaces)

        - nested (4 spaces)


- list

	- nested (1 tab)

		- nested (1 tab)


- list

   - nested (3 spaces)

      - nested (3 spaces)


- list

		- nested (2 tabs)
		
				- nested (2 tabs)

**Comment by RichieEscarez** [comment]
FYI: I'm testing out possibility of using our "sock puppet" that runs 'prettier' on all the markdown. We still would be faced with the lack of any type of UI or linter that enforces "4 spaces" (during authoring or PR review/merge) but having all tabs converted into spaces will reduce the overhead of manually adding 1-2 spaces to any existing "tabs".

**Comment by mhamwala** [comment]
Sounds good!

**Comment by RichieEscarez** [comment]
With the new Hugo v0.61.0 release, all of these issue go away. See pending [the PR in knative/website](https://github.com/knative/website/pull/115) for the fix that resolves these issues

**Comment by RichieEscarez** [comment]
Fix was merged, closing this
