### ISSUE TITLE
Remove ENV PORT from Dockerfile

### ISSUE THREAD

**Issue by saturnism** [knative/docs#1204]
## Expected Behavior
`PORT` environmental variable and its default value should not be specified in Dockerfiles. Remove this from existing Dockerfile examples

## Actual Behavior
`PORT` environmental variables are specified in Dockerfiles due to past historical reasons.

**Comment by hpandeycodeit** [comment]
I will fix this.

**Comment by sebgoa** [comment]
I think this applies to all Dockerfiles, not just the Java example

**Comment by samodell** [comment]
#1211 only partially fixes this issue, so reopening

**Comment by hpandeycodeit** [comment]
I will create a separate PR for other Dockerfiles.

**Comment by sebgoa** [comment]
This can be closed now that #1290 has been merged
