### ISSUE TITLE
The part of configuring Istio Gateway in the doc `using-an-ssl-cert.md` is stale

### ISSUE THREAD

**Issue by ZhiminXiang** [knative/docs#1210]
**Describe the change you'd like to see**
In Istio 1.1, it supports dynamically adding TLS certificates into Istio Gateway to terminate TLS connection. See [here](https://istio.io/docs/tasks/traffic-management/secure-ingress/sds/). While in our current [doc](https://github.com/knative/docs/blob/master/docs/serving/using-an-ssl-cert.md#configure-the-knative-shared-gateway-to-use-the-new-secret), it still uses the old way.

**Comment by ZhiminXiang** [comment]
The part about how to configure the Gateway (https://github.com/knative/docs/blob/master/docs/serving/using-a-tls-cert.md#manually-adding-a-tls-certificate) is still stale.

We should follow the way described in Istio doc (https://istio.io/docs/tasks/traffic-management/ingress/secure-ingress-sds/) as in Knative serving we already use Istio ingress SDS.

**Comment by RichieEscarez** [comment]
@ZhiminXiang is this fixed already?

**Comment by RichieEscarez** [comment]
Update: This is still in-progress.
