### ISSUE TITLE
Performing a Custom Knative Installation(docs/install/Knative-custom-install.md)

### ISSUE THREAD

**Issue by RichieEscarez** [knative/docs#1217]
Indentation is not displaying correctly nor are the lists.

**Comment by sebgoa** [comment]
this page here: https://github.com/knative/docs/blob/master/docs/install/Knative-custom-install.md

renders well on github

**Comment by RichieEscarez** [comment]
Yes, we have noticed that the markdown processor is very picky on knative.dev. Here is an example from that page:

![image](https://user-images.githubusercontent.com/11762685/56527309-50b6ad80-6502-11e9-9e15-850cd6e0e25a.png)
