### ISSUE TITLE
Is there any plan to implement knative i18n ?

### ISSUE THREAD

**Issue by SataQiu** [knative/docs#1222]
**Describe the change you'd like to see**
Is there any plan to implement knative i18n?
At present, our website `https://knative.dev` only supports English.
To facilitate internationalization, we should consider supporting more languages.
I am very interested in implementing knative Chinese localization.
If you have any plans, please let me know.
I'm happy to make an effort in this area!

**Additional context**

**Comment by samodell** [comment]
Related to #716  

Hi @SataQiu , and thanks for your interest in translating Knative into Chinese! So far, we don't have a firm plan for how to kick off i18n for Knative. As the project is still in its pre-beta phase, there will continue to be a great deal of change between now and the 1.0 version. Once we reach the beta phase, and in theory some more stability in the project, that will likely be the time for us to seriously look into adding translated languages. Sorry I don't have any concrete information for you, but we will update these issues when we have more information.

**Comment by samodell** [comment]
I'm going to close #716  as a duplicate of this, and we'll use this issue to track translation.

/cc @toshi0607 , who was interested in helping with translation into Japanese.

We are still not ready for translation (see initial response above), but the progress is getting closer to a stable phase. I'll update this issue when we're ready to start work on translation.

**Comment by toshi0607** [comment]
I'm looking forward to update! I'm willing to support it.

**Comment by abrennan89** [comment]
@omerbensaadon is this something the UX WG can look at?
I can't see this ever being implemented by the docs WG in the foreseeable future, we just don't have the resources to facilitate something like this which isn't a priority for us.

**Comment by omerbensaadon** [comment]
@SataQiu would you be willing to be the primary maintainer for this? Around 7% of our website visitors are coming from China so this makes sense, it's just something that would require a ton of overhead to maintain.

**Comment by abrennan89** [comment]
Issue moved to [knative/ux #36](https://github.com/knative/ux/issues/36) via [**ZenHub**](https://www.zenhub.com/)
