### ISSUE TITLE
Cannot apply helloworl-go service . Getting Error "admission webhook webhook.serving.knative.dev denied the request: mutation failed: unknown field template"

### ISSUE THREAD

**Issue by modassarrana** [knative/docs#1234]
<I am trying to bring up hello world service on knative , but getting error : admission webhook webhook.serving.knative.dev denied the request: mutation failed: unknown field template.

Let me give you a background of stuff performed

1>	Brought up kubernetes cluster of 1 master & 2 slave nodes using kubespray
2>	Kubectl version is 1.11.3
3>	Install istio & knative using url https://github.com/knative/docs/blob/master/docs/install/Knative-with-any-k8s.md
4>	All pods are in running state
5>	Enabled istio 
6>	Use helloworld-go service to test the app on the newly created setup
7>	Getting error while applying  above service:  admission webhook webhook.serving.knative.dev denied the request: mutation failed: cannot decode incoming new object: json: unknown field template

Service example
apiVersion: serving.knative.dev/v1alpha1 # Current version of Knative
kind: Service
metadata:
  name: helloworld-go # The name of the app
  namespace: default # The namespace the app will use
spec:
  template:
    spec:
      containers:
      - image: gcr.io/knative-samples/helloworld-go # The URL to the image of the app
        env:
          - name: TARGET # The environment variable printed out by the sample app
            value: "Go Sample v1"
Error:
[centos@svpod7mgmt002 ~]$ kubectl apply --filename service.yaml
Error from server (InternalError): error when creating "service.yaml": Internal error occurred: admission webhook "webhook.serving.knative.dev" denied the request: mutation failed: cannot decode incoming new object: json: unknown field "template"

8>	I have created same service in python , but didn’t use template under the spec & it worked

Service example
apiVersion: serving.knative.dev/v1alpha1 # Current version of Knative
kind: Service
metadata:
  name: testhelloworld-python # The name of the app
  namespace: default # The namespace the app will use
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: docker.io/modassarrana/testhelloworld-python # The URL to the image of the app
            env:
              - name: TARGET # The environment variable printed out by the sample app
                value: "Rana"

I have cross checked mutation as well 

[centos@svpod7mgmt002 ~]$ kubectl api-versions | grep admissionregistration
admissionregistration.k8s.io/v1alpha1
admissionregistration.k8s.io/v1beta1

Pod status for knative :
[centos@svpod7mgmt002 ~]$ kubectl get pods --namespace knative-monitoring
NAME                                  READY     STATUS    RESTARTS   AGE
elasticsearch-logging-0               1/1       Running   0          2h
elasticsearch-logging-1               1/1       Running   0          2h
grafana-754bc795bb-q6jxr              1/1       Running   0          2h
kibana-logging-7f7b9698bc-7xj52       1/1       Running   0          2h
kube-state-metrics-768dfff9c5-czps8   4/4       Running   0          2h
node-exporter-4n5dr                   2/2       Running   4          2h
node-exporter-np8xr                   2/2       Running   0          2h
node-exporter-tp5mw                   2/2       Running   0          2h
prometheus-system-0                   1/1       Running   0          2h
prometheus-system-1                   1/1       Running   0          2h

[centos@svpod7mgmt002 ~]$ kubectl get pods --namespace knative-serving
NAME                          READY     STATUS    RESTARTS   AGE
activator-664b5b9598-f7nzg    2/2       Running   0          2h
autoscaler-64d5bd84b8-gmnws   2/2       Running   0          2h
controller-658b9d5c6c-hvllf   1/1       Running   0          2h
webhook-5dffbfbb8b-bh54c      1/1       Running   0          2h

[centos@svpod7mgmt002 ~]$ kubectl get pods --namespace knative-build
NAME                                READY     STATUS    RESTARTS   AGE
build-controller-86f5b5b96d-dcccs   1/1       Running   0          2h
build-webhook-6fddd7c6df-z98bt      1/1       Running   0          2h

[centos@svpod7mgmt002 ~]$ kubectl get pods --namespace knative-eventing
NAME                                            READY     STATUS    RESTARTS   AGE
eventing-controller-6fdccd8c95-96z8v            1/1       Running   0          2h
in-memory-channel-controller-6fddb6655f-mtprb   1/1       Running   0          2h
in-memory-channel-dispatcher-7684cd7c7d-dr7ph   2/2       Running   2          2h
webhook-d496c66bd-bp747                         1/1       Running   0          2h

[centos@svpod7mgmt002 ~]$ kubectl get pods --namespace knative-sources
NAME                   READY     STATUS    RESTARTS   AGE
controller-manager-0   1/1       Running   0          2h

Can you let me know , whats going wrong . How can I debug ??

**Comment by RichieEscarez** [comment]
Thanks for opening this issue @modassarrana!
You should also consider pinging the Slack channel for help at https://knative.slack.com/

**Comment by RichieEscarez** [comment]
@modassarrana Im not sure if there is something here that might help (since I dont see the exact error message you recieved) but we have a Serving debugging topic here: https://knative.dev/docs/serving/debugging-application-issues/

/cc @grayside

**Comment by mhamwala** [comment]
@modassarrana could you put 3 backticks ``` before and after code blocks to make it easier for us to see whats going on?

**Comment by modassarrana** [comment]
Hi ,

I have used the sample helloworld-go service.yaml file in my knative environment. Tried to bring up the service using it. PLease find the sample service.yaml file code  and exact error :
```
apiVersion: serving.knative.dev/v1alpha1 # Current version of Knative
kind: Service
metadata:
name: helloworld-go # The name of the app
namespace: default # The namespace the app will use
spec:
template:
spec:
containers:
- image: gcr.io/knative-samples/helloworld-go # The URL to the image of the app
env:
- name: TARGET # The environment variable printed out by the sample app
value: "Go Sample v1"

```

Error
-----
Error from server (InternalError): error when creating "service.yaml": Internal error occurred: admission webhook "webhook.serving.knative.dev" denied the request: mutation failed: cannot decode incoming new object: json: unknown field "template"


I have written a different helloworld service.yaml file & it is working properly

```
apiVersion: serving.knative.dev/v1alpha1 # Current version of Knative
kind: Service
metadata:
name: testhelloworld-python # The name of the app
namespace: default # The namespace the app will use
spec:
runLatest:
configuration:
revisionTemplate:
spec:
container:
image: docker.io/modassarrana/testhelloworld-python # The URL to the image of the app
env:
- name: TARGET # The environment variable printed out by the sample app
value: "Rana"

```

I was debugging on my own & found out that knative v0.5.0 service structure doesnot matches with master branch service structure

Let me know , if you still have doubt

**Comment by modassarrana** [comment]
Hi Richie,

Can you add me in the slack , so that I can chat & get my issues resolved.

Thanks,
Modassar Rana

**Comment by modassarrana** [comment]
knative v0.5 upports istio 0.6 , but istio have already comeup with release 1.1 . Is there any plan to include istio latest version in knative.

**Comment by markusthoemmes** [comment]
@modassarrana Knative is tested with Istio 1.1 at HEAD. AFAIK 0.5 was tested with 1.0.7.

**Comment by modassarrana** [comment]
Knative Install doc still uses 0.5 yaml file for its component . Can installation doc be updated with master .

At present , there is no request limit in Knative serving.  After that max limit , it should either throw a message or should not accept any outside service request.

Example -> I have ping function as a service in knative environment. Now tester wants to test this ping service from outside . He will send 50 http request to ping within  a min. But our constraint is to allow only 20 request , not more than that

**Comment by mattmoor** [comment]
@modassarrana The samples at HEAD reflect Knative at HEAD.  In 0.6 (not released) we are changing the preferred resource layout to what's currently in the samples.  These samples will work against a nightly build, but not against the latest release (0.5).

For samples that work against 0.5, see the 0.5 branch off of this repo.

**Comment by RichieEscarez** [comment]
Sorry for the delay @modassarrana , ive added you to the docs slack channel. 

Also, here is the in-flight PR about the 0.6 change to use Istio from official source: https://github.com/knative/docs/pull/1272 (uses Istio 1.1.3 but not sure if that help you).

Regarding installing a version of Knative Serving v.Next, you can use the development instructions here, 
https://github.com/knative/serving/blob/master/DEVELOPMENT.md
Otherwise, knative/doc at `master` will continue to point to the last release until there are actual v.Next (ie. 0.6) images to point to.

**Comment by Nxtra** [comment]
Thanks @modassarrana , the structure of the file you provided is working for me.
I wasn't able to pull from docker hub. That's why I pointed `image` to the image provided in the official docs. For me it is working like this:
```
apiVersion: serving.knative.dev/v1alpha1 # Current version of Knative
kind: Service
metadata:
  name: helloworld-go # The name of the app
  namespace: default # The namespace the app will use
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: gcr.io/knative-samples/helloworld-go # The URL to the image of the app
            env:
            - name: TARGET # The environment variable printed out by the sample app
              value: "Knative Power"
```

**Comment by sebgoa** [comment]
I think this can be closed. Matt's answer is the correct one. HEAD is not showing a valid object for a 0.5 installation.

**Comment by balopat** [comment]
I just ran into this exact same issue today - not using HEAD - I was using the gloo installation and the latest 0.7 instructions on the docs to [deploy an app](https://knative.dev/docs/install/knative-with-gloo/#deploying-an-app). So there might be a disconnect in versions there too.

**Comment by modassarrana** [comment]
i was using the different template structure for creating service.yaml . Thats why it was failing. Check the service specification of 0.7 . it will resolve your issues, If you are still facing the issue , share me your service.yaml file . i will check it
