### ISSUE TITLE
Heads up: Changes in Knative Eventing Sources

### ISSUE THREAD

**Issue by n3wscott** [knative/docs#1235]
## What is changing? (Please include as many details as possible.)

1. We are going to rename knative/eventing-sources repo to knative/eventing-contrib
2. We are moving underlying source types to knative/eventing
    - ContainerSource
    - KubernetesSource
    - CronJobSource
3. We will move channel impls that are currently in knative/contrib to knative-contrib

## How will this impact our users?

Installing sources will have one less step: no need to install ContainerSource (or one of the other two)

## In what release will this take happen (to the best of your knowledge)?

v0.6

## Context
Link to associated PRs or issues from other repos here.

Will comment with this.

## Additional info

More to come. I will help update docs too as we make these migrations. Api does not change.

[ ] - Move samples from eventing-sources to docs.

**Comment by n3wscott** [comment]
Moving CronJobSource: https://github.com/knative/eventing/pull/1092

**Comment by n3wscott** [comment]
Moving ContainerSource:

- Adding - knative/eventing#1099
- Deleting - knative/eventing-sources#371

**Comment by n3wscott** [comment]
Moving ApiServer Source: 

- Adding - https://github.com/knative/eventing/pull/1108

**Comment by samodell** [comment]
All of these PRs were merged, so I think we can close out this issue.
