### ISSUE TITLE
How to build the docs website (knative.dev) locally?

### ISSUE THREAD

**Issue by aliok** [knative/docs#1239]
**Describe the change you'd like to see**
Instructions on how to build the docs locally.

**Additional context**
I noticed some formatting errors and wanted to debug them but I can't debug without being able to build the docs locally.

**Comment by mhamwala** [comment]
@aliok It's built into some code editors, so if your using (assuming your using a mac)
`Atom`:
Just open the Markdown file and hit Ctrl+Shift+M to toggle the Markdown preview panel next to it. It handles HTML and images also.
`vscode`:
I think its Ctrl+Shift+P then hit Markdown: Open Preview.
if your not using one of these editors i suggest a quick google and hopefully your editor supports this :)

**Comment by samodell** [comment]
Hey @aliok  -- do you mean building the docs to see how they'll appear on the knative.dev website? If that's the case, @RichieEscarez  can help with that.

It's true that the markdown rendering on the website isn't perfectly in sync with GitHub's own markdown rendering; I have seen some formatting issues. We'd love for you to look into those.

**Comment by aliok** [comment]
> Hey @aliok -- do you mean building the docs to see how they'll appear on the knative.dev website? If that's the case, @RichieEscarez can help with that.

@samodell  yes, exactly. Some Markdown content is rendered strange and I wanted to debug them locally. But I don't know what kind of set up is used here.

**Comment by aliok** [comment]
Ok, now I found it. https://github.com/knative/website is building it.

I will send a PR to note this in the docs repo.

**Comment by RichieEscarez** [comment]
Status: I will open a PR for this some time tomorrow (sorry, our team has been out of office the first part of the week at a workshop so playing catch up now).

@sebgoa @aliok 
For the interim, the local build steps are generally:

1. Install and setup Hugo local server: https://gohugo.io/getting-started/quick-start/
2. Meet Docsy requirements: https://github.com/google/docsy-example/blob/master/content/en/docs/Getting%20started/_index.md
3. Clone knative/website
4. Meet Hugo's expectation that all content lives under a single root directory. Either:
    - clone knative/docs into the `content/en` folder
    - clone knative/docs elsewhere and then create a symlink to there from the `content/en` folder (of knative/website)
5. Run `hugo server' from the root of knative/website and open your localhost

There is a little more to this (small details) but Ill consolidate all these steps and the missing detail into a single page.

**Comment by RichieEscarez** [comment]
Instructions and the new local build script are here: https://github.com/knative/website/pull/72/files

(a formal instruction page might come after the 0.8 release)

**Comment by aliok** [comment]
Thanks @RichieEscarez 
Didn't have a chance to verify the instructions and the script but I am ok with resolving this ticket.
If I have a chance, I would write here regardless.

**Comment by aliok** [comment]
@RichieEscarez just had a chance to give the script a try. It works great.

I guess we cannot have a README.md on the website repo as it would be rendered as well, right?
Can we have a txt file that is not rendered?

Would be nice to see how to build the website quickly, instead of looking inside the script

**Comment by RichieEscarez** [comment]
That's great to hear @aliok. I will eventually add a README the knative/website repo. Other than the fact that the process seems to change from month to month as I fix or improve things, I do have other priorities right now. We are restructuring all of our content right now but after that I'll be able to document all these administration type steps.
