### ISSUE TITLE
Commands/code snippets for samples in knative.dev are prefixed with spaces

### ISSUE THREAD

**Issue by ahmetb** [knative/docs#1240]
e.g. https://knative.dev/docs/serving/samples/hello-world/helloworld-go/index.html

this won't work because:

- yaml doesn't tolerate indentation errors like this
- bash commands prefixed with spaces aren't saved in bash history so people can't re-run them later again.

![image](https://user-images.githubusercontent.com/159209/56758689-20624f80-674c-11e9-8882-1db537ba00dc.png)

**Comment by RichieEscarez** [comment]
not exactly the same but related #1202
