### ISSUE TITLE
bad links/missing files in pubsub eventing example

### ISSUE THREAD

**Issue by amygdala** [knative/docs#1264]
The 'verify' section of https://github.com/knative/docs/tree/release-0.5/docs/eventing/samples/gcp-pubsub-source#verify as well as https://github.com/knative/docs/tree/master/docs/eventing/samples/gcp-pubsub-source has some issues. 

In the 0.5 version, the readme says: 

> We will verify that the published message was sent into the Knative eventing system by looking at what is downstream of the GcpPubSubSource. If you deployed the Subscriber, then continue using this section. If not, then you will need to look downstream yourself.

However, the link is bad: there's no Subscriber section.

In the master version, the text is:

> The function and the subscription were created by applying the subscriber.yaml manifest in the deployment section above.

However, there's no subscriber.yaml (as far as I can tell ..)

[This example appeared to deploy okay for me, but AFAICT is not actually working in the sense of responding to new pubsub data...  haven't dug into it yet but given the above I'm wondering if stuff is missing].

**Comment by sebgoa** [comment]
@amygdala can you tell us if the example worked for you or not ? Your last comment made it sound like it did not work.

if it did not, can you open an other issue.

I submitted a fix for your first issue in #1273

**Comment by amygdala** [comment]
It turns out the issues with the example were due to my changing the default namespace. (sorry, I forgot to update here.)  So the example itself is okay.  Those links that refer to non-existent files/sections just need to be cleaned up.
