### ISSUE TITLE
Fix telemetry Dockerfile and typo

### ISSUE THREAD

**Issue by savitaashture** [knative/docs#1294]
## Expected Behavior
Execution of 
```
docker build \
  --tag "${REPO}/docs/serving/samples/telemetry-go" \
  --file=docs/serving/samples/telemetry-go/Dockerfile .
```
should create a image successfully

## Actual Behavior
docker image build is failing because of path issue in the Dockerfile.

## Steps to Reproduce the Problem

1. Follow https://knative.dev/docs/serving/samples/telemetry-go/

**Install information:**
 - Knative Version:

**Comment by kzjackson1** [comment]
The fix for this issue has been merged.
/close
