### ISSUE TITLE
custom domain on Getting Started with App Deployment(docs/install/getting-started-knative-app.md)

### ISSUE THREAD

**Issue by torstenwerner** [knative/docs#1298]
Current status: The documentation uses the domain example.com. Below the text 'To find the host URL for your service, enter:' this example.com domain materializes out of thin air. There is a chance that I want to use my own custom domain but the documentation page does not guide me on how to configure it.

Task: Please provide either more documentation or a link to existing documentation on how to configure a custom domain.

**Comment by samodell** [comment]
Hi @torstenwerner  -- I think the documentation at https://knative.dev/docs/serving/using-a-custom-domain/ should answer this question. This is linked from the sidebar as "Setting up a custom domain".

1. Is that topic title clear, or is there a different wording that might've caught your eye when you were looking for this information?

2. Where would you want this information linked from?

**Comment by samodell** [comment]
Ah, for #2, I re-read the title for your issue and realized from "The Getting Started with App Deployment" guide would help. If you have other suggestions, let me know!

**Comment by torstenwerner** [comment]
Hi @samodell, yes a link from the 'Getting started...' page to the 'Setting up a custom domain' would be nice.
