### ISSUE TITLE
Add doc explaining how to upgrade an existing Knative install

### ISSUE THREAD

**Issue by steren** [knative/docs#130]
I installed Knative following [the docs](https://github.com/knative/docs/blob/master/install/README.md). Today, an issue has been fixed, I would like to update my Knative installation to include the fix. I don't know how to do that.

I suggest we add a doc "Updating an existing Knative installation"

CC @mattmoor for guidance about how to do that

**Comment by duglin** [comment]
Related to this we also need to decide if people can skip versions during an upgrade path, or do they need to install all versions on their way to the latest?

And, while I'm not sure yet what if anything kn can/should do about this, is the notion that some providers may need to run some kind of script during the install/upgrade process. So, would they need to run each script for each version or figure out some way to make sure the latest version can just deal with it?  Maybe just some guidance docs... not sure.

**Comment by samodell** [comment]
@mattmoor  Can you assign this to someone who has the bandwidth to write up a draft of these instructions?

**Comment by mattmoor** [comment]
/assign @mdemirhan 

... to delegate.

**Comment by grzesiek** [comment]
I believe that having a clear upgrade path is very important, should be supported and well documented. One of the OpenStack failure reasons was that it was really difficult to upgrade and it took ages to perform an update without a downtime. This is - in my opinion and at this moment - probably the most important missing piece of the puzzle in entire Knative story.

**Comment by samodell** [comment]
@mdemirhan  Please assign to someone who can explain the steps for upgrading an installation.
