### ISSUE TITLE
Missing how to get IP_ADDRESS for Minikube, docker desktop and other Kube platforms

### ISSUE THREAD

**Issue by houshengbo** [knative/docs#1300]
I am reading the docs at https://github.com/knative/docs/tree/master/docs/serving/samples/autoscale-go.

It is good to add how to get the IP address for other Kube backends beside GKE.

**Comment by sebgoa** [comment]
Can you edit your issue.

I don't understand what you mean when you say "it is good to add how..."

What is wrong ?
What is missing ?
