### ISSUE TITLE
Minikube install docs exhaust available memory

### ISSUE THREAD

**Issue by scothis** [knative/docs#1325]
## Expected Behavior

Using the Minikube install docs at https://knative.dev/docs/install/knative-with-minikube/, I expect to have a working Knative install on Minikube.

## Actual Behavior

Minikube runs out of memory and fails to schedule pods

```
$ kubectl describe node
<snip>
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource           Requests      Limits
  --------           --------      ------
  cpu                2905m (72%)   4900m (122%)
  memory             7674Mi (99%)  4740Mi (61%)
  ephemeral-storage  0 (0%)        0 (0%)
```

## Steps to Reproduce the Problem

1. follow the steps in the doc
1. run `kubectl describe pod`
1. notice that the memory requests are very close to 100%

## Additional Info

Either the amount of memory for the cluster needs to be increased from 8GB (see #76), fewer Knative components installed, or the reservations for those components need to be shrunk.

**Install information:**
 - Platform (GKE, IKS, AKS, etc.): Minikube v1.0.1
 - Knative Version: 0.5.x

**Comment by sebgoa** [comment]
Looks like you need to up the CPUs to 6:

https://github.com/knative/docs/pull/1322

**Comment by xpepermint** [comment]
This issue should be renamed to a general issue addressing required resources. I installed `istio v1.1.8` and `knative v0.6.0` on a server with 6 CPUs and 15GB memory, also running `Flannel` network fabric. I see all CPUs running at ~30% and the system is consuming about 10GB memory in idle mode - no functions installed. Is that expected?

**Comment by sdake** [comment]
see https://github.com/knative/docs/issues/1441 for related issue.

**Comment by sdake** [comment]
@scothis @sebgoa It appears (atleast with vfusion driver on macos) Istio 1.2 rcs ristio-demo-authh.yaml requires 8.6GiB of ram.
