### ISSUE TITLE
No docs on minScale/maxScale features

### ISSUE THREAD

**Issue by ahmetb** [knative/docs#1331]
Knative.dev has no documentation on how to use minScale/maxScale stuff.

There's some info buried in autoscale-go sample https://knative.dev/docs/serving/samples/autoscale-go/ which I wouldn't normally read as a user trying to learn Knative.

There should be ideally a dedicated concept or how-to page explaining these.

**Comment by abrennan89** [comment]
@ahmetb @samodell added a PR for this - can be closed once this is reviewed :)
