### ISSUE TITLE
No docs on how to configure scale-to-zero duration

### ISSUE THREAD

**Issue by ahmetb** [knative/docs#1332]
Google: `"scale-to-zero-threshold" site:knative.dev`

similarly `scale-to-zero-grace-period`.

This is a supported annotation, yet doesn't seem to be documented.

I had to go read some Red Hat Openshift blog to learn how to configure it https://blog.openshift.com/knative-serving-your-serverless-services/

**Comment by abrennan89** [comment]
@ahmetb I am currently working on some contributions for docs on autoscaling and scale-to-zero, @samodell I can take this issue but not sure how to assign it to me

**Comment by kameshsampath** [comment]
@ahmetb  - I dont that property anymore,I right now see no way to configure the scale down period. https://github.com/knative/serving/blob/master/config/config-autoscaler.yaml

**Comment by abrennan89** [comment]
Is this issue fixed in https://github.com/knative/docs/pull/1363 ?

**Comment by samodell** [comment]
Yep, it is! I'm going to close out this issue in favor of #1362 , to make sure we don't forget to come back and close this.
