### ISSUE TITLE
Install on OpenShift(docs/install/Knative-with-OpenShift.md)

### ISSUE THREAD

**Issue by goern** [knative/docs#1340]
## Expected Behavior
https://knative.dev/docs/install/scripts/knative-with-openshift.sh works

## Actual Behavior
https://knative.dev/docs/install/scripts/knative-with-openshift.sh can not find:
https://storage.googleapis.com/knative-releases/serving/latest/istio.yaml and https://storage.googleapis.com/knative-releases/serving/latest/release-lite.yaml

## Steps to Reproduce the Problem

1. follow the doc 
2. execute the script to install knative on openshift

## Additional Info
**Additional context**
n/a

**Install information:**
 - Fedora 30, oc 3.11
 - Knative Version: 0.5

**Comment by abrennan89** [comment]
@samodell @goern 

Hi all. @joaedwar is planning to update the instructions for installation on OpenShift 4 (developer preview), so it might make sense to re-purpose this issue to track that?

@bbrowning FYI

**Comment by samodell** [comment]
That would be great! Feel free to do that.

**Comment by samodell** [comment]
@abrennan89 , if @joaedwar  isn't a member of the Knative org on GitHub, you won't be able to assign to her. If you want to become a member, Joan, I'd be happy to sponsor you! Just let me know.
