### ISSUE TITLE
Update NodeJs demo Spec?

### ISSUE THREAD

**Issue by sfxworks** [knative/docs#1352]
Trying to deploy from the doc referenced here yields this error

```
Error from server (InternalError): error when creating "service.yml": Internal error occurred: admission webhook "webhook.serving.knative.dev" denied the request: mutation failed: cannot decode incoming new object: json: unknown field "spec"
```

## Expected Behavior
It deploys

## Actual Behavior
It doesn't

## Steps to Reproduce the Problem

1. Copy spec located at https://knative.dev/docs/serving/samples/hello-world/helloworld-nodejs/index.html
2. Change the docker repo
3. kubectl create -f thefile.yml

I had to modify the spec to get my demo to work.
https://github.com/sfxworks/knative-demo/commit/ffa3b316abb44da0978553fb44c641ff07918b98#diff-7c8556ea6d72e2b91be78d25d348628a

**Install information:**
 - Platform (GKE, IKS, AKS, etc.): Baremetal
 - Knative Version:
```
NAME         READY   UP-TO-DATE   AVAILABLE   AGE   RELEASE
activator    1/1     1            1           15d   devel
autoscaler   1/1     1            1           15d   devel
controller   1/1     1            1           15d   devel
webhook      1/1     1            1           15d   devel
```

**Comment by kzjackson1** [comment]
\kind needs-eng-input
