### ISSUE TITLE
Knative Build code samples(docs/build/samples.md)

### ISSUE THREAD

**Issue by abhip** [knative/docs#1367]
## Expected Behavior
Whenever I click the hyper link "Learn how to use Knative to build apps from source code and then run those containers." under Complex Code Samples , it should navigate to the link.

## Actual Behavior
Instead I get the following message 

"Page Not Found
Looks like you've followed a broken link or entered a URL that doesn't exist on this site.

 Back to our site"

## Steps to Reproduce the Problem

1. Goto https://knative.dev/docs/build/samples/
2. Click on Learn how to use Knative to build apps from source code and then run those containers. under Complex Code Samples

**Comment by moficodes** [comment]
Looks like the source-to-url folder was removed on knative version 0.0.6

Because the folder is present in version 0.0.5.

I think the team is trying to move the examples out to the community and only hold docs in the main repo.

**Comment by zhangtbj** [comment]
Hi all,
I created a PR to rollback the `source-to-url` folder remove:
https://github.com/knative/docs/pull/1445

I think there is no any error in this `source-to-url` sample, it is better to bring it back and let people can continue learning and try the end-2-end build and deploy process.

An error page is not good user experience.

Hope this is helpful.

**Comment by abrennan89** [comment]
@samodell build is gone now, isn't it? Is there a plan to remove it in the docs?
