### ISSUE TITLE
What is valid ticker for stock in rest-api-go example?

### ISSUE THREAD

**Issue by houshengbo** [knative/docs#1369]
## Expected Behavior
curl http://<url of stock example>/stock/<ticker> to get the price.

## Actual Behavior
I have no idea what ticker is available for this stock example. Where can we find? What is a valid ticker? At least we should offer a valid one as example.

## Steps to Reproduce the Problem

1. Follow the tutorial at https://github.com/knative/docs/tree/master/docs/serving/samples/rest-api-go#sending-requests

## Additional Info
**Additional context**

**Install information:**
 - Platform (GKE, IKS, AKS, etc.):
 - Knative Version:

**Comment by sebgoa** [comment]
A stock market ticker. So AAPL or AMZN or MSFT

**Comment by houshengbo** [comment]
Allow me to add it in the document.
