### ISSUE TITLE
Installing Knative(docs/install/_index.md)

### ISSUE THREAD

**Issue by tmoon8730** [knative/docs#1382]
## Expected Behavior
The "Picking the Right Solution" link would go to a valid page

## Actual Behavior
The "Picking the Right Solution" link redirects to a 404 not found page

## Steps to Reproduce the Problem
1. Click on the link... :)

**Install information:**
 - Documentation Website knative.dev

**Comment by houshengbo** [comment]
The page on https://kubernetes.io/docs/setup/ lists the learning and production environments for kube. I think we can use this link as the hyperlink of "Picking the Right Solution".

**Comment by tmoon8730** [comment]
Not sure if I did the pull request correctly. Someone more knowledgable on this project let me know if I need to do something different with it.

**Comment by tmoon8730** [comment]
Fixed in PR #1397
