### ISSUE TITLE
Install on OpenShift(docs/install/Knative-with-OpenShift.md)

### ISSUE THREAD

**Issue by bradfordcp** [knative/docs#1399]
## Expected Behavior

Istio is installed by copy and pasting the command at 
https://knative.dev/docs/install/knative-with-openshift/#installing-istio

## Actual Behavior

The curl command does not return a valid resource, instead an XML error message is returned.

## Steps to Reproduce the Problem

1. Run the following (per the linked doc)
```
curl -L https://storage.googleapis.com/knative-releases/serving/latest/istio.yaml \
  | sed 's/LoadBalancer/NodePort/' \
  | oc apply --filename -
```

## Additional Info
**Additional context**
N/A

**Install information:**
```
oc version
oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://127.0.0.1:8443
kubernetes v1.11.0+d4cacc0
```

 - Knative Version: v0.6, although it hasn't been installed yet.

**Comment by samodell** [comment]
Thanks for your report, but this looks like a duplicate of #1340 . Work on a fix is in progress, though!

**Comment by bradfordcp** [comment]
No worries, I should have searched before filing. Thanks for the reference.
