### ISSUE TITLE
Missing docs for cluster local setup

### ISSUE THREAD

**Issue by duglin** [knative/docs#1402]
While going thru the setup for Istio-lean everything seems to work except intra-cluster communications between pods.  Thanks to @ZhiminXiang for helping track down that the issue is that https://github.com/knative/docs/blob/master/docs/serving/cluster-local-route.md didn't include the step of adding:
```
local-gateway.cluster-local-gateway: cluster-local-gateway.istio-system.svc.cluster.local
```
to the `config-istio` configMap.  We should add that.

Additionally, this section: https://github.com/knative/docs/blob/master/docs/install/installing-istio.md#updating-your-install-to-use-cluster-local-gateway has a pointer to the `cluster local routes` page but the text there implies it's only needed for "cluster only" routes. So if we add the above configMap data to that page some people may miss it if they want both cluster-local and external routes. I would recommend putting the configMap steps on in this section: https://github.com/knative/docs/blob/master/docs/install/installing-istio.md#updating-your-install-to-use-cluster-local-gateway  

/cc @tcnghia

**Comment by abrennan89** [comment]
@duglin is this issue still valid?

**Comment by duglin** [comment]
Just tried it and it appears we no longer need to manually edit the config map - so we're good. I'll close.
