### ISSUE TITLE
Fix metadata in autoscaling docs

### ISSUE THREAD

**Issue by abrennan89** [knative/docs#1405]
## Expected Behavior
Metadata added to the docs to accommodate publishing for the website shouldn't show up in the .md.

## Actual Behavior
It shows up in the autoscaler docs as title: "Configuring the Autoscaler" weight: 10 type: "docs".

@samodell can you or someone on your team please provide information on how to add metadata properly? Am I missing docs somewhere relating to this (presumably it's for knative.dev)

## Additional Info
**Additional context**
N/A
**Install information:**
N/A

**Comment by samodell** [comment]
I think this is nearly WAI -- the metadata is visible in the .md files, but it will render properly on knative.dev.

I missed that you didn't delete the H1, though. That should've been removed.

**Comment by abrennan89** [comment]
No problem, I'll put in a PR to remove the H1 :) Is there a template or documentation somewhere that explains how to set the metadata properly in a new topic? Apologies if I missed this somewhere - would be useful to have if it exists though.

**Comment by samodell** [comment]
I think @RichieEscarez  is still working on that content. But, back when we did the migration to knative.dev, he made some issues with fairly detailed instructions, which covers the front matter, or the metadata, at the top of the files: #727 

Sorry we don't have it laid out concretely yet! We have a lot of room for improvement in our contributor docs.
