### ISSUE TITLE
No documentation on how to use volumeMounts

### ISSUE THREAD

**Issue by ahmetb** [knative/docs#1413]
/kind bug

I can't seem to find any docs on how to use volumes with Knative serving apps

![image](https://user-images.githubusercontent.com/159209/58824275-87e3a880-85f0-11e9-86f9-6f98ae53448a.png)

The "Code samples" page has 1 "volume" reference and that's the secrets sample: https://knative.dev/docs/serving/samples/secrets-go/index.html which doesn't make it clear that I can pretty much mount any supported Kubernetes volume spec I want here.

**Comment by olegchorny** [comment]
I could be wrong, but only ConfigMaps and Secrets allowed to be mounted as volumes. 
All other forms of volume are disallowed. 
See the https://github.com/knative/serving/pull/3061

**Comment by JRBANCEL** [comment]
Correct, see https://github.com/mattmoor/serving/blob/141ae566cb83077a7fcf7f95eec190ba00160646/pkg/apis/serving/v1alpha1/revision_validation.go#L156

**Comment by rinormaloku** [comment]
Yo! This wasted 2 days of work for me. 
Apparently, the idea behind is to enforce immutability and statelessness of a revision.

But then again, you can easily have a configmap mount it into a container change the configmap and the service wouldn't be immutable, i.e. new instances would have a different configuration. 

The question is are we really achieving immutability? Or am I getting the gist wrong?
