### ISSUE TITLE
Unable to fetch mapping. Do you have indices matching the pattern? Kibana UI

### ISSUE THREAD

**Issue by houshengbo** [knative/docs#1415]
## Expected Behavior
After entering logstash-* into the field of Index pattern, we should be allowed to proceed with further fields.

## Actual Behavior
Unable to fetch mapping. Do you have indices matching the pattern? 
This warning message blocked me from doing anything

## Steps to Reproduce the Problem

1. Follow the section of https://github.com/knative/docs/blob/master/docs/serving/installing-logging-metrics-traces.md#create-elasticsearch-indices and above.

## Additional Info
**Additional context**
All the pods seem running fine.
```
VincentPro:~ vincent$ kubectl get pods --namespace knative-monitoring
NAME                                  READY   STATUS    RESTARTS   AGE
elasticsearch-logging-0               1/1     Running   0          3m16s
elasticsearch-logging-1               1/1     Running   0          2m15s
fluentd-ds-g6cvl                      1/1     Running   0          36s
fluentd-ds-jxvpk                      1/1     Running   0          36s
fluentd-ds-m2wbn                      1/1     Running   0          36s
grafana-848574f8dc-z6stc              1/1     Running   0          5m50s
kibana-logging-7698db4f94-hpbbt       1/1     Running   0          3m16s
kube-state-metrics-5c46b58f6b-nf9bm   4/4     Running   0          5m45s
node-exporter-9s6mg                   2/2     Running   0          5m52s
node-exporter-kvvhf                   2/2     Running   0          5m52s
node-exporter-ntxcg                   2/2     Running   0          5m52s
prometheus-system-0                   1/1     Running   0          5m47s
prometheus-system-1                   1/1     Running   0          5m47s
VincentPro:~ vincent$ kubectl proxy
Starting to serve on 127.0.0.1:8001
```

**Install information:**
 - Platform (GKE, IKS, AKS, etc.): IKS
 - Knative Version: latest source code of master, and 0.6 for knative monitoring

**Comment by samodell** [comment]
These pages were recently update: https://github.com/knative/docs/pull/1568

Closing, since I think the updates might resolve your issue, but please reopen if the the new documentation doesn't help.
