### ISSUE TITLE
Eventing Sources are being renamed to Importers

### ISSUE THREAD

**Issue by grantr** [knative/docs#1417]
## What is changing? (Please include as many details as possible.)

We've decided to rename the Source concept to Importer to better convey its nature and avoid conflict with the CloudEvents concept of source.

## How will this impact our users?
Users will need to learn that the new term (Importer) refers to the same concept and objects as the old term (Source).

## In what release will this take happen (to the best of your knowledge)?
The rename is scheduled for 0.8.

For 0.7, we'd like to prepare users to expect this change. I'm hoping we can add a deprecation notice to the 0.7 docs wherever Source is mentioned saying that the name will soon change to Importer.

## Context
Link to associated PRs or issues from other repos here.

1. https://github.com/knative/eventing-sources/issues/402 rename discussion
1. https://github.com/knative/eventing/pull/1345 recording the decision
1. https://github.com/knative/eventing/issues/1344 tracking issue for rename work

**Comment by grantr** [comment]
The concept of importers has been useful for contributors, but it's not clear that it will be useful for users. We're now leaning against renaming identifiers in the code (see https://github.com/knative/eventing/issues/1344#issuecomment-517875279) and haven't decided how much of the importer concept should be in user docs.

**Comment by samodell** [comment]
Fixed by #1790
