### ISSUE TITLE
GRPC sample docs are not helpful

### ISSUE THREAD

**Issue by rgregg** [knative/docs#1428]
Page: gRPC server - Go 
https://github.com/knative/docs/blob/master/docs/serving/samples/grpc-ping-go/README.md

## Expected Behavior
This page would help me understand how to use GRPC with Knative.

## Actual Behavior
This page tells me only how to use docker to deploy a sample app, with no references to the code, the YAML, or concepts I need to understand to be successful.

**Comment by ahmetb** [comment]
I agree that I struggled quite a bit. Ideally there would be a concept page explaining that gRPC as a protocol is supported, and how to use it (i.e. the short service names like `http://foo` don't work.
