### ISSUE TITLE
Provide a link to the Knative tooling oncall

### ISSUE THREAD

**Issue by rgregg** [knative/docs#1429]
**Describe the change you'd like to see**
For contributors working on the Knative project, knowing who the oncall engineer for our tooling systems is an important detail when Prow or our testing process isn't working right. Today it's buried in a pinned item on the #general channel of Slack.

I think this information should be available/linked from the knative.dev website. The pinned topic links people to this page: https://storage.googleapis.com/knative-infra-oncall/oncall.html

**Comment by abrennan89** [comment]
@rgregg it seems like this link no longer works, but we could still add oncall eng information to docs if its available?

**Comment by evankanderson** [comment]
Ryan moved off the project a bit over a month ago.

/close
