### ISSUE TITLE
e2e tests are failing

### ISSUE THREAD

**Issue by chaodaiG** [knative/docs#1435]
## Expected Behavior
e2e tests pass

## Actual Behavior
e2e tests are failing, timed out but no other useful error message

## Steps to Reproduce the Problem

1. https://storage.googleapis.com/knative-prow/logs/ci-knative-docs-continuous/1137009033794818048/build-log.txt

## Additional Info
**Additional context**

**Install information:**
 - Platform (GKE, IKS, AKS, etc.):
 - Knative Version:

**Comment by adrcunha** [comment]
What about the code here?

```
I0607 15:08:03.285] github.com/knative/docs/test/e2e.checkDeployment(0xc0000d4200, 0xc0000caf80, 0x16, 0xc0000ca280, 0x1c)
I0607 15:08:03.285] 	/go/src/github.com/knative/docs/test/e2e/sampleapptestbase.go:153 +0xcc
I0607 15:08:03.286] github.com/knative/docs/test/e2e.SampleAppTestBase(0xc0000d4200, 0xc000090340, 0xb, 0xc0000ca280, 0x1c, 0xc0000e81c0, 0x3d, 0xc0000caf60, 0x1a, 0xc0000caf80, ...)
I0607 15:08:03.286] 	/go/src/github.com/knative/docs/test/e2e/sampleapptestbase.go:195 +0x6fa
I0607 15:08:03.286] github.com/knative/docs/test/e2e.TestSampleApp.func1(0xc0000d4200)
I0607 15:08:03.286] 	/go/src/github.com/knative/docs/test/e2e/sampleapp_test.go:47 +0x10e
I0607 15:08:03.287] testing.tRunner(0xc0000d4200, 0xc000084e90)
I0607 15:08:03.287] 	/usr/local/go/src/testing/testing.go:865 +0x164
I0607 15:08:03.287] created by testing.(*T).Run
I0607 15:08:03.287] 	/usr/local/go/src/testing/testing.go:916 +0x69a
```

**Comment by adrcunha** [comment]
Other threads were killed around sampleapptestbase.go:157

**Comment by chaodaiG** [comment]
I could repro locally, followed instruction https://github.com/knative/docs/tree/master/docs/serving/samples/hello-world/helloworld-go
And this command failed saying could not find helloworld-go, but helloworld-go does exist in my cluster:
kubectl get ksvc helloworld-go  --output=custom-columns=NAME:.metadata.name,DOMAIN:.status.domain

**Comment by chaodaiG** [comment]
Deploy helloworld-go sample app on knative installed from serving 0.6 release works fine. Deploying the same docker image with same service.yaml failed on knative installed from master nightly release. The error occurs at the command of determining domain:
`kubectl get ksvc helloworld-go --output=custom-columns=NAME:.metadata.name,DOMAIN:.status.domain`
It kept on showing `DOMAIN` as unknow. 
Expanding output with `kubectl get ksvc helloworld-go -oyaml` found out the `domain` doesn't exist under `status`. All the others worked fine

**Comment by chaodaiG** [comment]
Turned out to be `.status.domain` field was deprecated in PR: https://github.com/knative/serving/pull/4197. Filed a bug in knative serving: https://github.com/knative/serving/issues/4297

**Comment by chaodaiG** [comment]
@RichieEscarez FYI

**Comment by chaodaiG** [comment]
fixed 
/close
