### ISSUE TITLE
WORKING-GROUPS.md has missing / incomplete information

### ISSUE THREAD

**Issue by pmorie** [knative/docs#144]
## Expected Behavior

I can see meeting times and zoom/hangout links etc from WORKING-GROUPS.md in this repo.

## Actual Behavior

I can't do this

**Comment by josephburnett** [comment]
I've updated the link for Scaling now that Hangouts Chat took over the meeting.  I don't really know how to create a calendar invite link, so I just posted the day and time.  Invite goes out to knative-dev@ so you should have it.

**Comment by samodell** [comment]
Info in WORKING-GROUPS.md looks up-to-date and complete, so closing this.
