### ISSUE TITLE
IPv6 website enablement

### ISSUE THREAD

**Issue by jpds** [knative/docs#1440]
**Describe the change you'd like to see**

I'd like to see knative.dev accessible via IPv6.

**Comment by RichieEscarez** [comment]
I'll take a look into this soon. It might be a simple button that I need to click in the Netlify UI (the host we use for the site).

**Comment by jpds** [comment]
It would seem that this is the case. :)

- https://www.netlify.com/blog/2018/11/26/announcing-ipv6-support-on-the-netlify-application-delivery-network/
- https://www.netlify.com/docs/dns/#ipv6-traffic

**Comment by samodell** [comment]
@adrcunha  Can you give us input on this? We could do this for the knative.dev domain, but not sure if it something we want to do.

**Comment by adrcunha** [comment]
@samodell Let's sync up in person about this.

**Comment by samodell** [comment]
sounds good! This is really more @RichieEscarez 's domain than mine, so he may set up time with you to discuss.

**Comment by adrcunha** [comment]
This is already setup:

```
$ ping6 www.knative.dev
PING www.knative.dev(2604:a880:400:d1::7ff:b001 (2604:a880:400:d1::7ff:b001)) 56 data bytes
64 bytes from 2604:a880:400:d1::7ff:b001 (2604:a880:400:d1::7ff:b001): icmp_seq=1 ttl=50 time=69.9 ms
64 bytes from 2604:a880:400:d1::7ff:b001 (2604:a880:400:d1::7ff:b001): icmp_seq=2 ttl=50 time=69.5 ms
64 bytes from 2604:a880:400:d1::7ff:b001 (2604:a880:400:d1::7ff:b001): icmp_seq=3 ttl=50 time=69.6 ms
64 bytes from 2604:a880:400:d1::7ff:b001 (2604:a880:400:d1::7ff:b001): icmp_seq=4 ttl=50 time=69.7 ms
```

`[www.]knative.dev` points to `knative.netlify.com` using a CNAME record, so IPv6 support is provided by Netlify. Also, according to Netlify, using `www` is the preferred way to access the site to take advantage of their CDN.

/close
