### ISSUE TITLE
Recent mailing list post exposed problem with minikube settings

### ISSUE THREAD

**Issue by sdake** [knative/docs#1441]
## Expected Behavior

See recent thread here:
https://groups.google.com/forum/#!topic/knative-users/aEDf0pk4qHQ

## Actual Behavior

Some services don't enter running state - instead pending waiting on memory

## Steps to Reproduce the Problem

1. See mailing list for reproducer

## Additional Info
**Additional context**
See this PR for how we changed the minikube requirements for Istio and added additional warnings:
https://github.com/istio/istio.io/issues/4293#issuecomment-500235435

Note memory footprint for demo install of Istio is 8.6gb.  Not sure what footprint is for knative - been awhile since I have taken a look - I should take a look again.  See PR here for more details:
https://github.com/istio/istio.io/pull/4299/files

**Install information:**
 - minikube
- unknown

**Comment by sdake** [comment]
Rendering of the udpated docs for those that don't like to read diffs :)

https://deploy-preview-4299--preliminary-istio.netlify.com/docs/setup/kubernetes/platform-setup/minikube/

**Comment by sebgoa** [comment]
These mem requirements are huge. We should provide a minikube friendly setup that can run on 4GB or less.

**Comment by sdake** [comment]
@sebgoa 4gb...  that is pretty tight.  I think the 8.6gb can be reduced (by just running a minimal istio config) however, I don't think you will see a future where the Istio control plane itself can be deployed in 4gb of ram, much less Istio + knative.

Cheers
-steve

**Comment by sebgoa** [comment]
my thinking is that minikube is a dev environment hence does not need a production config.

The goal of something like minikube is quick start with minimal resources.

If we take istio without mesh then we are just running the ingress gateway and we should be able to disable a few other things to bring the mem requirements down:

see: https://github.com/weaveworks/flagger/blob/master/test/e2e-istio-values.yaml which allegedly runs on 2 GB.

Knative build is deprecated, folks may only want serving at the beginning...so no eventing. That brings it down to 4 containers.
