### ISSUE TITLE
Page needs improvement

### ISSUE THREAD

**Issue by evankanderson** [knative/docs#1446]
## Expected Behavior

"Concepts" LHS item talks about Knative. Link: https://knative.dev/docs/concepts/resources/

## Actual Behavior

"Concepts" LHS talks about a bunch of other related projects.

This is probably part of a larger refactor of the information architecture.

**Comment by samodell** [comment]
@evankanderson  -- I'm not familiar with LHS as an abbreviation; can you spell it out for me?

And yes, in the future we hope to have more topics under that heading than just the resource page you linked.

**Comment by evankanderson** [comment]
LHS = Left Hand Side.

Now that you mention it, that's probably a programming term used in assignment operations. (LHS = thing being assigned to, RHS = expression being computed and assigned)

**Comment by evankanderson** [comment]
"Related Projects" is probably clearer than "Resources", since Kubernetes uses the term "Resource" to denote "Object in the apiserver" with some regularity.

**Comment by abrennan89** [comment]
@evankanderson we can probably close this issue and just revisit this section during the planning session?
I don't know that this issue provides much information about we want to do with this section yet, unless you have some ideas?
