### ISSUE TITLE
https://knative.dev/docs/serving/samples/source-to-url-go can't be reached

### ISSUE THREAD

**Issue by bosaidong** [knative/docs#1449]
## Expected Behavior
Complex code samples
Learn how to use Knative to build apps from source code and then run those containers.

## Actual Behavior
https://knative.dev/docs/serving/samples/source-to-url-go
can't be reached 

## Steps to Reproduce the Problem

https://knative.dev/docs/serving/samples/source-to-url-go  
can't be reached

**Comment by samodell** [comment]
Hi @bosaidong  -- can you let us know where you found that link originally?

**Comment by samodell** [comment]
#1479 states where this link occurs, so I'm closing this one as a duplicate and leaving the other open.
