### ISSUE TITLE
Knative Eventing sources rendering issues (docs/eventing/sources/readme.md)

### ISSUE THREAD

**Issue by rgregg** [knative/docs#1459]
This page renders considerably worse than the version that shows on GitHub. We should figure out how we can tweak the markdown to be more consumable on the website.

https://knative.dev/docs/eventing/sources/

**Comment by justingrayston** [comment]
I am writing this underground in the tube and I have little or no internet.
So apologies for not having more context.

I have no idea how you are serving the docs, but it sounds to me like the
Markdown parsing to HTML is happening on page request.

Why not generate all the HTML for the docs offline on build? Then this
becomes a non problem for the users of the docs. Every page is just static.

**Comment by RichieEscarez** [comment]
Hugo Markdown processor does not like mixed content  (ie Markdown and HTML), especially for content in shortcodes because it can then be sent to the Markdown processor twice (so our HTML gets processed as Markdown).
