### ISSUE TITLE
Add REST API Reference

### ISSUE THREAD

**Issue by xpepermint** [knative/docs#1461]
Kubernetes has a section explaining [REST API Reference](https://kubernetes.io/docs/tasks/access-kubernetes-api/http-proxy-access-api/). Please explain how to manage Knative using REST API.

**Comment by abrennan89** [comment]
@xpepermint the link in this issue looks like it just gives a 404 error, can you provide an updated link for the docs you're referring to please?
There are some API docs in the current build of the docs https://knative.dev/development/reference/api/ but I'm not sure if that helps with your issue.

**Comment by xpepermint** [comment]
@abrennan89 that's a very old issue. I don't remember what I meant :). Closing ...

**Comment by abrennan89** [comment]
Thanks so much @xpepermint !
