### ISSUE TITLE
Code blocks on some pages appear to escape `"` character

### ISSUE THREAD

**Issue by kwyn** [knative/docs#1472]
## Expected Behavior
Code blocks should not escape `"` characters

## Actual Behavior
Code blocks appear to escape `"` as `&#34;`

## Steps to Reproduce the Problem

1. go to https://knative.dev/docs/serving/samples/secrets-go/

## Additional Info
**Additional context**
I'm on Firefox 67.0.2 on MacOS 10.14.5

Screenshot: 
![Screen Shot 2019-06-14 at 2 03 37 PM](https://user-images.githubusercontent.com/5528612/59538444-a5492a00-8eae-11e9-9d4b-f0af3e672ae3.png)

**Comment by sfxworks** [comment]
Just noticed this.
Was going to make a PR to a doc I noticed to correct a python script, but they appear fine in the README files.

**Comment by sfxworks** [comment]
This also applies to single quotes (&#39;)

**Comment by samodell** [comment]
@RichieEscarez  I'm guessing this is happening at build time, since the source seems correct?

**Comment by kwyn** [comment]
Where does the build code live for the document website out of curiosity?

**Comment by RichieEscarez** [comment]
Our website content is located in [knative/website](https://github.com/knative/website). Regarding this issue, i've found a solution (and the cause, which i unintentionally introduced [here](https://github.com/knative/website/pull/53)).

Basically, Hugo had a breaking change type fix for how it treats 'shortcodes'. It improved things by sending the shortcode content to the markdown processor. You can now define if a shortcode gets sent to the markdown processor (use `{{% ...%}}` vs `{{< ... >}}`). 

I found that change can also breaks things (like our double processed quotes) depending on syntax of previously defined shortcodes. The issue in our site is that our use of the `readfile` shortcode ends up sending content to the markdown processor twice. Ive determined how to fix this and need to set up a clean branch before opening a PR. In this effort, ive also determined how to "include" code files, so i also need to separate out that content for a separate PR (re PR #1409 ).

**Comment by kwyn** [comment]
Okay! Let me know if I can help at all. I have so experience with Javascript as well if that's involved at all.

**Comment by RichieEscarez** [comment]
> Okay! Let me know if I can help at all. I have so experience with Javascript as well if that's involved at all.

Will do. No Javascript needed yet but Ill reach out when that day comes.
 And, thanks @kwyn!

**Comment by RichieEscarez** [comment]
Everything is back to normal now!
