### ISSUE TITLE
Remove/Deprecate Build in the docs/website

### ISSUE THREAD

**Issue by dprotaso** [knative/docs#1475]
## What is changing? (Please include as many details as possible.)

Build is deprecated/being removed.

## How will this impact our users?

Docs don't mention this hence users will continue using this without being aware of it's deprecation.

## In what release will this take happen (to the best of your knowledge)?
All

## Context
Link to associated PRs or issues from other repos here.

1. https://github.com/knative/build/issues/614

**Comment by samodell** [comment]
No immediate action should be taken. Waiting on https://github.com/knative/build/issues/614
