### ISSUE TITLE
[Proposal] Apply a kind/proposal label for all Knative proposals

### ISSUE THREAD

**Issue by RichieEscarez** [knative/docs#1476]
For tracking and awareness across all Knative repos, can we update our process to require the `kind/proposal` label for any proposal created in any repo?

Using a label for all proposals could increase awareness and will allow simple tracking (you can view a list of all proposals on a single page):

https://github.com/search?q=org%3Aknative+label%3Akind%2Fproposal

Having a single reference point will reduce both the need to click through the multiple repo artifacts (WG meeting notes, individual repo issues, etc.), and the potential to miss a big change that's in the works.

It looks like knative/eventing is already using the label and I've just added that label to both the knative/docs and knative/website repos.

Can we get the other owners to create new `kind/proposal` labels and then apply them to any current and all future proposals?

Attn: Steering commitee and TOC:
cc/ @rgregg @evankanderson

**Comment by evankanderson** [comment]
What do you expect the semantics of `kind/proposal` to be? I'm not sure it's aligned right now. Which of the following would you expect to be tagged?

* Major engineering re-architecture which doesn't have direct user impact?
* Suggested process change around bug triage?
* New feature on an existing custom resource?
* New custom resource which is user-facing?
* New custom resource which is inernal?
* Enabling a field from `corev1.Container` which is currently validated out?
* Testing plan for scalability testing of a component?

**Comment by evankanderson** [comment]
Added to the June 20 TOC meeting

**Comment by RichieEscarez** [comment]
Good question. The docs team is most concerned with "external facing changes" and I envision this as being one possible 'tool' for determining what might or is going into the V.next release. 

If we were to narrow the scope of this down to just what the docs team would find most useful, I would expect the `kind/proposal` label on:

* any external change that impacts users (of which might, or does require some form of communication or documentation). 
* [nice to have] notifications for new proposals that get added to that list

If others find this useful (for other use cases) then perhaps we can discuss options, like other qualifying labels or perhaps how to utilize prow (ie. dashboards with a "user-facing" section along side any other useful section(s)?).

For example, I didn't know that [this Tekton Proposal](https://github.com/knative/build/issues/614) existed  (for one reason or another), and I think having a single point of reference to view potential "doc-impact-items" would be most efficient and effective (whether or not that's a query or something more in-depth (prow?)).

**Comment by RichieEscarez** [comment]
Closing. Post TOC discussion. TODO: work with @eallred-google to define a formal process for flagging external facing change
