### ISSUE TITLE
Broken link 

### ISSUE THREAD

**Issue by michael-serchenia** [knative/docs#1479]
i've found broken link, 
https://knative.dev/docs/serving/
link:  [Source-to-URL with Knative Serving](https://knative.dev/docs/serving/samples/source-to-url-go/index.html)

**Comment by samodell** [comment]
Thanks for opening an issue, but this is a duplicate of #1449

**Comment by samodell** [comment]
Actually, I'm going to close the other one, since this clearly calls out where the link was found.
