### ISSUE TITLE
code format error when use "

### ISSUE THREAD

**Issue by zgfh** [knative/docs#1509]
## Expected Behavior
https://knative.dev/docs/serving/samples/hello-world/helloworld-go/
```
  git clone -b "release-0.6" https://github.com/knative/docs knative-docs

```

## Actual Behavior

```
  git clone -b &#34;release-0.6&#34; https://github.com/knative/docs knative-docs

```

**Comment by samodell** [comment]
Thanks for opening this issue, but I'll have to close it out since it's a duplicate of #1472
