### ISSUE TITLE
quotes " are rendered incorrectly across the site as &#34

### ISSUE THREAD

**Issue by csantanapr** [knative/docs#1527]
quotes " are rendered incorrectly across the site as &#34

Visit a page with terminal or code sample with quotes "
https://knative.dev/development/serving/samples/hello-world/helloworld-go/index.html
You see it's rendered incorrectly :
![image](https://user-images.githubusercontent.com/1094878/60143903-7e340780-978e-11e9-87a9-e974f572d461.png)

Original markdown is correct:
https://github.com/knative/docs/blob/master/docs/serving/samples/hello-world/helloworld-go/README.md

**Comment by csantanapr** [comment]
It's not just quotes but also any other none alphanumeric character

![image](https://user-images.githubusercontent.com/1094878/60145521-4a5be080-9794-11e9-8222-897fa1bc97c9.png)

**Comment by samodell** [comment]
True! This is a known issue, and @RichieEscarez  is working on it. Closing this in favor #1472 , though.
