### ISSUE TITLE
Hardcoded links to Knative/eventing* repos are not versioned

### ISSUE THREAD

**Issue by RichieEscarez** [knative/docs#1534]
Hardcoded links to content that lives in the knative/eventing and knative/eventing-contrib repos should not point to the `master` branch in those repos for "versioned/releases content/branches".

[Seach results of bad links](https://github.com/knative/docs/search?q=%22https%3A%2F%2Fgithub.com%2Fknative%2F%22+%26+%22%2Fmaster%2F%22&unscoped_q=%22https%3A%2F%2Fgithub.com%2Fknative%2F%22+%26+%22%2Fmaster%2F%22)

Resolution:
- Determine if that link is outdated and can point to a relative page in Knative.dev
- Replace the URL with the corresponding "release version". For example replace `/blob/master/` with [`/tree/v0.7.0`](https://github.com/knative/eventing/tree/v0.7.0).
- (WIP) Replace link to code with a `readfile` short code (to include/render relative file)

cc/ @vaikas-google

**Comment by abrennan89** [comment]
Ties into any renaming of "master" branch happening in eng.
@markusthoemmes any updates on that yet?
