### ISSUE TITLE
Heads up: Go Import paths that used github.com/knative/pkg are now knative.dev/pkg

### ISSUE THREAD

**Issue by n3wscott** [knative/docs#1541]
Go Import paths that used `github.com/knative/pkg/*` are now `knative.dev/pkg/*`

**Comment by kzjackson1** [comment]
@n3wscott Would action should the docs team take on this issue? Thanks!

**Comment by carieshmarie** [comment]
Hey Scott - as mentioned in yesterday's WG, can you follow up on this issue and close or fix? Thanks!

**Comment by abrennan89** [comment]
@n3wscott any updates here?

**Comment by abrennan89** [comment]
No response so I am closing this issue. Please reach out if there's still a requirement here @n3wscott
