### ISSUE TITLE
gen-api-reference-docs API docs build script limitations

### ISSUE THREAD

**Issue by RichieEscarez** [knative/docs#1559]
The https://github.com/knative/docs/blob/master/hack/gen-api-reference-docs.sh API docs build script currently has the following issues:

(1)
The HTML output is incorrectly picking up a closing parenthesis from the API comment:
https://github.com/knative/eventing-contrib/blob/9d20f1c0ceeffd937d70d77abbea8bb1df3c32f3/contrib/gcppubsub/pkg/apis/sources/v1alpha1/gcp_pubsub_types.go#L58

The 404 is caused by a closing parenthesis `)`:
![image](https://user-images.githubusercontent.com/11762685/60372017-0513fa80-99b0-11e9-845b-0ff09a60e00e.png)

(2)
Some Packages are duplicated or appear to be duplicated (lack version qualifier):

![image](https://user-images.githubusercontent.com/11762685/60372089-44dae200-99b0-11e9-843f-8030dfb22f47.png)

![image](https://user-images.githubusercontent.com/11762685/60372132-6e940900-99b0-11e9-989f-cbb4e6ccfe9d.png)

Manual changes that are currently required in the HTML output:

### eventing-contrib-resources.md:

- remove duplicate Packages links
- remove duplicate section titles 
- consolidate Resource Types into single list
![image](https://user-images.githubusercontent.com/11762685/60373681-e153b300-99b5-11e9-9f3a-100ec2c703ec.png)
Example of removing the duplicate section titles and moving the Resource Types into the consolidated list:
![image](https://user-images.githubusercontent.com/11762685/60373958-fbda5c00-99b6-11e9-90a8-2de31dbd9f57.png)

### serving.md:

- Qualify v1alpha1 vs v1beta1 
   - fix Packages list
   - fix link IDs
   - fix Section titles
![image](https://user-images.githubusercontent.com/11762685/60373713-00eadb80-99b6-11e9-9236-ec7c24570899.png)
![image](https://user-images.githubusercontent.com/11762685/60373783-51623900-99b6-11e9-89b0-3a8a937a24c4.png)
![image](https://user-images.githubusercontent.com/11762685/60373794-5aeba100-99b6-11e9-8c05-3bcce9d5a763.png)

**Comment by ahmetb** [comment]
@RichieEscarez going forward it would be ideal to create these issues on the tool's repo (or in both places).

Looks like we can't fix the closing parents included in the links. https://github.com/ahmetb/gen-crd-api-reference-docs/issues/8 I recommend adding a space before them in the code. Feel free to make the PRs. I suspect it's not a big issue.

**Comment by RichieEscarez** [comment]
Parenthesis issue is tracked in https://github.com/ahmetb/gen-crd-api-reference-docs/issues/8
