### ISSUE TITLE
Sample app not working in an environment without direct internet connection

### ISSUE THREAD

**Issue by marcoliceti** [knative/docs#1574]
## Expected Behavior

The sample app should return an hello world message.

## Actual Behavior

It returns a 404 instead.

## Steps to Reproduce the Problem

1. Install Minikube.
2. [Install Knative](https://knative.dev/docs/install/knative-with-minikube/).
3. [Deploy the app](https://knative.dev/docs/install/getting-started-knative-app/).

## Additional Info
**Additional context**
I'm using a CNTLM proxy, so I started Minikube like this:

```
HTTP_PROXY=http://10.0.2.2:3128 HTTPS_PROXY=http://10.0.2.2:3128 NO_PROXY=localhost,127.0.0.1,10.96.0.0/12,192.168.99.1/24 minikube start --memory=16000 --cpus=6   --disk-size=30g   --extra-config=apiserver.enable-admission-plugins="LimitRanger,NamespaceExists,NamespaceLifecycle,ResourceQuota,ServiceAccount,DefaultStorageClass,MutatingAdmissionWebhook"
```
(see [these instructions](https://github.com/kubernetes/minikube/blob/master/docs/http_proxy.md) for using Minikube behind a proxy)

With these settings I can log into the VM (`minikube ssh`) and pull docker images (`docker run gcr.io/knative-samples/helloworld-go` works fine).

Unfortunately, when I deploy the sample app, something goes wrong when fetching the image of the sample app (`gcr.io`  isn't resolved):

```
$ kubectl describe ksvc/helloworld-go
Name:         helloworld-go
Namespace:    default
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"serving.knative.dev/v1alpha1","kind":"Service","metadata":{"annotations":{},"name":"helloworld-go","namespace":"default"},"...
              serving.knative.dev/creator: minikube-user
              serving.knative.dev/lastModifier: minikube-user
API Version:  serving.knative.dev/v1beta1
Kind:         Service
Metadata:
  Creation Timestamp:  2019-07-04T14:20:10Z
  Generation:          1
  Resource Version:    2899
  Self Link:           /apis/serving.knative.dev/v1beta1/namespaces/default/services/helloworld-go
  UID:                 e1de2a8f-d06e-4a23-a745-b4805ea3ef0b
Spec:
  Template:
    Metadata:
      Creation Timestamp:  <nil>
    Spec:
      Containers:
        Env:
          Name:   TARGET
          Value:  Go Sample v1
        Image:    gcr.io/knative-samples/helloworld-go
        Name:     user-container
        Resources:
      Timeout Seconds:  300
  Traffic:
    Latest Revision:  true
    Percent:          100
Status:
  Conditions:
    Last Transition Time:        2019-07-04T14:20:10Z
    Message:                     Revision "helloworld-go-2fp5l" failed with message: Unable to fetch image "gcr.io/knative-samples/helloworld-go": Get https://gcr.io/v2/: dial tcp: lookup gcr.io on 10.96.0.10:53: no such host.
    Reason:                      RevisionFailed
    Status:                      False
    Type:                        ConfigurationsReady
    Last Transition Time:        2019-07-04T14:20:10Z
    Message:                     Revision "helloworld-go-2fp5l" failed with message: Unable to fetch image "gcr.io/knative-samples/helloworld-go": Get https://gcr.io/v2/: dial tcp: lookup gcr.io on 10.96.0.10:53: no such host.
    Reason:                      RevisionFailed
    Status:                      False
    Type:                        Ready
    Last Transition Time:        2019-07-04T14:20:10Z
    Message:                     The Route is still working to reflect the latest desired specification.
    Reason:                      OutOfDate
    Status:                      Unknown
    Type:                        RoutesReady
  Latest Created Revision Name:  helloworld-go-2fp5l
  Observed Generation:           1
Events:
  Type    Reason   Age                From                Message
  ----    ------   ----               ----                -------
  Normal  Created  18m                service-controller  Created Configuration "helloworld-go"
  Normal  Created  18m                service-controller  Created Route "helloworld-go"
  Normal  Updated  18m (x2 over 18m)  service-controller  Updated Service "helloworld-go"
```

**Install information:**
 - Platform: Minikube (VirtualBox)
 - Knative Version: 0.7.0

**Comment by Baykonur** [comment]
why was this issue closed without any solution proposed?

**Comment by samodell** [comment]
Hmm, we've been able to successfully deploy the sample app, so we thought this may have been resolved in a subsequent Knative release. @Baykonur  have you run into this failure too?

**Comment by Baykonur** [comment]
@samodell , sorry I did not know you were at the reporter's side. Yes I have this exact issue: `Get https://gcr.io/v2/: dial tcp: lookup gcr.io on 10.96.0.10:53: no such host`, I am pretty sure because of our corporate proxy server, if I try to launch for an image which is from our internal repo, then it works.

**Comment by JCzz** [comment]
I have the same problem:

Env: 
```
- GKE
- https://github.com/knative/serving/releases/download/v0.9.0/serving.yaml 

kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.7", GitCommit:"8fca2ec50a6133511b771a11559e24191b1aa2b4", GitTreeState:"clean", BuildDate:"2019-09-18T14:47:22Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.6-gke.2", GitCommit:"c9de33b5439df6e206d7ba646787c6ace92d737b", GitTreeState:"clean", BuildDate:"2019-09-06T18:30:33Z", GoVersion:"go1.12.9b4", Compiler:"gc", Platform:"linux/amd64"}

```

knative yaml: hello.yaml
```
apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: go-hello-world
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
        - image: gcr.io/knative-samples/helloworld-go
          ports:
            - name: http1
              containerPort: 8080
```
No reply:
`curl -H "Host: http://go-hello-world.default.example.com" http://${IP_ADDRESS}`

**Comment by ayqazi** [comment]
It is the mid-2020s, and I have the same issue.

I followed the steps here (for example) to the letter: https://github.com/knative/docs/tree/master/docs/serving/samples/hello-world/helloworld-ruby

and here is the result when I try to get the URL:

```
$ kubectl get ksvc helloworld-ruby
NAME              URL                                          LATESTCREATED           LATESTREADY   READY   REASON
helloworld-ruby   http://helloworld-ruby.default.example.com   helloworld-ruby-55h75                 False   RevisionMissing
```

**Comment by charuni2018** [comment]
Hi Even I am facing the same issue and this is when I am using the image in my private Repo but still the sample ksvc states as Revision Missing. Any idea what is wrong wiht this ?

**Comment by tcnghia** [comment]
cc @vagababov

**Comment by vagababov** [comment]
Can you get the logs from knative-serving/controller-XXXXX pod to see what is the exact error you're getting?

**Comment by julz** [comment]
Agree that logs would be helpful. FWIW this looks to me like what may be happening is that you've set up HTTP_PROXY so that kubelet can resolve images, but our controller - which _also_ tries to talk to the registry to resolve the image digest - doesn't get passed that env variable and therefore can't get past the proxy. I think you may be able to set the HTTP_PROXY environment variable for the controller container (via [the env section in controller.yaml](https://github.com/knative/serving/blob/master/config/core/deployments/controller.yaml#L60)) so that we can access the registry.

**Comment by vagababov** [comment]
I think by default Transport uses https://golang.org/pkg/net/http/#ProxyFromEnvironment and we clone it, so it should be using the proxy set in the envvars.

**Comment by julz** [comment]
It does @vagababov, but I wonder if that environment variable gets propagated down to the inner containers - like our controller - by minikube or not (as opposed to just being propagated to the kubelet). Printing out HTTP_PROXY from inside a container in a local minikube just now, it looks like it doesn't -- but setting it in controller.yaml might do it.

**Comment by vagababov** [comment]
Yeah, it is worth trying.

**Comment by charuni2018** [comment]
Let me tell you what all I did in brief .. 
1. Install Istio and then knative serving all went smooth.
2. I installed the helloworld ksvc having the image using my local repo but when I do a kubectl get all -n default I see the ksvc deployment shows Revision Failed:

NAME                                  TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                             AGE
service/my-helloworld-w9gbs           ClusterIP   10.100.x.x    <none>        80/TCP                              2d22h
service/my-helloworld-w9gbs-private   ClusterIP   10.100.x.x  <none>        80/TCP,9090/TCP,9091/TCP,8022/TCP   2d22h

NAME                                             READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/my-helloworld-w9gbs-deployment   0/0     0            0           2d22h

NAME                                                        DESIRED   CURRENT   READY   AGE
replicaset.apps/my-helloworld-w9gbs-deployment-7bc65d557b   0         0         0       2d22h

NAME                                              LATESTCREATED         LATESTREADY   READY   REASON
configuration.serving.knative.dev/my-helloworld   my-helloworld-w9gbs                 False   RevisionFailed

NAME                                               CONFIG NAME     K8S SERVICE NAME      GENERATION   READY   REASON
revision.serving.knative.dev/my-helloworld-w9gbs   my-helloworld   my-helloworld-w9gbs   1            False   ProgressDeadlineExceeded

NAME                                        URL   LATESTCREATED         LATESTREADY   READY   REASON
service.serving.knative.dev/my-helloworld         my-helloworld-w9gbs                 False   RevisionFailed

3. Post which to solve this I followed some blog and added the env in controller.yaml deployment for http_prox https_prox & no proxy and then my controller.yaml started failing

So my main problem is my sample ksvc is not working for which I am trying to find fix for it in a private n/w.

**Comment by julz** [comment]
@charuni2018 could you please share the logs / error message from the failing container? (Also which blog is it you were following in step 3?)

**Comment by markusthoemmes** [comment]
Just to add regarding HTTP_PROXY values etc: You do have to set them explicitly on containers. They are not propagated via the kubelet.

**Comment by charuni2018** [comment]
These are the errors in the controller.yaml pod $ kubectl.exe  logs pod/controller-8b4848bbf-jzbhz -n knative-serving
2020/10/12 06:58:20 maxprocs: Updating GOMAXPROCS=1: determined from CPU quota
2020/10/12 06:58:20 Registering 5 clients
2020/10/12 06:58:20 Registering 5 informer factories
2020/10/12 06:58:20 Registering 12 informers
2020/10/12 06:58:20 Registering 7 controllers
2020/10/12 06:58:25 Error reading/parsing logging configuration: timed out waiting for the condition

Or if you can suf=ggest me what need to be done for the ksvc to work in On Prem K8S as I can bring back my ksvc pods running after removing the proxy parameters. I am trying the find the blog which I followed and will post it as I find it. Thanks a lot again for giving your inputs so promptly.

**Comment by julz** [comment]
Hmm.. did you add the `NO_PROXY` environment variable to controller.yaml or only the `HTTP_PROXY` env var? Without NO_PROXY _everything_ would be trying to go through the proxy, even internal stuff that the proxy can't resolve, which could explain stuff timing out

**Comment by markusthoemmes** [comment]
In particular, the host of your Kubernetes API should probably be part of the `NO_PROXY` environment.

**Comment by charuni2018** [comment]
- name: CONFIG_LOGGING_NAME
          value: config-logging
        - name: CONFIG_OBSERVABILITY_NAME
          value: config-observability
        - name: METRICS_DOMAIN
          value: knative.dev/internal/serving
        - name: http_proxy
          value: $$$$
        - name: https_proxy
          value: $$$$
        - name: no_proxy
          value: 10.100.x.x

So you mean to mention the Kubernets API to be given or the ClusterIP of the HelloWorld service ?

**Comment by evankanderson** [comment]
We don't currently have any testing for disconnected / proxy-required operation of Knative.

This is a reasonable thing to want to do, but we don't currently have working instructions, nor a test environment to keep it working. If someone wants to work on that, the [operations WG](https://github.com/knative/operator) might be a reasonable place to collaborate.

Without a test environment, any directions we write / debugging that happens in this issue are likely to rot over time. I'd be happy to help someone who wanted to work on this, but I don't expect that the documentation will appear without some substantial (1-2 weeks) engineering effort.

**Comment by abrennan89** [comment]
/close
Closing based on @evankanderson 's comment. Please feel free to reopen if this info ever becomes available / an owner is found, otherwise this issue is 2+ years old and can't actually be solved by docs alone.
