### ISSUE TITLE
Install on OpenShift(docs/install/Knative-with-OpenShift.md)

### ISSUE THREAD

**Issue by skuehnlein** [knative/docs#1575]
Hallo 
I'm trying to install Knative on an OpenShift cluster which I have started with oc cluster up. The cluster is working 
When I try to install Istio with the command 
curl -L https://storage.googleapis.com/knative-releases/serving/latest/istio.yaml \
   | sed 's/LoadBalancer/NodePort/' \
   | oc apply --filename -

I get an error.

error: unable to decode "STDIN": Object 'Kind' is missing in '{"\u003c?xml version='1.0' encoding='UTF-8'?\u003e\u003cError\u003e\u003cCode\u003eNoSuchKey\u003c/Code\u003e\u003cMessage\u003eThe specified key does not exist.\u003c/Message\u003e\u003cDetails\u003eNo such object":"knative-releases/serving/latest/istio.yaml\u003c/Details\u003e\u003c/Error\u003e"}'

## Expected Behavior
Istio should be installed

## Actual Behavior
error: unable to decode "STDIN": Object 'Kind' is missing in '{"\u003c?xml version='1.0' encoding='UTF-8'?\u003e\u003cError\u003e\u003cCode\u003eNoSuchKey\u003c/Code\u003e\u003cMessage\u003eThe specified key does not exist.\u003c/Message\u003e\u003cDetails\u003eNo such object":"knative-releases/serving/latest/istio.yaml\u003c/Details\u003e\u003c/Error\u003e"}'

## Steps to Reproduce the Problem

1. Executing the following statement
curl -L https://storage.googleapis.com/knative-releases/serving/latest/istio.yaml \
  | sed 's/LoadBalancer/NodePort/' \
  | oc apply --filename -

**Comment by joaedwar** [comment]
Hallo 
The curl command does not return a valid resource, instead an XML error message is returned.

Istio is installed when you install Knative serving. Please see updated documentation [here](https://github.com/knative/docs/blob/master/docs/install/Knative-with-OpenShift.md). This documentation walks you through installing Knative Serving  (as well as Istio) via an operator.

or

for Knative you can also try to use the link provided in the knative github repository --> https://raw.githubusercontent.com/knative/serving/master/third_party/istio-1.1.7/istio.yaml
https://knative.dev/docs/install/knative-with-minikube/ is an updated URL for installing with minkube.
