### ISSUE TITLE
Impossible to deploy app on Knative with Gloo

### ISSUE THREAD

**Issue by marcoliceti** [knative/docs#1576]
## Expected Behavior

The [hello world go app](https://knative.dev/docs/install/getting-started-knative-app/) should be deployable.

## Actual Behavior

It fails:

```
$ kubectl apply --filename service.yaml
Error from server (InternalError): error when creating "service.yaml": Internal error occurred: admission webhook "webhook.serving.knative.dev" denied the request: mutation failed: cannot decode incoming new object: json: unknown field "template"
```

## Steps to Reproduce the Problem

1. Install and start Minikube.
2. [Install Gloo and Knative](https://knative.dev/docs/install/knative-with-gloo/).
3. [Try to deploy the sample app](https://knative.dev/docs/install/getting-started-knative-app/).

## Additional Info

**Install information:**
 - Platform: Minikube
 - Knative Version: 0.7.0

**Comment by marcoliceti** [comment]
I noticed that `service.yaml` in the example [from KNative docs](https://knative.dev/docs/install/getting-started-knative-app/) has a different format than the one [from Gloo's documentation](https://gloo.solo.io/user_guides/knative/).

Maybe the documentation has to be updated to this new format?

**Comment by CelsoSantos** [comment]
I'm also facing the same issue..
