### ISSUE TITLE
"Gateway" not recognized: Install on Google Kubernetes Engine(docs/install/Knative-with-GKE.md)

### ISSUE THREAD

**Issue by arindam-b** [knative/docs#1578]
#470  Expected Behavior

While installing knative serving on GKE, getting the following error:

```
kubectl apply --filename https://github.com/knative/serving/releases/download/v0.7.0/serving.yaml
```

## Actual Behavior
following error encountered:

```
unable to recognize "https://github.com/knative/serving/releases/download/v0.7.0/serving.yaml": no matches for kind "Gateway" in version "networking.istio.io/v1alpha3"
unable to recognize 
```

Followed exactly the recommended procedure.

So when I tried to search knative-ingressgateway, it fails:

```
kubectl get service --namespace=istio-system knative-ingressgateway

Error from server (NotFound): services "knative-ingressgateway" not found
```

**Install information:**
 - Platform (GKE): 1.13.7-gke.8
 - Knative Version: v0.7

Any wayout?

**Comment by toshi0607** [comment]
I faced same error. But in my case (versions of GKE and Knative are same), when creating cluster, I forgot to add `--addons=HorizontalPodAutoscaling,HttpLoadBalancing,Istio` and failed to install Istio.
You can check whether Istio is enabled or not by clicking cluster name on GKE console.

```
$ gcloud beta container clusters create $CLUSTER_NAME \
  --addons=HorizontalPodAutoscaling,HttpLoadBalancing,Istio \
  --machine-type=n1-standard-4 \
  --cluster-version=latest --zone=$CLUSTER_ZONE \
  --enable-stackdriver-kubernetes --enable-ip-alias \
  --enable-autoscaling --min-nodes=1 --max-nodes=10 \
  --enable-autorepair \
  --scopes cloud-platform

$ kubectl create clusterrolebinding cluster-admin-binding \
  --clusterrole=cluster-admin \
  --user=$(gcloud config get-value core/account)
```

**Comment by arindam-b** [comment]
Thanks, I did not keep HorizontalPodAutoscaling before. So it did not work.
