### ISSUE TITLE
Install on Minikube(docs/install/Knative-with-Minikube.md)

### ISSUE THREAD

**Issue by rranjan-us** [knative/docs#1601]
## Expected Behavior
No error when install of knative CRDs

## Actual Behavior
Message like "unable to recognize "https://github.com/knative/serving/releases/download/v0.7.0/serving.yaml": no matches for kind "Image"" seen after following step to install knative CRD as per the online documentation. 

## Steps to Reproduce the Problem

1. Follow all the steps for v0.7 (https://knative.dev/docs/install/knative-with-minikube/)
2. On the step to install knative CRDs ("To install Knative, first install the CRDs by running"), the output includes the ominous message.  Impact is not clear from the message if user should continue or stop with install. 

## Additional Info
**Additional context**

**Install information:**
 - Platform (GKE, IKS, AKS, etc.): Followed all the steps as 0.7 install documentation (https://knative.dev/docs/install/knative-with-minikube/).
 - Knative Version: 0.7

ubectl apply --selector knative.dev/crd-install=true \
>    --filename https://github.com/knative/serving/releases/download/v0.7.0/serving.yaml \
>    --filename https://github.com/knative/build/releases/download/v0.7.0/build.yaml \
>    --filename https://github.com/knative/eventing/releases/download/v0.7.0/release.yaml \
>    --filename https://github.com/knative/serving/releases/download/v0.7.0/monitoring.yaml
customresourcedefinition.apiextensions.k8s.io/certificates.networking.internal.knative.dev created
customresourcedefinition.apiextensions.k8s.io/clusteringresses.networking.internal.knative.dev created
customresourcedefinition.apiextensions.k8s.io/configurations.serving.knative.dev created
customresourcedefinition.apiextensions.k8s.io/images.caching.internal.knative.dev created
customresourcedefinition.apiextensions.k8s.io/ingresses.networking.internal.knative.dev created
customresourcedefinition.apiextensions.k8s.io/podautoscalers.autoscaling.internal.knative.dev created
customresourcedefinition.apiextensions.k8s.io/revisions.serving.knative.dev created
customresourcedefinition.apiextensions.k8s.io/routes.serving.knative.dev created
customresourcedefinition.apiextensions.k8s.io/services.serving.knative.dev created
customresourcedefinition.apiextensions.k8s.io/serverlessservices.networking.internal.knative.dev created
customresourcedefinition.apiextensions.k8s.io/builds.build.knative.dev created
customresourcedefinition.apiextensions.k8s.io/buildtemplates.build.knative.dev created
customresourcedefinition.apiextensions.k8s.io/clusterbuildtemplates.build.knative.dev created
customresourcedefinition.apiextensions.k8s.io/images.caching.internal.knative.dev unchanged
customresourcedefinition.apiextensions.k8s.io/apiserversources.sources.eventing.knative.dev created
customresourcedefinition.apiextensions.k8s.io/brokers.eventing.knative.dev created
customresourcedefinition.apiextensions.k8s.io/channels.eventing.knative.dev created
customresourcedefinition.apiextensions.k8s.io/clusterchannelprovisioners.eventing.knative.dev created
customresourcedefinition.apiextensions.k8s.io/containersources.sources.eventing.knative.dev created
customresourcedefinition.apiextensions.k8s.io/cronjobsources.sources.eventing.knative.dev created
customresourcedefinition.apiextensions.k8s.io/eventtypes.eventing.knative.dev created
customresourcedefinition.apiextensions.k8s.io/sequences.messaging.knative.dev created
customresourcedefinition.apiextensions.k8s.io/subscriptions.eventing.knative.dev created
customresourcedefinition.apiextensions.k8s.io/triggers.eventing.knative.dev created
customresourcedefinition.apiextensions.k8s.io/inmemorychannels.messaging.knative.dev created
unable to recognize "https://github.com/knative/serving/releases/download/v0.7.0/serving.yaml": no matches for kind "Image" in version "caching.internal.knative.dev/v1alpha1"
unable to recognize "https://github.com/knative/build/releases/download/v0.7.0/build.yaml": no matches for kind "Image" in version "caching.internal.knative.dev/v1alpha1"
unable to recognize "https://github.com/knative/build/releases/download/v0.7.0/build.yaml": no matches for kind "Image" in version "caching.internal.knative.dev/v1alpha1"
unable to recognize "https://github.com/knative/build/releases/download/v0.7.0/build.yaml": no matches for kind "Image" in version "caching.internal.knative.dev/v1alpha1"
unable to recognize "https://github.com/knative/build/releases/download/v0.7.0/build.yaml": no matches for kind "Image" in version "caching.internal.knative.dev/v1alpha1"
unable to recognize "https://github.com/knative/eventing/releases/download/v0.7.0/release.yaml": no matches for kind "ClusterChannelProvisioner" in version "eventing.knative.dev/v1alpha1"

**Comment by samodell** [comment]
This is a known, documented issue. Simply re-run the commands and the install will succeed on the second try.
