### ISSUE TITLE
Update Installation instruction for Knative 0.8 release

### ISSUE THREAD

**Issue by ZhiminXiang** [knative/docs#1614]
**Describe the change you'd like to see**
As we will separate cert-manager related components from serving.yaml in our Knative 0.8 release, we need to update the installation instructions accordingly especially the parts related to cert-manager.

Here is the PR in the knative/serving side about the change of yaml generation: https://github.com/knative/serving/pull/4819

**Comment by rgregg** [comment]
Please include the changes that need to be made to the documentation for this and provide recommendations for how to install cert-manager separately.
