### ISSUE TITLE
Cron job source example(docs/eventing/samples/cronjob-source/_index.md)

### ISSUE THREAD

**Issue by moficodes** [knative/docs#1622]
## Expected Behavior
The code snippet should render single quote (') and double quote (") as is.

## Actual Behavior
In the code snippets for examples in the knative.dev website, single quote (') and double quote (") is not rendering right.

```
apiVersion: sources.eventing.knative.dev/v1alpha1
kind: CronJobSource
metadata:
  name: test-cronjob-source
spec:
  schedule: &#34;*/2 * * * *&#34;
  data: &#39;{&#34;message&#34;: &#34;Hello world!&#34;}&#39;
  sink:
    apiVersion: serving.knative.dev/v1alpha1
    kind: Service
    name: event-display
```

## Steps to Reproduce the Problem
Pretty much anywhere there is a quote 
e.g - https://knative.dev/docs/eventing/samples/cronjob-source/

**Comment by abrennan89** [comment]
@moficodes are you still encountering this issue?
It looks like its rendering fine to me at https://knative.dev/docs/eventing/samples/cronjob-source/
