### ISSUE TITLE
Knative Eventing page has inaccurate dependencies (docs/eventing/readme.md)

### ISSUE THREAD

**Issue by kzjackson1** [knative/docs#1630]
## Expected Behavior
As Knative Eventing and Knative serving are separate components, there should be no dependencies between the two components. 

## Actual Behavior

- "Knative Eventing currently requires Knative Serving and Istio version 1.0 or later installed."
- The "Getting Started" Section links to Knative Serving as well.

## Steps to Reproduce the Problem

N/A

## Additional Info
**Additional context**

**Install information:**
 - Platform (GKE, IKS, AKS, etc.): N/A
 - Knative Version: N/A

**Comment by abrennan89** [comment]
Hi @kzjackson1 
I think the issue relating to dependencies in the install guide has been fixed during the install docs overhaul: https://knative.dev/docs/install/any-kubernetes-cluster/
Let me know if that solves the issue for you.

Thanks!
