### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by RichieEscarez** [knative/docs#1633]
The following pages have one or more links that result in a 404:

- [x] https://knative.dev/docs/serving/using-a-tls-cert/
- [x] https://knative.dev/docs/install/knative-custom-install/ (3 total)
- [x] https://knative.dev/docs/install/installing-istio/
- [x] https://knative.dev/docs/build/samples/
- [x] https://knative.dev/docs/serving/
- [x] https://knative.dev/docs/serving/fluentd-requirements/
_- [ ] https://knative.dev/docs/serving/cluster-local-route/_ (This page doesn't have a broken link now?)
- [x] https://knative.dev/docs/serving/debugging-performance-issues/
_- [ ] https://knative.dev/docs/serving/samples/hello-world/helloworld-java-spark/_ (This page doesn't have a broken link now?)
- [x] https://knative.dev/docs/serving/samples/hello-world/helloworld-shell/
- [x] https://knative.dev/docs/eventing/ (This links correcly to default-channels, which is a real file that exists, but it for some reason isn't built on the website and doesn't show up in the left-hand nav?)
- [x] https://knative.dev/docs/eventing/event-registry/
- [x] https://knative.dev/docs/eventing/sources/
- [x] https://knative.dev/docs/eventing/debugging/ 
  - [x]  https://github.com/knative/eventing/pull/1484
  - [x] ` [KubernetesEventSource](https://github.com/knative/eventing-contrib/blob/master/pkg/apis/sources/v1alpha1/kuberneteseventsource_types.go)` - Page updates pending in https://github.com/knative/docs/pull/1478/files
- [x] https://knative.dev/docs/reference/

**Comment by samodell** [comment]
#1641  fixes 8 of the pages above. Checked them off.

**Comment by RichieEscarez** [comment]
@n3wscott can you help resolve the link to `[`KubernetesEventSource`](https://github.com/knative/eventing-contrib/blob/master/pkg/apis/sources/v1alpha1/kuberneteseventsource_types.go),` in https://knative.dev/docs/eventing/debugging/? Its not clear where that went.

**Comment by RichieEscarez** [comment]
> @n3wscott can you help resolve the link to `[`KubernetesEventSource`](https://github.com/knative/eventing-contrib/blob/master/pkg/apis/sources/v1alpha1/kuberneteseventsource_types.go),` in https://knative.dev/docs/eventing/debugging/? Its not clear where that went.

Nevermind, i found this https://github.com/knative/docs/pull/1478/
