### ISSUE TITLE
Knative Build code samples(docs/build/samples.md)

### ISSUE THREAD

**Issue by mischieflounge** [knative/docs#1644]
## Expected Behavior

The 'complex code samples' link is broken.

## Steps to Reproduce the Problem

1.
1.
1.

## Additional Info
**Additional context**

**Install information:**
 - Platform (GKE, IKS, AKS, etc.):
 - Knative Version:

**Comment by RichieEscarez** [comment]
That file was deleted (as Knative Build has been deprecated) but here is a copy: https://github.com/knative/docs/tree/90e77bc08c53730c5b40e057e96a6dd83aaef16e/docs/serving/samples/source-to-url-go
