### ISSUE TITLE
Investigating performance issues(docs/serving/debugging-performance-issues.md)

### ISSUE THREAD

**Issue by mischieflounge** [knative/docs#1645]
## Expected Behavior

knative 'serving page' image link is broken.

## Steps to Reproduce the Problem

1.
1.
1.

## Additional Info
**Additional context**

**Install information:**
 - Platform (GKE, IKS, AKS, etc.):
 - Knative Version:

**Comment by samodell** [comment]
I don't see any broken links on this page in the current docs (https://knative.dev/docs/serving/debugging-performance-issues/) so I'm closing this out.
