### ISSUE TITLE
Install on a Kubernetes cluster(docs/install/Knative-with-any-k8s.md)

### ISSUE THREAD

**Issue by grantr** [knative/docs#1648]
## Expected Behavior

Numbered lists increment the number for each step.

## Actual Behavior

Every step of the numbered list is rendered as step 1. This appears on some numbered lists in several other install docs too. Here are some examples:

https://knative.dev/docs/install/knative-with-gke/
https://knative.dev/docs/install/knative-with-icp/

## Additional Info
This is caused by paragraphs and code blocks that aren't indented properly. Paragraphs inside a numbered list must be indented with 4 spaces to allow the list numbering to work.

**Comment by mukobi** [comment]
Confusingly, it appears to render correctly [on GitHub](https://github.com/knative/docs/blob/release-0.8/docs/install/Knative-with-GKE.md) which is different behaviour from on Knative.dev.

**Comment by RichieEscarez** [comment]
known issue that we are working towards resolving (#1202 #1834)
