### ISSUE TITLE
Knative Eventing Docs Missing Documentation (docs/eventing/_index.md)

### ISSUE THREAD

**Issue by kzjackson1** [knative/docs#1649]
## Expected Behavior

No TODOs in the published docs

## Actual Behavior
<!– TODO(evankanderson): add documentation for Kafka bus once it is available. –>

## Steps to Reproduce the Problem

1.  Scroll down to the Architecture Heading
1. Go to the second image.
1. See <!– TODO(evankanderson): add documentation for Kafka bus once it is available. –>

## Additional Info
**Additional context**
I'm not 100% sure if this is a quick fix and I can remove the TODO or a missing diagram/info. 
@evankanderson , this was assigned to you, is the current documentation accurate?

**Install information:**
 - Platform (GKE, IKS, AKS, etc.): N/A
 - Knative Version: N/A

**Comment by RichieEscarez** [comment]
The graphic was fixed in the master branch: https://knative.dev/development/eventing/#architecture

**Comment by samodell** [comment]
Closing; not seeing the TODO anymore.
