### ISSUE TITLE
Remove Knative Build: Install on IBM Cloud Private(docs/install/Knative-with-ICP.md)

### ISSUE THREAD

**Issue by RichieEscarez** [knative/docs#1655]
Knative Build has been deprecated for the Knative v0.8 release and wont be supported in 0.9. ([More info](https://github.com/knative/build))

The docs/install/Knative-with-ICP.md topic includes Knative Build as part of the install process and should be removed for v0.8 and later.

**Comment by zxDiscovery** [comment]
OK, I will remove the `knative build` in `docs/install/Knative-with-ICP.md`.

**Comment by RichieEscarez** [comment]
Thanks @zxDiscovery !  FYI #1656 does not attempt to fix this IBM install guide (its my attempt to fix what i can) otherwise I opened issues, like this one.
