### ISSUE TITLE
Missing image (docs/serving/installing-logging-metrics-traces.md)

### ISSUE THREAD

**Issue by kzjackson1** [knative/docs#1674]
## Expected Behavior
Image should display on the page

## Actual Behavior
[This image](https://knative.dev/docs/images/kibana-landing-page-configure-index.png) 404s

## Steps to Reproduce the Problem

1. Go to the **Create Elasticsearch Indices** section.
1. See that the image is broken.
1. Possibly have trouble completing steps in that section.

## Additional Info
**Additional context**

**Install information:**
 - Platform (GKE, IKS, AKS, etc.): N/A
 - Knative Version: N/A

**Comment by RichieEscarez** [comment]
already fixed in the master branch which we will use to cut v08: https://knative.dev/development/serving/installing-logging-metrics-traces/#create-elasticsearch-indices
