### ISSUE TITLE
Install on Google Kubernetes Engine(development/install/Knative-with-GKE.md)

### ISSUE THREAD

**Issue by vaikas-google** [knative/docs#1689]
## Expected Behavior
The links that I paste have the correct URLs.

## Actual Behavior
The links contain a bogus version (*development.0*) does not exist.
   kubectl apply --selector knative.dev/crd-install=true \
   --filename https://github.com/knative/serving/releases/download/development.0/serving.yaml \
   --filename https://github.com/knative/eventing/releases/download/development.0/eventing.yaml \
   --filename https://github.com/knative/serving/releases/download/development.0/monitoring.yaml

## Steps to Reproduce the Problem

1. Create a cluster as per the directions
1. Try to install knative using:
   kubectl apply --selector knative.dev/crd-install=true \
   --filename https://github.com/knative/serving/releases/download/development.0/serving.yaml \
   --filename https://github.com/knative/eventing/releases/download/development.0/eventing.yaml \
   --filename https://github.com/knative/serving/releases/download/development.0/monitoring.yaml
1.it fails with:
vaikas@penguin:~/projects/go/src/knative.dev/serving$ kubectl apply --selector knative.dev/crd-install=true \
>    --filename https://github.com/knative/serving/releases/download/development.0/serving.yaml \
>    --filename https://github.com/knative/eventing/releases/download/development.0/eventing.yaml \
>    --filename https://github.com/knative/serving/releases/download/development.0/monitoring.yaml
unable to read URL "https://github.com/knative/serving/releases/download/development.0/serving.yaml", server reported 404 Not Found, status code=404
unable to read URL "https://github.com/knative/eventing/releases/download/development.0/eventing.yaml", server reported 404 Not Found, status code=404
unable to read URL "https://github.com/knative/serving/releases/download/development.0/monitoring.yaml", server reported 404 Not Found, status code=404

## Additional Info
**Additional context**

**Install information:**
 - Platform (GKE, IKS, AKS, etc.):
 - Knative Version:
Trying to install the version from the head (pre-release documentation).

**Comment by RichieEscarez** [comment]
https://github.com/knative/website/pull/83
