### ISSUE TITLE
Add social image preview to knative.dev

### ISSUE THREAD

**Issue by steren** [knative/docs#1696]
When I share https://knative.dev/ on Twitter, no image thumbnail appears in the twitter card.
You can test this at https://cards-dev.twitter.com/validator

How to fix: 

Add the appropriate <meta> tags so that Twitter and other social networks pick up the Knative logo as thumbnail as well as a nice summary

**Comment by samodell** [comment]
Closing; I'm going to reopen this issue in the website repo, since this is directly website-related. I'll @ mention you on the new issue for tracking.
