### ISSUE TITLE
Add projected service account token volumes

### ISSUE THREAD

**Issue by mikehelmick** [knative/docs#1697]
## What is changing? (Please include as many details as possible.)

In Knative Serving, we should change the specification to allow for the projected volume type of "serviceAccountToken"

see [k8s reference docs](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#service-account-token-volume-projection)

## How will this impact our users?

As part of the data plane security work for Knative eventing, see [eventing#705](https://github.com/knative/eventing/issues/705), we need the ability to generate bearer tokens on certain components to power authz/authn at the broker ingress point.

For example, a webhook importer needs to be able to receive events on a public endpoint, transform to a CloudEvent and deliver to the broker. Having an appropriate service account token available on the filesystem eliminates the code from having to know that it's on kubernetes or interact with the API server at all just use the JWT from the file system.

## In what release will this take happen (to the best of your knowledge)?

Serving 0.9

## Context
Link to associated PRs or issues from other repos here.

1. https://github.com/knative/eventing/issues/705

## Additional info

We should also consider data plan specs for protecting services with these types of accounts. We'll explore that in the eventing data plane security work and report back with service specification change requests.

**Comment by mikehelmick** [comment]
cc: @vaikas-google @dgerd

**Comment by samodell** [comment]
Hi @mikehelmick -- This issue seems like it might be more at home in the Serving repo. Would you be open to moving it there? (Let me know if you think it should stay in Docs, though!)
