### ISSUE TITLE
Knative Eventing(docs/eventing/_index.md)

### ISSUE THREAD

**Issue by RichieEscarez** [knative/docs#1716]
https://github.com/knative/docs/blob/release-0.8/docs/eventing/README.md

The link to "Channels" and "ClusterChannelProvisioner" in the Eventing overview both 404 and the files appears to have been deleted or moved but its not clear where this should point to now:

Broken URLs:
https://github.com/knative/eventing/blob/master/pkg/apis/eventing/v1alpha1/channel_types.go#L36
https://github.com/knative/eventing/blob/master/pkg/apis/eventing/v1alpha1/cluster_channel_provisioner_types.go#L35

![image](https://user-images.githubusercontent.com/11762685/63369160-3a93ef00-c334-11e9-9c9f-3a930fb9003b.png)

**Comment by abrennan89** [comment]
Seems to be fixed in the latest version of the docs
