### ISSUE TITLE
Missing pages in knative.dev

### ISSUE THREAD

**Issue by dgerd** [knative/docs#1729]
## Expected Behavior

https://knative.dev/docs/serving/deploying-with-private-registry/ goes to a valid page

## Actual Behavior

Retutrns "Page not found error"

## Steps to Reproduce the Problem

1. Go to knative.dev
1. Go to top right corner "Search this site" and type "private registry"
1. Click on the first link "Deploying to Knative using a private container registry | Knative"
1. Get "Page not Found"

## Additional Info

It is not clear to me if this is because the content was removed and the search index has not been updated or if the content has just moved or something else is broken...

**Additional context**

**Install information:**
 - Platform (GKE, IKS, AKS, etc.):
 - Knative Version:

**Comment by RichieEscarez** [comment]
That file was deleted since it used the deprecated Knative Build component: https://github.com/knative/docs/pull/1680

But its still available in the 0.7 archive: https://knative.dev/v0.7-docs/serving/deploying-with-private-registry/
