### ISSUE TITLE
Could anybody add docs about How to call the knative serving/eventing API?

### ISSUE THREAD

**Issue by sirius1024** [knative/docs#1739]
**Describe the change you'd like to see**
I've deployed Kubernetes/Istio and Knative on my servers. Now I wanna develop a UI for knative with its API/SDK. But for now only the API specs as the reference, could anyone show me a demo to call the API/SDK of Knative, please?

**Additional context**
I never know the kubernetes knowledge, but it never be a problem if knative need. Just a start! :)

**Comment by samodell** [comment]
Related: #1461

**Comment by abrennan89** [comment]
@markusthoemmes could you provide details for these docs, or do you know who can? Thanks.

**Comment by evankanderson** [comment]
The Serving and Eventing components auto-generate Kubernetes-style client bindings; there is automated `golang` documentation available here:

https://pkg.go.dev/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1
https://pkg.go.dev/knative.dev/eventing/pkg/client/clientset/versioned/typed/eventing/v1

The Kubernetes apiserver also serves an OpenAPI document for both serving and eventing which could be used to generate clients in other languages.

**Comment by abrennan89** [comment]
Closing per Evan's comments.
