### ISSUE TITLE
Secrets doc should use GOOGLE_APPLICATION_CREDENTIALS as key

### ISSUE THREAD

**Issue by lindydonna** [knative/docs#1744]
In the tutorial https://github.com/knative/docs/tree/release-0.8/docs/serving/samples/secrets-go, the environment variable key is `GOOGLE_APPLICATION_DEFAULT`. However, it should be `GOOGLE_APPLICATION_CREDENTIALS`, per GCP documentation (see https://cloud.google.com/docs/authentication/getting-started). See also the GKE secrets tutorial: https://cloud.google.com/kubernetes-engine/docs/tutorials/authenticating-to-cloud-platform.

Note: I haven't tried this exact tutorial, but I built a C# app where I saw that the key name was incorrect, and the app works using `GOOGLE_APPLICATION_CREDENTIALS`. Someone should verify the Go app end-to-end to make sure everything still works with the rename.

**Comment by samodell** [comment]
Fixed by #1769
