### ISSUE TITLE
Flesh out the contents of auto-scaling topic

### ISSUE THREAD

**Issue by rgregg** [knative/docs#175]
it's very light on details:

https://github.com/knative/docs/blob/master/serving/auto-scaling-with-knative.md

**Comment by josephburnett** [comment]
@rgregg, I just submitted the updated topic.  Includes more details on the autoscaling algorithm, pointers to graphs, a better self-contained load tool to replace `hey` and more test scenarios.

**Comment by josephburnett** [comment]
Well I thought that I submitted the pull request.  Something weird is going on with my fork ... I can't seems to make a comparison pull request.

This is what I'm trying to merge: https://github.com/josephburnett/docs/tree/autoscale-sample-prereview/serving/samples/autoscale-go
