### ISSUE TITLE
Broken links on knative.dev

### ISSUE THREAD

**Issue by eallred-google** [knative/docs#1750]
List of broken links / 404 / timeout on knative.dev

- [ ] 404 Error navigating to; https://github.com/knative/docs/tree/release-0.8/docs/serving/samples/hello-world/README.md

Source Page: https://knative.dev/docs/serving/samples/hello-world/ -> click on View/Edit this page 

- [x] 404 Error navigating to; 

https://github.com/knative/docs/blob/master/install/README.md
Source Page: https://knative.dev/docs/serving/samples/hello-world/helloworld-java-spark/ -> click on installation instructions

- [x] Timeout navigating to;

http://blog.arungupta.me/smaller-java-image-docker-multi-stage-build/
SourcePage: https://knative.dev/docs/serving/samples/hello-world/helloworld-java-spark/ -> click on Creating Smaller Java Image using Docker Multi-Stage Build.

- [ ] 404 Error navigating to; 

https://github.com/knative/eventing/blob/master/pkg/apis/eventing/v1alpha1/channel_types.go#L36
https://github.com/knative/eventing/blob/master/pkg/apis/eventing/v1alpha1/cluster_channel_provisioner_types.go
https://github.com/knative/eventing/blob/master/pkg/apis/eventing/v1alpha1/channel_types.go
https://github.com/knative/eventing/blob/master/pkg/apis/eventing/v1alpha1/subscription_types.go
https://github.com/knative/eventing/blob/master/pkg/apis/eventing/v1alpha1/subscription_types.
Source Page: https://knative.dev/docs/eventing/

- [ ] 404 Error navigating to; 

https://github.com/knative/eventing-contrib/blob/master/contrib/awssqs/pkg/apis/sources/v1alpha1/aws_sqs_types.go
https://github.com/knative/eventing-contrib/blob/master/contrib/gcppubsub/pkg/apis/sources/v1alpha1/gcp_pubsub_types.go
https://github.com/knative/eventing-contrib/blob/master/contrib/github/pkg/apis/sources/v1alpha1/githubsource_types.go
Source Page: https://knative.dev/docs/eventing/sources/

- [ ] 404 Error navigating to; 

https://github.com/knative/eventing/tree/master/contrib/gcppubsub/config
https://github.com/knative/eventing/tree/master/contrib/natss/config
https://github.com/knative/eventing/tree/master/contrib/natss/config/provisioner
Source Page: https://knative.dev/docs/eventing/channels/channels-crds/

- [ ] 404 Error navigating to; 

https://github.com/knative/docs/tree/release-0.8/docs/eventing/samples/README.md
Source Page: https://knative.dev/docs/eventing/samples/

- [ ] 404 Error navigating to; 

https://github.com/knative/docs/tree/release-0.8/docs/eventing/samples/sequence/README.md
Source Page: https://knative.dev/docs/eventing/samples/sequence/

- [ ] Page not found navigating to; 

https://book.kubebuilder.io/quick_start.html
Source Page: https://knative.dev/docs/eventing/samples/writing-a-source/01-bootstrap/

- [ ] 404 Error navigating to; 

https://www.envoyproxy.io/docs/envoy/latest/configuration/access_log
https://github.com/knative/eventing-contrib/blob/master/pkg/apis/sources/v1alpha1/kuberneteseventsource_types.go
Source Page: https://knative.dev/docs/eventing/debugging/

- [x] 404 Error navigating to; 

https://github.com/knative/docs/tree/release-0.8/docs/concepts/README.md
Source Page: https://knative.dev/docs/concepts/

**Comment by eallred-google** [comment]
fixed a couple of the non-eventing links

**Comment by nachocano** [comment]
The eventing links should have been fixed with this https://github.com/knative/docs/pull/1950.
Not closing it as some serving ones might still be broken?

**Comment by RichieEscarez** [comment]
all fixed!
