### ISSUE TITLE
Need review: event sources links are broken because of migration

### ISSUE THREAD

**Issue by daisy-ycguo** [knative/docs#1771]
## Expected Behavior

The links to event sources are correct in document [Documentation/Eventing Component/Eventing sources](https://knative.dev/v0.3-docs/eventing/sources/)

## Actual Behavior

Some links are broken because some event sources have been move to repo `event-contrib`

## Steps to Reproduce the Problem

1. Go to page [Documentation/Eventing Component/Eventing sources](https://knative.dev/v0.3-docs/eventing/sources/) and click on the links of event sources.

**Comment by mukobi** [comment]
I'm working on this issue. Some of the broken links can be fixed as the files were just moved out of the 'contrib' directory in the [eventing-contrib repo](https://github.com/knative/eventing-contrib), but the gcppubsub files seem to have all be deleted in https://github.com/knative/eventing-contrib/commit/40dddfd503a0e1b99d44b355dc4347261179b1d8. Should a new issue be opened to bring them in the root of the eventing-contrib repo, or should some other action be taken?

**Comment by samodell** [comment]
This is still valid. On https://knative.dev/docs/eventing/sources/:

Cron Job 404
GCP PubSub 404
Google Cloud Scheduler 404
Google Cloud Storage 404
Container Source 404

/remove-lifecycle rotten

**Comment by abrennan89** [comment]
@mukobi are you still working on this issue? Should we assign it to you?
Thanks :)

**Comment by mukobi** [comment]
> @mukobi are you still working on this issue? Should we assign it to you?
> Thanks :)

Oh sorry, I totally forgot about this. You can assign it to someone else.

**Comment by abrennan89** [comment]
Cron Job and Container Source have been replaced now; they're marked as deprecated, but maybe they should be removed from the list entirely since these are OOTB sources that should be covered eventually using `kn` commands in their own doc section (or at the least kubectl + yaml, as per ApiServerSource?).

**Comment by abrennan89** [comment]
Closed by #2714
