### ISSUE TITLE
Eventing metrics

### ISSUE THREAD

**Issue by nachocano** [knative/docs#1792]
## What is changing? (Please include as many details as possible.)
The current eventing metrics have changed, and we need to properly document them in knative/docs.
We also need to add instructions on how to configure the different metrics backends.

## How will this impact our users?
Users will be able to use metrics to better understand what is going on in their clusters.

## In what release will this take happen (to the best of your knowledge)?
v0.9

## Context
Link to associated PRs or issues from other repos here.

1. https://github.com/knative/eventing/issues/1693
1. Some initial work here: https://github.com/knative/eventing/blob/master/docs/metrics.md

**Comment by abrennan89** [comment]
@nachocano this is a pretty old one, but I figure the metrics still need to be updated.
Please check the current docs and let me know.

If there are updates required, can you please provide details of what needs to be updated, or point us to someone who can provide information for docs? Thanks.

**Comment by nachocano** [comment]
I haven't worked on metrics in a while. But at the time there was no page in knative.dev eventing, explaining how to set up metrics collection, and what metrics where being produced. I was thinking of something similar to tracing: https://knative.dev/docs/eventing/accessing-traces/

At the time I created this file in the eventing repo: https://github.com/knative/eventing/blob/master/docs/metrics.md
Some things there might need to be updated, but that is a good starting point. @zargarpur has done some work recently, and may have more context as to what needs to be updated.

**Comment by vaikas** [comment]
@devguyio would you mind tackling tracing parts of this with all the tracing work you've been doing?

**Comment by skonto** [comment]
@devguyio I am working on a PR to add the currently exposed Serving, Eventing metrics in docs. I can be assigned this.

**Comment by devguyio** [comment]
Thanks! 
/assign @skonto
