### ISSUE TITLE
testing: hello-world sample file configuration

### ISSUE THREAD

**Issue by grayside** [knative/docs#1793]
## Describe the change you'd like to see

Adding files to the hello-world samples requires a special test configuration step. This is not currently documented or made clear in the test output.

Document how to add new files to the hello-world samples:

* Contributing guide details that explain adding or removing files from an existing sample
* More actionable error messages in the test failure report that points to the instructions on the action to take

**Additional context**

Per the discussion about sample CI testing in #1774, all files which are copied to test the build must be added to a test configuration file at `test/sampleapp/config.yaml`.

From my understanding, this is to enable:

* Verify that all required files continue to be present in a given PR
* A superset list of the files which are checked for synchronization with the README

@chaodaiG for awareness

**Comment by chaodaiG** [comment]
Nice! Thanks a lot for making this clear!
/assign

**Comment by grayside** [comment]
It looks like the test system itself now explains this, but if we want instructions to which contributors can be pointed a further doc change is needed. Not sure if there are any written instructions on sample practices, if nothing exists then in my opinion this can be closed and referenced from a new issue to create such a page.
