### ISSUE TITLE
Improve clarity on outbound network access config

### ISSUE THREAD

**Issue by edvinerikson** [knative/docs#1804]
**Describe the change you'd like to see**
The [Configuring outbound network access](https://knative.dev/docs/serving/outbound-network-access/) document should make it explicit that it is only applicable if you are running Istio in "strict" mode.

Currently its quite confusing wether it is applicable or not if you don't run the egress service. 
 For someone not entirely comfortable with the configs in knative/istio yet.. this left me with a question mark wether I would need this config change or not.. the document stated that I needed it, but my cluster could still reach the external ips required.

**Comment by RichieEscarez** [comment]
That topic has been remove recently #1859 (it was only accurate for v0.8.1 and earlier)
