### ISSUE TITLE
Add documentation/FAQ for GKE private master setup

### ISSUE THREAD

**Issue by tcnghia** [knative/docs#1809]
**Describe the change you'd like to see**
We discovered in https://github.com/knative/serving/issues/4868 that some port whitelisting needs to happen before Knative can be used in GKE private clusters.  It would be great to include this in our getting started on GKE section.  The linked issue showed all the necessary steps.

**Additional context**

**Comment by bappr** [comment]
Literally spent 1 full day dealing with this issue. ;)
Documentation about that is more than welcome! 👍

**Comment by emaildanwilson** [comment]
Same here, this bit me today until I happened across the issue above. IMO it would also be helpful if there was a way to add network tags to the master gke instances. That way I could write a firewall rule that allows access without specifying the cidr block on either side.
