### ISSUE TITLE
GCP Cloud Pub/Sub source sample docs need to be updated for v0.9

### ISSUE THREAD

**Issue by meteatamel** [knative/docs#1814]
## Expected Behavior
I follow the instructions on this page (docs/eventing/samples/gcp-pubsub-source/index.md) to listen GCP Pub/Sub events in Knative. 

## Actual Behavior
The instructions say to run this:

`kubectl apply --filename https://github.com/knative/eventing-contrib/releases/download/v0.9.0/gcppubsub.yaml`

But that yaml file does not exist anymore. I think I might need to use https://github.com/google/knative-gcp somehow but it's not clear how. 

**Install information:**
 - Platform (GKE, IKS, AKS, etc.): GKE
 - Knative Version: 0.9

**Comment by meteatamel** [comment]
I have the instructions to set this up in my tutorial: https://github.com/meteatamel/knative-tutorial/blob/master/docs/08-helloworldeventing.md

**Comment by ahmetb** [comment]
+1 Can we prioritize updating this? I think it's pretty severe that the GCP eventing instructions are broken and it seems like this work to separate the repos was done as part of v0.9.
