### ISSUE TITLE
Site wide rendering issues for codeblocks w/o linebreaks

### ISSUE THREAD

**Issue by mattmoor** [knative/docs#1834]
The Ubuntu bullets are rendered improperly.

**Comment by RichieEscarez** [comment]
https://knative.dev/development/install/knative-with-aks/

![image](https://user-images.githubusercontent.com/11762685/65990808-20742300-e441-11e9-962d-e5f5b1376566.png)

**Comment by RichieEscarez** [comment]
Fixed with https://github.com/knative/website/pull/115
