### ISSUE TITLE
GKE cluster creation doesn't set up cluster local gateway

### ISSUE THREAD

**Issue by mattmoor** [knative/docs#1842]
## Expected Behavior

The cluster local gateway is installed

## Actual Behavior

It is not.

## Steps to Reproduce the Problem

Follow the GKE cluster creation commands and install knative.

cc @tcnghia

**Comment by vaikas-google** [comment]
This beasically means that anybody that installs Knative on GKE with 0.9 will get a broken setup. I think this warrants a dot release.

**Comment by meteatamel** [comment]
+1 on doing a dot release. A number of folks already ran into this. Either the installation yaml files or instructions should be updated to do whatever is needed to have this working by default on the current version of GKE with Istio add-on version.

**Comment by ZhiminXiang** [comment]
This issue was fixed by the PR https://github.com/knative/docs/pull/1894

**Comment by vaikas-google** [comment]
merged and cherrypicked to 0.9 documents. I'm closing, reopen if something else is missing.
