### ISSUE TITLE
GCP Cloud Pub/Sub source(docs/eventing/samples/gcp-pubsub-source/index.md)

### ISSUE THREAD

**Issue by xorver** [knative/docs#1843]
## Expected Behavior
   kubectl apply --filename https://github.com/knative/eventing-contrib/releases/download/v0.9.0/gcppubsub.yaml

should work

## Actual Behavior

error: unable to read URL "https://github.com/knative/eventing-contrib/releases/download/v0.9.0/gcppubsub.yaml", server reported 404 Not Found, status code=404

Question:
Would it be fine to use GCP PubSub event source from some older link?

**Comment by RichieEscarez** [comment]
Looks like this was removed for 0.9: https://github.com/knative/eventing/pull/1598

So the docs should be updated to use: https://github.com/google/knative-gcp
