### ISSUE TITLE
Remove mention of all past versions

### ISSUE THREAD

**Issue by RichieEscarez** [knative/docs#1850]
Going forward, knative.dev should only mention breaking or important changes from one previous version (v.latest -1). 

Todo:
- [ ] All references to any other version should be removed
- [ ] If necessary, revise all content to consider only one version prior (otherwise remove mention of a version altogether)
- [ ] If we must mention something, consider adding it to a migration guide or known issues page

We should assume that users understand that if you view the latest release (ie. v0.10), that all references imply that version (ie. Install Serving/Eventing, etc.).

If there is a circumstance that requires you to define the "current" version, you can insert a dynamic variable ([`{{% version %}}`](https://raw.githubusercontent.com/knative/website/master/layouts/shortcodes/version.md) shortcode) that gets populated at build time with the version number of whatever the latest release is:

Insert `{{% version %}}` where you want the version number to show. [See examples](https://knative.dev/smoketest/#install-version-numbers-and-clone-branch-commands).

Example:
The line about "Knative 0.3x" should be removed and revised:
https://knative.dev/docs/install/knative-custom-install/#installing-knative

**Comment by abrennan89** [comment]
Is there a way to also filter search results by version or prevent these from showing up older versions of docs mixed in with the latest docs? It makes the search a little confusing to use IMHO because you have to check the link to make sure the docs aren't from an older version every time.

**Comment by RichieEscarez** [comment]
Yeah, I feel the same about our search too. I've had that on my to-do list since the [site launch](https://github.com/knative/docs/projects/5#card-20873600) but have not been able to get to it. I'm opening formal issues for all the site backlog items, including improved search scope.

**Comment by abrennan89** [comment]
### Version mentions from review (list is WIP):

- [ ] Installing Knative > MicroK8s > Enable Knative (mentions Serving & Eventing 0.7.1)
     - [ ] Also has a note about updating versions in the doc. We should remove the note if we're not going to track / commit to tracking this for each version.
- [ ] Installing Knative > Azure Kubernetes Service > Installing Knative (mentions 0.3.x)
- [ ] Installing Knative > IBM Cloud Private > Installing Knative (mentions 0.3.x)
- [ ] Installing Knative > On existing cluster > Installing Knative (mentions 0.3.x)
- [ ] Installing Knative > Checking your install version (mentions pre-0.4.0)
- [ ] Serving component > Configuring the autoscaler (mentions v0.2 and links to v0.3 blog post)
- [ ] Serving component > Debugging issues w/ your application > Check ingress status (mentions 0.3)
- [ ] Serving component > Setting up a custom domain > deploy an application (example/code mentions multiple versions in comments)

**Comment by abrennan89** [comment]
@RichieEscarez @samodell any idea what to do about the last three on this list? Do we need a migration guide?
I will double check this is all of them with fresh eyes tomorrow :slightly_smiling_face:

**Comment by RichieEscarez** [comment]
Lets just remove that whole "upgrade step":

![image](https://user-images.githubusercontent.com/11762685/69385706-11f1fd00-0c75-11ea-923c-f61f625a7d84.png)

Thanks a ton!!!!

**Comment by abrennan89** [comment]
Thanks @RichieEscarez :slightly_smiling_face: the PR is updated to reflect this and the other comments now.
