### ISSUE TITLE
Enabling tag to digest resolution(docs/serving/tag-resolution.md)

### ISSUE THREAD

**Issue by drnic** [knative/docs#1854]
Link to Google Slide "Why we resolve tags in Knative" is private [1]. Could it be made public please?

[1] https://docs.google.com/presentation/d/1gjcVniYD95H1DmGM_n7dYJ69vD9d6KgJiA-D9dydWGU/edit?usp=sharing

**Comment by RichieEscarez** [comment]
It is publicly accessible but you need to first join the knative-users group, please see details here: https://knative.dev/contributing/contributing/#design-documents
