### ISSUE TITLE
Update C# sample to .Net Core 3.0

### ISSUE THREAD

**Issue by steren** [knative/docs#1856]
https://github.com/knative/docs/tree/master/docs/serving/samples/hello-world/helloworld-csharp

Apparently, .Net Core 3.0 is available. 
Our sample uses 2.2, we should make sure it's up to date.

**Comment by steren** [comment]
CC @grayside

**Comment by steren** [comment]
@meteatamel maybe you can help us?

**Comment by meteatamel** [comment]
Sure, please assign to me and I'll take a look

**Comment by steren** [comment]
I guess @RichieEscarez has the power to assign it to you

**Comment by meteatamel** [comment]
I have an open PR [1816](https://github.com/knative/docs/pull/1816) to fix this.

**Comment by EatonZ** [comment]
Looks like @meteatamel's PR was merged, so I think this can be closed now.
Still needs to be published to [Cloud Run docs](https://cloud.google.com/run/docs/quickstarts/build-and-deploy), though.

**Comment by EatonZ** [comment]
FYI, [Google's site](https://cloud.google.com/run/docs/quickstarts/build-and-deploy) is still not updated, someone may want to sync it up.😉

**Comment by grayside** [comment]
Thanks for the check EatonZ, looks like the problem is limited to the instruction to use dotnet v2.2. We'll get that fixed up.

**Comment by EatonZ** [comment]
Another FYI: 3.1 LTS is out now. Might want to do another update here - probably will be the last update needed for a while (next is 3.0 in Nov 2020).

**Comment by meteatamel** [comment]
Opened [2021](https://github.com/knative/docs/issues/2021). I'll send a PR.
