### ISSUE TITLE
Eventing samples README.md missing in repo

### ISSUE THREAD

**Issue by aslom** [knative/docs#1866]
## Expected Behavior

Able to edit in github
https://knative.dev/docs/eventing/samples/

## Actual Behavior

404 opening
https://github.com/knative/docs/tree/release-0.9/docs/eventing/samples/README.md

## Steps to Reproduce the Problem

1. Click " View/Edit this page" in right top corner in https://knative.dev/docs/eventing/samples/

## Additional Info
**Additional context**

_index.md is not editable?

https://github.com/knative/docs/blob/release-0.9/docs/eventing/samples/_index.md

**Install information:**
 - Platform (GKE, IKS, AKS, etc.):
 - Knative Version:

**Comment by RichieEscarez** [comment]
The "View/Edit" link in knative.dev expects there to be a README.md file in the repo. In this case that README is missing and should be added to the repo.

**Comment by RichieEscarez** [comment]
Resolved in https://github.com/knative/docs/pull/1975
