### ISSUE TITLE
New topic: "How to post to the blog" 

### ISSUE THREAD

**Issue by RichieEscarez** [knative/docs#1875]
Provide instructions about how users can post to the [Blog section](https://knative.dev/blog/).

- [ ] Create and add a GitHub template (so anyone who wants to post gets the necessary site content in their PR when clicking "Post to the blog" form the site)
- [x] Explain how to use the template, including:
  - how to add the post into the correction blog section
  - what [front matter](https://gohugo.io/content-management/front-matter/) is required
  - how to use [Hugo link syntax](https://gohugo.io/content-management/cross-references/) (best way since URLs get prefixed with the date which makes relative URL unintuitive)
  - how use relative links for any content within knative.dev
  - mention tips (or gotchas) for using Markdown
  - clarify how to add images (where, in which folder, and how to link, position, or [resize](https://gohugo.io/content-management/image-processing/) them)
  - how to test/preview

For example, this page has a set of steps we might be able to start with: 
https://opensource.com/article/18/3/start-blog-30-minutes-hugo

**Comment by abrennan89** [comment]
@macruzbar hope it's OK if I assign this to you :slightly_smiling_face: it's pretty much a duplicate issue for what you're working on with blog templates I think.

**Comment by macruzbar** [comment]
Hi @RichieEscarez ! I recently created the [blogging guidelines](https://github.com/knative/docs/blob/3e8e1b91f6e4c3ed22498df33007ec110551c751/blog/README.md), which go over all of the topics you mention on this issue. You can find the PR that is waiting to be approved [here](https://github.com/knative/docs/pull/2523). Please let me know via slack if there's anything that we should add to that document. 

Closing this issue for now.

**Comment by RichieEscarez** [comment]
Thanks @macruzbar! This looks great: https://github.com/knative/docs/tree/master/blog

**Comment by RichieEscarez** [comment]
I think ill reopen this because I'd like to get GitHub to open up an empty Blog template in the edit (when you click the "Post to the blog" link in the site (so that it includes the necessary Hugo content, etc).

**Comment by RichieEscarez** [comment]
Oh, that might be here already? https://github.com/knative/docs/pull/2511

**Comment by abrennan89** [comment]
Hey folks @RichieEscarez @macruzbar 
Any update on the status of the blog template? Is there anything blocking this from being completed, e.g. decisions we need to make in the WG, approval of PRs, etc?
Thanks

**Comment by macruzbar** [comment]
> Hey folks @RichieEscarez @macruzbar
> Any update on the status of the blog template? Is there anything blocking this from being completed, e.g. decisions we need to make in the WG, approval of PRs, etc?
> Thanks

Thanks for the ping, @abrennan89 . We need to hash out all contributing avenues at the next docs WG meeting, to update CONTRIBUTING.md (see [this comment](https://github.com/knative/docs/pull/2795#issuecomment-690491139))

**Comment by abrennan89** [comment]
This looks like it's being handled under #2960 since #2511 is being handled under that one. Closing.
