### ISSUE TITLE
Installing Istio for Knative(docs/install/installing-istio.md)

### ISSUE THREAD

**Issue by marcjoha** [knative/docs#1876]
## Expected Behavior

Istio is installed

## Actual Behavior

Components istio-ingressgateway and istio-pilot are not created because yaml validation fails due to wrong apiVersion of Deployment. 

## Steps to Reproduce the Problem

1. Follow the guide

## Additional Info
**Install information:**
 - Platform (GKE, IKS, AKS, etc.): GCE
 - Knative Version: 0.9.0

**Comment by tcnghia** [comment]
/close

I believe this has been fixed in newer version of Istio.
