### ISSUE TITLE
Update the "releases" section of the Blog

### ISSUE THREAD

**Issue by RichieEscarez** [knative/docs#1880]
[Blog -> Releases](https://knative.dev/blog/releases/)

Determine how to use this section going forward. It is outdated and excludes mention of any of the recent releases.

Will contributors continue to add posts here for each release?

**Comment by abrennan89** [comment]
@macruzbar this seems like it might be related to the work you're doing with our blog infrastructure :slightly_smiling_face: do you want to take this one?

**Comment by evankanderson** [comment]
/assign @macruzbar 

One question to consider is whether we want to have a blog post for every release that summarizes all the release notes at a high level, or whether we want the release notes to speak for themselves and _never_ do a blog post about a release.

I'm fine with either choice; my personal world wouldn't have a blog post because we'd be releasing stably from nightly, but I understand that's hard for people to keep up with, so a summary of the step change from one release to the next makes sense, too.

**Comment by macruzbar** [comment]
@evankanderson I'm inclined to having a summary blogpost every 2 months*, where readers can find a link to extended notes. Happy to add a section about featuring releases on the blog once [the PR](https://github.com/knative/docs/pull/2523) is approved. 

* what cadence would make sense here? I looked at the blog, and last year we had a blog about releases in January, and another one in April. This year we don't have anything up yet.

**Comment by csantanapr** [comment]
I would like to contribute on this 

Navigation to this link mades me 😢 so I wan to contribute from time ideas to improve and can be done in iterations with feedback loop 

Part 1
I would like to have a single summary blog post for every “release number” for example do 0.17 then do 0.18 with the dates next to them like to day people can see the good cadence of ~ 6 weeks

If there is a component that gets release and someone wants to write a blog post between 0.17 and 0.18 is ok to discuss if it’s better to wait for 0.18 or just release the blog post and on the next summary release capture and highlight again 

Part 2
Advertising the release 
I think people that subscribe to rss via the blog will be happy to get notify of a release post every 6 weeks 
Other channels:
Twitter account KnativeProject
 Ailing lists dev and users
Any other social media presence ?

Part 3
The last Blog release on the site is 0.5 I think is worth going and do a mechanical thing and post for each release from 0.6 to 0.16 this will have some minor benefits 
- When new person comes to the index it will see the time line and all the releases so it doesn’t take the impression we only do large time gap releases, on the contrary every 6 weeks there is stable code being release
- if someone is using an old knative Version like a downstream like openshift operator using knative 0.13 is handy to find in one place specific version and all the release notes and changes for the 0.13 release

Part 4
Capture feedback ideas and eventually write down the steps for the hit by the bus effect and also for anyone that ant to handle the release announcement it can be rotate or even automate a bit. 
We can start with a google doc and then move to an md file on git repo 


If there are no strong objections, I would like to start putting hands on keyboard for this.

**Comment by csantanapr** [comment]
My proposal doesn’t prevent if we want to do a quarterly blog with “what’s new” that’s all great but I would 
Ike to start small and simple

**Comment by evankanderson** [comment]
I like the ideas of:

1. Having a post for each release, even if it's just a link summary and "top 3" highlights plus any gotchas. It also makes for a good link to amplify on Twitter, etc.
2. For bigger changes, I'd lean towards doing a _separate_ deep-dive on the feature in the blog. This decouples the "write content for feature X" from "run the trains on time", which has almost always helped with the latter in my experience.

**Comment by csantanapr** [comment]
>1. Having a post for each release, even if it's just a link summary and "top 3" highlights plus any gotchas. It also makes for a good link to amplify on Twitter, etc.
>2. For bigger changes, I'd lean towards doing a separate deep-dive on the feature in the blog. This decouples the "write content for feature X" from "run the trains on time", which has almost always helped with the latter in my experience.

I agree with the approach on separate blog on big features on writing content focusing on the new big feature.

**Comment by macruzbar** [comment]
I just submitted [a PR](https://github.com/knative/docs/pull/2795) to add this as a dedicated section to the blogging guidelines, and added a note to mention this at the next community meetup (Sept 17)
