### ISSUE TITLE
New topic: Use cases

### ISSUE THREAD

**Issue by RichieEscarez** [knative/docs#1882]
Conceptual content about Knative use cases:
- describe in depth the primary use cases 
- build from where the "Overview" left off
- provide architecture and diagrams for the well-known "solutions"
- this topic avoids going into that "How To" 
- should link to "Next steps", including our "Getting Started" guides and any related tutorials

**Comment by abrennan89** [comment]
Closing in favor of creating smaller issues for each use case or concept.

**Comment by RichieEscarez** [comment]
Hi, @abrennan89!

Just trying to get back up to speed and am wondering if these were all completed through the mentioned "smaller issues for each use case"?  Are there still pending items?

This issue wasn't meant to do more than just track that effort in a single location (ie. epic or story).
