### ISSUE TITLE
Restructure the "Reference" section

### ISSUE THREAD

**Issue by RichieEscarez** [knative/docs#1883]
Revise the "Reference and API" section:

- [x] Rename the section to "Reference"
- [x] Move the API docs down into a sub-section "API"
   - [x] Position Serving above Eventing
- [x] Add a new "Release notes" section (initially act as a landing page that links to all the repo "Releases" pages)
- [x] Move and rename "Concepts > Resources" topic as a "Related resources" sub-topic
     - [x] Add `aliases` to frontmatter to set redirect from past filename/url
- [ ] Move "install files and dependencies" matrix into new ref topic https://github.com/knative/docs/issues/1896

[View proposed structure](https://docs.google.com/spreadsheets/d/1L3EAeTX7RRdZhcQZeNmxwN4DCncuImCXA5A1_KQvwSk/edit?ts=5d826691#gid=413198505&range=187:187)

**Comment by abrennan89** [comment]
>     * [x]  Rename the section to "Reference"
https://github.com/knative/docs/pull/2052/files#diff-b00a88a07ceb21b1a83e5822e0c86c1dR3

**Comment by abrennan89** [comment]
> Move "install files and dependencies" matrix into new ref topic #1896
This one has its own issue now so I won't do it as part of this issue.

**Comment by RichieEscarez** [comment]
Noting the known issues from #2806:
- maintainer instructions about how to build the API are now published as the top level API page.
- the release notes page renders the auto generated "Table of contents" header but its blank because there are not child topics below that page

**Comment by abrennan89** [comment]
@RichieEscarez can you please put in a small PR to fix this since you understand the TOC issue and the other PR has already merged? Thanks.

**Comment by RichieEscarez** [comment]
Sure, not a problem. I'll eventually get around to it but I wanted to at least capture these details so we dont forget about them.

BTW, they are the same changes that are already the PR but those commits were overwritten (so details are there and in the comments).
