### ISSUE TITLE
New "reference" topic "Knative installation files"

### ISSUE THREAD

**Issue by RichieEscarez** [knative/docs#1896]
Move the "reference" info out of https://knative.dev/development/install/knative-custom-install/, into its own topic so what remains are two distinct topics (1) a task and (2) this new reference.

New ref topic should include and be the new home for:
- Title: "Knative installation files and dependencies" (short: "Install files and dependencies")
- list of installation files
- table the describes the file and identifies dependencies/requirements
- For all moved or renamed files, add a redirect to that file's frontmatter (#1925)

**Comment by RichieEscarez** [comment]
Reopening for now but we need revisit this

**Comment by abrennan89** [comment]
@RichieEscarez the page https://knative.dev/development/install/knative-custom-install/ doesn't exist anymore, so I think this is outdated. I'd recommend opening a new issue if there's stuff to improve in the current install docs.

**Comment by RichieEscarez** [comment]
@abrennan89 Sorry, I probably should have looked before resetting the stale bot =). 

This issue was not about that page, but specifically about documenting all the assets listed in each of the component release pages. For example, do we answer the question of "What is this `...xyz.yaml` file for on the eventing/serving releases page?" Ive honestly not run an install in a long time and I can see that these docs have completely changed so if we do cover all the eventing and serving assets in other tasks, then yes we are done here (nice work!)

![image](https://user-images.githubusercontent.com/11762685/98025207-41cedd80-1dbe-11eb-9b7a-f9a64a0ead2c.png)
![image](https://user-images.githubusercontent.com/11762685/98025301-59a66180-1dbe-11eb-95c8-9ea248c5cf0b.png)

**Comment by abrennan89** [comment]
@RichieEscarez I think we explain some of these throughout docs as they're mentioned (in memory channel, mt broker, etc), and some of the monitoring stuff has probably been removed now if it's part of that monitoring stuff that was deprecated.
I think the best thing to do would instead be to raise an issue if there's a specific YAML file that you think needs a section / explanation, rather than adding a giant issue with them all, because in the past those don't tend to get picked up because they're too big.
Maybe something for discussion in the roadmap planning, i.e. plan to document all the Knative resources / objects properly as individual user stories?

**Comment by RichieEscarez** [comment]
=) This was the issue to state the known issue (for someone to drill in and investigate where those doc gaps/issues are). It was meant for someone to pick up and run with (and/or open those smaller issues) or better yet, just fix them all. 

The context is that given the limited resource, it was wasn't productive for one of us to open a bunch of issues. Instead, we took one of these and then set off to fixed all the items found/mentioned. The lower overhead allowed for more contributions.

**Comment by omerbensaadon** [comment]
@RichieEscarez I am taking a stab at splitting this now. 

In the future, we need to split these sorts of things before they hit the Issues tabs (or, at the very least, add a "needs split" tag or something). The resources we have at our disposal (drive-by ENG contributions and not much else) means we need to spell out very clearly what work needs to be done...

Splitting this into very generic high-level user stories in the [Installing Knative Epic Tracker](https://github.com/orgs/knative/projects/19?add_cards_query=is%3Aopen), can be converted into issues once they are moved into In-progress 

CC: @abrennan89

**Comment by omerbensaadon** [comment]
If the stories I have split this into look good to you, please close this issue 👍🏼 

I am not opening any other epics until all of the stories I have put on this board have been turned into Issues, so there is no worry about losing them.

**Comment by omerbensaadon** [comment]
@RichieEscarez I think this is done?
