### ISSUE TITLE
Knative Eventing docs need to explain somewhere Knative with GCP project

### ISSUE THREAD

**Issue by meteatamel** [knative/docs#1902]
[Knative with GCP](https://github.com/google/knative-gcp) is needed to read Google Cloud events in Knative Eventing. However, Knative Eventing docs does not mention this project at all. There should be a page somewhere in Knative Eventing docs where we explain Knative with GCP project and what it's used for, so people are aware and have context.

**Comment by meteatamel** [comment]
This bug is still relevant

**Comment by abrennan89** [comment]
We no longer include documentation for Knative on specific platforms, with the exception of the https://knative.dev/docs/knative-offerings/ page that lists links to vendor docs.
Closing this issue since it relates only to GCP.
