### ISSUE TITLE
Ensure that all topics with long titles use a `linkTitle`

### ISSUE THREAD

**Issue by RichieEscarez** [knative/docs#1919]
To avoid text wrapping the left navigation menu, topics with long titles should use the [`linkTitle` frontmatter](https://gohugo.io/content-management/front-matter/) element to specify a shorter title (for the nav only).

Navigation titles should not be repetitive, for example, every topic under the "Install" section, should avoid repeating "Install" in every nav element within that section (because the context is visually set by that section). [Example](https://github.com/knative/docs/blob/master/docs/install/Knative-with-GKE.md)

[Another shorter title example](https://github.com/knative/docs/blob/master/docs/serving/installing-cert-manager.md)

Note: For `linkTitle`'s that do not alphabetically match the file's longer title, you must ensure that you define the correct `weight` in that file's frontmatter so that it renders in the proper order.

**Comment by abrennan89** [comment]
@RichieEscarez are there guidelines around the max length for the linkTitles?
Also, do we keep any reference doc of which sections have which weights / go in which order, something like a Google sheet maybe?

**Comment by samodell** [comment]
@abrennan89  We do not have a max length documented (although we should!) and we do not currently keep a reference doc for the weights of the pages. It's an area where we need to come up with a solution, for sure. I like you idea of a Google Sheet, but I'm not sure how we'd maintain something like that.
