### ISSUE TITLE
Create an "archive" section in the site for old releases

### ISSUE THREAD

**Issue by RichieEscarez** [knative/docs#1921]
Determine how to accomplish this in the site and then implement one of the following options:

* Create/host a peer "archives" site that gets refreshed at each release 
    - Send version 'latest-2' to archive when new version is published to knative.dev.
    - Create and publish another site on Netlify (ie. archives.knative.dev)
    - The archive site would a separate build process

* Static content is copied at build time. 
    - Remove archived content from the builds.
    - Content is built once and then copied into a static folder
    - Continue to be published in the same knative.dev site
    - Requires manual updates and publishing (so far nobody has wanted or tried to update past releases) 

Notes: 
1. Both options require some tweaking to Menus (including how the right nav bar GitHub links are generated).
2. Any existing redirects in the frontmatter should be updated accordingly

**Comment by samodell** [comment]
Since we decided not to host all versions of the content on Knative.dev, I am going to close this out. You built a pointer to the old release branches on GitHub, which is accessible from the version-switcher menu. Feel free to reopen if you disagree! :)
