### ISSUE TITLE
Add support for cmd and args when creating a new service

### ISSUE THREAD

**Issue by duglin** [knative/docs#1958]
Knative, via yaml, supports specifying the cmd and args in the podSpec - `kn` should support this too since there are times when people may need to specify which exe in the image to run or what args to pass to the exe. Sometimes the default values in the image are not sufficient.

**Comment by samodell** [comment]
@duglin  Should this issue be in the client repo instead? Doesn't seem like a docs issue if the functionality doesn't exist in `kn` yet. I'm closing this out, but if that's not the case, feel free to reopen here.

**Comment by duglin** [comment]
hmm not sure why I opened it here - sorry :-)
