### ISSUE TITLE
Custom domains doc only explains customizing default domain

### ISSUE THREAD

**Issue by ahmetb** [knative/docs#1964]
https://knative.dev/docs/serving/using-a-custom-domain/

This doc is titled "Setting up a custom domain" but it actually only covers "Configuring the default domain".

It doesn't explain how can I expose my `hello-go.default.example.com` with a domain name I own like `hello.com`.

**Comment by jonatasbaldin** [comment]
Hhey @ahmetb!

@bsideup wrote this article on how to create custom domains per Service: https://bsideup.github.io/posts/knative_custom_domains/

I'm thinking about documenting this process in the docs.

What do you think?

**Comment by bsideup** [comment]
@jonatasbaldin funny thing - I thought about contributing it to the docs but didn't find time yet :D

I was thinking about doing it this week, but if you do it first - feel free to! 👍

**Comment by jonatasbaldin** [comment]
hey, just made the docs! would love a review from you @bsideup

**Comment by ahmetb** [comment]
I don’t think that blog post quite explains my need. I am looking to map example.com to a ksvc. To do that, I guess you need to drop {{.Name}} because I don’t care about ksvc’s name in my domain?

**Comment by bsideup** [comment]
@ahmetb you can use the same approach as described in the blog post, just instead of using `$subdomain.{{.Domain}}` (where `$subdomain` is the label's value) you can replace it with just `$domain`

**Comment by ahmetb** [comment]
I see. I think that’s the useful scenario docs should actually mention. 1:1 domain ksvc mappings; not templates.
