### ISSUE TITLE
Cloud Events - Go(development/serving/samples/cloudevents/cloudevents-go/index.md)

### ISSUE THREAD

**Issue by mattmoor** [knative/docs#2001]
## Expected Behavior

Numbered list at top to appear like: https://github.com/knative/docs/tree/master/docs/serving/samples/cloudevents/cloudevents-go

## Actual Behavior

The first element is folded into the paragraph before.

cc @RichieEscarez

**Comment by samodell** [comment]
Looks like this page (https://knative.dev/docs/serving/samples/cloudevents/cloudevents-go/index.html) renders properly now. This was probably fixed by Richie's work in https://github.com/knative/website/pull/115
