### ISSUE TITLE
grpc code sample build breaks

### ISSUE THREAD

**Issue by lucamaf** [knative/docs#2005]
## Expected Behavior
I expect to be able to build the docker image for the grpc code sample successfully

## Actual Behavior
When I launch this:
docker build --tag "lucamaf/grpc-ping-go" .

I get back this:
Sending build context to Docker daemon 22.53 kB
Step 1/10 : FROM golang:1.12 as builder
Error parsing reference: "golang:1.12 as builder" is not a valid repository/tag: invalid reference format

## Steps to Reproduce the Problem

1. Follow the instruction to build the docker image for the grpc server

## Additional Info
**Additional context**
Related maybe:
https://github.com/spotify/docker-maven-plugin/issues/264

**Install information:**
 - Platform (GKE, IKS, AKS, etc.): Fedora 31, Docker 1.13.1 and OpenShift 4.2
 - Knative Version: 0.10

**Comment by mpetason** [comment]
This might be related to your Docker version and support for multi stage builds. 

Docker version - 19.03.8

$ docker build --tag "mpetason/grpc-ping-go" .
Sending build context to Docker daemon  22.53kB
Step 1/10 : FROM golang:1.12 as builder
 ---> 80bb9c6de3f2
Step 2/10 : RUN go get google.golang.org/grpc
 ---> Running in d0fba80e573a

**Comment by abrennan89** [comment]
@lucamaf @mpetason is there any actual documentation work to complete here, or can we close this issue?

**Comment by abrennan89** [comment]
Closing this since it was opened against an old version and haven't received any further information about requested doc changes. If this is still a problem using the latest versions, please open a new issue.
