### ISSUE TITLE
Can't find any docs about Revision Tags

### ISSUE THREAD

**Issue by ahmetb** [knative/docs#2014]
`spec.traffic` block of a ksvc supports a `tag` field (new-ish feature).

But I can't seem to find what this field does and how it can be used to split traffic.

Ideally it would be mentioned here https://knative.dev/docs/serving/samples/traffic-splitting/index.html

It's actually used here: https://knative.dev/v0.8-docs/serving/samples/blue-green-deployment/ but it doesn't explain what the "tag" field is for and what it does.

**Comment by abrennan89** [comment]
kind/new-docs-needed
