### ISSUE TITLE
Eventing binding sample

### ISSUE THREAD

**Issue by labadav** [knative/docs#202]
Moving Binding sample stuff from Mark's repo:
https://github.com/mchmarny/next18/tree/master/event-flow
to the eventing/samples and cleaning it up

**Comment by evankanderson** [comment]
It looks like this was committed directly to the tree without prow(!).

https://github.com/knative/docs/commit/2bb9073b0debf489b406714c0a91465f0fac4f1c
https://github.com/knative/docs/commit/d6ab031ec02c1ac826874db127a155c644a9733a
https://github.com/knative/docs/commit/bc0684caaa6175b245f5dae366383c7a7415a4ce
