### ISSUE TITLE
markdown code fence syntax error

### ISSUE THREAD

**Issue by ahmetb** [knative/docs#2026]
found at  https://knative.dev/docs/eventing/getting-started/#installing-knative-eventing

> ![image](https://user-images.githubusercontent.com/159209/70276244-b2abe680-1764-11ea-8e41-044d4eedef1c.png)

**Comment by ahmetb** [comment]
This issue actually happens 3 times on this page.

**Comment by RichieEscarez** [comment]
Fixed in https://github.com/knative/website/pull/115

Preview here: https://5df99dd0591d650008c975c8--knative.netlify.com/docs/eventing/getting-started/
