### ISSUE TITLE
Knative Eventing samples should be updated to use CloudEvents 1.0

### ISSUE THREAD

**Issue by meteatamel** [knative/docs#2029]
Knative docs use CloudEvents 0.3 spec in samples. One example is [here](https://knative.dev/docs/eventing/getting-started/) where `Ce-Specversion: 0.3` has been mentioned a few times. 

From v0.10.2 onwards Knative eventing works with both CE 0.3 as well as CE 1.0. Docs should be updated to mention this and samples ideally use the new CE 1.0 spec.

**Comment by samodell** [comment]
@evankanderson @grantr 

Can we update to CloudEvents 1.0 without making changes to the samples, or do updates need to be made first?
