### ISSUE TITLE
Broken link in knative docs for installing a Kubernetes cluster

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [knative/docs#2030]
## Expected Behavior

Link is not broken
## Actual Behavior
link is broken

## Steps to Reproduce the Problem

1. Follow the link to the [docs](https://github.com/knative/docs/tree/175313457f94baa036b400f12d162157edef70a7/community/samples/serving/helloworld-dart#prerequisites)
2. follow the link here. (replicated) below 👇🏾
 A Kubernetes cluster with Knative installed. Follow the [installation instructions](https://github.com/knative/docs/blob/master/install/README.md) if you need to create one.

**Comment by samodell** [comment]
@ThinkDigitalSoftware  Following your link to the Helloworld-Dart sample, it looks like you were viewing the docs on an out-of-date tree that was last edited Jan. 2019: https://github.com/knative/docs/tree/175313457f94baa036b400f12d162157edef70a7/community/samples/serving/helloworld-dart#prerequisites

If you navigate instead to the same page on the most recent release branch, the link resolves correctly: https://github.com/knative/docs/tree/release-0.10/community/samples/serving/helloworld-dart

Let me know if I'm missing something, but it looks like the error doesn't exist in the most current versions of the documentation, so I'm closing this issue out.

**Comment by ThinkDigitalSoftware** [comment]
Ok, thanks. I was linked here from a docker getting started tutorial. Maybe
that needs to be updated.
