### ISSUE TITLE
Investigate idea of having a bot post "needs eng input" docs PRs into related channels to encourage review

### ISSUE THREAD

**Issue by samodell** [knative/docs#2032]
**Background**

Sometimes, a PR hangs open in the Docs repo because we need someone with the right technical expertise to verify an update to the details of the documentation. Right now, the Docs team usually has to manually solicit input from engineers, but this process won't scale very effectively.

We want to look into the idea of a bot that would take any open PR in the Docs repo flagged "needs eng input" and post the link to the PR to any related Slack channels. This could be inferred by the bot by looking at the issue's "kind" labels. For example, "kind/eventing" should be posted to the "#eventing" slack channel. In the case where there is no correlated channel for a kind/ flag, the bot would do nothing. If there are multiple kind labels on a single PR, the bot would post to multiple channels. I imagine we'd need to maintain a mapping of kind labels to their respective Slack channels for this to work.

The bot could have a message similar to, "This docs PR has been waiting for a technical accuracy review for X days. If you're an expert in <topic>, please review Docs PR #  for technical accuracy. Thanks in advance for helping to improve the Knative documentation!"

I would want the bot to post when a PR has had the "needs eng input" flag for more than 3 days, and then post again every week until the PR is either merged or closed.

**Comment by samodell** [comment]
@chaodaiG  I think you created the Slack bot that posts test updates. Do you think a bot that worked as described above would be feasible to implement?

**Comment by chaodaiG** [comment]
I think it's feasible to implement, the challenge I can imagine would be the buy in from other WGs, since it could be noisy to other channels

**Comment by samodell** [comment]
@chaodaiG  -- thanks for your input! I'll think about collecting buy in :)
