### ISSUE TITLE
Update documentation / samples to not use deprecated fields.

### ISSUE THREAD

**Issue by vaikas** [knative/docs#2033]
## What is changing? (Please include as many details as possible.)
As per: https://github.com/knative/eventing/issues/2298

We need to update examples that use:
sequence, parallel and subscription and sources to use non-deprecated fields.

## How will this impact our users?
They will need to use non-deprecated fields (they were deprecated in 0.10, so in 0.12 they will be gone).

## In what release will this take happen (to the best of your knowledge)?
v0.12

## Context
Link to associated PRs or issues from other repos here.

1. https://github.com/knative/eventing/issues/2300
1.
1.

**Comment by samodell** [comment]
@vaikas  Do you have anyone in mind who can make these updates to the samples?

**Comment by vaikas** [comment]
oops, I think I updated all the ones I could find. If there are still others that are wrong, let's open targeted issues to fix those instead. Ok with that? I'll close and if you don't agree, please reopen :)
