### ISSUE TITLE
document broker delivery options

### ISSUE THREAD

**Issue by lionelvillard** [knative/docs#2043]
## What is changing? (Please include as many details as possible.)
The Broker now supports `spec.delivery`.

## How will this impact our users?
They will be able to control what to do (retries, deadlettersink) when event delivery fails.

## In what release will this take happen (to the best of your knowledge)?
Ex. v0.2-v0.3
0.12.0

## Context
Link to associated PRs or issues from other repos here.

1. https://github.com/knative/eventing/pull/2305
1.
1.

**Comment by evankanderson** [comment]
@lionelvillard Is this still active?

**Comment by lionelvillard** [comment]
yes

/remove-lifecycle stale

**Comment by abrennan89** [comment]
@lionelvillard this looks like its covered here https://knative.dev/docs/eventing/event-delivery/#configuring-subscription-delivery ?
Is there anything else to add?

**Comment by slinkydeveloper** [comment]
@abrennan89 I think we should link from the broker doc this page you posted and provide an example (eg how to setup a dead letter sink in a broker), i feel this page itself is not enough and it's too much "channel" centric

**Comment by pierDipi** [comment]
@abrennan89 are you working on this otherwise I can take this one.

**Comment by abrennan89** [comment]
That would be great, thanks @pierDipi ! :pray:
