### ISSUE TITLE
Remove Ambassador from docs in 0.12

### ISSUE THREAD

**Issue by mattmoor** [knative/docs#2050]
It is unclear whether this integration still works, and we need to land e2e testing for this integration to remain.  We shouldn't just remove these eagerly, but if it looks like we won't have them in 0.12, then we should remove the docs to avoid them becoming a hazard for users.

See also: https://github.com/datawire/ambassador/issues/1871

**Comment by samodell** [comment]
@mattmoor  can you confirm if the e2e testing has landed and these docs are good to stay, or if we should take them out?

**Comment by mattmoor** [comment]
I don't see a tab, though I believe some of the pieces have landed.  @concaf where are we on getting this into testgrid.knative.dev?

**Comment by concaf** [comment]
@samodell @mattmoor e2e tests have landed, I'm now looking at what the next steps are, will be pinging on Slack for the same.

Tests have landed at https://github.com/knative/serving/pull/6268 and https://github.com/knative/test-infra/pull/1598. I've updated the docs at https://github.com/knative/docs/pull/1893 as well. Will be updating to the latest Ambassador which was released last week.

https://github.com/datawire/ambassador/issues/1871 has been fixed as well, so instructions work fine without any panic.

**Comment by abrennan89** [comment]
@concaf can this issue be closed or is there any additional docs work to do? Thanks :slightly_smiling_face:

**Comment by concaf** [comment]
@abrennan89 the docs are fine, there are tests as well which are not perfect but being worked on as and when time permits - I'm OK with closing this issue.

**Comment by thecodacus** [comment]
Issue is still happening if installed via helm chart

**Comment by abrennan89** [comment]
> Issue is still happening if installed via helm chart

What issue?

**Comment by thecodacus** [comment]
> > Issue is still happening if installed via helm chart
> 
> What issue?

[datawire/ambassador#1871](https://github.com/datawire/ambassador/issues/1871)

if I install Ambassador via helm chart, its throwing same error
Found a temporary solution I have added as comment [datawire/ambassador/issues/1871#issuecomment-669095130](https://github.com/datawire/ambassador/issues/1871#issuecomment-669095130l)
