### ISSUE TITLE
rest-api-go uses an SaaS service API which is now deleted.

### ISSUE THREAD

**Issue by d2iq-shadowbq** [knative/docs#2053]
## Expected Behavior

A sample application in the documentation should work as expected.

https://github.com/knative/docs/blob/06881add07600c2e8252e77a45aa489714710c1a/docs/serving/samples/rest-api-go/stock.go#L66

A price is returned

## Actual Behavior

The docs reference in a sample a SaaS service by [iextrading.com](iextrading.com) which is no longer publicly available.

Fetching "https://api.iextrading.com/1.0/stock/ibm/price" outside of the docs api shows this API no longer works.

"forbidden" 

## Steps to Reproduce the Problem

1. Make an api request to the sample rest-api-go example
2. recieve an "forbidden"
3. See: https://iextrading.com/developers/ 
Phase I (Removed June 1, 2019) removed "Price"

**Comment by abrennan89** [comment]
@markusthoemmes @mattmoor is there someone who can provided updates for these docs? Otherwise if the sample is outdated we should remove it.

**Comment by abrennan89** [comment]
(closed by accident, apologies!)

**Comment by mattmoor** [comment]
We should probably just remove this sample.
