### ISSUE TITLE
istio self-install instructions broken/incomplete

### ISSUE THREAD

**Issue by ahmetb** [knative/docs#2067]
Page: https://knative.dev/docs/install/installing-istio/#installing-istio-with- sidecar-injection
and
https://knative.dev/docs/install/installing-istio/#installing-istio-without-sidecar-injection

Specifically the highlighted part `install/kubernetes/helm/istio`.

![image](https://user-images.githubusercontent.com/159209/71142232-a0519400-21cb-11ea-9ef3-920a8e549a41.png)

I'm not sure how it's supposed to work. That's a file path reference but docs don't explain where to find that file. (I assume istio/istio repo needs to be cloned first, but it's not mentioned in the page).

Furthermore `kubectl create namespace istio-system` is required before kubectl apply. It's not mentioned.

**Comment by mpetason** [comment]
It looks like both of these items are covered by -

https://knative.dev/docs/install/installing-istio/#downloading-istio-and-installing-crds

# Download and unpack Istio
export ISTIO_VERSION=1.3.6
curl -L https://git.io/getLatestIstio | sh -
cd istio-${ISTIO_VERSION}

After doing the above commands you'll have the correct path - istio-1.3.6/install/kubernetes/helm/istio.

Then we create a namespace before running the kubectl commands:

cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
  labels:
    istio-injection: disabled
EOF
