### ISSUE TITLE
superfluous new lines in some code blocks

### ISSUE THREAD

**Issue by ahmetb** [knative/docs#2068]
Code blocks in https://knative.dev/docs/serving/accessing-traces/ page have trailing new line

![image](https://user-images.githubusercontent.com/159209/71143226-a301b880-21ce-11ea-841d-65066ee5ae61.png)

**Comment by ahmetb** [comment]
ditto this page: https://knative.dev/docs/serving/cluster-local-route/
and this page: https://knative.dev/docs/serving/debugging-application-issues/
I think there are more.

**Comment by mpetason** [comment]
Most of the docs look like this were shell is used:

```shell
kubectl proxy
```

To get it to show up without the extra spacing other sections use:

```
scale-to-zero-grace-period: "30s"
```

I think either we would have to change all of the ```shell blocks and use ```, or leave it as is since most of the shell blocks match. 

Any ideas?

**Comment by abrennan89** [comment]
@mpetason agreed, I think this is a larger question about whether or not we use fenced code blocks. Let's take it to a WG call and figure it out before we tackle this. We should do a review of the whole site to make this consistent once we've decided a style.

**Comment by evankanderson** [comment]
This seems to be something about the `<pre` wrapping the `<code` that introduces an extra 15 pixels (per Developer tools)

<pre style="background-color:#f8f8f8;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-shell" data-lang="shell">kubectl label kservice <span style="color:#4e9a06">${</span><span style="color:#000">KSVC_NAME</span><span style="color:#4e9a06">}</span> networking.knative.dev/visibility<span style="color:#ce5c00;font-weight:bold">=</span>cluster-local
</code></pre>

**Comment by RichieEscarez** [comment]
Not sure what the cause is but the syntax highlighting configuration is here that you might be able to play with and fix/remove the extra line: https://gohugo.io/content-management/syntax-highlighting/
