### ISSUE TITLE
Document which PodSpec fields are valid

### ISSUE THREAD

**Issue by duglin** [knative/docs#2085]
**Describe the change you'd like to see**
While the yaml for a KnService leverages the Kubernetes PodSpec definition, not all of the PodSpec fields are valid for KnServices. We should document which fields people can use.

**Comment by duglin** [comment]
Perhaps just a pointer to https://github.com/knative/docs/blob/master/docs/serving/spec/knative-api-specification-1.0.md#container since I didn't see how to get to this doc from our md files.
Seem like https://knative.dev/docs/reference/serving-api/#serving.knative.dev/v1beta1.Revision might be a duplicate, which is unfortunate since that might mean they get out of sync.

**Comment by arghya88** [comment]
is initcontainers allowed?

**Comment by duglin** [comment]
@arghya88 no I do not think they are supported yet

**Comment by evankanderson** [comment]
This is currently only available in code, AFAIK.

The code [is here](https://github.com/knative/serving/blob/main/pkg/apis/serving/k8s_validation.go#L281) (`ValidatePodSpec`), but I don't think there's an easy way to go from that code to any sort of documentation. If this is still a high priority, it will probably require some amount of pairing, plus some type of tracking checking for items getting out of date between code and docs. (Possibly as simple as a list of PRs from some date to now affecting the file which could be used to update the documentation.)

/triage needs-eng-input

(We should pair-assign this to an engineer for pairing if it becomes high enough priority that someone wants to start writing this and the code isn't clear on its own.)

**Comment by duglin** [comment]
Not sure about its relative priority but as it stands today, only reading the docs I'm not sure someone can figure out which podSpec fields are supported - and I think that's an important concern.

**Comment by markusthoemmes** [comment]
For whatever that's worth: We now also have this as part of the openAPI schema of the Revision (and Service and Configuration). Maybe we can generate something from that?

**Comment by abrennan89** [comment]
I think we should close this one since it seems that https://github.com/knative/docs/issues/3523 supersedes it, and it has been open for over 1.5 years with no meaningful action or eng input provided to create docs. Please bring the discussion to the DUX WG if you feel that there's something important stemming from this that needs to be raised.
