### ISSUE TITLE
`deploy your own version knative serving`  IS NOT WORK

### ISSUE THREAD

**Issue by Iamlovingit** [knative/docs#2088]
I have changed the https://github.com/knative/serving/blob/1d263950f9f2fea85a4dd394948a029c328af9d9/pkg/reconciler/revision/resources/resourceboundary.go#L30, give more resource to `queue-proxy`, at least `200m to 400m`. Then i run the `ko apply -f config/`, and `apply` a `hello-world` demo.
Describe the pod, the container resource is not changed.  Where is wrong?
 ```
queue-proxy:
    Container ID:   docker://0466b532c898be263366752ef24f5841b67e6ee503dd448d53d6ce2e891050a2
    Image:          docker.io/iamlovingit/queue-39be6f1d08a095bd076a71d288d295b6@sha256:2cacac930f366900364f3bfcdf8249f1a2a581e6a1d85b4692b818d8d42f3f17
    Image ID:       docker-pullable://iamlovingit/queue-39be6f1d08a095bd076a71d288d295b6@sha256:2cacac930f366900364f3bfcdf8249f1a2a581e6a1d85b4692b818d8d42f3f17
    Ports:          8022/TCP, 9090/TCP, 9091/TCP, 8012/TCP
    Host Ports:     0/TCP, 0/TCP, 0/TCP, 0/TCP
    State:          Running
      Started:      Thu, 09 Jan 2020 19:27:23 +0800
    Ready:          True
    Restart Count:  0
    Requests:
      cpu:      25m
```
## Expected Behavior
the resource of `cpu` is `200m`

## Steps to Reproduce the Problem

1. change the resource code https://github.com/knative/serving/blob/1d263950f9f2fea85a4dd394948a029c328af9d9/pkg/reconciler/revision/resources/resourceboundary.go#L30
1. run the `ko apply -f config/`
1. deploy demo `kubectl apply -f service.yaml`
1. describe the pod, and check the `resource`

## Additional Info
**Additional context**

**Install information:**
 - Platform (GKE, IKS, AKS, etc.):minikube
 - Knative Version:0.2.2

**Comment by samodell** [comment]
@Iamlovingit  for troubleshooting, you may want to post to the Knative Slack.

Did you encounter this error while following a particular page in the docs? If so, please let us know! For now, it sounds to me like this might not be a documentation issue. Feel free to open an issue in the Serving repo, or reopen this issue if this is a documentation issue.
