### ISSUE TITLE
Page needs improvement

### ISSUE THREAD

**Issue by rstroop** [knative/docs#2104]
I have the fanout error described at the bottom of the post, but the document does not describe how to fix or debug the issue. Only that it is having an issue communicating. This section at least should be finished, even if the rest of the document cannot be.

**Comment by samodell** [comment]
Hi @rstroop  -- your issue doesn't contain any information about the page you were on when you encountered this problem. Can you please link to the document?

**Comment by rstroop** [comment]
I was referring to this page: https://knative.dev/docs/eventing/debugging/


Richard Stroop

Senior Integration Architect

Red Hat <https://www.redhat.com>

M: 703.200.7586
<https://www.redhat.com>

Let no debt remain outstanding, except the continuing debt to love one
another, for whoever loves others has fulfilled the law. -Romans 13:8 NIV
