### ISSUE TITLE
Support for networking protocols is not explained anywhere

### ISSUE THREAD

**Issue by ahmetb** [knative/docs#2108]
Upon visiting https://knative.dev/docs/serving/
I read what Knative serving is.

I wonder, does it support HTTP? Ctrl-f 'http':
![image](https://user-images.githubusercontent.com/159209/72502073-57eabd80-37ed-11ea-8d92-07ed7985ba71.png)

I wonder: does it support grpc? 
Ctrl-F 'grpc': [no results]

I wonder: does it support any TCP application? How about UDP?
Ctrl-F 'tcp', 'protocol', 'network': [no relevant results]

**Comment by abrennan89** [comment]
@ahmetb is this issue still relevant? I tried searching grpc and saw some results but idk if it's what you're looking for.
I'd recommend using the actual site search rather than Ctrl+F until docs are organized better...

**Comment by ahmetb** [comment]
I think it’s still very much relevant. Almost like it should be in project introduction. A very fundamental question a visitor might ask.

**Comment by evankanderson** [comment]
This should probably be in some very introductory (first 2-3 pages of the site) content that both HTTP and HTTPS are supported, and that Knative has tools to help with HTTPS setup if you want that and are internet-connected with a DNS name.

**Comment by abrennan89** [comment]
@evankanderson I see this one's still assigned to you, do you plan to add a PR or something for this? Thanks
