### ISSUE TITLE
Concurrent request to the helloworld-go example.

### ISSUE THREAD

**Issue by dongdan39** [knative/docs#2113]
Hi,
  I have successfully deploy and test the helpful helloworld-go knative example on my kubernetes cluster. Now I want to test multiple concurrent request to the knative serverless service to watch the auto scale up and down of the service, but I found the curl command does not work here, there's always only one pod running for all the requests. And I also tested with commands like "ab" and "hey" but neither works. Any suggestions here? 

Cheere,
Dan

**Comment by samodell** [comment]
Hi @dongdan39 , for help with troubleshooting, you'll probably have the best luck reaching out on Slack: slack.knative.dev
