### ISSUE TITLE
Internal error occurred: failed calling webhook "sinkbindings.webhook.sources.knative.dev": Post https://eventing-webhook.knative-eventing.svc:443/sinkbindings?timeout=30s: service "eventing-webhook" not found

### ISSUE THREAD

**Issue by karimbzu** [knative/docs#2124]
failed to run operator. error starting device discovery daemonset. Error starting discover daemonset: failed to create rook-discover daemon set. Internal error occurred: failed calling webhook "sinkbindings.webhook.sources.knative.dev": Post https://eventing-webhook.knative-eventing.svc:443/sinkbindings?timeout=30s: service "eventing-webhook" not found

## Expected Behavior
The pods should be created successfully

## Actual Behavior
Failed on every operator installation

## Steps to Reproduce the Problem

1.
1.
1.

## Additional Info
**Additional context**
Previously i installed knative successfully on openshift 4.2 and removed for practice, may be i did not properly delete all the knative resources, however when i tried to reinstall knative or any other operator, i am no longer able to do.
Now i cannot install any operator from operator hub every package failed with the above-mentioned error i.e
Internal error occurred: failed calling webhook "sinkbindings.webhook.sources.knative.dev": Post https://eventing-webhook.knative-eventing.svc:443/sinkbindings?timeout=30s: service "eventing-webhook" not found

**Install information:**
 - Platform (Openshift 4.2.14.):
 - Knative Version 0.12:

**Comment by samodell** [comment]
Hi @karimbzu  -- sorry to hear you're having trouble! For help, you'll probably have the best luck reaching out on slack: https://slack.knative.dev

**Comment by karimbzu** [comment]
@samodell Thanks for your support, i have resolved the issue from slack group you shared. 
This was the solution: oc delete mutatingwebhookconfigurations.admissionregistration.k8s.io sinkbindings.webhook.sources.knative.dev

thanks alot

**Comment by sxmon** [comment]
I also had to delete delete mutatingwebhookconfigurations.admissionregistration.k8s.io legacysinkbindings.webhook.sources.knative.dev

**Comment by kailashyogeshwar85** [comment]
It still tries to send data to eventing-webhook after deletion. Any further steps.

**Comment by abrennan89** [comment]
@karimbzu are you still having issues if you use the current 0.16 docs to do a fresh install?
It doesn't look to me like this is a documentation issue, at least not until it's clear what is causing the problem and needs to change in docs.

If you're specifically trying to install in OpenShift Container Platform, this has its own documentation for each version of the platform: https://docs.openshift.com/

Let me know if this issue can be closed. Thanks.
