### ISSUE TITLE
GCP Cloud Pub/Sub source page needs update for v0.12.0

### ISSUE THREAD

**Issue by meteatamel** [knative/docs#2136]
[GCP Cloud Pub/Sub source](https://knative.dev/docs/eventing/samples/gcp-pubsub-source/) page is out of date as of Knative v0.12.0. It needs to be updated to show all the setup steps I mentioned here:

https://github.com/meteatamel/knative-tutorial/blob/master/docs/pubsubeventing.md

**Comment by abrennan89** [comment]
This page doesn't exist anymore - docs point out to a different example repo now: https://knative.dev/docs/eventing/samples/cloud-pubsub-source/
Closing.
