### ISSUE TITLE
Page needs improvement - Links provided for UIs are localhost URLs and are of no use

### ISSUE THREAD

**Issue by SarnathK** [knative/docs#2139]
## Expected Behavior
The URL for various tracing tools should show how the tracing UI looks like
## Actual Behavior
The URL is mapped to localhost which expects the UI to run on my machine
## Steps to Reproduce the Problem

1. Click the URLs given for Zipkin UI and the other one
2. You will receive a Unable to connect message
3.

**Comment by samodell** [comment]
Hi @SarnathK  -- those URLs do work if you have the monitoring tools set up locally. If you are just wanting to see what the tools look like before installing Knative or monitoring, you could check out each tool's website. We do link out to each tool's page in the accessing metrics guide: https://knative.dev/docs/serving/accessing-metrics/ , which I think may have been the page you were on.

I'm going to close this out.
