### ISSUE TITLE
Cron job source example: outdated image

### ISSUE THREAD

**Issue by matejvasek** [knative/docs#2145]
## Expected Behavior
Log of the pod running the event-display service should contain information about received events (begins with "☁️  cloudevents.Event" as described in the example).

## Actual Behavior
Log contains errors:
`{"level":"error","ts":1580396460.0210204,"logger":"fallback","caller":"http/transport.go:408","msg":"failed to decode message","error":"unknown encoding","stacktrace":"github.com/knative/eventing-sources/vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/http.(*Transport).ServeHTTP
	/go/src/github.com/knative/eventing-sources/vendor/github.com/cloudevents/sdk-go/pkg/cloudevents/transport/http/transport.go:408
net/http.(*ServeMux).ServeHTTP
	/usr/local/go/src/net/http/server.go:2375
net/http.serverHandler.ServeHTTP
	/usr/local/go/src/net/http/server.go:2774
net/http.(*conn).serve
	/usr/local/go/src/net/http/server.go:1878"}
`

## Steps to Reproduce the Problem
Follow [Cron Job Source example](https://github.com/knative/docs/blob/2500dffaf24475dfb9082a6e11971a86ec9924dc/docs/eventing/samples/cronjob-source/README.md) from documentation.

## Additional Info
The service yaml references older registry: `gcr.io/knative-releases/github.com/knative/eventing-sources/cmd/event_display`.
I believe it should reference newer registry: `gcr.io/knative-releases/knative.dev/eventing-contrib/cmd/event_display` (maybe with fixed revision).

**Install information:**
 - Knative Eventing Version: 0.12.0

**Comment by matejvasek** [comment]
The gcr.io/knative-releases/github.com/knative/eventing-sources/cmd/event_display image is also used in some other places:

`docs/eventing/getting-started.md
docs/eventing/getting-started.md
docs/eventing/samples/container-source/service.yaml
docs/eventing/samples/container-source/README.md
docs/eventing/samples/gcp-pubsub-source/event-display.yaml
docs/eventing/samples/cronjob-source/service.yaml
docs/eventing/samples/cronjob-source/README.md
docs/eventing/samples/iot-core/trigger.yaml
docs/eventing/samples/helloworld/helloworld-go/README.md
docs/eventing/samples/parallel/mutual-exclusivity/event-display.yaml
docs/eventing/samples/parallel/mutual-exclusivity/README.md
docs/eventing/samples/parallel/multiple-branches/event-display.yaml
docs/eventing/samples/parallel/multiple-branches/README.md`

maybe it could caused problems there too.

**Comment by samodell** [comment]
Related to #2147  -- @vaikas  should we update the eventdisplay URL to the one used in PR #2148  in these other locations in the docs?

**Comment by vaikas** [comment]
Yes we should. That was my question in the docs meeting about using a variable and then when we push a new version, all these should change :)
