### ISSUE TITLE
Document HPA-class autoscaling in Knative/Serving

### ISSUE THREAD

**Issue by mattmoor** [knative/docs#2152]
We need documentation for how to configure HPA-class autoscaling in knative/serving

/assign @markusthoemmes 
cc @vagababov 

I'm opening this as a placeholder for a TODO in the consolidated install documentation that I'm working on, which covers how to *install* this, but we still need docs on *using* it.

**Comment by vagababov** [comment]
Is there a way to link it to the project in the serving? 🙄 
Ref: https://github.com/knative/serving/projects/11

**Comment by markusthoemmes** [comment]
I think with the recent autoscaling docs rework, this is done.

/close
