### ISSUE TITLE
Document the installation of additional Channel implementations

### ISSUE THREAD

**Issue by mattmoor** [knative/docs#2153]
I'm adding this for use in a TODO, which will hopefully make the intent of this more clear, but the gist is as follows...

I'm reworking the core installation instructions to use tabs at various decision points, and for Eventing one of those decision points is which Channel to use.  At present, the only documented channel will be `InMemory`, which is called out as not production ready.  It would be good to get at least a handful of production ready options documented in this format.

**Comment by vaikas** [comment]
I brought this up in the Channel WG last week and this week also. @matzew volunteered to have a simple way to install at least Kafka. Nats we're looking for volunteers. For others we need to follow up.

**Comment by matzew** [comment]
Is something like:

```
#!/usr/bin/env bash
set -e
# Turn colors in this script off by setting the NO_COLOR variable in your
# environment to any value:
#
# $ NO_COLOR=1 test.sh
NO_COLOR=${NO_COLOR:-""}
if [ -z "$NO_COLOR" ]; then
  header=$'\e[1;33m'
  reset=$'\e[0m'
else
  header=''
  reset=''
fi
strimzi_version=`curl https://github.com/strimzi/strimzi-kafka-operator/releases/latest |  awk -F 'tag/' '{print $2}' | awk -F '"' '{print $1}' 2>/dev/null`
function header_text {
  echo "$header$*$reset"
}
header_text "Using Strimzi Version:                  ${strimzi_version}"
header_text "Strimzi install"
kubectl create namespace kafka
curl -L "https://github.com/strimzi/strimzi-kafka-operator/releases/download/${strimzi_version}/strimzi-cluster-operator-${strimzi_version}.yaml" \
  | sed 's/namespace: .*/namespace: kafka/' \
  | kubectl -n kafka apply -f -
header_text "Applying Strimzi Cluster file"
kubectl -n kafka apply -f "https://raw.githubusercontent.com/strimzi/strimzi-kafka-operator/${strimzi_version}/examples/kafka/kafka-persistent-single.yaml"
header_text "Waiting for Strimzi to become ready"
sleep 5; while echo && kubectl get pods -n kafka | grep -v -E "(Running|Completed|STATUS)"; do sleep 5; done
``` 

working for you, for kafka install (the kafka broker - not any knative kafka bits)

**Comment by vaikas** [comment]
sorry, been distracted. I'm going to see if we can pipe the artifacts into yaml and just apply that one yaml?

**Comment by vaikas** [comment]
Thanks for doing this @matzew 
I ran these with just a small change by piping the intermediate yamls into .yaml files and then applying them separately, they worked great from what I can tell!! 💪 
Seems like we should be able to add this very similarly to how we create Istio install yamls in Serving:
https://github.com/knative/serving/blob/0b0f9605df5c080a91fa26eb50f8d895364e5c57/third_party/istio-1.3.6/download-istio.sh

So, if we had a "download-istio.sh" that would then create minimal-kafka.sh that would be a fantastic start.
@matzew @mattmoor make sense? If so, @matzew would you mind doing that?

**Comment by mattmoor** [comment]
I think we want something like that for Eventing developers/development, but I'm not sure we want to ship the yamls for our docs (we don't for Istio, the produced yamls are just for contributors).

I think we need a goal where the default tabs [here](https://knative.dev/development/install/knative-with-any-k8s/#installing-the-eventing-component) leave users with a realistic install of Eventing.  In-Memory is all we have/support upstream today and it is (and always will be) a toy.

If you take a look at the networking options in Serving, that's sort of the direction I'd like to see us head for Eventing.  At a minimum we need a default "blessed" option that isn't a toy, and I'll admit I'm a little worried about a "v1" story for Eventing where the only neutral options live in contrib with limited/no testing 😬

**Comment by matzew** [comment]
some work being captured here: https://github.com/knative/eventing-contrib/issues/895

**Comment by mattmoor** [comment]
Works for me @matzew !
