### ISSUE TITLE
No eventing install docs

### ISSUE THREAD

**Issue by duglin** [knative/docs#2161]
Unless I'm missing it, I can't find any docs on https://knative.dev/docs/install/ about installing eventing. I know that people can be selective about what to install, but can we at least point people to the corresponding release on github and give a little bit of guidance as to what the list of release artifacts are?

**Comment by samodell** [comment]
I feel like this is addressed with the new version of the install page Matt put together: https://knative.dev/development/install/knative-with-any-k8s/

That will go live in v0.13, so closing this out. Feel free to reopen if you disagree.
