### ISSUE TITLE
Create streamlined Istio install instructions to inline

### ISSUE THREAD

**Issue by mattmoor** [knative/docs#2166]
See the original comment here: https://github.com/knative/docs/pull/2155#discussion_r374427602

The idea is that we should have some instructions that inline some basic steps here to avoid folks having to jump elsewhere and return.

cc @tcnghia

**Comment by mattmoor** [comment]
I wonder how feasible it would be to try and adopt `istioctl install` for this.

**Comment by mattmoor** [comment]
In fact, given that it seems to have built-in "profiles" I wonder how hard it would be to get them to build in a knative profile 😍

**Comment by mattmoor** [comment]
/lifecycle frozen

cc @nak3 @ZhiminXiang @julz @markusthoemmes 

Similar to the sentiment in Serving's DEVELOPMENT.md, I've long wanted a simple default story here.

Can we please put some energy into this?  Does the idea of having a custom Istio profile for knative hold water?  I seem to recall Louis Ryan being receptive to even potentially shipping such a thing built-into istioctl...

🙏

**Comment by nak3** [comment]
/assign

Sure, I will try to discuss with Istio community.
