### ISSUE TITLE
Add editable search box to search results page

### ISSUE THREAD

**Issue by duglin** [knative/docs#2202]
**Describe the change you'd like to see**
From this page: https://knative.dev/docs/
if I enter a search phrase I get a new tab/window with the results.
However, the search phrase is not shown to me on that results page in an editable form. Which means if I had a typo in my search I need to close the window and use the old/previous window. It would be nice if I could just edit the search phrase on this new results page.

Here's what the page looks like now:
<img width="1059" alt="image" src="https://user-images.githubusercontent.com/1944671/74239014-fced9e80-4ca4-11ea-8662-489584903ab2.png">

**Comment by samodell** [comment]
@duglin  could you reopen this in the Website repo?
