### ISSUE TITLE
Document what's going beta in 0.13

### ISSUE THREAD

**Issue by mattmoor** [knative/docs#2204]
I believe a bunch of stuff in eventing is hitting Beta in 0.13, we should update the `feature-state`s of these and make sure our samples reflect any changes.

cc @vaikas @lionelvillard

**Comment by mattmoor** [comment]
I think this is done?  @vaikas ?

**Comment by abrennan89** [comment]
Closing since this is a couple of releases old. Please open a new issue and call out any specific doc changes if there's still a requirement here.
