### ISSUE TITLE
Samples should listen on $PORT instead of 8080

### ISSUE THREAD

**Issue by rgregg** [knative/docs#221]
## Expected Behavior
Per the container contract in knative/serving, containers serving HTTP traffic should listen on the port specified in the $PORT environment variable, and not assume 8080 (despite this being the default value).

## Actual Behavior
Most of the samples are hard coded to listen on 8080.

**Comment by Duaard** [comment]
Hi I know this is not the place to ask this but did you manage to change the exposed port and target port? The documentation should really provide examples for servers listening to ports other than 8080

**Comment by ahmetb** [comment]
Context:
- process contract explaining $PORT https://github.com/knative/serving/blob/master/docs/runtime-contract.md#process
- network contract https://github.com/knative/serving/blob/master/docs/runtime-contract.md#inbound-network-connectivity

**Comment by Uvindu96** [comment]
Hey I have an application running on port number 9095 but my knative service is on port 8080, so can i chnage this 8080 port to 9095 in  my knative service?
