### ISSUE TITLE
Document and update examples for v1beta1 for Broker,Trigger, and EventType

### ISSUE THREAD

**Issue by vaikas** [knative/docs#2248]
## What is changing? (Please include as many details as possible.)
Adding v1beta1 apis for Broker,Trigger, EventType

## How will this impact our users?
Users will have a cleaner API.

## In what release will this take happen (to the best of your knowledge)?
V0.13

## Context
Link to associated PRs or issues from other repos here.

1. Trigger: https://github.com/knative/eventing/pull/2414
1. EventTypes: https://github.com/knative/eventing/pull/2466
1. Broker: https://github.com/knative/eventing/pull/2449

**Comment by abrennan89** [comment]
@vaikas is this issue closed by #2259 ? If not, what else is required here?
