### ISSUE TITLE
glooctl --dry-run doesn't include the creation of the gloo-system namespace

### ISSUE THREAD

**Issue by mreferre** [knative/docs#2255]
## Expected Behavior
When I generate the yaml file using the `--dry-run` flag (i.e. `glooctl install knative --dry-run > knative-gloo-fargate.yaml`) I expect to produce a yaml that I can apply. 

## Actual Behavior
The yaml generated apparently misses the creation of the `gloo-system` namespace so everything that is being applied in that ns fails.

## Steps to Reproduce the Problem
```
glooctl install knative --dry-run > knative-gloo.yaml
kubectl apply -f knative-gloo.yaml
```
At this point all resources that are deployed in the `gloo-system` ns fails. A quick workaround is to edit the file and add the following:
```
apiVersion: v1
kind: Namespace
metadata:
  name: gloo-system
```
## Additional Info
Not sure if this is a documentation bug or (more likely?) a `glooctl` bug?

**Install information:**
 - Platform: EKS
 - Knative Version: 0.10

**Comment by mpetason** [comment]
Which section were you running into issues on docs? It does seem like you'd want to either setup the gloo namespace first or if you want to use a namespace other than the gloo-system namespace you would want to add the -n flag:

  -n, --namespace string    namespace for reading or writing resources (default "gloo-system")

**Comment by mreferre** [comment]
Thanks @mpetason. It turned out this is more of a `glooctl` issue than a doc issue. I am tracking it here: https://github.com/solo-io/gloo/issues/2533. 

Thanks for chiming in. I am going to close this issue.
