### ISSUE TITLE
Application Kafka topics with KNative Trigger filtering configuration and example

### ISSUE THREAD

**Issue by tarunrathor-pro** [knative/docs#2262]
**Describe the change you'd like to see**
A example where Kafka is the default channel and Trigger with filters based on event fields.
Additionally the real source of events is application kafka  topics ( not the kafka channel topics).

What would the complete setup be in this case. Does it still need the KafkaSource to read from application level kafka topics to publish to brokers (with kafka backed channels)

Any guidance on how the schema for the application level Kafka topic should be to support Trigger filters
Options:
1. CloudEvent specification for Kafka with binary content mode  with avro serialisation
https://github.com/cloudevents/spec/blob/master/kafka-protocol-binding.md#32-binary-content-mode
2. CloudEvent specification for Kafka with structure mode with avro serialization.
https://github.com/cloudevents/spec/blob/master/kafka-protocol-binding.md#33-structured-content-mode

**Additional context**
https://github.com/knative/docs/tree/master/docs/eventing/samples/kafka
contains example for  
1) 'kafka source' -> 'service'
2) 'broker' -> 'trigger' -> 'service'

**Comment by abrennan89** [comment]
Also move all Kafka samples to one place under Eventing instead of buried in Code Samples
https://github.com/knative/docs/pull/2707#discussion_r468762810

**Comment by vaikas** [comment]
@matzew thoughts on who might be able to help out here?

**Comment by vaikas** [comment]
@slinkydeveloper

**Comment by slinkydeveloper** [comment]
> What would the complete setup be in this case. Does it still need the KafkaSource to read from application level kafka topics to publish to brokers (with kafka backed channels)

Yes that's how knative eventing works. You send events from KafkaSource through the broker that filters them to the final consumers

**Comment by abrennan89** [comment]
@tarunrathor-pro 

Default Kafka channel info: https://knative.dev/docs/eventing/configuration/kafka-channel-configuration/
Using Kafka broker: https://knative.dev/docs/eventing/broker/kafka-broker/
Triggers: https://knative.dev/docs/eventing/broker/triggers/
Kafka source: https://knative.dev/docs/eventing/sources/kafka-source/

I believe there should be enough information between those links to answer your questions, but please let me know otherwise what specifically is missing
