### ISSUE TITLE
Release 0.13 blocker: Install docs look out of date

### ISSUE THREAD

**Issue by RichieEscarez** [knative/docs#2265]
docs/docs/install/knative-with-any-k8s.md

1. includes lots of "feature state" version numbers and its unclear if they all need to be changed to 0.13. im not familiar with these entries or where else they are used but we should ensure that they are up to date before cutting a release branch and publishing

2. there are also lots of new terminology that do not align with the previous team agreed on "observability plugin". looks like this is the only place where "monitoring bundle" is used but the rest of the docs do not align

3. SEO: the filename include the product name and an unofficial short reference to kubernetes. this means that search engines will read the url and not actually get targeted results. given that this is a major change, we should not stack two filename changes back to back and should do this prior to publishing (see redirects issue mentioned below). the goal is that the filename should specifically reflect the content and not just repeat the product. for example the site domain and folder name already provide the context of "Knative" + "install", so a filename like `any-kubernetes-cluster.md` would greatly improve SEO.

4. For all the files moved, deleted, or renamed, there should be redirects created to avoid all user's links (from articles, blog posts, bookmarks, etc.) from landing on 404s.

**Comment by mattmoor** [comment]
1. This is consistent with (in fact based on) Kubernetes's equivalent, it lists the version at which the feature reached the current state.

2. This is news to me, and I'm a little surprised it wasn't raised in code review.

3. The only change I made to this (pre-existing) filename was to make it all lowercase because otherwise Hugo and the markdown linter couldn't agree on links.

4. My recollection is that these were all added to the main page, are you aware of any that are missing?

**Comment by RichieEscarez** [comment]
Sorry, Im really just trying to help ellenevans@ push out a release and dont have time to track any of this down nor try to fix it.

1. I see. Do we have a list somewhere that explains more about Knative feature states, it initially looked like we failed to update the numbers from v0.09 and confused me.

2. All the tools in the "observability plugin" are not just monitoring, there is tracing and visualization. This is a consistency thing, it should be referenced the same everywhere.

3. This is an opportunity thing to not only fix the build (i think i have a issue opened for that somewhere) but to improve it while this change is happening (i think there is another issue somewhere for that too).

4. General rule is to not assume everyone linked to just the main page like most of our docs did. We should always cover all scenarios and basically, always ensure nobody hits a 404 (we dont know who bookmarked their favorite install guide but with a redirect we can guarantee they wont find the new version).

**Comment by mattmoor** [comment]
@RichieEscarez re: `4.`

Is that not what this does?
```
aliases:
  - /docs/install/knative-with-aks
  - /docs/install/knative-with-ambassador
  - /docs/install/knative-with-contour
  - /docs/install/knative-with-docker-for-mac
  - /docs/install/knative-with-gke
  - /docs/install/knative-with-gardener
  - /docs/install/knative-with-gloo
  - /docs/install/knative-with-icp
  - /docs/install/knative-with-iks
  - /docs/install/knative-with-microk8s
  - /docs/install/knative-with-minikube
  - /docs/install/knative-with-pks
---
```

**Comment by mattmoor** [comment]
> This is an opportunity ... to improve it 

Ack, so not blocking?

**Comment by RichieEscarez** [comment]
oh yup, the aliases covers that. I do think that we should maintain a level of quality and not challenge our users all the time my minimizing the filename changing (thus my push for changing this before it goes out). but that said, im completely distracted right now (enough to not even notice the aliases)  and dont have the bandwidth to help here. thanks @mattmoor !

**Comment by mattmoor** [comment]
Sent a PR for `2.`, are any of the rest blocking / actionable?

**Comment by mattmoor** [comment]
@RichieEscarez re: renames, the knative-with-any-k8s -> other is itself a rename! 🤣

**Comment by mattmoor** [comment]
I can TAL at that now, since I've got my repo warmed up.

**Comment by RichieEscarez** [comment]
@mattmoor to save the day! thank for fixing all this!
