### ISSUE TITLE
[0.14] Eventing is removing api group sources.eventing.knative.dev

### ISSUE THREAD

**Issue by n3wscott** [knative/docs#2267]
## What is changing? (Please include as many details as possible.)
Eventing is dropping the api group `sources.eventing.knative.dev` from knative/eventing.

## How will this impact our users?

The following resources are removed:

- `CronJobSource/sources.eventing.knative.dev`
- `ApiServerSource/sources.eventing.knative.dev`
- `SinkBinding/sources.eventing.knative.dev`
- `ContainerSource/sources.eventing.knative.dev`

## In what release will this take happen (to the best of your knowledge)?
v0.14

**Comment by abrennan89** [comment]
@n3wscott what would be the required doc changes in relation to this?

**Comment by n3wscott** [comment]
It might be already done

**Comment by n3wscott** [comment]
Searched and found no old refs to the Kinds listed.
