### ISSUE TITLE
Document Broker Classes and how to default them.

### ISSUE THREAD

**Issue by vaikas** [knative/docs#2281]
## What is changing? (Please include as many details as possible.)
We're going to have multiple Broker Classes, document how you can default them in the broker defaults configmap.

## How will this impact our users?
They can specify different brokers and in particular with this issue, we need to document how they can default them.

## In what release will this take happen (to the best of your knowledge)?
v0.14

## Context
Link to associated PRs or issues from other repos here.

1. https://github.com/knative/eventing/pull/2724
1.
1.

**Comment by pierDipi** [comment]
This is done: https://knative.dev/docs/eventing/broker/defaults-br-config/

/close
