### ISSUE TITLE
Monitoring docs depend on istio

### ISSUE THREAD

**Issue by matzew** [knative/docs#2290]
## Actual Behavior

when using different ingress than istio... the installation of monitoring does not fully work!

## Steps to Reproduce the Problem

1. go here: https://knative.dev/docs/install/any-kubernetes-cluster/#installing-the-observability-plugin
1. run `kubectl apply --filename https://github.com/knative/serving/releases/download/v0.13.0/monitoring-metrics-prometheus.yaml
` and get error:
```
...
kubectl apply --filename https://github.com/knative/serving/releases/download/v0.13.0/monitoring-metrics-prometheus.yaml
...
```

or is this more a serving bug? since it's in its release section? /cc @mattmoor

**Comment by vaikas** [comment]
@mdemirhan is this something that you could find an owner for?
/assign @mdemirhan

**Comment by matzew** [comment]
@mdemirhan any thoughts on this   and/or https://github.com/knative/serving/issues/7197 ?

**Comment by mdemirhan** [comment]
Our only installation story at the moment is via hard coded YAML files. These problems can be solved when we move to an operator based installation and I believe this would be a good input for the operations work group. For YAML based installation, the only option I can think of is to define different YAMLs for each of the networking ingresses.

I put my thoughts for #7197 as well - see below for a copy/paste of that:

_We need to have a solution for this, but not sure if a common namespace is the right solution. Istio for example use istio-system in a hard coded fashion (unless we customize it for ourselves). A better option would be to customize our installation to take that as an input. But that probably requires deploying via operators. @k4leung4 any suggestions?_

I cannot work on this myself, but CCing @jjzeng-seattle who is looking into do some work in observability area.

**Comment by abrennan89** [comment]
Closing this issue since there's a dependency here.
@matzew please open a new issue with details of what needs to be documented if this has changed / been fixed.
