### ISSUE TITLE
Autoscale sample shows wrong number of Pods under load

### ISSUE THREAD

**Issue by sebgoa** [knative/docs#2293]
## Expected Behavior

I expect the autoscale sample:
https://github.com/knative/docs/blob/master/docs/serving/samples/autoscale-go/README.md

To actually depict what really happens.

## Actual Behavior

With the introduction of `container-concurrency-targe-percentage` default to 70%, the autoscaling sample actually ends up with 7 or 8 pods instead of 5 like mentioned in the doc.

## Steps to Reproduce the Problem

1. Run the sample step by step

## Fix

Set `container-concurrency-targe-percentage` to 100% of change the number of pods shown as output.

**Comment by mpetason** [comment]
The service is created with `autoscaling.knative.dev/target: "10"` which will overwrite the new default 70 value. I think the output is correct after testing it a few times. I can prob update the wording to reflect the new default, but I think the output is correct.

**Comment by sebgoa** [comment]
Which version of knative are you testing this on ?

**Comment by mpetason** [comment]
@sebgoa I was using the latest from master, but I can install a specific version and test again this week. I'm not sure if the version matters when the service specifies a target amount (unless older APIs don't accept that option.)

**Comment by sebgoa** [comment]
just did it again and same results, 7 pods

```
$ kubectl get pods
NAME                                             READY   STATUS    RESTARTS   AGE
autoscale-go-00001-deployment-78bc8b87dd-2f7bz   2/2     Running   0          33s
autoscale-go-00001-deployment-78bc8b87dd-5ltfg   2/2     Running   0          31s
autoscale-go-00001-deployment-78bc8b87dd-5m4b2   2/2     Running   0          33s
autoscale-go-00001-deployment-78bc8b87dd-66tdk   2/2     Running   0          27s
autoscale-go-00001-deployment-78bc8b87dd-fkrbc   2/2     Running   0          33s
autoscale-go-00001-deployment-78bc8b87dd-wvhw2   2/2     Running   0          34s
autoscale-go-00001-deployment-78bc8b87dd-zpswp   2/2     Running   0          31s
```
