### ISSUE TITLE
Install docs point to eventing 0.13.0 but we want them to install 0.13.3

### ISSUE THREAD

**Issue by grantr** [knative/docs#2301]
## Expected Behavior
Install docs direct users to install the latest point release of the minor version, e.g. 0.13.x where x is the most recent release in the 0.13 branch.

## Actual Behavior
Eventing has released 0.13.3, but docs still refer to 0.13.0.

## Steps to Reproduce the Problem

1. https://knative.dev/docs/install/any-kubernetes-cluster/#installing-the-eventing-component

## Additional Info
**Additional context**
This url is generated by the `artifact` render method, but I'm not sure where that lives or how to update its output.

/cc @mikehelmick

**Comment by abrennan89** [comment]
We're on version 0.15 now, so this is pretty outdated.
Also, I think it's a reasonable assumption that a user of the docs can update the number in the sample to the latest version if they know that they want to target a specific Knative version beyond the last major release when docs were published.
