### ISSUE TITLE
Update image in Eventing Design Overview, replace Targetable with Addressable

### ISSUE THREAD

**Issue by trisberg** [knative/docs#2319]
## Expected Behavior

The image used in Eventing Design Overview should use the correct terminology

## Actual Behavior

It says that the Service should be `Targetable` when it should be `Addressable`

## Steps to Reproduce the Problem

1. go here https://knative.dev/docs/eventing/ 
1. scroll down to the image

## Additional Info
**Additional context**

**Install information:**
 - Platform (GKE, IKS, AKS, etc.):
 - Knative Version:

**Comment by abrennan89** [comment]
@trisberg if I look for "Targetable" in https://knative.dev/docs/eventing/ I don't see anything - is this issue still valid, and is this the right link?

**Comment by trisberg** [comment]
If you look at the image for "Event brokers and triggers" under [Design Overview](https://knative.dev/docs/eventing/#design-overview) the text in the image uses "Targetable" for the Service instead of "Addressable" which is mentioned a bit earlier.

**Comment by abrennan89** [comment]
This image has since been removed.
