### ISSUE TITLE
Double version number in dropdown menu for v.012.x

### ISSUE THREAD

**Issue by ellenevans** [knative/docs#2328]
## Expected Behavior
![Kn-docs-dropdown](https://user-images.githubusercontent.com/35748459/77113983-ff03f500-69e8-11ea-960c-bb1a1062d835.png)

## Steps to Reproduce the Problem

1.
1.
1.

## Additional Info
**Additional context**

**Install information:**
 - Platform (GKE, IKS, AKS, etc.):
 - Knative Version:

**Comment by abrennan89** [comment]
This isn't reproducible in the current version of docs (0.14).
