### ISSUE TITLE
Refers to knative-serving domain config out of order

### ISSUE THREAD

**Issue by jeffgriffith** [knative/docs#2343]
'Install istio for knative' gives steps for modifying the config-domain for knative-serving, but we have not yet created knative-serving. Istio is a pre-req. Perhaps suggest doing it after knative-serving is installed or move it there?

**Comment by nak3** [comment]
Yes, I think that we can just remove it. The current doc explains it in another section.

https://knative.dev/docs/install/any-kubernetes-cluster/
> 4. Configure DNS
`Magic DNS (xip.io)`

(Or  add `Magic DNS (xip.io) manual` tab, but I think we don't need it.)

/assign
