### ISSUE TITLE
Installing Knative(docs/install/any-kubernetes-cluster.md)

### ISSUE THREAD

**Issue by cc4i** [knative/docs#2348]
## Expected Behavior
➜  knative kubectl apply --filename https://github.com/knative/serving/releases/download/v0.13.0/monitoring-tracing-jaeger-in-mem.yaml
jaeger.jaegertracing.io/jaeger created
service/zipkin unchanged

## Actual Behavior
➜  knative kubectl apply --filename https://github.com/knative/serving/releases/download/v0.13.0/monitoring-tracing-jaeger-in-mem.yaml

service/zipkin unchanged
error: unable to recognize "https://github.com/knative/serving/releases/download/v0.13.0/monitoring-tracing-jaeger-in-mem.yaml": no matches for kind "Jaeger" in version "jaegertracing.io/v1"

## Steps to Reproduce the Problem

Install Jaeger with unrecognized kind. 

## Additional Info
**Additional context**
Install following resources before Jaeger installation and would be success. 

kubectl create -f https://raw.githubusercontent.com/jaegertracing/jaeger-operator/master/deploy/crds/jaegertracing.io_jaegers_crd.yaml
kubectl create -f https://raw.githubusercontent.com/jaegertracing/jaeger-operator/master/deploy/service_account.yaml
kubectl create -f https://raw.githubusercontent.com/jaegertracing/jaeger-operator/master/deploy/role.yaml
kubectl create -f https://raw.githubusercontent.com/jaegertracing/jaeger-operator/master/deploy/role_binding.yaml
kubectl create -f https://raw.githubusercontent.com/jaegertracing/jaeger-operator/master/deploy/operator.yaml

kubectl apply --filename https://github.com/knative/serving/releases/download/v0.13.0/monitoring-tracing-jaeger-in-mem.yaml

**Install information:**
 - Platform (GKE, IKS, AKS, etc.):
EKS
 - Knative Version: 
0.13.0

**Comment by objectiser** [comment]
Rather than including the steps to install the individual yaml files, which may get out of sync if changes occur in the Jaeger project, it may be better to reference the Jaeger docs: https://www.jaegertracing.io/docs/latest/operator/#installing-the-operator-on-kubernetes or install via the operatorhub (press Install on https://operatorhub.io/operator/jaeger)? Possibly offer both options.

**Comment by nak3** [comment]
This can be closed as https://github.com/knative/docs/pull/1249 merged.
@cc4i please feel free to re-open if any objections.

/close
