### ISSUE TITLE
Knative community roles(community/contributing/ROLES.md)

### ISSUE THREAD

**Issue by Cynocracy** [knative/docs#2350]
## Expected Behavior
* Edit/view link redirects to correct MD page 

## Actual Behavior
* Stale link points to community/contributing/ROLES.md, which was moved to a top level dir.

**Comment by abrennan89** [comment]
@evankanderson any update on this one?

**Comment by mpetason** [comment]
Maybe this fixed it? 

https://github.com/knative/docs/commit/23c337c070b5de04ef3abb9d4e2855c4cfc8b4ec#diff-6a3371457528722a734f3c51d9238c13

I don't see other links to the Roles.md or where the original issue is.

**Comment by evankanderson** [comment]
Yeah, I think I forgot to add `Fixed #...` in that PR description.

/close
