### ISSUE TITLE
Document ApiServerSource v1alpha2 and delete all v1alpha1 examples.

### ISSUE THREAD

**Issue by n3wscott** [knative/docs#2352]
## What is changing? (Please include as many details as possible.)

Adding APIServerSource v1alpha2, APIServerSource is reconciled and realized only in the v1alpha2 API, some fields are now ignored. v1alpha1 documentation no longer fully apply.

## How will this impact our users?

The v1alpha1 shape of ApiServerSource will no longer work for the extra fields such as label selectors and the owner bool.

## In what release will this take happen (to the best of your knowledge)?

v0.14

## Context
Link to associated PRs or issues from other repos here.

1. https://github.com/knative/eventing/pull/2872

**Comment by abrennan89** [comment]
@n3wscott is there anything else to do on this one or can it be closed? :slightly_smiling_face:

**Comment by n3wscott** [comment]
looks like one more ref in this page: https://github.com/knative/docs/blob/95926c6c0078b887dfd8e0b3d02a827ad6a9d110/docs/eventing/sources/_index.md

the APIServerSource says v1beta1 in the table but the link is v1alpha
