### ISSUE TITLE
Writing Source the Hard Way (With RA) needs updating

### ISSUE THREAD

**Issue by lberk** [knative/docs#2354]
## What is changing? (Please include as many details as possible.)
As per knative/sample-source#40 
The sample source now uses sinkbindings to track the deployment/ra and uses the v2 version of the RA.  Updates, benefits, and changes should be documented.  Including CeOverrides, and metrics.

cc/ @n3wscott @matzew
## How will this impact our users?
The reconciler should be much more compact and more tidy. Easier to write, but we need to update what exactly is included.

## In what release will this take happen (to the best of your knowledge)?
v0.14

## Context
Link to associated PRs or issues from other repos here.

1. knative/sample-source#40
1.
1.

## Additional info

**Comment by aliok** [comment]
Updates for https://github.com/knative/sample-source/pull/40 is done with https://github.com/knative/docs/pull/2475. 

No ceOverrides nor metrics though.
