### ISSUE TITLE
Skipped setup step on GKE, what to do?

### ISSUE THREAD

**Issue by grayside** [knative/docs#236]
## Expected Behavior

Clarity about whether I can move on through the steps after potentially making a misstep or how to rollback and retry if needed.

## Actual Behavior

Clear statement on the required step, but nothing to help back out of the mistake.

## Steps to Reproduce the Problem

1. Work through the [Knative on GKE](https://github.com/knative/docs/blob/6ea6b9a72ae29c4d30b32eb60131391bb7d59668/install/Knative-with-GKE.md) instructions
2. Skip step 2 under [Creating a Kubernetes cluster](https://github.com/knative/docs/blob/6ea6b9a72ae29c4d30b32eb60131391bb7d59668/install/Knative-with-GKE.md#creating-a-kubernetes-cluster)
3. Complete [Installing Istio](https://github.com/knative/docs/blob/6ea6b9a72ae29c4d30b32eb60131391bb7d59668/install/Knative-with-GKE.md#installing-istio) steps
4. See the various post-install line items failing like so:

Run `kubectl get pods -n istio-system`

```
[...]
istio-mixer-post-install-97l4t             0/1       Error               0          26s
[...]
```

I ended up returning to run the cluster-admin permissions command before continuing, and my hello world app worked, so maybe these errors were non-impacting.

**Comment by samodell** [comment]
I'm not sure it makes sense to document all the bad states users can get themselves into if they perform steps out-of-order. We'll stick to documenting the "happy path."
