### ISSUE TITLE
Broken links under `Higher Level eventing constructs`

### ISSUE THREAD

**Issue by maisem** [knative/docs#2367]
The links for [Sequence](https://knative.dev/docs/eventing/sequence) and [Parallel](https://knative.dev/docs/eventing/parallel) constructs result in "Page Not Found".

## Expected Behavior
Clicking on the link opens the correct page with details about the construct.

## Actual Behavior
Page Not Found

## Steps to Reproduce the Problem

1. Go to https://knative.dev/docs/eventing
1. Scroll down to "Higher Level eventing constructs"
1. Click Sequence/Parallel

**Comment by maisem** [comment]
cc @vaikas

**Comment by mpetason** [comment]
Fixed by https://github.com/knative/docs/pull/2338
