### ISSUE TITLE
Upgrade cloudevents-go to the new SDK

### ISSUE THREAD

**Issue by mattmoor** [knative/docs#2382]
The cloudevents SDK for Go has been getting overhauled, and we should update the Serving sample `cloudevents-go` to match.

/assign @slinkydeveloper @n3wscott 
cc @duglin

**Comment by n3wscott** [comment]
I can do this... I have a few things I want to show people.

**Comment by slinkydeveloper** [comment]
@n3wscott cool, loop me in the review ;)
