### ISSUE TITLE
Version Dropdown stutters 

### ISSUE THREAD

**Issue by duglin** [knative/docs#2397]
When I go to https://knative.dev/v0.12-docs/  by choosing v0.12 from the version drop-down in the title bar, I see this:

<img width="264" alt="image" src="https://user-images.githubusercontent.com/1944671/79348634-3f309780-7f03-11ea-9246-ec10332017e6.png">

Seems like the "v0.12" shouldn't be repeated

**Comment by mpetason** [comment]
There's currently two other issues opened about this:

https://github.com/knative/docs/issues/2328
https://github.com/knative/website/issues/154

**Comment by jonatasbaldin** [comment]
Was this fixed? I remember I was able to reproduce it but not anymore 🤔

**Comment by abrennan89** [comment]
Seems to be fixed now, can't reproduce for v0.14 docs.
