### ISSUE TITLE
Doc bug: simple link not found for "using-auto-tls"

### ISSUE THREAD

**Issue by JCzz** [knative/docs#2399]
In the documentation from: 
https://knative.dev/v0.13-docs/serving/using-cert-manager-on-gcp

"Enabling automatic TLS certificate provisioning"
The link(https://knative.dev/v0.13-docs/using-auto-tls) is not working, error message:
```
Page Not Found
Looks like you've followed a broken link or entered a URL that doesn't exist on this site.
```

This works, and hopefully for Knative v0.13:
https://knative.dev/docs/serving/using-auto-tls/

**Comment by sebgoa** [comment]
it seems to be a build issue because the source seems good to me and the pre-release page are correct:

https://knative.dev/development/serving/using-cert-manager-on-gcp/

the 0.12 pages are also good:

https://knative.dev/v0.12-docs/serving/using-cert-manager-on-gcp/

**Comment by abrennan89** [comment]
This is fixed in the latest version of the docs. Closing.
