### ISSUE TITLE
Document GithubBinding

### ISSUE THREAD

**Issue by mattmoor** [knative/docs#2400]
## What is changing? (Please include as many details as possible.)

Introducing a new binding to make it simple to talk to the Github API 

## How will this impact our users?

There is a new resource to facilitate authenticating with the Github API, and a helper library to make bootstrapping a client trivial.

## In what release will this take happen (to the best of your knowledge)?

Targeting 0.15

## Context
Link to associated PRs or issues from other repos here.

1. https://github.com/knative/eventing-contrib/pull/1113

**Comment by abrennan89** [comment]
@mattmoor any update on this one?
