### ISSUE TITLE
Document KafkaBinding

### ISSUE THREAD

**Issue by mattmoor** [knative/docs#2401]
## What is changing? (Please include as many details as possible.)

Introducing a new binding to make it simple to talk to the Kafka API 

## How will this impact our users?

There is a new resource to facilitate authenticating with the Kafka API, and a helper library to make bootstrapping a client trivial.

## In what release will this take happen (to the best of your knowledge)?

Targeting 0.15

## Context
Link to associated PRs or issues from other repos here.

1. https://github.com/knative/eventing-contrib/pull/11136

**Comment by itsmurugappan** [comment]
PR referenced above has a type. The PR url is https://github.com/knative/eventing-contrib/pull/1116
