### ISSUE TITLE
Sequence and Parallel documentation are missing in v0.13.0

### ISSUE THREAD

**Issue by jonatasbaldin** [knative/docs#2402]
## Expected Behavior
Be able to access the main Sequence and Parallel documentation in the `v0.13.0` as they were present in the `v0.12.0`.

- https://knative.dev/v0.12-docs/eventing/sequence/
- https://knative.dev/v0.12-docs/eventing/parallel/

## Actual Behavior
The links are both broken (nonexistent) in `v0.13.0`.

## Steps to Reproduce the Problem
- Search for the docs in v0.13.0
- Not find any heheh

**Comment by lionelvillard** [comment]
The new links are:
- https://knative.dev/v0.13-docs/eventing/flows/sequence/
- https://knative.dev/v0.13-docs/eventing/flows/parallel/

**Comment by jonatasbaldin** [comment]
Oh, ok, thanks! I think that from going from the pages on v0.12 to v0.13 it breaks because of the new parent page.
