### ISSUE TITLE
Add example of consuming managed services provisioned by Crossplane

### ISSUE THREAD

**Issue by hasheddan** [knative/docs#2430]
**Describe the change you'd like to see**
We recently gave a [demo on TBS](https://youtu.be/UnMm_T79drA?t=2495) of provisioning a [GCP Cloud SQL](https://cloud.google.com/sql) instance using [Crossplane](https://crossplane.io/), then consuming the connection information in a Knative `Service`. This is a valuable workflow that enhances the Knative experience and allows for a sample to be written that provisions both the serverless function and the backing infrastructure from manifests in this repo.

**Additional context**
I would be happy to do the work to add this sample and provide documentation, as well as maintain it over time. We also demonstrated the use of the `SQLBinding` to provide connection information to the function. It looks like these bindings are slowly making their way into the [`eventing-contrib`](https://github.com/knative/eventing-contrib) repo, so it may be useful to show the use of one of these bindings in this example so that it serves both purposes of documenting how to consume managed infrastructure and how to use bindings.

/cc @mattmoor for thoughts / approval on an example like this being added to docs
/assign

**Comment by jonatasbaldin** [comment]
Hey @hasheddan, thanks for reaching out! It always awesome to have more contributions to the samples :)

There are currently two ways to contribute to the samples, as described [here](https://knative.dev/community/contributing/docs/docs-contributing/) under the `Determining where to add user focused code samples` section:

- 1 **Knative owned and maintained**: where the sample will need to be actively maintained by a Knative team member, be integrated into the e2e tests and receive regular traffic.
- 2 **Community owned and maintained samples**: where the sample lives in the [community](https://github.com/knative/docs/blob/master/community/samples/README.md) part of the project, where the requirements above are not mandatory.

I believe is up to you to decide which route to take. Number `1` will require more future work and commitment, while number `2` is faster to get up and running.

**Comment by abrennan89** [comment]
@hasheddan any status update on this issue? Can it be closed? :slightly_smiling_face:

**Comment by hasheddan** [comment]
@abrennan89 apologies for the long delay here! I am still interested in adding an example so would like to keep this open for now if possible. I can likely have this implemented in the next week or so if that seems reasonable for yall :slightly_smiling_face:

**Comment by abrennan89** [comment]
Thanks so much for the quick response, @hasheddan ! That's no problem, just wanted to check :slightly_smiling_face:

**Comment by abrennan89** [comment]
@hasheddan any update on this, or should I move it to the backlog perhaps?

**Comment by abrennan89** [comment]
@hasheddan haven't heard any update on this in about ~6 months, so not sure if it's still in progress.
This seems to be GCP specific, so it should maybe be a blog post or something as opposed to part of core docs.
Are there any plans to take on this work soon? Otherwise I'd like to close this issue.
