### ISSUE TITLE
Create OWNERS file under each samples folder

### ISSUE THREAD

**Issue by jonatasbaldin** [knative/docs#2433]
**Describe the change you'd like to see**
Since the samples under `eventing/samples` and `serving/samples` are more official (maintained by a Knative member, integrated with e2e tests etc) it would be nice to have a OWNERS file under each folder so we know who to ping if an issue is raised.

What do y'all think?

**Comment by abrennan89** [comment]
I think this is a good idea, but keeping those OWNERS files up to date seems like it might be outside the scope of the docs WG.
Might be one to raise at the TOC @markusthoemmes @pmorie ?
