### ISSUE TITLE
Autoexpand example section when multiple tabs are given

### ISSUE THREAD

**Issue by rhuss** [knative/docs#2436]
## Expected Behavior

Examples which have different flavors presented by tabs should already show the default presentation, like in

![image](https://user-images.githubusercontent.com/99080/81091789-fcf5e700-8eff-11ea-9c8a-9d693e011d40.png)

## Actual Behavior

In the current version of the new [autoscaling docs](https://knative.dev/development/serving/configuring-autoscaling/) the examples are not expanded by default, which leads to a view like:

![image](https://user-images.githubusercontent.com/99080/81091514-ab4d5c80-8eff-11ea-9c64-00ca25bedbf1.png)

For the reader is not clear whether this is already the example or what she should do. It's not obvious that you have to press a link to show the example. Also, if you press a link to reveal one of the example, you get never back to this empty view, so why not already start with the first example shown ? (the borders then make it also clear that this is tabbed view. these borders are missing in the initial view).

## Steps to Reproduce the Problem

1. Got to https://knative.dev/development/serving/configuring-autoscaling/ and check the examples

**Comment by jonatasbaldin** [comment]
Got it!
