### ISSUE TITLE
Re-add install and getting-started walkthrough for build

### ISSUE THREAD

**Issue by ImJasonH** [knative/docs#246]
## Expected Behavior

Able to find a simple command to install Knative Build onto my cluster

## Actual Behavior

No simple setup instructions

## Additional Info

https://github.com/knative/build/pull/283 updated the build repo's README, and removed the install instructions and "Getting started" walkthrough.

That information should be added to the docs repo instead, with links from the build repo's README.

**Comment by RichieEscarez** [comment]
Realized that this is specific to build only, and our current install docs only refer to serving. We are working out where to fit in these steps as well:

ie.
Run:
kubectl create -f https://storage.googleapis.com/knative-releases/build/latest/release.yaml 

And create the required role:
kubectl create clusterrolebinding myname-cluster-admin-binding \	
   --clusterrole=cluster-admin \	
   --user=myname@example.org
