### ISSUE TITLE
Add a command to set min/max scale for Activators (i.e. edit knative-serving/activator HPA resource.

### ISSUE THREAD

**Issue by abrennan89** [knative/docs#2472]
**Describe the change you'd like to see**
Follow up from #2454 #2455  
Add additional configuration options for Activators.

@vagababov can you provide details please and I'll add them to the docs? Thanks.

**Comment by vagababov** [comment]
```
 k patch hpa -n knative-serving activator --patch='{"spec":{"minReplicas":10, "maxReplicas": 13}}'
```

**Comment by abrennan89** [comment]
Somewhat related to #2477 since LB needs the activator. Maybe add a link between these docs.

**Comment by abrennan89** [comment]
#2477 has been closed now so we can probably revisit this one.
@vagababov thanks for the comment, but I'm not sure this provides enough context since I don't know what it means :/

**Comment by vagababov** [comment]
Basically how to specify how many replicas of activators the user would like (or should) to have.
