### ISSUE TITLE
Document the usage of storage version migrator for Eventing

### ISSUE THREAD

**Issue by vaikas** [knative/docs#2484]
## What is changing? (Please include as many details as possible.)
There will be a new tool similar to Serving for migrating the storage version from v1alpha1 to v1beta1. This issue tracks adding docs for it.

## How will this impact our users?
They can run a tool that upgrades all their resources.

## In what release will this take happen (to the best of your knowledge)?
v0.15
## Context
Link to associated PRs or issues from other repos here.

1. https://github.com/knative/eventing/issues/3095
1.
1.

**Comment by abrennan89** [comment]
@vaikas can you provide details about how to use this tool please?

I think upgrade docs in general need to be updated, so maybe we can combine this work
https://knative.dev/docs/install/upgrade-installation/

**Comment by vaikas** [comment]
Sure thing:
https://github.com/knative/docs/pull/2485/files

**Comment by abrennan89** [comment]
It looks like this one #2484 can be closed by #2485  - is that correct @vaikas or is there more to do here?
