### ISSUE TITLE
event-display requires CE 0.2

### ISSUE THREAD

**Issue by ryandawsonuk** [knative/docs#2487]
I deployed the event-display kservice from https://github.com/knative/docs/blob/master/docs/eventing/samples/kafka/source/README.md#create-the-event-display-service i.e. gcr.io/knative-releases/github.com/knative/eventing-contrib/cmd/event_display

I then deployed a curler pod and did the following curl:
```
curl -v "http://event-display" \
-X POST \
-H "Ce-Id: say-hello" \
-H "Ce-Specversion: 1.0" \
-H "Ce-Type: aloha" \
-H "Ce-Source: mycurl" \
-H "Content-Type: application/json" \
-d '{"key":"from a curl"}'
```
Which the event-display received but couldn't decode. I then sent it with Ce-Specversion as 0.2 and it worked. Shouldn't this be able to handle 1.0?

**Comment by sebgoa** [comment]
Could you try with `gcr.io/knative-releases/knative.dev/eventing-contrib/cmd/event_display` instead ?

**Comment by evankanderson** [comment]
Requested in #productivity on Slack to delete all the `gcr.io/knative-releases/github.com/*` releases, assuming that they are months old at this point.

**Comment by chizhg** [comment]
I think the root cause of this issue is not the images are outdated but is the doc is incorrect. 

If the doc is up-to-date, then users won't be directed to these images and they won't have issues like this. Also deleting the images itself does not help with solving this issue as they will get a new "image not found" error.

**Comment by evankanderson** [comment]
We need to fix both -- find the cases where these links exist, but also take down the images that are months old and probably incompatible with most of our environments.
