### ISSUE TITLE
Default channels(docs/eventing/channels/default-channels.md) - update apiVersion

### ISSUE THREAD

**Issue by kameshsampath** [knative/docs#2489]
The Knative Channel samples needs to be updated for apiVersion `messaging.knative.dev/v1beta1`

## Expected Behavior
https://github.com/knative/eventing-contrib/issues/1239

## Actual Behavior
https://github.com/knative/eventing-contrib/issues/1239

## Steps to Reproduce the Problem

https://github.com/knative/eventing-contrib/issues/1239

**Install information:**
 - Knative Version: v0.14.x

**Comment by kameshsampath** [comment]
wondering if this needs a fix as later releases have already fixed it and this bug affects only 0.14.x

**Comment by kameshsampath** [comment]
@slinkydeveloper ^^

**Comment by slinkydeveloper** [comment]
Are you willing to do a pr for it?

**Comment by slinkydeveloper** [comment]
You can pr this doc fix for the specific 0.14 release: https://github.com/knative/docs/tree/release-0.14

**Comment by kameshsampath** [comment]
Yes will do that way then.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
