### ISSUE TITLE
Installing Knative components using Operator(development/install/knative-with-operators.md)

### ISSUE THREAD

**Issue by tang-john** [knative/docs#2500]
## Expected Behavior
The following file does not exist

https://storage.googleapis.com/knative-sandbox-nightly/operator/latest/operator.yaml

## Steps to Reproduce the Problem

1. Go to https://knative.dev/development/install/knative-with-operators/
1.Look for the line:  kubectl apply -f https://storage.googleapis.com/knative-sandbox-nightly/operator/latest/operator.yaml
1. The operator.yaml file on this page does not exist.

## Additional Info
**Additional context**

**Install information:**
 - Platform (GKE, IKS, AKS, etc.):
 - Knative Version:

**Comment by abrennan89** [comment]
@jcrossley3 @houshengbo can you provide the correct information to resolve this?
Thanks!

**Comment by jcrossley3** [comment]
We promoted the operator out of the sandbox, so the correct url for nightlies is now: https://storage.googleapis.com/knative-nightly/operator/latest/operator.yaml

**Comment by abrennan89** [comment]
Whoops, looks like it's already updated in the latest version :slightly_smiling_face: 
https://knative.dev/development/install/knative-with-operators/#install-knative-with-the-knative-operator
