### ISSUE TITLE
Remove references to ChannelBasedBroker

### ISSUE THREAD

**Issue by vaikas** [knative/docs#2516]
## What is changing? (Please include as many details as possible.)
ChannelBasedBroker is going away. Update documentation by removing it and changing all the examples to use MTChannelBasedBroker

## In what release will this take happen (to the best of your knowledge)?
v0.16

## Context
Link to associated PRs or issues from other repos here.

1. https://github.com/knative/eventing/issues/3139
1.
1.

**Comment by matzew** [comment]
/assign @matzew 

see PR: https://github.com/knative/docs/pull/2533
