### ISSUE TITLE
serving sample `source-to-url-go` does not use dockerhub creds

### ISSUE THREAD

**Issue by paulczar** [knative/docs#252]
## Expected Behavior

Should use dockerhub credentials when pulling and pushing docker image

## Actual Behavior

cannot find credentials, therefore uses anonymous and fails.

## Steps to Reproduce the Problem

1. follow the instructions in the doc.

## Additional Info

/assign @paulczar

**Comment by ImJasonH** [comment]
#253 looks correct to me. @mchmarny @rgregg does this look correct to you too?
