### ISSUE TITLE
What is the reason to not use an existing version (latest) of cloudevents SDK

### ISSUE THREAD

**Issue by k33g** [knative/docs#2524]
Hello, I don't understand why you use this:

https://github.com/knative/docs/blob/bf5fef670e5bc96457a39e3c86c824ed236843bf/docs/serving/samples/cloudevents/cloudevents-nodejs/package.json#L16

**Comment by sebgoa** [comment]
let's ask @csantanapr since he wrote it

**Comment by csantanapr** [comment]
Hi at the time when the sample was written, I used the latest version. I’m waiting for version 2.0 of the sdk to be release.

**Comment by csantanapr** [comment]
It looks like there is a tag v2.0.1 out today that we can update the sample to use this version

https://github.com/cloudevents/sdk-javascript/tags

**Comment by evankanderson** [comment]
/assign @csantanapr 

Though @k33g should feel free to send a PR if they'd prefer.

**Comment by k33g** [comment]
@csantanapr @evankanderson I had some issues to run the sample with the latest version last week - I will give it a try again this week

**Comment by csantanapr** [comment]
@k33g check out PR #2547 I fixed the problems you saw using nodejs sdk v2.0.1

**Comment by k33g** [comment]
@csantanapr it works like a charm 😃 thank you very much
