### ISSUE TITLE
Update Istio installation to use `istioctl`, not `helm`

### ISSUE THREAD

**Issue by tcnghia** [knative/docs#2525]
**Describe the change you'd like to see**
Now that Istio 1.6 is released and 1.4 is deprecated, we should switch our instruction to use `istioctl`

**Additional context**

**Comment by tcnghia** [comment]
cc @ZhiminXiang

**Comment by nak3** [comment]
This has done by https://github.com/knative/docs/pull/2458, so we can close it?

**Comment by ZhiminXiang** [comment]
Yea. I think we can close it. Thanks @nak3 !
