### ISSUE TITLE
improve webdev and pagespeed scores

### ISSUE THREAD

**Issue by richterdavid** [knative/docs#2526]
Google's public website measurement tools indicate that knative.dev and the pages on that site could use some improvements.
 
https://web.dev/measure/
https://developers.google.com/speed/pagespeed/insights/?url=knative.dev&tab=mobile
https://developers.google.com/speed/pagespeed/insights/?url=knative.dev&tab=desktop
https://www.thinkwithgoogle.com/feature/testmysite/
testmysite report: https://storage.googleapis.com/gweb-mobile-hub-test-my-site.appspot.com/public/reports/efd38062ead9419386ce04fdcfc45461.pdf

I mainly looked at the homepage, but testmysite averages across the whole domain. I'm guessing we use some shared css etc across the whole site, and that fixing the homepage will improve most/all other pages as well, but others should be checked too.

Possibly of interest: https://developers.google.com/speed/

**Comment by richterdavid** [comment]
Sounds like the current best tool from Google is https://web.dev/vitals/

https://webmasters.googleblog.com/2020/05/evaluating-page-experience.html

**Comment by abrennan89** [comment]
@richterdavid please raise this issue in the website repo, since it's not related to actual docs content. Thanks.

**Comment by richterdavid** [comment]
Done: https://github.com/knative/website/issues/188
