### ISSUE TITLE
Upgrading your installation(docs/install/upgrade-installation.md)

### ISSUE THREAD

**Issue by abrennan89** [knative/docs#2564]
## Expected Behavior
Docs should be current for the version selected in the dropdown.

## Actual Behavior
v0.15 upgrade docs still refer to old versions:
"For example, if you have v0.6.0 installed, you should upgrade to v0.7.0 before attempting to upgrade to v0.8.0. To verify the version number you currently have installed, see Checking your installation version."

## Steps to Reproduce the Problem

1. Visit https://knative.dev/docs/install/upgrade-installation/ and look at the docs :sweat_smile:

**Comment by rajitha1998** [comment]
Hi, can you elaborate a little bit more about this issue @abrennan89. Would like to take it.

**Comment by mpetason** [comment]
Are we looking for a manual update or trying to find a way to automate versions based on the selection in the drop down?

**Comment by rajitha1998** [comment]
> Are we looking for a manual update or trying to find a way to automate versions based on the selection in the drop down?

I am not sure about that @mpetason.

**Comment by abrennan89** [comment]
@rajitha1998 @mpetason it was actually just some mentions of older versions throughout the doc that needed to be cleaned up. I think this is out of date now though so I'm going to close it.

@rajitha1998 sorry if you came here from Hacktoberfest - unfortunately we don't have as many issues labelled for it as I'd have liked this year, since a lot of the open issues aren't really "good first issue" friendly and I've been lacking time to go through them. Feel free to reach out to me directly on the Knative Slack if you're looking for good ways to start contributing in docs though. I'm not sure if you're new to the project?
