### ISSUE TITLE
Need documentation for using tag header based routing

### ISSUE THREAD

**Issue by ZhiminXiang** [knative/docs#2568]
For the feature of tag header based routing: https://docs.google.com/document/d/12t_3NE4EqvW_l0hfVlQcAGKkwkAM56tTn2wN_JtHbSQ/edit?disco=AAAAGUeHCm4&ts=5e7d8607&usp_dm=false

After we implement it, we need to have a documentation about how to use this feature.

/cc @igsong @tcnghia

**Comment by nak3** [comment]
We can close this as https://github.com/knative/docs/pull/2617 was merged.
Thank you @ZhiminXiang !

/close
