### ISSUE TITLE
Documentation on how to use Istio Authorization with Knative

### ISSUE THREAD

**Issue by tcnghia** [knative/docs#2569]
**Describe the change you'd like to see**
Users are asking for samples of how Istio Authz can be used with Knative.

These are non-trivial and would require understanding of how `activator` may be need to be whitelisted in conjunction with Revision headers. The `cluster-local-gateway` is also sitting on the request path and needs to be taken into consideration.

As a result some samples will be super helpful for our users.
 
**Additional context**

**Comment by nak3** [comment]
/assign

> Since many of Istio Authz features only work when sidecar turned on (like from clause with namespaces), I think we may want be start there first and expand the doc later

Sounds great. I added the part-1 https://github.com/knative/docs/pull/2583

**Comment by Shashankft9** [comment]
hi, whats the difference between istio providing policy control and security in knative? aren't both policy control and security the same thing? 
ref: slide 27 here https://static.sched.com/hosted_files/kccnceu19/5f/Knative-on-Istio.pdf

**Comment by Shashankft9** [comment]
Hey, can you please add documentation on using istio policies with components like `activator` and `cluster-local-gateway` included? I have been having a tough time configuring the `cluster-local-gateway` with the policies to accept requests from some knative sources (I am working with kafkasource).
