### ISSUE TITLE
Can't join Slack without @google.com email address

### ISSUE THREAD

**Issue by AkihiroSuda** [knative/docs#257]
## Expected Behavior

Can join https://knative.slack.com without @google.com email address

## Actual Behavior

@google.com email address is required

## Steps to Reproduce the Problem

1.  Open https://knative.slack.com
2.  Try to create an account

## Additional Info

Sorry if this repo is not the right place to report this.

**Comment by mchmarny** [comment]
Slack channel is still by invitation only (for non-google domains), we are working on opening to allow users to enable on-boarding but have to solve some billing issues first. No specific ETA, but shouldn't be long.

**Comment by mchmarny** [comment]
Knative Slack is open to all we just finalizing our self enrollment. For now you can use the super long URL here (https://join.slack.com/t/knative/shared_invite/enQtNDA1ODA1MTc2NjE1LWYxYjhhNDVjOWY1ZTMzMzMwZjE4YTA5YWUxODBmYWQzZTNlMjc0YzlhNmZhYmNhMTk4MzExOTU5MjU5MDcxNzA …). Later this morning https://slack.knative.dev  will be working as well. Apologies for the inconvenience

**Comment by AkihiroSuda** [comment]
Thanks!

**Comment by ScorpioCPH** [comment]
@mchmarny Thanks! How about add this invitation URL in this doc [SLACK-GUIDELINES](https://github.com/knative/docs/blob/master/community/SLACK-GUIDELINES.md).
