### ISSUE TITLE
Document Istio installation options sidecar vs no sidecar 

### ISSUE THREAD

**Issue by tcnghia** [knative/docs#2571]
**Describe the change you'd like to see**
We need to clearly document our Istio installation in case of sidecar vs no sidecar setups. In the no sidecar setup, where the `cluster-local-gateway` is needed, we should convert to using the IstioOperator / Istio profile to be more aligned with other existing Istio users who will also be using IstioOperator as well.

cc @nak3 @ZhiminXiang 

**Additional context**

**Comment by abrennan89** [comment]
@nak3 any updates for this one? Are you still planning to work on it?

**Comment by nak3** [comment]
`cluster-local-gateway` was removed and https://github.com/knative/docs/pull/3152 will clarify it.
So closing this issue.
