### ISSUE TITLE
PingSource Sample Not Rendering Tabs Correctly for v0.15.0 Docs

### ISSUE THREAD

**Issue by danielhelfand** [knative/docs#2586]
## Expected Behavior

Tables and associated tabs render correctly for the website as with v0.14.0 docs: https://knative.dev/v0.14-docs/eventing/samples/ping-source/

## Actual Behavior

Tables and associated tabs not rendering: https://knative.dev/docs/eventing/samples/ping-source/

## Additional Info

Only change from v0.14.0 I noticed was #2377. Not sure if anything in the pr caused the change, or if additional docs would also be affected.

**Comment by abrennan89** [comment]
@evankanderson can you please take a look at this - I'm not sure if the other PR that you merged caused something in the tabs to break? :slightly_smiling_face:

**Comment by lionelvillard** [comment]
same issue with this page: https://knative.dev/development/eventing/sources/

**Comment by abrennan89** [comment]
#2680 by @lionelvillard fixes this issue.
Needs to be cherrypicked into 0.15, 0.16

**Comment by lionelvillard** [comment]
for the record, shortcodes don't get processed by [readFile](https://gohugo.io/functions/readfile/).

**Comment by lionelvillard** [comment]
Apparently there is a workaround by using GetPage: https://discourse.gohugo.io/t/readfile-does-not-parse-shortcodes/16667/7
