### ISSUE TITLE
Markdown link is broken

### ISSUE THREAD

**Issue by dprotaso** [knative/docs#2607]
From: https://github.com/knative/docs/pull/2606

https://prow.knative.dev/view/gcs/knative-prow/pr-logs/pull/knative_docs/2606/pull-knative-docs-markdown-link-check/1275090436058255360

**Comment by vaikas** [comment]
https://github.com/knative/docs/pull/2696

**Comment by abrennan89** [comment]
Thanks @vaikas ! :tada:
