### ISSUE TITLE
"Native" is mispelled

### ISSUE THREAD

**Issue by dellis23** [knative/docs#263]
## Expected Behavior

"Native" should be spelled "native".

## Actual Behavior

"Native" is spelled "knative."

## Steps to Reproduce the Problem

1. Look at the word "knative"

## Additional Info

https://www.merriam-webster.com/dictionary/native

**Comment by mchmarny** [comment]
I'm getting popcorn, ready to watch the show following this thread ;)

**Comment by dewitt** [comment]
I'm DeWitt and approve this PR.

Thanks for the smile this morning, @dellis23!
