### ISSUE TITLE
Unable to read entire cookie policy without accepting cookie policy first

### ISSUE THREAD

**Issue by brian-burton** [knative/docs#2636]
## Expected Behavior
A user of the site should be able to read the full cookie policy before accepting the pop-up.

## Actual Behavior
When reading any page on the site before accepting the cookie policy, the ability to scroll down the page is disabled. Accepting the cookie policy enables scrolling. The cookie policy itself is longer than a single page (tested at full screen, 100% sizing, 2560x1440 display) so the user must accept the cookie policy before being able to read it in its entirety.

In fact the policy is mostly displayed on the single page, but the user doesn't know that until they accept (or work around the pop up).

## Steps to Reproduce the Problem

1. Browse the site for the first time (any page, before accepting the cookie policy).
2. Click "Learn More" on the policy pop-up.
3. Click "Learn about analytics cookies and how you can take steps to opt-out from sharing your usage data."
4. Attempt to scroll down the entire policy page.

## Additional Info
Zooming out allows the user to read the policy, but also allows the user to read any page without accepting the policy, so disabling scroll a) breaks the user experience and b) doesn't enforce acceptance of the policy for the determined reader.

**Install information:**
Reproduced by me on:
1. Chrome 83
2. Internet Explorer 11 (Don't ask)
3. Edge 44
4. Firefox 78
5. Edge 83

**Comment by abrennan89** [comment]
This may need to be filed in the website repo instead, but I will bring it to the WG for discussion.

**Comment by abrennan89** [comment]
The "learn more" link in the cookies policy seems to work fine now. It directs you to https://knative.dev/about-analytics-cookies/ and it's easy to read the whole page in firefox at least. Closing.
@brian-burton please let me know if you're still having issues.

**Comment by brian-burton** [comment]
Hi, it's still not fixed, even in Firefox. I'm on my PC now and the behaviour hasn't changed in Firefox for Windows. I originally read your most recent message in the Github app on my Android phone and the problem is actually more significant on Firefox for Android: you cannot scroll down or zoom out to read the cookie policy, forcing the visitor to accept the policy in order to read something they may then subsequently wish to decline. Tested on all the following browsers this evening: Firefox for Windows 81.0.2 64-bit; Firefox for Android 81.1.4; Microsoft Edge 86.0.622.38 64-bit; Google Chrome for Android 85.0.4183.127.

**Comment by RichieEscarez** [comment]
Depending on timezone, there are two notices (https://github.com/knative/website/pull/89) and its the EU version that I believe is causing the usability issues. 

I think the fix might be to add an [ X ] close icon in the dialog to close it (not accept). Then when the next page is loaded, the notice appears again.

**Comment by abrennan89** [comment]
@omerbensaadon probably another consideration for any new website stuff

**Comment by abrennan89** [comment]
Issue moved to [knative/ux #40](https://github.com/knative/ux/issues/40) via [**ZenHub**](https://www.zenhub.com/)
