### ISSUE TITLE
[Eventing] Please document how to set the TTL attribute

### ISSUE THREAD

**Issue by FWiesner** [knative/docs#2646]
Please see https://knative.slack.com/archives/C9JP909F0/p1594037799295200

It would be great if the TTL feature would be documented (https://github.com/knative/eventing/blob/282bb726fcb36dcd40b5dbb54aa07db99c042807/pkg/mtbroker/ttl.go#L32)

**Comment by n3wscott** [comment]
@Harwayne

**Comment by n3wscott** [comment]
FWIW you can not set the attribute on an event, the broker will drop it if you attempt to set it. You can set the max TTL in the eventing controller. And here is where I would give you a link to know how to do that, but it was never implemented. 

See here https://github.com/knative/eventing/blob/master/cmd/mtbroker/ingress/main.go#L66, 255 is the default and it is not set-able at the moment.

**Comment by abrennan89** [comment]
Please raise a new issue if this ever becomes an implemented feature. Closing since there is no fix for this that can be done by docs.
