### ISSUE TITLE
Revamp eventing/getting-started.md's install instructions to point to ./install/any-kubernetes-cluster.md

### ISSUE THREAD

**Issue by n3wscott** [knative/docs#2648]
I'd remove this whole installation bit here and just point to any-kubernetes-cluster.md. They have drifted in the past.

_Originally posted by @vaikas in https://github.com/knative/docs/diffs_

**Comment by n3wscott** [comment]
https://github.com/knative/docs/pull/2647/files#r450497196

**Comment by vaikas** [comment]
It's actually been removed from there already. We should close this issue.
/close
