### ISSUE TITLE
drop enabledComponents documentation

### ISSUE THREAD

**Issue by mattmoor** [knative/docs#2661]
## What is changing? (Please include as many details as possible.)

We are going to enable leader election by default, and have a flag per-component to disable it.  This will require changed to at least the "config-ha" docs, but we should grep for other places that may need this as well.

## How will this impact our users?

They'll have a better default wrt HA posture, but otherwise it should just get simpler to enable HA.

## In what release will this take happen (to the best of your knowledge)?

0.17

## Context

https://knative.slack.com/archives/C93E33SN8/p1594307991141200

**Comment by mattmoor** [comment]
cc @abrennan89

**Comment by mattmoor** [comment]
https://knative.dev/development/serving/config-ha/

**Comment by abrennan89** [comment]
Follow up with docs review of https://github.com/knative/docs/pull/2691

**Comment by abrennan89** [comment]
No additional comments for #2691 right now. Closing.
