### ISSUE TITLE
explain the GKE scopes needed for install

### ISSUE THREAD

**Issue by sebgoa** [knative/docs#268]
not a bug but a doc request.

In: https://github.com/knative/docs/blob/master/install/Knative-with-GKE.md#creating-a-kubernetes-cluster there are several scopes needed

We should document why those scopes are needed and what would break without them.

**Comment by samodell** [comment]
@mattmoor  Who on the team knows why the various scopes for the K8s cluster are required? I'll need to talk with someone to document this.

**Comment by mattmoor** [comment]
I'm actually surprised there are so many scopes here, since `cloud-platform` implies most of these.

When I last touched these it was basically just that.  This line seems like a hint at why more were added:

> API scopes for cloud-platform, logging-write, monitoring-write, and pubsub (if those features will be used)

**Comment by mattmoor** [comment]
@mchmarny Do you know why the set of scopes grew?

**Comment by mchmarny** [comment]
Don't know all of them but storage/monitoring and app-level native service connectors like pubsub/datastore I think were not 100% covered under the `cloud-platform`. Evan or Greg, do you know when/why these have been added? 

/unassign @mchmarny 
/assign @evankanderson 
/assign @rgregg

**Comment by samodell** [comment]
@rgregg  Can you assign this to someone who would know why we need all the GKE-specific scopes?

**Comment by evankanderson** [comment]
We are now only requesting `cloud-platform`, which seems fairly self-explanatory.

/close
