### ISSUE TITLE
Feature/Extension Flags(docs/serving/feature-flags.md)

### ISSUE THREAD

**Issue by mattmoor** [knative/docs#2684]
# Expected Behavior

The podspec dry-run flag matches: https://github.com/knative/serving/blob/66a88a4ff431fbd717e89ecc80793c6643c1f1b4/config/core/configmaps/features.yaml#L53

## Actual Behavior

It has a `/`, which isn't correct (or allowed).

cc @whaught

**Comment by whaught** [comment]
kubernetes.podspec-dryrun is the feature flag that is present in the yaml, but there is also an annotation that may be attached to individual services to enable it on a one-off basis.

When the configmap is set to `"kubernetes.podspec-dryrun": "allowed"`, the server will not dry-run incoming Services. However the user may opt-in an individual service by attaching the following to its metadata: ` Annotations: {"features.knative.dev/podspec-dryrun": "enabled"}`. Annotations do expect the `/` prefix https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/#syntax-and-character-set

I suspect either you were confused by the similarity between the feature flag and the annotation or I've misunderstood. We can try to make that more clear (that said we'll eliminate both once this moves to GA)

**Comment by mattmoor** [comment]
The docs page has `kubernetes/podspec-dryrun` in the context of the configmap:
![image](https://user-images.githubusercontent.com/2442466/87822013-a2450980-c825-11ea-92a6-b5fcc1010049.png)

**Comment by mattmoor** [comment]
@whaught fixed this ☝️ 

/close
