### ISSUE TITLE
Creating a private cluster-local service(docs/serving/cluster-local-route.md)

### ISSUE THREAD

**Issue by ajtomato** [knative/docs#2702]
## Expected Behavior

To label a Kubernetes service:

kubectl label __svc__ ${SERVICE_NAME} serving.knative.dev/visibility=cluster-local

## Actual Behavior

To label a Kubernetes service:

kubectl label __route__ ${SERVICE_NAME} serving.knative.dev/visibility=cluster-local

## Steps to Reproduce the Problem

None

## Additional Info

None

**Comment by abrennan89** [comment]
@ajtomato can you please provide a link to where you're seeing this in the docs?
Thanks!

**Comment by ajtomato** [comment]
https://knative.dev/docs/serving/cluster-local-route/

**Comment by nak3** [comment]
Thank you @ajtomato 
Fixing it https://github.com/knative/docs/pull/2710.

/kind networking
