### ISSUE TITLE
Fix review comments from #2299

### ISSUE THREAD

**Issue by abrennan89** [knative/docs#2704]
**Describe the change you'd like to see**
Fix review comments from #2299

**Additional context**
Usually these should be fixed by the person opening a PR but in this case I am making an exception to get the content included at least.

**Comment by vmexalien** [comment]
actively working on this issue; still familiarizing before next steps

**Comment by abrennan89** [comment]
Hey @vmexalien :slightly_smiling_face: just wondering if you've made any progress on this issue and if it should be targeted for early Oct? Thanks.

**Comment by vmexalien** [comment]
@abrennan89 yes! Making progress and early Oct is exactly what I have in mind.

**Comment by vmexalien** [comment]
@abrennan89 looks like I don't have write access to this repo. I was trying to make a branch. Forgive me, I am a total newbie

**Comment by abrennan89** [comment]
Hi @vmexalien - please check out the https://knative.dev/community/contributing/ guidelines before you contribute.
Thanks.

**Comment by abrennan89** [comment]
@vmexalien are you still working on this one?

**Comment by vmexalien** [comment]
@abrennan89 yes but to be totally honest, I don't know what needs to be done next.
this is the related PR https://github.com/knative/docs/pull/2930

**Comment by abrennan89** [comment]
@vmexalien sorry I'm just looking at this now, it lgtm just waiting for Grant to fix the CLA issue so we can merge. Thank you!
