### ISSUE TITLE
Switch to use go mod

### ISSUE THREAD

**Issue by ZhiminXiang** [knative/docs#2715]
In the other Knative repos (e.g. serving, pkg), we already switched to use "go mod" for golang dependency management.

We should also switch to use "go mod" for this repo.

**Comment by evankanderson** [comment]
Actually, we should use `go mod` for each sample, rather than vendoring all the `go` libraries at the top level. This would also allow different samples to use different versions of Go libraries if needed.

**Comment by mpetason** [comment]
Looks like there is an open PR addressing this - https://github.com/knative/docs/pull/2718
