### ISSUE TITLE
Kubernetes event using the API Server Source(docs/eventing/samples/kubernetes-event-source/index.md)

### ISSUE THREAD

**Issue by mjschmidt** [knative/docs#2724]
Hey docs folks!
Eventing API Server Source use to work in release 0.13, but is broken in release 0.16, please consider retesting and cleaning up the example.
https://knative.dev/docs/eventing/samples/kubernetes-event-source/

**Comment by pierDipi** [comment]
/kind eventing
/kind sample

cc @lionelvillard @nachocano @n3wscott @vaikas
