### ISSUE TITLE
PingSource example(docs/eventing/samples/ping-source/index.md)

### ISSUE THREAD

**Issue by mattmoor** [knative/docs#2733]
## Expected Behavior

No hugo markdown in rendered docs

## Actual Behavior

I see unrendered tabs

## Steps to Reproduce the Problem

1. Look at https://knative.dev/docs/eventing/samples/ping-source/

cc @lionelvillard @abrennan89

**Comment by abrennan89** [comment]
@evankanderson assigning this one to you since I think it's maybe related to some other bugs in how our docs render that you were working on? Otherwise if it's just due to a typo or something feel free to reassign :slightly_smiling_face:

**Comment by lionelvillard** [comment]
This might be a workaround: https://discourse.gohugo.io/t/readfile-does-not-parse-shortcodes/16667/7

**Comment by lionelvillard** [comment]
this is fixed

/close
