### ISSUE TITLE
Add docs for .NET Core unencrypted HTTP2 (h2c)

### ISSUE THREAD

**Issue by EatonZ** [knative/docs#2750]
[If the underlying Cloud Run application supports h2c, HTTP2 can be used all the way through.](https://github.com/ahmetb/cloud-run-faq#can-my-application-server-run-on-http2-protocol)

I was looking into this for .NET Core and while I found some [promising info to enable h2c on .NET Core's Kestrel](https://docs.microsoft.com/en-us/aspnet/core/grpc/troubleshoot?view=aspnetcore-3.1#unable-to-start-aspnet-core-grpc-app-on-macos), I wasn't able to get it working (Cloud Run logs were saying "The request failed because either the HTTP response was malformed or connection to the instance had an error.").

I didn't follow the above linked example code exactly. I tried this:
`webBuilder.ConfigureKestrel(options => options.ConfigureEndpointDefaults(o => o.Protocols = HttpProtocols.Http2));`
...but that doesn't appear to be correct.

I would like to request that a small note be added to the .NET Core tutorial/sample with instructions on how to set up h2c. I might be missing something simple, in that case great, but it would also be great to have this info published for other customers to benefit.

**Comment by EatonZ** [comment]
I think I found the issue - it doesn't look like the application is actually receiving HTTP2 data. There is a `--use-http2` flag in [gcloud run deploy](https://cloud.google.com/sdk/gcloud/reference/run/deploy), but it's restricted to Anthos.😡

I believe my code is the correct way to go about doing this, but it won't work until this Cloud Run (Fully Managed) limitation is removed.

**Comment by ahmetb** [comment]
I'd say documenting how to listen on h2c isn't the right place for Knative, however it would be indeed good for Knative to explain and document how h2c can be configured (in knative case, it's done by naming the port as `h2c` in `containers[0].ports` section).

**Comment by EatonZ** [comment]
@ahmetb There are samples [here](https://github.com/knative/docs/tree/master/docs/serving/samples/hello-world/helloworld-csharp) to which info could be added.

**Comment by ahmetb** [comment]
But those samples aren't h2c (GRPC/Websockets). :) They're lean and simple for a reason like they're the per-language hello world samples. Adding h2c there is not the right idea.
