### ISSUE TITLE
Document Github Vanity URLs

### ISSUE THREAD

**Issue by lionelvillard** [knative/docs#2751]
## What is changing? (Please include as many details as possible.)
The MT GitHubSource controller generates cleaner URLs

## In what release will this take happen (to the best of your knowledge)?
v0.19

## Context
Link to associated PRs or issues from other repos here.

1. https://github.com/knative/eventing-contrib/pull/1473
1.
1.

**Comment by lionelvillard** [comment]
@abrennan89 Can we move this to the v0.20.0 milestone?

**Comment by abrennan89** [comment]
@lionelvillard can you provide content for this please? I don't know what needs to be documented to close it.

**Comment by lionelvillard** [comment]
I will close and reopen when this feature lands.
