### ISSUE TITLE
The link to slack is broken

### ISSUE THREAD

**Issue by taragu** [knative/docs#2762]
## Expected Behavior
Clicking on the link "Knative Slack channels" on [this page](https://knative.dev/community/) should lead to the current slack login page. 

## Actual Behavior
Clicking on the link "Knative Slack channels" on [this page](https://knative.dev/community/) lead to this:
![2020-08-19_15-32-52](https://user-images.githubusercontent.com/6353048/90681392-54ab2a80-e231-11ea-9447-c323937561fc.png)

## Steps to Reproduce the Problem
1. Goto page https://knative.dev/community/
1. Open the link "Knative Slack channels"

## Additional Info
**Additional context**

**Install information:**
 - Platform (GKE, IKS, AKS, etc.):
 - Knative Version:

/good-first-issue

**Comment by vmexalien** [comment]
I will work on this issue

**Comment by RichieEscarez** [comment]
Duplicate: https://github.com/knative/website/issues/204
