### ISSUE TITLE
Api version sources.eventing.knative.dev/v1alpha1 still used in some examples

### ISSUE THREAD

**Issue by apupier** [knative/docs#2765]
## Expected Behavior

the examples are using `sources.eventing.knative.dev/v1alpha1` although the api version has been modified to `sources.knative.dev/v1alpha1`

for instance, see https://github.com/knative/docs/blob/master/docs/eventing/samples/apache-camel-source/source_http_poller.yaml

## Steps to Reproduce the Problem

1.
1.
1.

## Additional Info
**Additional context**

**Install information:**
 - Platform (GKE, IKS, AKS, etc.):
 - Knative Version:

**Comment by lionelvillard** [comment]
@nicolaferraro @matzew @lberk

**Comment by vaikas** [comment]
Fixed by #2766 
Thanks!
