### ISSUE TITLE
operator 0.17 install link dead

### ISSUE THREAD

**Issue by Morriz** [knative/docs#2773]
## Expected Behavior

the link to the operator yaml to work on page https://knative.dev/docs/install/knative-with-operators/

## Actual Behavior

404

**Comment by abrennan89** [comment]
@Morriz links seem to be OK to me in 0.17 docs.
Does this refer to an older version, or can you maybe show in a screen grab the link you mean?
Thanks

**Comment by nak3** [comment]
Operator is usually released after Serving/Eventing was released. So I am sure that it was 404 error when @Morriz reported this issue. But now operator released 0.17 https://github.com/knative/operator/releases (5 days ago) so the link became OK.

I think that we can close this issue for now, but need to care about this time lag between serving/eventing release and operator release.
