### ISSUE TITLE
Repeated Contents in knative docs.

### ISSUE THREAD

**Issue by Abhishek-kumar09** [knative/docs#2774]
# 1.
![image](https://user-images.githubusercontent.com/48255244/90963426-1c2b7b00-e4d5-11ea-833c-c88530efdf07.png)

## Steps to Reproduce the Problem

1. Go to https://knative.dev/contributing/#before-you-begin

# 2. 

![image](https://user-images.githubusercontent.com/48255244/90963456-572dae80-e4d5-11ea-80ae-47290084ffa3.png)

## Steps to Reproduce the Problem
1. Go to https://knative.dev/contributing/#style-guide

**Comment by nak3** [comment]
@Abhishek-kumar09 for the slack issue, could you please open another issue? I think it would be helpful if you could attach the screen shot or something with the error.

**Comment by nak3** [comment]
/close

This was fixed by https://github.com/knative/docs/pull/2783.
