### ISSUE TITLE
Not able to join Slack Channel

### ISSUE THREAD

**Issue by Abhishek-kumar09** [knative/docs#2777]
I hovered over here to know more about the community: https://knative.dev/community/
![image](https://user-images.githubusercontent.com/48255244/91023293-fe186480-e613-11ea-8156-6a315f2a7d5c.png)
## the slack link is not working
![image](https://user-images.githubusercontent.com/48255244/91023340-0ec8da80-e614-11ea-8de5-3c50ba1fe284.png)
It shows users with email ending with `@google.com, @pivotal.io, or @redhat.com` could join. Mine ends with `@gmail.com`

**Comment by vaikas** [comment]
Does this link work for you?
https://knative.slack.com/

**Comment by duglin** [comment]
that link works, in that it's not a 404, but from there when you click on the "create an account" link you go back to https://knative.slack.com/signup#/  which only seems to like 3 companies.
<img width="723" alt="image" src="https://user-images.githubusercontent.com/1944671/91240477-21283e80-e710-11ea-9432-49b476b6f8eb.png">

**Comment by abrennan89** [comment]
@evankanderson @RichieEscarez I think this is a duplicate for a website issue you had open / discussion in Slack about this

**Comment by RichieEscarez** [comment]
Duplicate: https://github.com/knative/website/issues/204
