### ISSUE TITLE
Links to edit a page are broken is previous releases

### ISSUE THREAD

**Issue by JRBANCEL** [knative/docs#2790]
## Expected Behavior
When I go to 0.16 docs, e.g. https://knative.dev/v0.16-docs/, then click `View/Edit this page`, I expect to go to the related markdown file in GitHub. 

## Actual Behavior
It goes to https://github.com/knative/docs/tree/release-0.16/v0.16-docs/README.md which is a 404.

**Comment by abrennan89** [comment]
I was able to see this too, also an issue for 0.14, 0.15 docs.

**Comment by RichieEscarez** [comment]
Thanks for reporting the issue. I'm investigating.

**Comment by RichieEscarez** [comment]
Fix is here: https://github.com/knative/website/pull/211
