### ISSUE TITLE
Confirm if Observability plugin was actually deprecated, and if it was update the docs

### ISSUE THREAD

**Issue by abrennan89** [knative/docs#2804]
## Expected Behavior
https://knative.dev/docs/install/any-kubernetes-cluster/ contains only up to date information about components that can be installed.

## Actual Behavior
It mentions an Observability plugin that was deprecated in 0.14. The oldest currently published version of the docs is now 0.14, so this could be removed from all the documentation if it actually was deprecated at 0.14.

## Steps to Reproduce the Problem

1. See https://knative.dev/docs/install/any-kubernetes-cluster/
1. See https://knative.dev/docs/install/any-kubernetes-cluster/#installing-the-observability-plugin

**Comment by abrennan89** [comment]
Updated older branches
#2905 (0.15)
#2907 (0.16)
#2908 (0.17)
#2909 (0.18)

**Comment by evankanderson** [comment]
Other refs to the monitoring bundle:

https://knative.dev/docs/serving/fluentd-requirements/
https://knative.dev/docs/serving/accessing-metrics/
https://knative.dev/docs/serving/accessing-traces/
https://knative.dev/docs/serving/samples/telemetry-go/index.html
https://knative.dev/docs/eventing/accessing-traces/

**Comment by evankanderson** [comment]
I have some work on the fluentd item, but nothing for traces (which may just need "if you have Jaeger/Zipkin" rather than "here's a Jaeger/Zipkin").

**Comment by dprotaso** [comment]
It's now been dropped in serving - so it'll be part of the 0.19 release

https://github.com/knative/serving/pull/9807
