### ISSUE TITLE
Knative Eventing tutorials use not supported CRD for trigger (and probably more)

### ISSUE THREAD

**Issue by tclasen** [knative/docs#2816]
## Expected Behavior
cat <<EOF | kubectl apply -f -
apiVersion: eventing.knative.dev/v1alpha1
kind: Trigger
metadata:
  name: helloworld-python
  namespace: knative-samples
spec:
  broker: default
  filter:
    attributes:
      type: dev.knative.samples.helloworld
      source: dev.knative.samples/helloworldsource
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: helloworld-python
EOF

error: unable to recognize "STDIN": no matches for kind "Trigger" in version "eventing.knative.dev/v1alpha1"

## Actual Behavior
cat <<EOF | kubectl apply -f -
apiVersion: eventing.knative.dev/v1alpha1
kind: Trigger
metadata:
  name: helloworld-python
  namespace: knative-samples
spec:
  broker: default
  filter:
    attributes:
      type: dev.knative.samples.helloworld
      source: dev.knative.samples/helloworldsource
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: helloworld-python
EOF

trigger.eventing.knative.dev/helloworld-python created

## Steps to Reproduce the Problem

1. Follow tutorial at https://knative.dev/docs/eventing/samples/helloworld/helloworld-python/
2. kubectl explodes during trigger creation
3. Change trigger apiVersion from v1alpha1 to v1beta1 and re-apply to cluster
4. Profit?

## Additional Info
The tutorial documentation located at the below link (and probably many others) reference triggers with the old v1alpha1 apiVersion. By updating the apiVersion to v1beta1 you can successfully run the tutorials.

https://knative.dev/docs/eventing/samples/helloworld/helloworld-python/

**Install information:**
 - Platform (GKE, IKS, AKS, etc.): DigitalOcean
 - Knative Version: 0.17.0

**Comment by pierDipi** [comment]
Fixed in: https://github.com/knative/docs/pull/2818
/close
