### ISSUE TITLE
curl: (6) Could not resolve host: helloworld-python.default.example.com

### ISSUE THREAD

**Issue by wenzhaojie** [knative/docs#2821]
## Expected Behavior
I have followed the knative install guide [https://knative.dev/docs/install/any-kubernetes-cluster/](url), and then tested the helloworld python code example in here [https://knative.dev/docs/serving/samples/hello-world/helloworld-python/](url)

It seems good, until final run step:
curl http://helloworld-python.default.1.2.3.4.xip.io
Hello Python Sample v1!

## Actual Behavior
curl: (6) Could not resolve host: helloworld-python.default.example.com

## Steps to Reproduce the Problem

1.Setting up a kubernetes cluster
2.Follow the guide link above.

## Additional Info
**Additional context**

**Install information:**
 - Platform (GKE, IKS, AKS, etc.): Kubernetes cluster created by kubeadm. 
 - Knative Version: v0.17.0

**Comment by mpetason** [comment]
There's a requirement for `A Kubernetes cluster with Knative installed and DNS configured.` I think what is happening here is that the domain is still setup as example.com but DNS has not been setup to resolve the domain. You may want to setup a custom domain and then setup a DNS record (if you have local DNS setup), or edit your hosts file and point the record to your "public ip" (in this case probably just a local IP address that you use to hit the cluster.)

**Comment by mpetason** [comment]
Custom Domain link - https://knative.dev/docs/serving/using-a-custom-domain/

**Comment by mpetason** [comment]
@wenzhaojie Were you able to take a look at the suggestions + successfully walk through the python code example?

**Comment by abrennan89** [comment]
@wenzhaojie could you provide an update please on whether this is working for you now? Thanks.
