### ISSUE TITLE
Page needs improvement

### ISSUE THREAD

**Issue by csharpknife2002** [knative/docs#2851]
## Expected Behavior
I can finish the example as described.
https://knative.dev/docs/eventing/samples/sequence/sequence-with-broker-trigger/index.html

## Actual Behavior
It will be an endless loop between the broker and the sequence. Because the ksvc yaml doesn't set the TYPE env so it doesn't change the cloud event type. and the trigger to broker will be always triggered and the trigger to the display will be never triggered.

## Steps to Reproduce the Problem

1.
2.
3.

## Additional Info
After set the TYPE env for step3 to "samples.http.mod3", the problem solved.

**Comment by abrennan89** [comment]
@lionelvillard @matzew could you please provide some guidance here re what needs to be updated in docs, if you're able to reproduce the problem? Thanks.
