### ISSUE TITLE
Provide a Source documentation template

### ISSUE THREAD

**Issue by evankanderson** [knative/docs#2852]
**Describe the change you'd like to see**

The current[ sample for writing new sources in Knative](https://github.com/knative-sandbox/sample-source) doesn't have any suggestions on documentation. It would be nice to have a documentation template that includes at least the following information:

* How to install
* Fields on the custom object
* Sample emitted event

**Additional context**

Sample-sources will be cloned by users (as a template) to write new event sources; it should be clear from the template that the content should be replaced with the documentation for the specialized event source. I might suggest putting the template in `docs/README.md` to avoid a collision with the repo-level README.

**Comment by evankanderson** [comment]
@nachocano

**Comment by abrennan89** [comment]
Slack thread on latest updates: https://knative.slack.com/archives/C9CV04DNJ/p1611676612008300
Issue still WIP

**Comment by abrennan89** [comment]
@evankanderson @n3wscott can we call this one done since one of the PRs Evan raised was merged? I think there's enough work done on this now to provide a jumping off point for whatever eng folks want to do with docs.
