### ISSUE TITLE
Remove Migration (development/eventing/migration/_index.md)

### ISSUE THREAD

**Issue by abrennan89** [knative/docs#2855]
## Expected Behavior
The docs should only reference versions of Knative that still have supported documentation versions, i.e. as far back as 0.14 at the moment.

## Actual Behavior
We still have migration docs here relating to 0.13.
These may be suitable to remain in 0.14 docs, but I have a feeling they shouldn't appear in later docs versions than that. These docs even in 0.14 should probably also exist in the upgrading section rather than a separate migration section under eventing.

## Steps to Reproduce the Problem

1. See https://knative.dev/development/eventing/migration/

## Additional Info
**Additional context**
Need to check with someone in eng that this information is actually deprecated before removing and doesn't apply for later versions than 0.13.

**Comment by pierDipi** [comment]
It makes sense to me. Also, ContainerSource is still supported.
/assign
