### ISSUE TITLE
Stale version information in any-kubernetes-cluster.md

### ISSUE THREAD

**Issue by rhuss** [knative/docs#2858]
## Expected Behavior
 Versions referenced in the documentation should reflect the current state

## Actual Behavior

![image](https://user-images.githubusercontent.com/99080/94269674-42fb2800-ff3f-11ea-856c-06fa648218a0.png)

## Solution

Either keep the version numbers current or, my recommendation, remove them completely here as they are not. really important in this context and it would have to be updated for every version.

While we are at it, I wonder whether the section on the Observability Plugin should be removed as it is deprecated and maybe not even working with the current version of Knative

**Comment by markusthoemmes** [comment]
I think they are supposed to reflect the current state + how long they've been that way for reference :thinking:. I.e. in this case Serving is stable since 0.9.

**Comment by rhuss** [comment]
Really ? So the gist of this information is that you can use Knative Serving still ? Shouldn't it be the version of the least supported version ? (0.15 I think)

I find this information more confusing than helpful.

**Comment by rhuss** [comment]
Consider that the `Installation` page is one of the pages a user hits first when trying out Knative for the first time. Having this very specific detail information is IMO not helpful in this context but raises unnecessary questions what this actually means.

**Comment by abrennan89** [comment]
@rhuss completely agreed re this being more confusing than it's worth. I would like to get the WG consensus on what to do about versions; could you come to the WG sometime and stick this on the agenda?

Re observability, I'd keep this to a separate issue please if that's OK so it's easier to assign.

**Comment by abrennan89** [comment]
OH, I forgot I actually opened an issue on the observability plugin a while ago https://github.com/knative/docs/issues/2804
I guess we can say this is confirmed then and remove it?

**Comment by abrennan89** [comment]
Related issue from Julz https://github.com/knative/docs/issues/2781

**Comment by rhuss** [comment]
> I guess we can say this is confirmed then and remove it?

@knative/technical-oversight-committee is the definitive authority for answering this question.

**Comment by mattmoor** [comment]
We need to triage remaining references (some may still be valuable samples that should be adapted to use upstream observability bits), and then we should remove what we need to to turn it down.  I think @evankanderson has at least one AI related to this.
