### ISSUE TITLE
Event sources(docs/eventing/sources/_index.md)

### ISSUE THREAD

**Issue by vaikas** [knative/docs#2883]
## Expected Behavior
Clicking on the PingSource under the 'Eventing Sources' here will take me to a page about PingSource.
https://knative.dev/docs/eventing/sources/

## Actual Behavior
Clicking on the PingSource takes me here:
https://knative.dev/docs/eventing/sources/pingsource.md

## Steps to Reproduce the Problem

1. Navigate to: https://knative.dev/docs/eventing/sources/
1. Click on PingSource under 'Eventing Sources'
1. Observe the non-existent page.

## Additional Info
**Additional context**

**Install information:**
 - Platform (GKE, IKS, AKS, etc.): N/A
 - Knative Version: v0.18

**Comment by RichieEscarez** [comment]
Fixed in https://github.com/knative/docs/pull/2840
