### ISSUE TITLE
Istio installation instructions do not work with recommended Istio version (1.4.10)

### ISSUE THREAD

**Issue by jroper** [knative/docs#2894]
Following the instructions documented here:

https://knative.dev/docs/install/installing-istio/

It says the version of Istio that Knative tests and certifies stability with is 1.4.10. So I installed that version of istioctl:

```
curl -L https://istio.io/downloadIstio | ISTIO_VERSION=1.4.10 TARGET_ARCH=x86_64 sh -
```

But then when I go to install it using the manifest described:

```
istio-1.4.10/bin/istioctl manifest apply -f istio-minimal-operator.yaml
Failed to generate and apply manifests, error: failed to generate manifest: could not unmarshal the overlay file: unknown field "addonComponents" in v1alpha2.IstioControlPlaneSpec
```

Running with Istio 1.6.11 instead, it works.

The instructions should at least list the minimum version of Istio that is needed in order to follow them if that version contradicts the version recommended above.

**Comment by nak3** [comment]
@jroper Thank you.

/cc @ZhiminXiang @JRBANCEL @tcnghia we can bump up to 1.7.1? (As per https://github.com/knative/serving/commit/b199526507d5719a4864b4341ddc45a20c94d691)

**Comment by ZhiminXiang** [comment]
SGTM. One caveat is that there are several PRs within net-istio repo that were checked in after we cut release-0.18 before we promoted Istio 1.7 (https://github.com/knative-sandbox/net-istio/commits/master). But I don't think they are specific to Istio 1.7.
