### ISSUE TITLE
[samples/helloworld-go] remove redundant "flag" import|parse

### ISSUE THREAD

**Issue by DazWilkin** [knative/docs#290]
## Expected Behavior

Since `"flag"` is not used, remove the import and the `Parse`.

## Actual Behavior

`"flag"` is imported in #20 and `Parse`'d.
https://github.com/knative/docs/blob/master/serving/samples/helloworld-go/helloworld.go

**Comment by vdemeester** [comment]
This one is closeable (PR is merged)
/close
