### ISSUE TITLE
[samples/helloworld-go] Synchronize content between tutorial pages

### ISSUE THREAD

**Issue by DazWilkin** [knative/docs#291]
## Expected Behavior

Recommend referring to the getting-started page's content from the sample page's README.

The getting-started page provides better guidance in grabbing the correct IP and host name and its approach makes what's happening more obvious.

## Actual Behavior

These pages are somewhat duplicative particularly in deployment/interacting sections:

https://github.com/knative/docs/blob/master/install/getting-started-knative-app.md 
https://github.com/knative/docs/tree/master/serving/samples/helloworld-go

**Comment by labadav** [comment]
We are missing a separate page to provide guidance in getting the IP and host name.
