### ISSUE TITLE
Accessing request traces links to missing resource.

### ISSUE THREAD

**Issue by bdurette** [knative/docs#2923]
## Expected Behavior

It appears that the configuration for tracing has been refactored to separate config for Zipkin and Jaeger (https://github.com/knative/serving/tree/master/config/monitoring). Ideally, this documentation would be updated to not direct people to missing documentation. 

## Actual Behavior

The hyperlinked text 'config-tracing.yaml'  links to a non-existent resource (https://github.com/knative/serving/blob/master/config/config-tracing.yaml). 

## Steps to Reproduce the Problem

1. Click the link config-tracing.yaml. 
1. Observe the 404. 

## Additional Info
N/A

**Comment by abrennan89** [comment]
@mpetason assigning this one to you since you fixed the link for the upcoming version, thanks!
Can you also update this in the 0.16-0.18 versions please?
