### ISSUE TITLE
helloworld-scala doesn't use a Dockerfile

### ISSUE THREAD

**Issue by mattmoor** [knative/docs#2927]
## Expected Behavior

Uniformity with other samples, so Dockerfile.

## Actual Behavior

The image is assembled with an sbt plugin.

## Steps to Reproduce the Problem

https://github.com/knative/docs/blob/master/docs/serving/samples/hello-world/helloworld-scala/README.md

**Comment by mattmoor** [comment]
cc @markusthoemmes (self-proclaimed Scala addict 😉 )

**Comment by skonto** [comment]
it is the scala-way to use the sbt plugin to automate the generation of the file ;)

**Comment by mattmoor** [comment]
Yeah, this issue was mostly about consistency.  I'd love nothing more than for folks to stop using Dockerfile and instead pick up "last-mile" builders like `ko` and `jib`.  @chanseok did Jib ever ship sbt support?

I'm receptive to supporting alternatives (like this, or `ko`) as options (I have `ko` tabs in the tabular version), but I think we want a baseline Dockerfile for every one of these samples. 🙏
