### ISSUE TITLE
Add a sample app that exercises all aspects of Knative

### ISSUE THREAD

**Issue by skonto** [knative/docs#2934]
**Describe the change you'd like to see**
Istio has this nice [sample app](https://istio.io/latest/docs/examples/bookinfo/) that demonstrates how to use it.
It would be nice to have a non-trivial example to demonstrate similar concepts in Knative. Not sure if there is any but for example for Eventing I didn't find anything beyond hello-wrold like samples..
I would suggest an app that is aligned with common Knative use cases eg. an IoT app that processes sensor readings using a microservices based approach. It could use a different language per microservice.

/cc @matzew @slinkydeveloper @abrennan89 WDYTH?

**Comment by abrennan89** [comment]
@omerbensaadon this one may interest you?

**Comment by omerbensaadon** [comment]
@abrennan89 totally, this feels like a deliverable that ought to come out of the UX WG and is currently coming to light in User Interviews. 

CC: @csantanapr

**Comment by omerbensaadon** [comment]
Once we wrap up this cycle of interviews (I think next week?) we may want to take a crack at creating an epic and splitting this issue into a few smaller issues to be worked.

**Comment by slinkydeveloper** [comment]
That's nice!

**Comment by skonto** [comment]
@omerbensaadon let me know if I can help there.

**Comment by pierDipi** [comment]
@omerbensaadon any updates?

**Comment by skonto** [comment]
@pierDipi @omerbensaadon We can create a proposal for the app to get started. I already have one.

**Comment by pierDipi** [comment]
Cool, go ahead then.

**Comment by csantanapr** [comment]
This is great a sample app(s) to explain Knative concepts is something I have being wanted to have Knative for a while. 

Is great to have some helping hands on this now. 

Would you like to write a proposal and present to the UX WG?

Someone from VMware that @omerbensaadon brought in is also working on an app. We should combine ideas and efforts.

**Comment by omerbensaadon** [comment]
sorry folks, let this one slip. 

@skonto would love to see a proposal! 

After you write the proposal, we can see where the work we have been doing with the Tanzu Developer's Center could fit together? 

Moving this issue to the UX Repo...

**Comment by omerbensaadon** [comment]
Issue moved to [knative/ux #33](https://github.com/knative/ux/issues/33) via [**ZenHub**](https://www.zenhub.com/)

**Comment by skonto** [comment]
Cool! I am working on it next week will have something for review, I recently developed a [small one](https://github.com/skonto/serverless-zero-demo-app) (not polished) and spent some time thinking about it anyway.

**Comment by omerbensaadon** [comment]
Responded to this in https://github.com/knative/ux/issues/33
