### ISSUE TITLE
Writing an Event Source(docs/eventing/samples/writing-event-source/_index.md)

### ISSUE THREAD

**Issue by aldirrix** [knative/docs#2936]
## Expected Behavior
When you click to the event source links, they should take you to the appropiate documentation

## Actual Behavior
GithubSource and AWSSQSSource take you to a page that doesn't exist

## Steps to Reproduce the Problem

1. go to https://knative.dev/docs/eventing/samples/writing-event-source/
2. click on GithubSource and AWSSQSSource
3. get a 404

## Additional Info
**Additional context**
Actual links here: 
https://github.com/knative-sandbox/eventing-awssqs/
https://github.com/knative-sandbox/eventing-github

As I don't know if `event-contrib` is going to be still a valid source for documentation or the place o add an eventing source I didn't want to change the whole context in this page so I'll leave that to someone with more knowledge :)

**Comment by pierDipi** [comment]
cc @lionelvillard @lberk 

/good-first-issue
/kind eventing

**Comment by pierDipi** [comment]
I think we should change the `eventing-contrib` link to point to the [event sources page](https://knative.dev/docs/eventing/sources/#knative-sources) and remove the list ("such as ...").

Would you mind creating a PR?

**Comment by aldirrix** [comment]
no problem, I will submit one soon :)
