### ISSUE TITLE
Channel Link in Knative Eventing(docs/eventing/_index.md)

### ISSUE THREAD

**Issue by yelloman** [knative/docs#2942]
## Expected Behavior
In my option it is better to bring the reader do documentation than source code if documentation is availibly. 

The Link Channels should be show to (channels/README.md)

## Actual Behavior

In section Event channels and subscriptions the link to Channel bring me to https://github.com/knative/eventing/blob/master/pkg/apis/messaging/v1/channel_types.go#L57. But I think there is a good documentation for Channels unter (channels/README.md).

## Steps to Reproduce the Problem

1. Open the URL: https://knative.dev/docs/eventing/#event-channels-and-subscriptions
1. Use the Link to Channels in the first sentence.

**Comment by abrennan89** [comment]
@omerbensaadon when I look at the latest development version of the docs: https://knative.dev/development/eventing/#event-channels-and-subscriptions
It doesn't appear as if #3132 actually fixed this issue, since it still links to the code? Do you still want to work on this one?

**Comment by abrennan89** [comment]
@omerbensaadon oh I see the issue, the fix was made against the 0.19 branch. Changes like this should be made against master if they need to be carried through to newer versions of the docs rather than just the one specific version. Can you cherry pick that PR to the master branch please?
/assign @omerbensaadon

**Comment by omerbensaadon** [comment]
Sorry @abrennan89 I am just getting used to following up on Github notifications, they were going to an email I never checked for awhile there... 

Pardon the ball drop and thanks for picking this back up :)
