### ISSUE TITLE
Split link in "Before you begin" in Event registry(docs/eventing/event-registry.md)

### ISSUE THREAD

**Issue by yelloman** [knative/docs#2943]
## Expected Behavior
After splitting the doc of brokers and triggers there should be 2 links, in my opinion. One should bring me to brokers and the other one to triggers.

## Actual Behavior
In Section "Before you begin" there is only one link named "Broker and Trigger objects" which bring me to (broker/README.md). 

## Steps to Reproduce the Problem

1. Open https://knative.dev/docs/eventing/accessing-traces/#before-you-begin
1. Read at the first item of enumeration.

**Comment by abrennan89** [comment]
Correct link: https://knative.dev/development/eventing/event-registry/
