### ISSUE TITLE
Install docs are very Serving focused.

### ISSUE THREAD

**Issue by mattmoor** [knative/docs#295]
*This came up in TGIK8s talking about Knative.*

1. We should show how to install just [Build](https://github.com/knative/build/releases)
1. We should clarify that Istio is a Serving/Eventing dependency, but not a Build dependency
1. We should clarify that Serving bundles Build (for now).
1. We should install `release-no-mon.yaml` by default, and talk about installing monitoring separately.
1. We should add a section on installing eventing.

**Comment by RichieEscarez** [comment]
1 and 3 were recently completed

**Comment by samodell** [comment]
This work is in progress: #542 and to some extent #565
