### ISSUE TITLE
bad link in https://knative.dev/docs/eventing/

### ISSUE THREAD

**Issue by zhaojizhuang** [knative/docs#2967]
**Describe the change you'd like to see**
bad link in https://knative.dev/docs/eventing/ 

404 when click   [View/Edit this page](https://github.com/knative/docs/tree/release-0.18/docs/eventing/README.md)

![image](https://user-images.githubusercontent.com/3124692/96952648-f0069780-1521-11eb-81d0-4e2409e64a0b.png)

**Additional context**

**Comment by mpetason** [comment]
I can't replicate this. It looks like it links to "https://github.com/knative/docs/blob/release-0.18/docs/eventing/README.md", which resolves. Are you still having this issue?

**Comment by zhaojizhuang** [comment]
I can't replicate this too now, i will close this issue

> I can't replicate this. It looks like it links to "https://github.com/knative/docs/blob/release-0.18/docs/eventing/README.md", which resolves. Are you still having this issue?
