### ISSUE TITLE
host url is zero in helloworld-go

### ISSUE THREAD

**Issue by ab-sin-the** [knative/docs#297]
## Expected Behavior
host url should not be none after 

`export HOST_URL=$(kubectl get services.serving.knative.dev helloworld-go  -o jsonpath='{.status.domain}')
`

## Actual Behavior

host url is zero

## Additional Info

follow the steps in https://github.com/knative/docs/blob/master/install/getting-started-knative-app.md

**Comment by ab-sin-the** [comment]
I use azure and the installation is very successful.

**Comment by krancour** [comment]
@ab-sin-the, when you say you used Azure, did you use AKS? I work on the AKS team and we're currently trying to pin down some issues with Knative on Azure. See https://github.com/knative/serving/issues/1730. I'd love if you wanted to hop over to that thread _or_ https://github.com/Azure/AKS/issues/561 and share any observations.

**Comment by anggakes** [comment]
I got same issues, 

I run this command : 
kubectl get services.serving.knative.dev helloworld-go  -o=custom-columns=NAME:.metadata.name,DOMAIN:.status.domain

result :
NAME            DOMAIN
helloworld-go   <none>

I use Google Kubernetes Engine

**Comment by dictvm** [comment]
```
kubectl get ksvc helloworld-go  --output=custom-columns=NAME:.metadata.name,DOMAIN:.status.domain
NAME            DOMAIN
helloworld-go   <none>
```

The same happens to me with the latest GKE Kubernetes version:
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.7", GitCommit:"0c38c362511b20a098d7cd855f1314dad92c2780", GitTreeState:"clean", BuildDate:"2018-08-20T10:09:03Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.7-gke.6", GitCommit:"144b681e3870074abfdaaf176e48b1b13360d7e5", GitTreeState:"clean", BuildDate:"2019-02-09T00:08:19Z", GoVersion:"go1.10.7b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by miosman** [comment]
I was experiencing the same issue but it turns out the route issue is with kubectl version. I had kubectl version 1.8.0 installed and the command 
```
kubectl get ksvc helloworld-go  --output=custom-columns=NAME:.metadata.name,DOMAIN:.status.domain
```
would fail due to the fact that kubectl was returning the kubernets service rather than the knative service.

Upgrading to kubectl version 1.13 fixes the issue. On both versions getting the domain name from the route resource always worked.
```
kubectl get route helloworld-go  --output=custom-columns=NAME:.metadata.name,DOMAIN:.status.domain
```
