### ISSUE TITLE
Broken logging/monitoring pages.

### ISSUE THREAD

**Issue by senthilnathan** [knative/docs#2984]
## Expected Behavior
The following pages should either be complete or should be removed.
 - https://knative.dev/docs/serving/accessing-logs/
 - https://knative.dev/docs/serving/setting-up-a-logging-plugin/
 - https://knative.dev/v0.18-docs/serving/installing-logging-metrics-traces/

## Actual Behavior
They are in a broken state and rendered partially.  This is probably due to the removal of the monitoring bundle.

## Steps to Reproduce the Problem

Click on the above links.

## Additional Info
**Additional context**
Relevant thread in the slack channel: https://knative.slack.com/archives/C9CV04DNJ/p1603945221176600

**Install information:**
 - Platform (GKE, IKS, AKS, etc.): NA
 - Knative Version: 0.18.0

**Comment by abrennan89** [comment]
These pages have all been removed now, since the observability plugin was deprecated a few versions ago.
