### ISSUE TITLE
Search box sometimes shows the result from wrong site

### ISSUE THREAD

**Issue by nak3** [knative/docs#2995]
## Expected Behavior

- The search results should be from https://knative.dev/docs/.

## Actual Behavior

- The search result shows some results from wrong site.

## Steps to Reproduce the Problem

1. Put some word - e.g. "header" in search box in the left pane in https://knative.dev/docs/.
1. The result shows this:

![search-result](https://user-images.githubusercontent.com/2138339/98210740-5ceb4a00-1f84-11eb-805e-be1d3cbd8a02.png)

The second result is an issue in https://github.com/google/exposure-notifications-server which is not knative's.

**Comment by abrennan89** [comment]
@nak3 please open this in the website repo instead
