### ISSUE TITLE
Creating builds task has unexpected kubectl log .. response

### ISSUE THREAD

**Issue by RichieEscarez** [knative/docs#300]
## Expected Behavior
Running the final `kubectl logs....` command returns the response "hello build".

## Actual Behavior

Running `kubectl logs $(kubectl get build hello-build -ojsonpath={.status.cluster.podName}) -c build-step hello` returns:

"Unable to retrieve container logs for docker://0ebe1.........4f2cf9eedf0285b5crescarez-macbookpro:kubectl logs"

If I manually enter the podName and run:
`kubectl logs hello-build-[ID] -c build-step-hello`

In the terminal, I get:
"Nothing to push"

Which also aligns with what shows in the Stackdriver logs:

insertId: "n1m8ung1jtqky0"
labels: {…}
logName: "projects/richie-elafros1/logs/nop"
receiveTimestamp: "2018-07-24T21:39:51.767245948Z"
resource: {…}
severity: "INFO"
textPayload: "Nothing to push"
timestamp: "2018-07-24T21:39:03Z"

## Steps to Reproduce the Problem

1. Create new cluster
2. Install Knative
3. Run steps in https://github.com/knative/docs/blob/master/build/creating-builds.md

/assign @ImJasonH

**Comment by ImJasonH** [comment]
This is what happens when the build is successful and Kubernetes deletes the pod before we can get to its logs. I think the solution is going to be to update the documentation to point users to a more persistent copy of the pod's logs, either in Kibana or (if it's GKE) Stackdriver Logs.

**Comment by tequilarista** [comment]
Makes sense.  Alternately (totally throwing this tangential thought out there) does it make sense to have something like a debug option that leaves the pod running if it's completed the specified action?

**Comment by RichieEscarez** [comment]
Being deprecated: https://github.com/knative/build/blob/master/README.md
