### ISSUE TITLE
Update the Hyperlinks for using kn with Tekton and using kn container Image with Tekton

### ISSUE THREAD

**Issue by DARK-art108** [knative/docs#3006]
## Expected Behavior
Links should redirect to kn docs in tekton repo.

## Actual Behavior
The hyperlinks provided in the Docs for Installing the Knative using Tekton are not working.

## Steps to Reproduce the Problem

1. Go to the [Knative Installation Docs](https://knative.dev/docs/install/install-kn/)
2. Move to the **Kn Container Images** and click on **tekton** the link is not working.
3. Click on the run **kn with tekton** it is also not working.

**Comment by abrennan89** [comment]
This has been updated in the latest version of the docs
https://knative.dev/development/client/install-kn/
