### ISSUE TITLE
Update serving samples docker build instructions with buildx for arm64 for 0.19

### ISSUE THREAD

**Issue by csantanapr** [knative/docs#3011]
## What is changing? (Please include as many details as possible.)

When the release `0.19` of Kantive lands, it will be able to support arm64

## How will this impact our users?

Users would be able to build run containers that are build for multiarchitecture.

## In what release will this take happen (to the best of your knowledge)?
v0.19

## Additional info

The serving samples README's mention building with `docker build` to build a container with multiple architectures they would need to use `docekr buildx` .

The command would look something like this
```
docker buildx build \
     -t ${DOCKER_HUB_USER}/helloworld-nodejs:latest \
     --platform linux/amd64,linux/arm64 \
     --push .
```

cc @mattmoor

**Comment by mattmoor** [comment]
This only works if they have the qemu stuff configured, and technically they may not need buildx if they use an arm64 dev box 🤓 .  We could add a tab?
