### ISSUE TITLE
PingSource example(docs/eventing/samples/ping-source/index.md)

### ISSUE THREAD

**Issue by mattmoor** [knative/docs#3012]
## Expected Behavior

Rendered tabs

## Actual Behavior

Hugo shortcodes.

## Steps to Reproduce the Problem

Load: https://knative.dev/docs/eventing/samples/ping-source/

/assign @lionelvillard

**Comment by lionelvillard** [comment]
This has been fixed: https://knative.dev/development/eventing/samples/ping-source/

**Comment by mattmoor** [comment]
should we backport?
