### ISSUE TITLE
Improve docs on Installing Knative (development/install/any-kubernetes-cluster.md)

### ISSUE THREAD

**Issue by abrennan89** [knative/docs#3018]
# Expected Behavior

It should be clear at a glance to a user what is required for a basic working Knative Serving and/or Eventing installation.

## Actual Behavior

1. The TOC on the https://knative.dev/development/install/any-kubernetes-cluster/ page only shows the major headings for installing the two components. I think some of the numbered steps on this page should instead be made into sub-headings, e.g. **Installing the Eventing component** > **Installing the broker**. instead of having this subcomponent hidden away in a numbered step. This would make it easier to find and update sections of the docs that require changes, e.g. if we need to add an additional DNS or broker option in future, the commands or flags change, etc.

2. We do not clearly call out which steps are required vs which steps are optional. A user doesn't have to use the broker afaik if they elect to use an eventing workflow that uses sources and channels instead, or connects sources directly to services, etc. At the moment the install guide calls out both channel and broker as if they're required steps, but not how to actually implement them, e.g. triggers and subscriptions. I think adding this would be TMI for the install section - this makes it closer to a getting started guide. Consider removing the broker and channel parts entirely from the install guide, and similar parts like DNS, networking for serving, and instead having these in a post-install config or getting started guide?

**Comment by RichardJJG** [comment]
Blocker: https://knative.slack.com/archives/C9CV04DNJ/p1615287550079400

**Comment by evankanderson** [comment]
I see this tagged as `/triage needs-eng-input`, but it's not clear what engineering answers are needed. If someone wants to summarize those (or `/remove-triage needs-eng-input`), I'd be happy to take a swing.

**Comment by snneji** [comment]
@omerbensaadon, I think this has been done so we can close this issue, right?

**Comment by omerbensaadon** [comment]
I'd defer to @abrennan89 ?
