### ISSUE TITLE
The Build working group Calendar Invitation link doesn't work

### ISSUE THREAD

**Issue by pivotal-nader-ziada** [knative/docs#302]
## Expected Behavior
Clicking on the Calendar Invitation for the Build working group meeting would show me the calendar invite or add it to my calendar

## Actual Behavior
Link does not show anything 

## Steps to Reproduce the Problem

1. clink on the `Calendar Invitation` link for the `Build` working group in the Readme https://github.com/knative/docs/blob/master/community/WORKING-GROUPS.md

**Comment by duglin** [comment]
none of the calendar invites (except eventing) in https://github.com/knative/docs/blob/master/community/WORKING-GROUPS.md work for me and I'm in knative-user and knative-dev.

Can we please get this fixed?

**Comment by samodell** [comment]
Fixed.
