### ISSUE TITLE
Missing  Log,trace,and metrics user guide in 0.16 0.17 0.18

### ISSUE THREAD

**Issue by zhaojizhuang** [knative/docs#3032]
## Actual Behavior
Where is the Log,trace,and metrics user guide in 0.16 0.17 0.18
like this in 0.15 https://knative.dev/v0.15-docs/serving/installing-logging-metrics-traces/

**Comment by riyueshiwang** [comment]
I also met this issue

**Comment by abrennan89** [comment]
While some of the documentation around metrics etc still exists, the observability plugin was deprecated in an earlier release (0.14 IIRC), so any related documentation that was no longer valid for the observability components was removed.

We have a project tracking the work to add replacement documentation: https://github.com/knative/docs/projects/35 but this is not in progress yet AFAIK.

If you have a specific request for how to complete a task that you would like to have considered for addition to the docs, please raise an issue requesting docs for that specific user task. Thanks.
