### ISSUE TITLE
[samples/thumbnailer-go] Can't save generated thumbnail

### ISSUE THREAD

**Issue by justingrayston** [knative/docs#304]
## Expected Behavior
Expect `curl -X POST -H "Content-Type: application/json" -H "Host: $SERVICE_HOST"   http://$SERVICE_IP/image -d '{"src":"https://www.youtube.com/watch?v=DjByja9ejTQ"}'` to return success

## Actual Behavior
curl -X POST -H "Content-Type: application/json" -H "Host: $SERVICE_HOST"   http://$SERVICE_IP/image -d '{"src":"https://www.youtube.com/watch?v=DjByja9ejTQ"}'

Returns 

```
{"request_id":"a796c971-cd24-488b-a502-88c9c21d1a8c","created_at":"2018-08-01 22:13:47.343678892 +0000 UTC","status":"Failed","req":{"src":"https://www.youtube.com/watch?v=DjByja9ejTQ","width":200,"height":200},"message":"Processing...","thumbnail":""}
```

## Steps to Reproduce the Problem

1. Set up GKE cluster, istio and knative
2. Deploy build 
3. `{"request_id":"a796c971-cd24-488b-a502-88c9c21d1a8c","created_at":"2018-08-01 22:13:47.343678892 +0000 UTC","status":"Failed","req":{"src":"https://www.youtube.com/watch?v=DjByja9ejTQ","width":200,"height":200},"message":"Processing...","thumbnail":""}`
4. Fails
5. Try deploying from the prebuilt image
6. New deployment succeeds
7 retry curl - still fails.

## Additional Info
I could be doing something super stupid here but if I run the app locally all is good.
This is the error, and if I look at that file it is at the point of saving the file to the system.
`service.go:118: Error while creating thumbnail: ID:90cbcc59-9a81-46c7-b7c1-55259e62`

Raising this here as it feels like a k8s deployment issue. Does this need to create a disk mount fort humbs?

**Comment by samodell** [comment]
@mchmarny  I think you originated the thumbnailer sample -- any time to investigate?
