### ISSUE TITLE
API docs - The eventing-contrib repo has changed again

### ISSUE THREAD

**Issue by RichieEscarez** [knative/docs#3041]
## What is changing?

The `eventing-contrib` repo (fka "eventing-sources") has been restructured and no longer should be a part of the API docs build (it no longer releases along with the Knative Serving and Eventing components/repos).

This page should be removed from knative.dev: https://knative.dev/docs/reference/api/eventing/eventing-contrib-api/

## How will this impact our users?
From Slack discussion:

"all the sources/channels moved to `knative-sandbox/eventing-*` so for example kafka got moved to `knative-sandbox/eventing-kafka` and so on...."

What remains is "only tools in eventing-contrib"

**QUESTION**: Does the other/new repo need to be built and added to the API docs?

This is the API docs build script that needs to be updated to include the new repo details: https://github.com/knative/docs/blob/master/hack/gen-api-reference-docs.sh

After the script is updated, here are the API docs build instructions for generating the API docs: https://github.com/knative/docs/blob/master/docs/reference/api/README.md

## In what release will this take happen (to the best of your knowledge)?
0.19

cc/ @vaikas @grantr @devguyio

**Comment by vaikas** [comment]
@slinkydeveloper @matzew @aliok @lionelvillard just raising awareness here :)

**Comment by abrennan89** [comment]
This seems like a very old issue; we can revisit what is/isn't included in API docs builds when that comes up in the docs roadmap, wrt automation etc as well.
