### ISSUE TITLE
Font in left menu should be made easier to read

### ISSUE THREAD

**Issue by mattwelke** [knative/docs#3042]
**Describe the change you'd like to see**
The font used makes it hard to see. It's too thin. Here's an example:

![image](https://user-images.githubusercontent.com/7719209/99325433-59897580-2844-11eb-9910-c19837759138.png)

Every piece of text on this screenshot I find easy to read, except the menu on the left. I think it has to do with angle and viewing conditions for the user's screen. In a screenshot, it might look easy to read, but on some computers I've used, I found it hard. I think the font should be made thicker, like the rest of the text in the screenshot.

**Comment by omerbensaadon** [comment]
Hey @mattwelke! Thanks for the issue 😄  I think we use a Hugo template that other OSS projects use as well (see cert-manager.io). I couldn't find where the template actually lives, but if we do find it we should maybe contribute this change to them as well. 

I went ahead and tested the different colors of the left-nav with the same Color Content Analyzer [the government uses for Section 508 compliance](https://section508coordinators.github.io/TrustedTester/TestEnvironment.html#testing-tools) i.e. Accessibility 

# Results for a "Selected" Option
![Screen Shot 2021-01-07 at 11 20 34 AM](https://user-images.githubusercontent.com/16281246/103916452-715dd700-50da-11eb-954d-3b8242bdb58e.png)

# Results for "Main" Sub-Nav Option 
![Screen Shot 2021-01-07 at 11 22 11 AM](https://user-images.githubusercontent.com/16281246/103916589-9fdbb200-50da-11eb-83ce-7b107abe0eb4.png)

# Results for "Child" Sub-Nav Option
![Screen Shot 2021-01-07 at 11 23 00 AM](https://user-images.githubusercontent.com/16281246/103917030-22647180-50db-11eb-8ab7-915abe33ed42.png)

Looks like there are Accessibility issues for the "Selected" Option. 

I went ahead and changed line-weight to 1.7 vs the original 1.5 as well as altering the color of the "Selected Option" to "#0049CD" and this is what it looks like. 

# Revised Sizing and Coloring
![screencapture-knative-dev-docs-serving-knative-kubernetes-services-2021-01-07-11_30_08](https://user-images.githubusercontent.com/16281246/103917644-d7972980-50db-11eb-8079-e2e28f7d9a9b.png)


What do you think of these changes?

**Comment by mattwelke** [comment]
@omerbensaadon I think that looks better, but it's still the unselected stuff on the left that I find hard to read on my laptop.

On my desktop it's fine. And now I think I realize why. My laptop is a gaming laptop. I find that the other devs I meet have either professional laptops like XPS Pro or Macbooks, or they have gaming laptops because gaming laptops have pretty good value for the performance you get from them. These gaming laptops tend to have lower quality screens. For me, when I look down at my screen, like things in the bottom left corner, it looks blurry and the text looks very thin, with a reddish grey hue on the background. If I lower my face to look right at it, it looks fine, but that's not how I use my laptop. I found myself squinting or scrolling down to raise the text higher on my screen just to be able to read it while I was learning about Knative on my laptop when I made this issue.

So this is a bit of a niche thing I think. But I think it's a simple solution - make the text thicker. Then, it would be easy to read on all screen types, including those not using professional laptops.

**Comment by abrennan89** [comment]
cc @RichieEscarez

**Comment by RichieEscarez** [comment]
By bumping up the `font-weight` to `400`, give us (sorry its backwards but left is after and right is before) below. Let me know if this is enough and I can send the PR.
![image](https://user-images.githubusercontent.com/11762685/105884307-b334bb80-5fbc-11eb-9119-590315e5326d.png)

**Comment by mattwelke** [comment]
Holy crap my 👀 feel so much better looking at that. I'd have to test it on my laptop to know for sure. This page (https://github.com/knative/website/blob/master/DEVELOPMENT.md) appears up to date. I'll give it a go tonight.

**Comment by RichieEscarez** [comment]
@mattwelke how about I open a PR and we can review the staging server preview? I'll send that out shortly.

**Comment by mattwelke** [comment]
Sure, sounds good.

**Comment by RichieEscarez** [comment]
Preview here: https://60109c2d580aa60007de3455--knative.netlify.app/docs/serving/services/

If all looks good, you can comment a `/lgtm` here: https://github.com/knative/website/pull/248

**Comment by omerbensaadon** [comment]
@RichieEscarez Thank you!!!
