### ISSUE TITLE
Improve troubleshooting eventing docs

### ISSUE THREAD

**Issue by ctron** [knative/docs#3044]
## Steps to Reproduce the Problem

1. Read https://knative.dev/docs/eventing/debugging/
2. Read up until: https://knative.dev/docs/eventing/debugging/#channel-dispatcher
3. Problem shown, but guide stops at this point

**Comment by vaikas** [comment]
@n3wscott @vaikas we'll talk about this tmw in the dux/channel meeting.

**Comment by abrennan89** [comment]
@vaikas any update on this one?

**Comment by abrennan89** [comment]
@devguyio was this related to the stuff you wanted to work on?

It's a really poor UX at the minute to end the guide like this 
![image](https://user-images.githubusercontent.com/40172997/122274785-92f09500-cea8-11eb-8659-a6acae8e11da.png)

If we're not going to add more information here I am tempted to just clean up what we do have and move it to the developer guide, close this issue, and add a UX outcome (cc @omerbensaadon ) to add good troubleshooting docs based on user input from interviews as part of a roadmap / future plans

**Comment by devguyio** [comment]
@abrennan89 thanks for pinging! I totally agree and I'm gonna be working on this on Monday (release day is June 29th)

**Comment by abrennan89** [comment]
@devguyio any updates on this one yet? Should we unassign it and ask the @knative/eventing-wg-leads for help on it if you don't have bandwidth? It's been open for almost a year now so I'd like to get it closed 🙂
