### ISSUE TITLE
`istioctl install` command not found

### ISSUE THREAD

**Issue by futureCreator** [knative/docs#3048]
Hello, Istio 👋 

## Expected Behavior
https://knative.dev/v0.18-docs/install/installing-istio/#installing-istio-without-sidecar-injection
```
istioctl install -f istio-minimal-operator.yaml
```
Istio installation is expected.
`Istioctl` version: 1.4.10

## Actual Behavior

```
Error: unknown command "install" for "istioctl"
Run 'istioctl --help' for usage.
```

The v1.4.10 is recommended in the [Knative document](https://knative.dev/v0.18-docs/install/installing-istio/#before-you-begin).
> You need:
> - A Kubernetes cluster created.
> - istioctl (v1.4.10 or later) installed.
> 

But `install` command does not exist in [v1.4.10](https://istio.io/v1.4/docs/reference/commands/istioctl/).

## Steps to Reproduce the Problem

1. Follow [this step](https://knative.dev/v0.18-docs/install/installing-istio/#installing-istio-without-sidecar-injection).

## Additional Info
**Additional context**
n/a

**Install information:**
 - Platform (GKE, IKS, AKS, etc.): Plain K8s
 - Knative Version: v0.18

**Comment by nak3** [comment]
Hello @futureCreator
Thank you for your report. Yes, it is a bug and fixing by https://github.com/knative/docs/pull/3056.

And if you don't mind, could you please use Knative v0.19?
0.19 is the latest version and the doc already has the fix - 0.19 doc is here https://knative.dev/v0.19-docs/install/installing-istio/#installing-istio-without-sidecar-injection

**Comment by futureCreator** [comment]
@nak3 
Thank you! 🙏 
I'm going to install the 0.19 version and proceed.

**Comment by brun0xff** [comment]
I'm trying to install Istio with the 1.5.0 version and I had the same error, any help?
