### ISSUE TITLE
Bad link in https://knative.dev/docs/install/install-kn/#using-kn-with-tekton

### ISSUE THREAD

**Issue by zhaojizhuang** [knative/docs#3061]
## Expected Behavior

link works well

## Actual Behavior
![image](https://user-images.githubusercontent.com/3124692/100125934-50d61680-2eb8-11eb-9349-7a478cca268c.png)

Bad link `run kn using Tekton.` at https://knative.dev/docs/install/install-kn/#using-kn-with-tekton

**Comment by omerbensaadon** [comment]
Hey @zhaojizhuang  thanks for submitting this issue! Would it make more sense if the link pointed here?  https://github.com/tektoncd/catalog/tree/master/task/kn/0.1

**As in:** 
>You can also [run kn using Tekton.](https://github.com/tektoncd/catalog/tree/master/task/kn/0.1)

**Comment by zhaojizhuang** [comment]
> Hey @zhaojizhuang thanks for submitting this issue! Would it make more sense if the link pointed here? https://github.com/tektoncd/catalog/tree/master/task/kn/0.1
> 
> **As in:**
> 
> > You can also [run kn using Tekton.](https://github.com/tektoncd/catalog/tree/master/task/kn/0.1)

@omerbensaadon yeah, That looks good

**Comment by omerbensaadon** [comment]
Opened a PR to fix this, see above. 

Thanks again for submitting an issue, keep 'em coming!

**Comment by omerbensaadon** [comment]
Had to open another one because of a CLA issue...
