### ISSUE TITLE
Apache Kafka Channel Example(docs/eventing/samples/kafka/channel/index.md) simplification

### ISSUE THREAD

**Issue by xtreme-sameer-vohra** [knative/docs#3078]
The rendered content on the website isn't as friendly to navigate as the repo

## Expected Behavior
The files are rendered inline like the previous resources that are created or there is a hyperlink to the files to make the experience for users on the site more friendly

## Actual Behavior
The [demo](https://knative.dev/docs/eventing/samples/kafka/channel/#creating-a-service-and-trigger-to-use-the-apache-kafka-broker) section references a bunch of files such as `000-ksvc.yaml`

There is no reference to indicate where to fetch the files. 

## Steps to Reproduce the Problem

1. Visit the [Kafka examples on Knative.dev](https://knative.dev/docs/eventing/samples/kafka/channel/#creating-a-service-and-trigger-to-use-the-apache-kafka-broker)
1. A user will not be able to complete the examples without knowing about [the docs repo](https://github.com/knative/docs/tree/master/docs/eventing/samples/kafka/channel) to find the referenced files

**Install information:**
 - Platform (GKE, IKS, AKS, etc.): n/a
 - Knative Version: 0.19 / master

**Comment by abrennan89** [comment]
@omerbensaadon might be a good one to look at from a UX perspective.
I'm not sure why the files are referenced this way, it feels like adding docs to explain what each yaml is/does would be good, as well as maybe just including the yaml in the docs directly, or properly explaining where to find them in a repo.

**Comment by omerbensaadon** [comment]
Agreed, this is certainly worth exploring, feels like an "Icebox" item for now, especially if Channels take a backseat to Brokers in our Eventing "Getting Started" documentation
