### ISSUE TITLE
Apache Kafka Source Example(docs/eventing/samples/kafka/source/index.md) Discrepancies

### ISSUE THREAD

**Issue by xtreme-sameer-vohra** [knative/docs#3081]
# Issue 1: Verify output for Kafka Topic
## Actual Behavior
```
$ k -n kafka get kafkatopics.kafka.strimzi.io
NAME                 CLUSTER      PARTITIONS   REPLICATION FACTOR
knative-demo-topic   my-cluster   3            1
```
## Expected Behavior
```
$ kubectl -n kafka get kafkatopics.kafka.strimzi.io
NAME                 AGE
knative-demo-topic   16s
```

# Issue 2: Ensure Apache Kafka Event Source started with the necessary configuration
## Actual Behavior
The label selector has changed from `knative-eventing-source-name=kafka-source` to `eventing.knative.dev/SourceName=kafka-source`

## Expected Behavior
```
$ kubectl logs --selector='knative-eventing-source-name=kafka-source'
{"level":"info","ts":"2020-05-28T10:39:42.104Z","caller":"adapter/adapter.go:81","msg":"Starting with config: ","Topics":".","ConsumerGroup":"...","SinkURI":"...","Name":".","Namespace":"."}
```

# Issue 3: The purpose of the sample
## Actual Behavior
The example is about deploying a Kafka Source and configuring it.

## Expected Behavior
Building a Kafka source from source code. I might have misunderstood the purpose, but this is was my expectation going through the sample. 

# Issue 4: Change log settings for the Kafka source
## Actual Behavior
There were no new logs. 
A message has to be resent to generate debug level logs. It might make sense to move the log configuring step above sending the message so its not as confusing.

## Expected Behavior
Modify the log settings `kubectl -n knative-sources edit cm/config-logging` to `debug`
Deleting the Kafka Source deployment and re-fetching logs would have `debug` messages

## Steps to Reproduce the Problem

1. Follow guide [here](https://knative.dev/docs/eventing/samples/kafka/source/)

## Other considerations
This may be out of scope for the sample but it wasn't obvious what the implications of a namespace are on resources. I created the topic in a temp namespace `kafka-ex` and not where kafka was installed. Everything seemed to work fine, except when sending the message to the topic, I had to deploy the pod in the `kafka` namespace for things to work. So, should one never create a topic in another namespace than where Kafka is installed ?

**Install information:**
 - Platform (GKE, IKS, AKS, etc.): GKE
 - Knative Version: 0.19

**Comment by abrennan89** [comment]
@xtreme-sameer-vohra for issue #1, what is the actual requested docs change? Can you provide a link to the page please?

**Comment by abrennan89** [comment]
Note: https://knative.dev/docs/eventing/samples/kafka/source/ should be moved to be a subsection of https://knative.dev/docs/eventing/sources/

**Comment by xtreme-sameer-vohra** [comment]
Hey @abrennan89 
Looks like you already found it but just in case the link for issue #1 is [here](https://knative.dev/docs/eventing/samples/kafka/source/#apache-kafka-topic-optional)

**Comment by xtreme-sameer-vohra** [comment]
In terms of the docs change, the actual output when running `$ kubectl -n kafka get kafkatopics.kafka.strimzi.io` doesn't match what is on the website. I added the actual output I observed to the issue description, that could be used to update the website

**Comment by abrennan89** [comment]
> Hey @abrennan89
> Looks like you already found it but just in case the link for issue #1 is [here](https://knative.dev/docs/eventing/samples/kafka/source/#apache-kafka-topic-optional)

I didn't mean issue #1 in this repo 😄 I meant in the description of this issue: **Issue 1: Verify output for Kafka Topic**

**Comment by abrennan89** [comment]
Related Slack thread requiring other updates to this doc section, probably worth doing both as an overhaul together: https://knative.slack.com/archives/C9CV04DNJ/p1618339815199000

**Comment by abrennan89** [comment]
- Issue 1: in PR, updated output to "actual" from "expected"
- Issue 2: `knative-eventing-source-name=kafka-source` no longer appears in the docs https://knative.dev/docs/eventing/sources/kafka-source/, so I don't think this selector applies anymore. Only selector seems to be:
   ```
   kubectl logs --selector='serving.knative.dev/service=event-display' -c user-container
   ```
- Issue 3: removed misleading intro line
- Issue 4: requires modifying configmaps i.e. admin permissions, this is out of scope for the tutorial. @xtreme-sameer-vohra please open a separate issue for this if you would like for it to be documented in the admin topics for eventing, similar to https://knative.dev/docs/eventing/configuration/kafka-channel-configuration/

**Comment by abrennan89** [comment]
Thanks @pierDipi 🙂 can you open an issue for 4 and we can look into making that a shared page or something? If you're OK with it I'd like to get this PR merged and close Sameer's old issue 😉
