### ISSUE TITLE
Add a pointer to release notes for each component.

### ISSUE THREAD

**Issue by vaikas** [knative/docs#3092]
**Describe the change you'd like to see**
For each release that we cut, we should either link to, or include the release notes. @csantanapr do I recall correctly that you were maybe thinking of (or had started to?) tackle this?

**Additional context**

**Comment by omerbensaadon** [comment]
Hey folks, bumping this 😄 

CC: @csantanapr @vaikas

**Comment by csantanapr** [comment]
Not sure what this issue is asking for specifically

I'm doing a overall release note that includes everything in a single place that covers all components with a change here https://knative.dev/blog/2020/11/13/version-v0.19-release

**Comment by vaikas** [comment]
I had been thinking that mayhaps we could add something like a link here (since they are version specific install instructions):
https://knative.dev/docs/install/any-kubernetes-cluster/

Or here:
https://knative.dev/docs/install/

Or, maybe we link your blog instead of the actual release notes, or ?? :)
