### ISSUE TITLE
helm chart for knative

### ISSUE THREAD

**Issue by obeyler** [knative/docs#311]
Do you plan to create a helm chart for knative ?
best regards

**Comment by krancour** [comment]
I've written many. I'd be happy to help with this if there is consensus that we should do this.

**Comment by samodell** [comment]
Labeling as not docs related for now, but when the helm chart is finished we'll need to update the documentation to reference it.

**Comment by bhack** [comment]
See https://github.com/trisberg/knative-charts
I really hope that you can maintain or keep in symc and be the owners of "official" helm charts at https://github.com/helm/charts

**Comment by simplytunde** [comment]
Thanks @bhack for the tip. I and @boluisa submitted a PR https://github.com/helm/charts/pull/7268  to official helm/charts.  @samodell  Please share with the community so that others can contribute.

**Comment by gyliu513** [comment]
FYI @zxdiscovery @clyang82

**Comment by neeraj-laad** [comment]
We have created a helm chart for Knative 0.2.3 and submitted a PR https://github.com/helm/charts/pull/11024 to helm/charts repo. We would welcome any feedback / contributions on the chart.

We are now looking at creating the similar chart for Knative 0.4.0, but would like to integrate the helm chart as part of Knative CI / release process. Can someone point us to the right people / channel to discuss this further?

**Comment by obeyler** [comment]
@prydonius

**Comment by samodell** [comment]
Hey @neeraj-laad ! I would recommend bringing it up in the Knative slack channel. Possibly @jessiezcc  or @adrcunha  are the right folks to talk to, but I'm not 100% positive.

**Comment by neeraj-laad** [comment]
Thanks @samodell. I've asked the question in the general slack channel.

**Comment by adrcunha** [comment]
Yes, the Slack channel is the best place for discussing this, but definitely @mattmoor or @evankanderson or @mchmarny are best suited for such discussion. I believe I remember some discussion about having a helm chart for Knative a long time ago, but I don't remember why this didn't become an integral part of it (maybe it was something related to permission, or admin, or complications, but I might be wrong).

**Comment by evankanderson** [comment]
I think several of us had concerns about the security implications of Tiller in the Helm 2.0 model.

Assuming that this can be used to build a set of yaml which can be applied by hand, as well as a helm chart (and that it can integrate smoothly with our current `ko` usage), I have no problem with `helm` as an additional install option. In order to be a supported install option, I'd like to see:

1. That we exercise `helm` regularly in at least one of our test environments.
2. That we do not require `helm` installed in the cluster in order to install Knative.

**Comment by gyliu513** [comment]
@evankanderson @neeraj-laad we have did similar thing for CI in Kuberenetes federation v2 at here https://github.com/kubernetes-sigs/federation-v2/issues/506 , perhaps we can follow same way as federation v2 here.

> That we do not require `helm` installed in the cluster in order to install Knative

@evankanderson Yes, helm is not requested when install Knative, but if you want to install Knative via helm chart, then you should have helm installed.

Another question we need to consider is if we want to enable helm CI for knative, do we need to commit the Knative helm chart to Knative repo? For federation v2, we are maintaining the chart in federation v2 currently but also trying to create PR to commit it to helm/charts repo.

**Comment by adrcunha** [comment]
> 1. That we exercise `helm` regularly in at least one of our test environments.

That can be a separate E2E test in the CI flow, and even presubmit if necessary, no problem.

**Comment by abrennan89** [comment]
@evankanderson is there still a reason to have this issue open in the docs repo? It's almost 2 years old :scream: 
If so, do you know the specific docs changes required?

**Comment by evankanderson** [comment]
I think we've decided to prefer an operator to helm packaging:

https://knative.dev/docs/install/knative-with-operators/

/close

**Comment by ArtemChekunov** [comment]
If you wanna install knative-operator with helm chart you can make it with helmify

```
curl -s -L https://github.com/knative/operator/releases/download/knative-v1.2.0/operator.yaml | helmify knative-operator
```
