### ISSUE TITLE
Knative Kubernetes Services(docs/serving/knative-kubernetes-services.md)

### ISSUE THREAD

**Issue by xtreme-sameer-vohra** [knative/docs#3116]
## Expected Behavior
The networking section discusses the generic responsibility of the networking layer as Knative is agnostic and folks can pick a networking layer that is suitable for their needs.  

## Actual Behavior
Refers to the`net-istio-controller` deployment. If a user has made an alternative choice during the installation process, the actual deployment would be different.

## Steps to Reproduce the Problem
Visit [Knative Serving Services](https://knative.dev/docs/serving/knative-kubernetes-services/)
Particularly [this Istio](https://knative.dev/docs/serving/knative-kubernetes-services/#deployment-net-istio-controller) reference can mention that this deployment depends on what networking layer choice was made (eg. net-istio-controller, net-contour-controller, etc)

**Comment by omerbensaadon** [comment]
Thanks for taking the time to submit an issue @xtreme-sameer-vohra! 

In your opinion, would the example say something like `networking-certmanager` ... `networking` (i.e. simply removing istio reference). 

Maybe we could also include a note that says something to the effect of "Your networking deployment may be called something different depending on what networking layer you chose to use in [Getting Started](https://knative.dev/docs/install/any-kubernetes-cluster/)" ?

**Comment by xtreme-sameer-vohra** [comment]
Yep, a short snippet that mentions that what you observe will depend on the networking layer choice during installation.

Specifically [this](https://knative.dev/docs/serving/knative-kubernetes-services/#deployment-networking-istio) section could be made more generic to capture the responsibility of any networking layer. 
Suggestion: `The networking layer deployment(eg. networking-istio, contour-ingress-controller, etc)  reconciles a cluster’s ingress into the appropriate networking layer primitives`

**Comment by omerbensaadon** [comment]
@xtreme-sameer-vohra see above, does that address your concerns?

**Comment by mattmoor** [comment]
cc @knative/networking-wg-leads

**Comment by RichardJJG** [comment]
@xtreme-sameer-vohra, does this issue still apply?

**Comment by xtreme-sameer-vohra** [comment]
Hey @RichardJJG 
Thanks for following up on this.
The issue has changed but still applies, I updated the issue's body to reflect the current state (new website & Istio's deployment name change). Does it need more info/context ?

**Comment by RichardJJG** [comment]
Thanks, @xtreme-sameer-vohra -- I'm sure whoever starts work on it will reach out if they need to.

**Comment by abrennan89** [comment]
Unless anyone sees value in the https://knative.dev/docs/serving/knative-kubernetes-services/ page, after discussion with Markus, I think we can delete this page entirely. Wdyt @xtreme-sameer-vohra ?

**Comment by xtreme-sameer-vohra** [comment]
IMHO it is valuable to help new contributors / operators understand what each Knative Serving component does. From a quick glance on the site search I didn't find this info any where else 🤔 
For the new contributors, we could merge this page with [Serving Resources Overview](https://github.com/knative/serving/blob/main/docs/resources-overview.md). Thoughts ?
For operators, I don't have any data to back up my opinion 😥 . Do we know the page views this page receives?
