### ISSUE TITLE
Knative Serving(docs/serving/_index.md)

### ISSUE THREAD

**Issue by xtreme-sameer-vohra** [knative/docs#3117]
## Expected Behavior
Reference to generic networking layer

## Actual Behavior
Reference to Istio. Depending on the installation choice, this may or may not be accurate.

## Steps to Reproduce the Problem
Visit [here](https://knative.dev/docs/serving/)

**Comment by abrennan89** [comment]
@nak3 @xtreme-sameer-vohra @markusthoemmes can you confirm details please about which networking layers need to be documented and if there's some kind of generic/default we use besides Istio?

It feels like we should have a Serving > Networking section in the docs to gather all this information and then just point out to it, because it seems buried here: https://knative.dev/docs/install/any-kubernetes-cluster/#installing-the-serving-component 

Thoughts?

**Comment by xtreme-sameer-vohra** [comment]
To be clear and avoid confusing folks new to Knative, it would be helpful to have a term such as "Networking Layer" thats used throughout the documentation and it could link to a page which has the choices (including Istio) and a brief explanation similar to what @abrennan89 linked above

**Comment by evankanderson** [comment]
There are two references to Istio; one in the first paragraph and one in the first set of bullets. I might try rewriting this as:

```diff
- Knative Serving builds on Kubernetes and Istio to support deploying and serving of serverless applications and functions. 
+ Knative Serving builds on Kubernetes to support deploying and serving of serverless applications and functions. 
  Serving is easy to get started with and scales to support advanced scenarios.

  The Knative Serving project provides middleware primitives that enable:

  - Rapid deployment of serverless containers
  - Automatic scaling up and down to zero
- - Routing and network programming for Istio components
+ - Integration with multiple HTTP proxies (Ambassador, Courier, Gloo, Istio and Kong) to fit into existing environments
  - Point-in-time snapshots of deployed code and configurations
```

**Comment by nak3** [comment]
Yes, @evankanderson 's fix above looks good to me.

**Comment by xtreme-sameer-vohra** [comment]
👍 thats simple and straightforward as well.
The [Serving Install Page](https://knative.dev/docs/install/any-kubernetes-cluster/#installing-the-serving-component) refers to it as picking a `networking layer`. I'll defer to @nak3 & @evankanderson  as to which is better `HTTP proxy` or `Networking Layer`, but it would be awesome to keep the language consistent.
