### ISSUE TITLE
Documentation/Eventing Component/Code samples/Apache Kafka/Binding Example

### ISSUE THREAD

**Issue by MaciekLeks** [knative/docs#3121]
## Expected Behavior
Good understanding of KafkaBinding rationales:
- why
- when
- what
- how

## Actual Behavior
It's really hard to understand the concept of KafkaBinding. To be ownest I don;t understand it. Something is injected but how, when, where? Link of kafka-publisher is broken. I can't even find the source code of the image used for the Job.

v0.19

**Comment by omerbensaadon** [comment]
Hey @MaciekLeks! Thanks for the issue 👍🏼 

I am assuming the link you're talking about is this one? 
![Screen_Shot_2021-01-06_at_10_42_14_AM](https://user-images.githubusercontent.com/16281246/103787727-f5955900-500b-11eb-94d2-6b1d812c54c3.png)

I am going to open a new issue and fix this in a PR. 

As for understanding of KafkaBinding, can you point me to the documentation you used? Would also be willing to get on a video chat to better understand your frustrations

**Comment by MaciekLeks** [comment]
I'm not frustared any longer. I realized that first I should read more about SinkBinding first. It would be enough to add some bullet in prerequistites: "You must understand  [SinkBinding](https://knative.dev/docs/eventing/sources/sinkbinding/) before move on". It would help I think.
