### ISSUE TITLE
Installing Knative(docs/install/any-kubernetes-cluster.md)

### ISSUE THREAD

**Issue by canyugs** [knative/docs#3122]
## Expected Behavior
Kubernetes cluster v1.16 can install Knative.

## Actual Behavior
But Kubernetes minimum version has changed to v1.17 and Install failed.

## Additional Info
log from controller
```
	runtime/proc.go:203", "commit": "db4879e", "logger": "controller", "level": "fatal", "ts": "2021-01-06T10:03:54.493Z", "caller": "sharedmain/main.go:287", "error": "pre-release kubernetes version "1.16.15-gke.4300" is not compatible, need at least "1.17.0" (this can be overridden with the env var "KUBERNETES_MIN_VERSION"); note pre-release version is smaller than the corresponding release version (e.g. 1.x.y-z < 1.x.y), using 1.x.y-0 as the minimum version is likely to help in this case", "msg": "Version check failed", "knative.dev/pod": "controller-6bf5c9d778-85tf8" }
```

**Install information:**
 - Platform: GKE
 - Knative Version: 0.19

**Comment by omerbensaadon** [comment]
Thank you for taking the time to submit an issue!  

I am chasing down an answer for this now 👍🏼

**Comment by omerbensaadon** [comment]
Done! Updated the Version No. as per changes made in the following merged PR: https://github.com/knative/pkg/pull/1880

**Comment by omerbensaadon** [comment]
Thanks again for your time @canyugs

**Comment by canyugs** [comment]
Version in web changed, Thanks for quick response
