### ISSUE TITLE
PingSource(docs/eventing/sources/pingsource.md) source schedule confusion

### ISSUE THREAD

**Issue by lancerdima** [knative/docs#3154]
## Expected Behavior
Documentation should state that events are produced every minutes. Text should be inline with the samples.

## Actual Behavior
Documentation states that events are produced every second.

**Comment by abrennan89** [comment]
@lancerdima can you provide some links to where you are seeing this please

**Comment by lancerdima** [comment]
https://github.com/knative/docs/blob/master/docs/eventing/sources/pingsource.md

Example section:
This example shows how to send an event every **second** to a Event Display Service.

Running samples from the page indicate that events are generated once in a minute, or once in two minutes
`schedule: "*/1 * * * *"`
`schedule: "*/2 * * * *"`

I am not sure about the intended design decisions, but this CRON pattern with 5 fields is for minutes granularity - and behaves accordingly. Attempt to provide 6 fields for seconds granularity, result in an error. This is a bit confusing when taking the first introductory steps with the platform.

**Comment by abrennan89** [comment]
@lancerdima got it, pretty sure it's just a typo and should be minute :slightly_smiling_face: thanks
