### ISSUE TITLE
Broken link in Event sources(docs/eventing/sources/_index.md)

### ISSUE THREAD

**Issue by zhaojizhuang** [knative/docs#3159]
## Actual Behavior 
Broken link in https://knative.dev/docs/eventing/sources/，404 when click `Kafka Source`
![image](https://user-images.githubusercontent.com/3124692/104816283-1dc75800-5855-11eb-9f60-d2cfd871eabb.png)

**Comment by abrennan89** [comment]
@zhaojizhuang can this issue be closed now? It looks like the PRs to fix this were merged?

**Comment by zhaojizhuang** [comment]
> @zhaojizhuang can this issue be closed now? It looks like the PRs to fix this were merged?

I will close this issue
