### ISSUE TITLE
broken link in Sink(docs/eventing/sink/_index.md)

### ISSUE THREAD

**Issue by zhaojizhuang** [knative/docs#3161]
## Actual Behavior
broken link in page

![image](https://user-images.githubusercontent.com/3124692/104844940-cd600100-590d-11eb-8848-31c780a6f42b.png)

**Comment by abrennan89** [comment]
@zhaojizhuang can you please provide actual links to the page where the link is broken rather than screenshots please?

**Comment by zhaojizhuang** [comment]
> @zhaojizhuang can you please provide actual links to the page where the link is broken rather than screenshots please?

Hi, @abrennan89 ,see this page https://knative.dev/docs/eventing/sink/

**Comment by eclipselu** [comment]
seems it should be https://knative.dev/docs/eventing/sink/kafka-sink/ instead of https://knative.dev/docs/eventing/sink/kafka-sink.md

**Comment by pierDipi** [comment]
Done in #3241
/close
