### ISSUE TITLE
Red Hat -> IBM

### ISSUE THREAD

**Issue by richterdavid** [knative/docs#3172]
IBM bought Red Hat.

We should update references to "Red Hat" in the docs to either "IBM" or "IBM/Red Hat", after picking the right replacement.

https://www.redhat.com/en/about/press-releases/ibm-closes-landmark-acquisition-red-hat-34-billion-defines-open-hybrid-cloud-future

**Comment by abrennan89** [comment]
Hi @richterdavid . While you are correct that Red Hat was acquired by IBM, we still operate as a separate entity, so it is not correct to refer to IBM and Red Hat as the same thing. In the article that you reference, this is mentioned:
"Red Hat will operate as a distinct unit within IBM and will be reported as part of IBM’s Cloud and Cognitive Software segment."

Please do not change any references to Red Hat, they should remain as they are.

**Comment by richterdavid** [comment]
For the purposes of the Steering committee, subsidiaries may be considered as part of their parents. For the purposes of the Trademark committee, subsidiaries must be considered as part of their parents. So while I acknowledge that IBM and RedHat expressed a plan to remain separate, for these purposes highlighting the full affiliation is valuable. 

https://knative.dev/search/?q=subsidiary#gsc.tab=0&gsc.q=subsidiary&gsc.page=1

**Comment by richterdavid** [comment]
"IBM/RedHat" is currently in use for these two committees:
https://knative.dev/search/?q=%22IBM/RedHat%22#gsc.tab=0&gsc.q=%22IBM%2FRedHat%22&gsc.page=1

However RedHat is used separately elsewhere
https://knative.dev/search/?q=redhat#gsc.tab=0&gsc.q=redhat&gsc.page=1

**Comment by pmorie** [comment]
@richterdavid I think an example of something you feel should change would help me. 

Reviewing the links you sent, above I see:

- Places where Red Hat is used correctly to indicate someone's employer
- Places where Red Hat is used correctly in the name of a product offering (ie Red Hat OpenShift Cloud Platform)
- Places where Red Hat is used to refer to the name of the company before the acquisition closed (July 2019)
