### ISSUE TITLE
Contrib docs aren't accurate wrt. to cherry picks

### ISSUE THREAD

**Issue by dprotaso** [knative/docs#3179]
Hi, I see that the [contributing docs](https://github.com/knative/docs/blob/master/CONTRIBUTING.md#choosing-the-correct-branch) recommended to add a label to indicate when a pr needs to be merged into master and a release branch. I tried to add the label `needs-cherry-pick` and `release-0.20`, but it didn't work.

_Originally posted by @izabelacg in https://github.com/knative/docs/issues/3170#issuecomment-763783877_

**Comment by nak3** [comment]
/close

@dprotaso https://github.com/knative/docs/pull/3185 clarified the problem. Please feel free to re-open this if it is still unclear. Thanks.
