### ISSUE TITLE
Knative multi-container samples(docs/serving/samples/multi-container/_index.md)

### ISSUE THREAD

**Issue by steren** [knative/docs#3195]
Page is empty: https://knative.dev/docs/serving/samples/multi-container/

![image](https://user-images.githubusercontent.com/360895/106196013-c8008300-6165-11eb-9fee-1fe6bfd04c04.png)

**Comment by nak3** [comment]
Thank you! https://github.com/knative/docs/pull/3198 will fix it.

**Comment by nak3** [comment]
master branch (Pre-release doc) fixed https://knative.dev/development/serving/samples/multi-container/index.html
I will backport it to each branch.
