### ISSUE TITLE
Eventing debugging example points to non-existing message_dumper image

### ISSUE THREAD

**Issue by tplevko** [knative/docs#3201]
## Expected Behavior

The example describing debugging of eventing component should contain [example.yaml](https://github.com/knative/docs/blob/master/docs/eventing/debugging/example.yaml) pointing to correct image. Specifically the [message_dumper](gcr.io/knative-releases/knative.dev/eventing-sources/cmd/message_dumper) seems not to exist.

## Steps to Reproduce the Problem

1. Follow the steps in [example.yaml](https://github.com/knative/docs/blob/master/docs/eventing/debugging/example.yaml)
2. When instructed to apply example.yaml - the problem can be observed on the cluster.

**Install information:**
 - Platform (GKE, IKS, AKS, etc.): AWS
 - Knative Version: OpenShift 4.7

**Comment by grantr** [comment]
Message_dumper was replaced by event_display. Probably just needs an update to `gcr.io/knative-releases/knative.dev/eventing-sources/cmd/event_display`
