### ISSUE TITLE
View/Edit link on some "Community" pages link to the wrong repo

### ISSUE THREAD

**Issue by antoineco** [knative/docs#3211]
The "View/edit on GitHub" on some pages such as https://knative.dev/community/annual_reports/ link to https://github.com/knative/community, but the pages are actually in https://github.com/knative/docs/ so the links are dead (example: https://github.com/knative/docs/blob/master/community/annual_reports/).

**Comment by RichardJJG** [comment]
Addressing this issue within https://github.com/knative/docs/issues/4038
