### ISSUE TITLE
Knative Offerings(docs/knative-offerings.md)

### ISSUE THREAD

**Issue by yangyunfeng007** [knative/docs#3220]
1. The [Gardener](https://gardener.cloud/documentation/050-tutorials/content/howto/knative-install/) link is 404.
2. There is no content in the [Managed Knative for IBM Cloud Kubernetes Service](https://cloud.ibm.com/docs/containers?topic=containers-serverless-apps-knative).

![image](https://user-images.githubusercontent.com/17523539/107197078-688c5800-6a2e-11eb-99df-26a144771c91.png)

![image](https://user-images.githubusercontent.com/17523539/107197203-8e196180-6a2e-11eb-8e45-1886d39a98bd.png)

![image](https://user-images.githubusercontent.com/17523539/107197223-96719c80-6a2e-11eb-93c2-619cccb989df.png)

**Comment by yangyunfeng007** [comment]
@zhaojizhuang

**Comment by pierDipi** [comment]
cc @csantanapr @duglin for `Managed Knative for IBM Cloud Kubernetes Service.`

**Comment by duglin** [comment]
See: https://github.com/knative/docs/pull/3245

**Comment by omerbensaadon** [comment]
Fixed by #3245 and #3280 !
