### ISSUE TITLE
We should provide a preview for knative/docs pr like kubernetes/website

### ISSUE THREAD

**Issue by yangyunfeng007** [knative/docs#3221]
Like [kubernetes/website](https://github.com/kubernetes/website), we should provide a preview for docs pr. 
This is the [example](https://github.com/kubernetes/website/pull/26418).
This is the [link](https://deploy-preview-26418--kubernetes-io-master-staging.netlify.app/) generated by the robot.
![image](https://user-images.githubusercontent.com/17523539/107198525-2bc16080-6a30-11eb-987a-260f894cec45.png)

**Comment by yangyunfeng007** [comment]
@zhaojizhuang

**Comment by abrennan89** [comment]
@yangyunfeng007 you can use Hugo to create a local preview of docs PRs before submitting them: https://github.com/knative/website/blob/master/DEVELOPMENT.md#run-locally

There is currently a `stage-bot` that provides previews on PRs, but afaik @mattmoor plans to remove this and it isn't completely stable.

**Comment by mattmoor** [comment]
I killed stage-bot yesterday ☠️

**Comment by yangyunfeng007** [comment]
Thank you.
