### ISSUE TITLE
Setting up a custom domain(docs/serving/using-a-custom-domain.md)

### ISSUE THREAD

**Issue by yangyunfeng007** [knative/docs#3222]
There is a dead link.
https://github.com/knative/serving/blob/master/config/config-domain.yaml
![image](https://user-images.githubusercontent.com/17523539/107201759-62997580-6a34-11eb-8482-40893608118b.png)

**Comment by nak3** [comment]
Thank you @yangyunfeng007 for the report. https://github.com/knative/docs/pull/3261 is fixing the issue.
