### ISSUE TITLE
Event registry(docs/eventing/event-registry.md)

### ISSUE THREAD

**Issue by yangyunfeng007** [knative/docs#3224]
There is a [dead link](https://knative.dev/docs/reference/eventing/) in this [page](https://knative.dev/docs/eventing/event-registry/).

![image](https://user-images.githubusercontent.com/17523539/107206200-ae9ae900-6a39-11eb-9124-307e49e42c53.png)

**Comment by abrennan89** [comment]
New link provided by @vaikas : https://github.com/knative/eventing/blob/master/pkg/apis/eventing/v1beta1/eventtype_types.go
