### ISSUE TITLE
Sink(docs/eventing/sink/_index.md)

### ISSUE THREAD

**Issue by yangyunfeng007** [knative/docs#3225]
There is a [dead link](https://knative.dev/docs/eventing/sink/kafka-sink.md) in this [page](https://knative.dev/docs/eventing/sink/).
![image](https://user-images.githubusercontent.com/17523539/107206764-7051f980-6a3a-11eb-85ef-c0da06b4d6b6.png)

**Comment by pierDipi** [comment]
Hi @yangyunfeng007, thanks for reporting!
There is already a PR fixing this, we're in the process of cherry-picking the fix.
The content of the broken link is available at https://knative.dev/docs/eventing/sink/kafka-sink/

**Comment by yangyunfeng007** [comment]
Thanks!
