### ISSUE TITLE
Welcome to Knative(docs/_index.md) edit link broken

### ISSUE THREAD

**Issue by bdurette** [knative/docs#3234]
## Expected Behavior

The View/Edit this page link should take me to https://github.com/knative/docs/blob/release-0.20/docs/_index.md. 

## Actual Behavior

The View/Edit this page link takes me to https://github.com/knative/docs/tree/release-0.20/docs/README.md, which is a 404. 

## Steps to Reproduce the Problem

1. Open https://knative.dev/docs/.
1. Click on the View/Edit this page link in the upper right.

**Comment by abrennan89** [comment]
This doesn't seem to work for 0.19 either, it takes me to https://github.com/knative/docs/blob/release-0.16/docs/README.md which is the wrong version.

**Comment by mpetason** [comment]
It looks like this might have been fixed with v0.20 and v0.21. It might be related to the change over from using the index to point to the README file. Now there is only an index and a README file is no longer used.

**Comment by abrennan89** [comment]
This is actually fixed in all versions now on the site since Evan did some work for it. We may need to update some other docs to get them moved from README --> index to make sure they all work, but the page specified in this issue works fine now. Closing.
