### ISSUE TITLE
Broken link to eventing sugar controller URL

### ISSUE THREAD

**Issue by pianohacker** [knative/docs#3236]
## Expected Behavior
The `Installing` section on https://knative.dev/docs/eventing/sugar/ should give a link to an installable YAML URL.

## Actual Behavior
`{{< artifact ...` is shown instead.

**Comment by mpetason** [comment]
I think this has to do with it being a README file - it's not getting built properly. Other files with artifacts work with .md files instead. Opened a PR to move the readme over to an _index.md file.

**Comment by benmoss** [comment]
Yep, this is the problem
