### ISSUE TITLE
Docs should use the `kservice` short name instead of `services.serving.knative.dev`

### ISSUE THREAD

**Issue by steren** [knative/docs#324]
We now have short names for Knative resources (see https://github.com/knative/serving/pull/1723)
In particular, the service object can now be queried with `kservice`.

This simplifies our docs, for example: `kubectl get services.serving.knative.dev helloworld-go` becomes `kubectl get kservice helloworld-go`

CC @rgregg

**Comment by RichieEscarez** [comment]
@rgregg is this something we should move forward with in the docs and replace all instances of "services.serving.knative.dev" with "kservice" ?

**Comment by steren** [comment]
This touches another important topic: documentation versioning. Which I am not sure we have an answer today.

I think that the master branch of the `docs` repo should always document the master branch of the other repos.

Short term, I recommend you to do the opposite: use the new short names in the docs, and keep a note that they require a recent version (after August 9th) to be used.
