### ISSUE TITLE
"Sink Binding" doc is possibly buggy and/or could be improved

### ISSUE THREAD

**Issue by rhuss** [knative/docs#3263]
I see some issue with the current sink binding documentation at https://knative.dev/docs/eventing/sources/sinkbinding/ which I'm happy to work on if somebody can help me to answer some questions:

> By default, the webhook is set to exclusion mode, which means that any namespace that does not have the label bindings.knative.dev/exclude: true will be subject to mutation evaluation.

That doest not sound correct: If the default mode is 'exclude' then I would expect the include-label to use to override this, not an `exclude: true` label (btw, why are there two different label `bindings.knative.dev/exclude` and `bindings.knative.dev/include` with four possible combinations with binary values (instead of only one label with two values true/false)

> 1. Copy the sample YAML into a cronjob.yaml file:
> ...
> kubectl apply --filename heartbeats-source.yaml

The filenames don't align.

* In the cronjob.yaml example --> 
```
  image: <FILL IN YOUR IMAGE HERE>
```
What image is a used to suppose to use ? Is there a default one ? Which characteristics would such an app have ? Evaluate K_SINK (that is is an *important* information missing on this side) and send a Cloude Event to it ?

> all the ko stuff.
> ko publish knative.dev/eventing-contrib/cmd/heartbeats

Wouldn't it be *way* better to pre-publish an image and just use the reference here ? 

@knative/serving-writers anybody who could help me here with answering the questions ?

**Comment by lberk** [comment]
@n3wscott would you have a few minutes to look into this one?

**Comment by n3wscott** [comment]
@snneji is working on rewriting the entire section, so hold tight

**Comment by snneji** [comment]
Done in #3669
