### ISSUE TITLE
[1.0] Prepare Eventing

### ISSUE THREAD

**Issue by n3wscott** [knative/docs#3268]
Eventing is preparing to become 1.0 ready. This is a parent issue to track that work.

**Comment by evankanderson** [comment]
In addition to component-level "how to guides" and "reference", we need some "tutorials" and "explanation" that probably spans the entire Eventing component (https://documentation.divio.com/)

The overall story may be able to coordinate with the UX Working Group.

@omerbensaadon

**Comment by omerbensaadon** [comment]
@evankanderson some of this is covered in the Eventing Getting Started prototype, but the rest of the tutorial stuff probably needs to be post 1.0

**Comment by abrennan89** [comment]
Assigning some folks who have been working on issues for this

**Comment by abrennan89** [comment]
@n3wscott are there any other issues that need to be added to this epic, or is it finished once Samia is done with the last open issue?

**Comment by omerbensaadon** [comment]
Since 1.0 is already out, I am going to assume this is done
