### ISSUE TITLE
(Split of #1896) Add technical reference for install files for Knative Eventing

### ISSUE THREAD

**Issue by omerbensaadon** [knative/docs#3273]
**Describe the change you'd like to see**
This issues is a child issue to #1896. The only thing required for the "closing" of this issue is to create a markdown table of all of the Assets listed in the Eventing release. 

In Scope: 
- list of installation files
- table the describes the file and identifies dependencies/requirements

STORY 
```
AS A New User

I WANT to understand what each of the Assets in a Knative Eventing Release is for 

SO THAT if I am preforming a custom install, I have reference documentation
```

Install files for Eventing can be found under "Assets" here: https://github.com/knative/eventing/releases/tag/v0.21.0

NOTE: unclear where this content goes as of yet, but don't let that stop you from making progress! It's just a 3 column .MD table after all :)

**Comment by lberk** [comment]
@omerbensaadon there is typically a table in the release notes that could potentially be copied.

The eventing triage group looks over any issue that has the 'needs-eng-input' -- given that it seems you're already well on your way to solving this issue, can we drop the label at this time?

Thanks!

**Comment by omerbensaadon** [comment]
@lberk dropped! 

And thanks for that tip about release notes...

**Comment by omerbensaadon** [comment]
@lberk sorry, where can I find that table in the release notes...? I looked https://github.com/knative/eventing/releases/tag/v0.21.0 and didn't see it

**Comment by lberk** [comment]
Thanks!

Its under the `Assets` label and has each file needed as well as the size.

**Comment by omerbensaadon** [comment]
@lberk ah yes, I was meaning something more like https://github.com/knative/docs/pull/3296

Is this something one of the folks on the Eventing WG could write up...? 

That's sort of why I added the `needs input` label

**Comment by xtreme-sameer-vohra** [comment]
@lberk I understood the ask as providing a description for the files that are under the `Assets` label as the file name themselves are not sufficient to help folks understand;
- what each file contains (without looking at the contents)
- which files are required/optional
- if the files have dependencies

**Comment by omerbensaadon** [comment]
Please PR this to docs/install/assets/eventing.md!

**Comment by xtreme-sameer-vohra** [comment]
Good timing, @snneji  created https://github.com/knative/docs/pull/3304

**Comment by omerbensaadon** [comment]
Fantastic! This is coming along nicely. 

Let's get some other reviewers on here :)
