### ISSUE TITLE
Publish new Knative release v0.21 blog

### ISSUE THREAD

**Issue by csantanapr** [knative/docs#3277]
Publish new Knative release v0.21 blog

Similar to the previous blogs https://knative.dev/blog/releases/

/assign

**Comment by zhanggbj** [comment]
Hi @csantanapr 

Here is the kn-plugin-admin latest release for 0.21.

https://github.com/knative-sandbox/kn-plugin-admin/releases/tag/v0.21.0

**Comment by dsimansk** [comment]
The other one is `kn-plugin-source-kafka`.

https://github.com/knative-sandbox/kn-plugin-source-kafka/releases/tag/v0.21.0
