### ISSUE TITLE
"View/Edit this Page" Button missing README.md 

### ISSUE THREAD

**Issue by Xunzhuo** [knative/docs#3283]
## Expected Behavior

To edit target pages

## Actual Behavior

404 Not Found

![企业微信截图_20210228141157](https://user-images.githubusercontent.com/48784001/109409585-f1b00280-79ce-11eb-95d4-82dbbee4b61b.png)

## Steps to Reproduce the Problem

1.  separate _index.md to _index.md and README.md

## Additional Info
**Additional context**

**Install information:**
 - Platform (GKE, IKS, AKS, etc.):
 - Knative Version:

**Comment by abrennan89** [comment]
As far as I know we're moving away from having READMEs intentionally. Need some clarification on this. Please do not merge any PRs to re-add READMEs until this is clarified.

**Comment by evankanderson** [comment]
Oh, is the issue that the "edit this page" link is directing to the README.md rather than `_index.md`?

**Comment by Xunzhuo** [comment]
> Oh, is the issue that the "edit this page" link is directing to the README.md rather than `_index.md`?
yes the "edit this page" is directing to README.md rather than _index.md. This is what the issue means.

**Comment by abrennan89** [comment]
We've decided to update the build to stop using the READMEs. It may break in some places temporarily where we have yet to remove these in favor of index, but we'll fix them as we find them. Closing this PR since we should not be re-adding the READMEs.
