### ISSUE TITLE
Document how to proper uninstall Knative

### ISSUE THREAD

**Issue by csantanapr** [knative/docs#3300]
**Describe the change you'd like to see**

Yesterday, I saw someone struggling to uninstall and re-install knative. 

The person deleted the knative-serving namespace and then had issues re-installing with webhooks resources left behind and old resources of ksvc could not uninstall after reinstalling

We should document the details and how to properly uninstall 

**NOTE:** not super important where this goes, the Docs WG can figure out where this content will live later. Just need the content.

**Comment by houshengbo** [comment]
@csantanapr Suggest them use knative operator. I would rather they mess up the operator.

**Comment by csantanapr** [comment]
We need to document clearly proper way to uninstall for both methods of installation we support operator and simple yaml. 

We can't force people to only use operator for the open source project.

**Comment by RichardJJG** [comment]
Blocker: https://knative.slack.com/archives/C9CV04DNJ/p1615820052105600

**Comment by grantr** [comment]
From eng perspective, this can take the form of "these steps must be done in order or uninstall will fail". For example:

1. Delete all CRDs owned by knative (pretty sure we label these). I think as part of this, the k8s apiserver also deletes all instances of each CRD.
2. Delete all MutatingWebhookConfiguration and ValidatingWebhookConfiguration owned by knative (do we label these?)
3. Delete system namespaces. As part of this, deployments and service accounts are also deleted.
4. Delete ClusterRoles owned by knative (do we label these?)

I'm sure there's more to it than that, but could be a starting point.
