### ISSUE TITLE
(Split of #1896) Create "custom-install" page

### ISSUE THREAD

**Issue by omerbensaadon** [knative/docs#3303]
**Describe the change you'd like to see**
This issues is a child issue to #1896. 

**Dependencies:** 
This issue is dependent on the work done in #3273 & #3274. 

`Files to be created:`
/install/custom-install/

`Existing files to be edited:`
/docs/install/ (add link to /docs/custom-install/) 

`Files to remove:`
/docs/install/assets/serving.md
/docs/install/assets/eventing.md

`STORY`
```
AS AN Advanced User of Knative

I WANT to perform a "Custom Installation" of Knative
AND I want to understand what each of the yaml files within each release are for

SO THAT if I am preforming a custom install, I have reference documentation
AND it is referenced on the main Knative Install page as "custom-install" 
```

Install files for Serving can be found under "Assets" here: https://github.com/knative/serving/releases/tag/v0.21.0

Install files for Eventing can be found under "Assets" here: https://github.com/knative/eventing/releases/tag/v0.21.0

**Comment by omerbensaadon** [comment]
I believe closing this issue will also close #1896... 

CC: @RichieEscarez correct me if I am wrong here?

**Comment by RichieEscarez** [comment]
Great question!

This is a question of accessibility and enabling those users who are not yet "adv users". 

I previously hand crafted this content, which defines what each YAML does / what it's purpose is
 (here is a link from a past version. i randomly pick .10 but its not clear to me when it was deleted from the install guide): https://github.com/knative/docs/blob/release-0.10/docs/install/Knative-custom-install.md#choosing-knative-installation-files

That type of information is "reference" information and should live separately from the "how-to guide".

It looks like at some point, someone decided to just hide all that detail and deleted it (ie. the install guide just says to install a YAML file without explaining the WHY, zero context, loss of learning opportunity).

Linking users to the release assets also fails to explain what the purpose of each YAML does.

Example: What is the difference with these and why would I choose one over the other?

serving-core.yaml
serving-crds.yaml
serving-default-domain.yaml

If the "custom-install" page holds the expectation that a "**Knative user is an adv Kubernetes user**", then I think just simple links to the release assets page accomplishes that goal.

But, if the goal is to enable all users, then there is a large information gap.

Context: In the past, we established doc quality goals, roadmaps, etc, and this was one of the items that we felt had beneficial up-and-running impact, especially for new users.

**Comment by omerbensaadon** [comment]
@RichieEscarez ok this is helpful context. 

@snneji and @RichardJJG have created this table anew (see the "Dependencies" section in the issue above. 

Do they have the correct granularity of information? If so, where do you think these tables ought to live in the installation journey to enhance the understanding of what users are functionally installing?   

CC: @abrennan89

**Comment by omerbensaadon** [comment]
Bump
