### ISSUE TITLE
Update blue/green deployment docs

### ISSUE THREAD

**Issue by abrennan89** [knative/docs#3349]
This issue is to update the docs about using the blue/green traffic routing pattern.
Existing docs are here: https://knative.dev/development/serving/samples/blue-green-deployment/

Tasks required:

- [x] Move these docs from the obscurity of serving/samples to their own section in the docs under dev guide.
- [ ] Add alternative kn CLI commands as well as cleaning up kubectl/YAML docs.

May require some additional info from eng re commands to add.

**Comment by evankanderson** [comment]
Here's a CLI command to split traffic:

```shell
kn service update example --traffic green=80 --traffic blue=20
```

To assign 80% of traffic to green and 20% to blue revisions of the "example" Service. Note that the actual Revision names will probably be more like "example-green" and "example-blue" -- you'll probably want to use the user-selected revision name option in the YAML/the `--revision-name` flag to `kn service` create and update commands.

/remove-triage needs-eng-input

**Comment by abrennan89** [comment]
Note to self: Related to https://github.com/knative/ux/issues/39

**Comment by abrennan89** [comment]
Existing docs have moved to here https://dev-knative.netlify.app/development/serving/samples/blue-green-deployment
Possibly combine this with work to update https://dev-knative.netlify.app/development/serving/samples/traffic-splitting/
