### ISSUE TITLE
Split the current YAML-based installation into "click through" sub-headings

### ISSUE THREAD

**Issue by omerbensaadon** [knative/docs#3361]
**Describe the change you'd like to see**
We ought to split the main "install doc" (page referenced in title) for Knative into sections which necessitate "progressing" along the install path. 

This allows us to provide more context per step without overwhelming users and allows users to open Issues/PRs against specific installation steps.  

It has the added bonus of allowing us to track where users are falling off the installation journey.

**Additional context**
Ideally, the overall heading of the page would be "YAML-based installation" as it currently is in https://knative.dev/development/install/any-kubernetes-cluster/. 

Each of the sub-headings would be navigable via the left-nav and "Next + Prev" links. 

Each of the subheadings would be: 
1. Prerequisites 
2. Install Knative Serving
5. Install Knative Eventing 
6. Install Optional Knative Extensions

Prototype: 
![Install Split Prototyping Final](https://user-images.githubusercontent.com/16281246/112477102-00c56e80-8d49-11eb-9c6d-ba63c7870726.png)

This is a child issue of https://github.com/knative/ux/issues/11 and is part of a larger track of work related to improving the User Experience in Installing Knative (https://github.com/knative/ux/issues/1)

**Comment by snneji** [comment]
@omerbensaadon the YAML-based installation already has sub-headings. I'm not sure what you mean by click through sub-headings - would these all be on one page or does it mean multiple pages?

**Comment by omerbensaadon** [comment]
@snneji it would be multiple pages! Let's hop on a quick call and I will put our resolution in this issue.

**Comment by omerbensaadon** [comment]
After speaking to @snneji we have come to the following conclusions: 

1. This is too many splits! While this would be good for the UX WG to measure the effectiveness of changes to each section, it may negatively impact the user experience (making people click more could introduce unneeded friction)
^^ `Action Item` vv 
- [ ] Add this to the Docs WG Agenda. Pitch the idea of separating either Required + Optional and Serving + Eventing 
2. The steps themselves need more context (things like "What is this?" and "Why do I need this?" and "Which of these should I pick?") so I will create an epic for this in the UX Repo

**Comment by omerbensaadon** [comment]
@snneji I haven't gotten around to updating this issue yet, but I think we are on the same page so feel free to start work :) 

Pre-Req > Serving > Eventing > Optional

For this story, I would just focus on splitting out Pre-Req > Serving + Optional > Eventing + Optional

**Comment by snneji** [comment]
@omerbensaadon Since we agreed in the docs WG that we would split this topic into 4 parts, do we need to also have #3362? Would it be possible to repurpose this issue to do all the splitting work here and delete the other issue?

**Comment by omerbensaadon** [comment]
If that works better for you, absolutely. I'll close that issue now and expand this one!

**Comment by omerbensaadon** [comment]
OK, we are totally aligned and I think you'll be the only one working this for the time-being. I will expand this story to capture our discussion from the Docs WG 👍🏼

**Comment by omerbensaadon** [comment]
@snneji take a look 👍🏼
