### ISSUE TITLE
Clean up PingSource docs for eventing v1.0

### ISSUE THREAD

**Issue by abrennan89** [knative/docs#3366]

**Comment by omerbensaadon** [comment]
@abrennan89 I am trying to write an issue to move this content:
https://docs.google.com/document/d/1V_6Cjqbt0khUhewXnT_3_Hc2L0RDFThy4lHo8z-sEQ8/edit#heading=h.rq419k3cyw2t
into the PingSource example as apart of https://github.com/knative/ux/issues/21. 

If @RichardJJG took a stab at this and moved the content we have above into this page (docs/eventing/samples/ping-source/index.md) would that satisfy this issue?

**Comment by omerbensaadon** [comment]
@RichardJJG I made this a child issue of https://github.com/knative/ux/issues/21. 

The portion of the document you've been editing under the subheading [When this happens do that (1:1 event delivery)
](https://docs.google.com/document/d/1V_6Cjqbt0khUhewXnT_3_Hc2L0RDFThy4lHo8z-sEQ8/edit#heading=h.rq419k3cyw2t) is an example found with much less detail and polish in [PingSource Example](https://knative.dev/docs/eventing/samples/ping-source/). 

Do you think we could get this on our development branch of the Knative site in time for User Testing? If not we can use the Google Doc 👍🏼

**Comment by abrennan89** [comment]
@RichardJJG can you link the pull request to this issue please?

**Comment by RichardJJG** [comment]
Oh, sorry, that's confusing, bear with...

**Comment by RichardJJG** [comment]
After a lot of head-scratching and Googling I resorted to: https://github.com/knative/docs/pull/3476

(I couldn't push my feature branch to GitHub for the life of me so I just created a PR through the GitHub UI directly. Inelegant, but at least my proposed changes are here now...)
