### ISSUE TITLE
Diagram in serving docs is a broken link

### ISSUE THREAD

**Issue by grantr** [knative/docs#3367]
On this page https://knative.dev/docs/serving/ the "Diagram that displays how the Serving resources coordinate with each other" is a broken link.

I think the closest correct link is https://github.com/knative/serving/blob/main/docs/spec/images/object_model.png.

**Comment by mpetason** [comment]
The link is correct, it just isn't getting rendered properly on the website. Works in github - but that's because it actually renders the README file. 

/assign
