### ISSUE TITLE
Event delivery(docs/eventing/event-delivery.md)

### ISSUE THREAD

**Issue by denny-lclin** [knative/docs#3368]
## Expected Behavior
An example of configuring Broker delivery for Configuring Broker Delivery part

## Actual Behavior
An example of subcription

## Steps to Reproduce the Problem
N/A

## Additional Info
**Additional context**
BTW, regarding to 'Knative Eventing provides various configuration parameters to control the delivery of events in case of failure.' in Overview, is there a more specific description for what is counted as an 'failure' in Eventing (e.g timeout/not able to reslove uri/error code...) ? Thx

**Install information:**
 - Platform (GKE, IKS, AKS, etc.): 
 - Knative Version:

**Comment by abrennan89** [comment]
Hi @denny-lclin 
I made some updates to the broker docs for the upcoming v0.23 version: https://knative.dev/development/eventing/broker/broker-event-delivery/
Please let me know if this covers your issue or if you feel that there's more to do before we close this issue. Thanks!
