### ISSUE TITLE
GKE setup won't work from a GCE VM

### ISSUE THREAD

**Issue by mattmoor** [knative/docs#337]
https://github.com/knative/docs/blob/master/install/Knative-with-GKE.md#creating-a-kubernetes-cluster

In particular, I believe this command fails:
```
kubectl create clusterrolebinding cluster-admin-binding \
  --clusterrole=cluster-admin \
  --user=$(gcloud config get-value core/account)
```

I think it is because the service account doesn't have adequate permissions?

**Comment by skim1420** [comment]
`gcloud` no longer seems to add `username`/`password` entries to kubeconfig with `container/use_client_certificate = true`. So `kubectl` uses certificates and user `client` which has insufficient permissions to create the `clusterrolebinding`.

On a parallel note, I've opened a bug with the gcloud team to verify behavior.
