### ISSUE TITLE
 Add context as to why users need to add a Networking layer, add a recommendation for prototyping (development/install/any-kubernetes-cluster.md)

### ISSUE THREAD

**Issue by omerbensaadon** [knative/docs#3377]
## Expected Behavior
When a new users comes to the "Installing a networking layer" section of the YAML-based install page, they should understand why Knative Serving needs a Networking layer, what it enables them to do and should be instructed to choose the Networking layer they are most familiar with/is already installed in their cluster. 

In the event users do not have a Networking layer they are familiar with (or the one they are familiar with is not supported in the documentation), we should make a recommendation as to which Networking layer to use **strictly for prototyping purposes.**

Based on a fairly lax Slack survey, I recommend we tell users Kourier would probably be easiest, while noting that production use-cases may work better with Istio. 

## Actual Behavior
When a new users comes to the "Installing a networking layer" section of the YAML-based install page, they are given no context as to why they are being asked to install Networking. Moreover, the Networking multi-select defaults to "Istio" which is a heavy-handed networking layer to use to "Get Started" 

This sends users on a goose-chase through the Istio docs, where they leave the site at an average rate of 45% (15% higher than site average). In both rounds of interviews we did, we had a grouping of User Feedback which was titled "Istio! Arg!" 

## Steps to Reproduce the Problem

1. Go to https://knative.dev/development/install/any-kubernetes-cluster/#installing-a-networking-layer
1. Commence goose-chase

## Additional Info
**Additional context**
Child issue of knative/ux#26 part of the ongoing efforts in knative/ux#1

**Comment by snneji** [comment]
@omerbensaadon should this and #3378 wait until the installing topic has been split (ie #3361 has been closed)? I'll be creating new pages for the split. The information added here might need to be on one of the new pages.

**Comment by omerbensaadon** [comment]
You could work these in either order, but I don't feel they block each other. 

If there were more folks working this, we'd have to think a bit harder, but since it looks like it's just you (thank you) I'd say work either! 

My preference would be split first then context, only because you could do the split without ENG input :)
