### ISSUE TITLE
Add YAML description to each of the files under "Installing Eventing Component" (development/install/any-kubernetes-cluster.md) #3376

### ISSUE THREAD

**Issue by omerbensaadon** [knative/docs#3378]
## Expected Behavior
When a new users comes to the "Installing Eventing Component" section of the YAML-based install page, they should be given a brief description for each of the YAML files they are applying, a link out to learn more and an understanding of what impact those YAML files will have on their cluster. 

## Actual Behavior
When a new users comes to the "Installing Eventing Component" section of the YAML-based install page, they see 2 `kubectl apply` commands without much additional context. 

## Steps to Reproduce the Problem

1. Go to https://knative.dev/development/install/any-kubernetes-cluster/#installing-the-eventing-component
1. Check out the contextual information for each of the steps 
1. Be forced to investigate the YAML files in Github to understand what each of them does

## Additional Info
**Additional context**
Child issue of https://github.com/knative/ux/issues/26 part of the ongoing efforts in https://github.com/knative/ux/issues/1

A sister issue to #3376

**Comment by snneji** [comment]
@omerbensaadon, I think this was done in your PR #3411 so we can close this issue, right?

**Comment by omerbensaadon** [comment]
Yup!
