### ISSUE TITLE
Need a doc about various installation of Istio we can support

### ISSUE THREAD

**Issue by ZhiminXiang** [knative/docs#340]
## Expected Behavior
We plan to provide at least two versions of Istio for user to install (one is [istio.yaml](https://github.com/knative/serving/blob/master/third_party/istio-1.0.0/istio.yaml), the other is [istio-lean.yaml](https://github.com/knative/serving/pull/1889) which is being worked in progres).
We need a doc to tell user:
1. The main difference btw these two versions of Istio installation.
2. What kind of features will not be enabled by installing the light-weight Istio (istio-lean.yaml)
3. How users install their own Istio (if they want) in order to run Knative on it.

## Actual Behavior
Currently we don't have this doc.

**Comment by samodell** [comment]
@ZhiminXiang Do we have a projected timeline for getting the istio-lean.yaml ready for release?

**Comment by tcnghia** [comment]
Right, probably not in 0.1.1.  May be 0.2?

**Comment by tcnghia** [comment]
I am not sure it's priority/0 either.

**Comment by samodell** [comment]
Sounds good. Where are we tracking release timelines? I haven't seen any info on when we're planning to release 0.1.1 or 0.2.

**Comment by samodell** [comment]
This is now documented in the Knative custom install guide: https://github.com/knative/docs/blob/master/install/Knative-custom-install.md
