### ISSUE TITLE
Katacoda: configure the minikube to use a local domain name

### ISSUE THREAD

**Issue by sbawaska** [knative/docs#3402]
**Describe the change you'd like to see**
In the katacoda tutorials being discussed in #3142, rather than using the minikube IP, it would better to use a local domain name such as `http://demo.default.127.0.0.1.nip.io`. see comment here: https://github.com/knative/docs/pull/3142#discussion_r598965848

**Comment by abrennan89** [comment]
Issue moved to [knative/ux #41](https://github.com/knative/ux/issues/41) via [**ZenHub**](https://www.zenhub.com/)

**Comment by abrennan89** [comment]
IMO any issues for things like Katacoda going forward should be opened in the UX repo, not docs, since doc writers generally don't work on these. I've moved this issue. Thanks.
