### ISSUE TITLE
Katacoda: eventing broker tutorial improvement

### ISSUE THREAD

**Issue by sbawaska** [knative/docs#3403]
**Describe the change you'd like to see**
Change the order of consumers in the eventing broker tutorial

**Additional context**
For the katacoda tutorial discussed in #3142, consider changing the order of consumers to have one trigger on consumer1 and two triggers on consumer2. https://github.com/knative/docs/pull/3142#discussion_r599195722

**Comment by abrennan89** [comment]
Issue moved to [knative/ux #45](https://github.com/knative/ux/issues/45) via [**ZenHub**](https://www.zenhub.com/)
