### ISSUE TITLE
Is knative GA?

### ISSUE THREAD

**Issue by mattfarina** [knative/docs#342]
I recently received a notification that said...

<img width="817" alt="screen shot 2018-08-21 at 2 00 12 pm" src="https://user-images.githubusercontent.com/62991/44419945-932a8380-a54a-11e8-8e8c-2e5bbf54f2b1.png">

Is it GA without being tagged as a 1.0.0?

**Comment by josephburnett** [comment]
No, Knative is not GA.  It's early alpha (`v1alpha1`).

**Comment by josephburnett** [comment]
This will say `v1` and we will tag `1.0.0` when it's GA.  Sorry for the confusion.
