### ISSUE TITLE
Reorganize the Prerequisites topic

### ISSUE THREAD

**Issue by snneji** [knative/docs#3446]
In the [Prerequisites](https://knative.dev/development/install/prerequisites/) topic, it seems weird to have system reqs and then prereqs as two separate sections. Reorganize these sections to be more logical. One option is to combine as one section, maybe one as a sub-heading of the other.

**Comment by soham283** [comment]
Hello @snneji , I would like to work on this issue, can you please assign me this issue ?

**Comment by snneji** [comment]
Done
