### ISSUE TITLE
Follow up comments from PR #3434

### ISSUE THREAD

**Issue by abrennan89** [knative/docs#3451]
**Describe the change you'd like to see**
https://github.com/knative/docs/pull/3434 needs some follow up after merging to fix the doc structure and improve the content so that it's easier to understand.

**Comment by RichardJJG** [comment]
Awaiting answers to: https://knative.slack.com/archives/C017X0PFC0P/p1630927912038000

**Comment by RichardJJG** [comment]
> Awaiting answers to: https://knative.slack.com/archives/C017X0PFC0P/p1630927912038000

Answers received and acted on
