### ISSUE TITLE
Add documentation for the revision garbage collector

### ISSUE THREAD

**Issue by rhuss** [knative/docs#3461]
## What is changing? (Please include as many details as possible.)

Currently, there is no comprehensive user-facing documentation for describing the _revision garbage colletor_, i.e. the way how unused revisions are removed and which parameters are used to configure the garbage collector.

## How will this impact our users?

This will help the admin persona to configure the revision garbage collector according to her needs (+ of course understanding the way how the garbage collector works).

## In what release will this take happen (to the best of your knowledge)?

Exists since quite some time already (no exact version known when introduced)

## Context
Link to associated PRs or issues from other repos here.

* This is a _Knative Serving_ feature
* The global config parameters influencing the revision garbage collector are described in https://github.com/knative/serving/blob/main/config/core/configmaps/gc.yaml
* Switching on/off the [Responsive Revision Garbage Collector] is described in https://knative.dev/docs/serving/feature-flags/#responsive-revision-garbage-collector
* Use case that require a different, more aggressive revision GC:
   - https://github.com/boson-project/func/issues/285#issuecomment-808227612
   - https://github.com/knative/serving/issues/8208

## Additional info

This concept might be extended later with namespace or KService specific configuration to allow a Knative installation to serve multiple GC configurations, so the documentation might be extended a bit over time.

**Comment by abrennan89** [comment]
@rhuss was the documentation for  https://knative.dev/docs/serving/feature-flags/#responsive-revision-garbage-collector removed? I don't see anything in the site for this when I search for garbage collector

**Comment by rhuss** [comment]
@abrennan89 good point, looks like that this flag has been removed in the meantime. I'm not aware of this change, but @knative/serving-writers should know.

**Comment by julz** [comment]
Yeah, there's no feature flag any more (as of https://github.com/knative/serving/pull/11309) since gc v2 is now the default (and only) option

**Comment by rhuss** [comment]
@julz thanks for the pointer. But I guess we still would need documentation to explain how the garbage collector works in detail ? Or is this PR then obsolete, too ?

**Comment by julz** [comment]
No we definitely - imo - still need docs for the feature in general, just no longer for turning it on and off :-)

**Comment by abrennan89** [comment]
Thanks folks, can someone provide details for docs for this please?

**Comment by julz** [comment]
I think the comments in https://github.com/knative/serving/blob/main/config/core/configmaps/gc.yaml are actually a reasonably good start, but I'll happily work with someone to convert it in to a proper doc. Do you want me to try to do a first draft and if so is there a template I should use etc?

**Comment by abrennan89** [comment]
I think @RichardJJG was working on some doc templates but idk if they were finished / implemented yet.

The only thing I'd ask is that you add it to the admin guide under serving config if it's configmap stuff 😉 Happy for you to take a look if you want to, and I can give a review later if you ping when you need it.
Thanks!

/assign @julz

**Comment by abrennan89** [comment]
@julz any update on this one?

**Comment by julz** [comment]
Ach, sorry, this dropped off my list. Is there a template I should start from now or should I just pick some doc that seems similar and start from there?

**Comment by abrennan89** [comment]
@julz current templates list is here: https://knative.dev/docs/help/contributor/#templates 🙂
