### ISSUE TITLE
Setting up a custom domain per Service

### ISSUE THREAD

**Issue by pmbanugo** [knative/docs#3462]
**Describe the change you'd like to see**
I want to easily reference how to set up a custom domain per service in Knative. I found this [page](https://knative.dev/docs/serving/using-a-custom-domain-per-service/) with some info but what I was looking for was on a different [page](https://knative.dev/docs/serving/creating-domain-mappings/) with a title that I think should also be `Setting up a custom domain per Service`. 

I think they're both informative and a way to set up a custom domain per service. I suggest that both contents be merged into one using the title `Setting up a custom domain per Service` and not `Creating a Mapping between a Custom Domain Name and a Knative Service (Alpha)`. That would make it easier for someone not knowledgeable about the inner working of the project to know what to search for or which page to navigate to. If you'd prefer having them as separate pages, then maybe a better title for https://knative.dev/docs/serving/creating-domain-mappings/ would make it easy to read/find.

**Comment by nak3** [comment]
So there are three options:

A. Merge [1] and [2] into one page.
B. Keep them as separate pages but change the titles and add link each other.
C. Remove [1] and have only [2].

[1]: Custom domain by annotation    - https://knative.dev/docs/serving/using-a-custom-domain-per-service/
[2]: Custom domain by DomainMapping - https://knative.dev/docs/serving/creating-domain-mappings/

**Comment by nak3** [comment]
I am prefer to C. because I assumed that [1] is not official docs as it mentioned `There is currently no official process to set up a custom domain per Service. The topic is being discussed here.` in the page.

**Comment by julz** [comment]
yeah @nak3 I agree: I think 1 was an interesting hack that was worth documenting when it was the best option, but isnt something we should have as the main suggested way now that theres a top level feature about to move to beta that works properly with tls and arbitrary addressables etc. So I'd vote for C also; if we really really want a reference to the other trick we can put it in a collapsible Alternative Approaches section in [1] or something along those lines.

**Comment by pmbanugo** [comment]
I will go for *C* with a note at the end referencing `[1]` as an alternative but not recommended.

**Comment by evankanderson** [comment]
@pmbanugo 

If you're working on this item, you can type `/assign`, and Prow will mark you as assigned so no one else works on it.
