### ISSUE TITLE
Improving / reorg of broker docs

### ISSUE THREAD

**Issue by omerbensaadon** [knative/docs#3463]
Creating an issue to track the work in knative/docs#3427

Part of the epic https://github.com/knative/docs/issues/3268 and covers: 

>- [x]  Explanation of resource.
> - [x]  Sample minimum of component
>- [ ]  With kubectl cli

**Comment by abrennan89** [comment]
CLI stuff will be part of #3483 but I think it's overkill to track with this issue since I've already got Scott's issue assigned to me now https://github.com/knative/eventing/issues/4910
