### ISSUE TITLE
Document "reviewers" as a path to "approvers"

### ISSUE THREAD

**Issue by mattmoor** [knative/docs#348]
We should document the process to "approver" (OWNERS) to include a path where folks add themselves to the "reviewers" group ([e.g.](https://github.com/knative/serving/blob/84d891bad1d01c55cf49238e9f4ebec6b002cbf2/OWNERS_ALIASES#L6)) to get sufficient review volume.

/kind process

**Comment by n3wscott** [comment]
where is the "reviewers" group? it that a file or a github thing?

**Comment by abrennan89** [comment]
It would be good to have more detail [here](https://github.com/knative/docs/blob/master/CONTRIBUTING.md) in general about different roles within docs contributions.

**Comment by samodell** [comment]
Related: #958, which adds in details around becoming a docs reviewer/approver

**Comment by mhamwala** [comment]
This can be closed @samodell
fixes: #958

**Comment by samodell** [comment]
Thanks! @mhamwala
