### ISSUE TITLE
Broken link on Installing Knative(development/install/_index.md)

### ISSUE THREAD

**Issue by omerbensaadon** [knative/docs#3481]
For whatever reason, the prerequisite.md doesn't render out ".md" in the development site so that link goes to a broken link even though it is correctly referenced in the docs repo

**Comment by evankanderson** [comment]
It turns out the content there looks like:

```markdown
You can install the Serving component, Eventing component, or both on your cluster by using one of the following deployment options:

- Using a [YAML-based installation](./prerequisites.md)
- Using the [Knative Operator](./knative-with-operators).
- Following the documentation for vendor managed [Knative offerings](../knative-offerings).

You can also [upgrade an existing Knative installation](./upgrade-installation).

**NOTE:** Knative installation instructions assume you are running Mac or Linux with a bash shell.
```

Which suggests we should just trim off the `.md` from that one link. I thought that Hugo did that for us, but I think Hugo wants `{{<ref ...>}}` and `{{<relref ...>}}`, which seems to miss the point of Markdown, TBH.
