### ISSUE TITLE
[1.0] Fully document brokers.eventing.knative.dev

### ISSUE THREAD

**Issue by abrennan89** [knative/docs#3488]
@n3wscott commented on [Mon Feb 22 2021](https://github.com/knative/eventing/issues/4910)

Related to https://github.com/knative/docs/issues/3268
The following work needs to be validated for brokers.eventing.knative.dev to be ready for 1.0:
- [ ] Getting Started demo using the component.
- [x] Sample minimum of component
- [x] Sample complete resource of component
- [ ] Fully documented features and options, including
    - [x] Explanation of resource.
    - [x] All spec fields
    - [ ] All status fields
    - [ ] Any magic labels or annotations that apply.
    - [x] With kubectl cli
    - [x] With kn cli

---

@omerbensaadon commented on [Thu Apr 15 2021](https://github.com/knative/eventing/issues/4910#issuecomment-820678541)

https://github.com/knative/docs/issues/3463 is relevant here 

---

@omerbensaadon commented on [Thu Apr 15 2021](https://github.com/knative/eventing/issues/4910#issuecomment-820680415)

> - [x]  All spec fields

https://github.com/knative/specs/blob/main/specs/eventing/broker.md

Done here? 

---

@omerbensaadon commented on [Thu Apr 15 2021](https://github.com/knative/eventing/issues/4910#issuecomment-820682760)

> - [ ] Getting Started demo using the component.

Check out https://julz.github.io/docs/dev/getting-started/first-cloud-event/ 

Does this (or something like it) satisfy TODO? 

May also satisfy: 
> - [x]  Sample minimum of component

---

@omerbensaadon commented on [Thu Apr 15 2021](https://github.com/knative/eventing/issues/4910#issuecomment-820685067)

Will wait to check anything else off until @abrennan89 is done with https://github.com/knative/docs/issues/3463 https://github.com/knative/docs/pull/3427

It looks like her PR currently covers: 

>- [x]  Explanation of resource.
> - [x]  Sample minimum of component

---

@omerbensaadon commented on [Thu Apr 15 2021](https://github.com/knative/eventing/issues/4910#issuecomment-820692657)

> - [x] All spec fields
> - [ ] All status fields

Looks like spec has been delivered, Status looks like it needs an update.
https://github.com/knative/docs/blob/ea26207311e96551ec78726b335c4fc207718648/docs/reference/api/eventing/eventing.md#broker

---

@n3wscott commented on [Thu Apr 15 2021](https://github.com/knative/eventing/issues/4910#issuecomment-820712266)

> > * [x]   All spec fields
> 
> https://github.com/knative/specs/blob/main/specs/eventing/broker.md
> 
> Done here?

we would need a link from docs to the spec?

---

@omerbensaadon commented on [Thu Apr 15 2021](https://github.com/knative/eventing/issues/4910#issuecomment-820799779)

I'll create a new issue for that! 

---

@abrennan89 commented on [Tue Apr 20 2021](https://github.com/knative/eventing/issues/4910#issuecomment-823318432)

/assign

**Comment by abrennan89** [comment]
@n3wscott moved the issue so I can tick things off 😄 
Attached PR needs a review (I have some minor changes to make from our Slack convo earlier), and otherwise the only things I think left to address are;
- the demo thing, idk what you need for this?
- any extra status stuff, labels or annotations I've left out

**Comment by omerbensaadon** [comment]
:O 

@abrennan89 we should totally do this as we pick things up and start work on them!! A stellar move

**Comment by abrennan89** [comment]
@n3wscott feel free to reopen this if there's stuff that wasn't covered by the last PR
