### ISSUE TITLE
Eventing dependency on istio-1.0.0 is not clearly mentioned

### ISSUE THREAD

**Issue by neosab** [knative/docs#349]
## Expected Behavior

A user has a successful Eventing installation following the instructions at https://github.com/knative/docs/tree/master/eventing#getting-started 

## Actual Behavior
I don't end up with a successful Eventing installation.

It seems like Eventing requires Istio-1.0.0 to support the opt-in behavior w.r.t sidecar injection (Ref:-[b9f89a9](https://github.com/knative/eventing/commit/b9f89a9c0943b68e998d8f4c68a6e56d8b62bfa8)). If I follow the docs here I would be installing latest Eventing with knative Serving 0.1.1 and istio-0.8.0. As a result, I wasn't able to set up a successful Eventing installation. I had to explicitly label the knative-eventing namespace for istio-injection and add annotations to opt-out for most deployments. 

It will be great to mention that Eventing requires istio-1.0.0 or ask the users to install latest Knative Serving that seems to publish the [Istio-1.0.0 yaml](https://github.com/knative/serving/blob/master/third_party/istio-1.0.0/istio.yaml).

## Steps to Reproduce the Problem
Following the instructions in Getting Started to setup Eventing.

**Comment by samodell** [comment]
This is now called out clearly on that page, and all the install guides recommend installing a current version of Istio.
