### ISSUE TITLE
document Client CLI kn domain

### ISSUE THREAD

**Issue by csantanapr** [knative/docs#3496]
The new version of the `kn` CLI container a new command `domain`

The info is included in the release notes but it should properly be documented in the website

It was suggested by @abrennan89 to open an issue in the PR for the release notes blod [here](https://github.com/knative/docs/pull/3486#discussion_r617561269)
>@csantanapr can you please open a docs issue for kn domain to get it properly documented in the site so it's not only explained here?

/assign @rhuss

**Comment by rhuss** [comment]
Is this something I could actively drive or is it more about delivering input for the documentation and the docs creation happens by somebody else ?

Happy to do either, if I know where to put this documentation to.

**Comment by abrennan89** [comment]
Note to self: Related to https://github.com/knative/ux/issues/39

**Comment by abrennan89** [comment]
@rhuss either is fine - do you have draft info for docs for this, or want to take this issue and add a PR yourself?

**Comment by rhuss** [comment]
Let me pick this issue and write a documentation PR.

**Comment by abrennan89** [comment]
Bump @rhuss - any progress on this one? Thanks!

**Comment by rhuss** [comment]
@abrennan89 thanks for the reminder. I know you will be angry with me 🙇 :) , but could you give me a quick pointer where to add the PR for the documentation ? (I mean to which file) . Thanks and apologies to bug you with this question, but the location is probably not https://knative.dev/docs/client/ ?

**Comment by abrennan89** [comment]
lol I'm not angry, don't worry 😄 thanks for getting back to me!
I would be inclined to say https://knative.dev/docs/developer/serving/services/custom-domains/ since you're right, there's not really a client reference guide so to speak, we tend to just add `kn` commands where they fit in procedures. Feel free to ping me on Slack if you need any additional help.

**Comment by rhuss** [comment]
@abrennan89 to which source file does https://knative.dev/docs/developer/serving/services/custom-domains/  translate ? I can't find it in the docs repo. There I only can find https://github.com/knative/docs/blob/mkdocs/docs/serving/using-a-custom-domain.md which is a completely different document.

**Comment by abrennan89** [comment]
@rhuss are you sure you're on the correct branch in git and that you have pulled / rebased any changes from upstream? I just checked on my local repo and it's definitely under docs/docs/developer/serving/services/custom-domains.md
![image](https://user-images.githubusercontent.com/40172997/132535989-d45f0635-fdb6-40a1-ab7b-4e275e67a4eb.png)

**Comment by rhuss** [comment]
Thanks ! 

I was on the `main` branch (which does not contain that file), but it looks like that `mkdocs` is the default branch in the docs repo. Is there a particular reason why the `main` branch is not used as default, like for the others Knative repos ?

<img width="886" alt="Screen Shot 2021-09-08 at 17 39 35" src="https://user-images.githubusercontent.com/99080/132540820-e3ba64e0-bf1b-4bd1-a0a1-997a6a3f3f5e.png">

**Comment by abrennan89** [comment]
It's because it just hasn't been moved over yet, the plan was to use mkdocs temporarily.
@omerbensaadon any plans to move us back to the main branch?
