### ISSUE TITLE
Staging and publishing Knative documentation(help/contributor/publishing.md)

### ISSUE THREAD

**Issue by ellenevans** [knative/docs#3499]
## Actual Behavior

"The page and any elements like widgets, titles, and links, work and renders correctly."
Wrong verb number in either "work" or "renders".  I go with plural subject, so "render".

## Steps to Reproduce the Problem

1.
1.
1.

## Additional Info
**Additional context**

**Install information:**
 - Platform (GKE, IKS, AKS, etc.):
 - Knative Version:

**Comment by abrennan89** [comment]
I think https://dev-knative.netlify.app/development/help/contributor/publishing points to a page that no longer exists
