### ISSUE TITLE
autoscaler-go sample has OOB

### ISSUE THREAD

**Issue by mattmoor** [knative/docs#350]
[This](https://github.com/knative/docs/blob/26a432a20f08475307b77127a9feaf27d26cd79d/serving/samples/autoscale-go/autoscale.go#L35) line allocates an array of length `N`, but [these](https://github.com/knative/docs/blob/26a432a20f08475307b77127a9feaf27d26cd79d/serving/samples/autoscale-go/autoscale.go#L40) predicates check the bounds as `n <= N` (inclusive!).

We should probably be allocating an array of length `N+1` or make these `n < N`.

Repro: `http://${IP_ADDRESS?}?prime=5` yields:

```
panic: runtime error: index out of range goroutine 19 [running]: main.allPrimes(0x5, 0xc00010a0c0, 0x0, 0x0)
/usr/local/google/home/mattmoor/go/src/github.com/knative/docs/serving/samples/autoscale-go/autoscale.go:41 +0x375 main.prime(0x5, 0x6bc850, 0xc00010c0c0)
/usr/local/google/home/mattmoor/go/src/github.com/knative/docs/serving/samples/autoscale-go/autoscale.go:84 +0x35 main.handler.func2(0xc00010c0c0, 0x6eea40, 0xc00012c000, 0x5) 
/usr/local/google/home/mattmoor/go/src/github.com/knative/docs/serving/samples/autoscale-go/autoscale.go:144 +0x5c created by main.handler 
/usr/local/google/home/mattmoor/go/src/github.com/knative/docs/serving/samples/autoscale-go/autoscale.go:142 +0x239
```

cc @josephburnett

**Comment by samodell** [comment]
@josephburnett  Can you confirm if this problem still exists with the autoscaler-go sample? If not, feel free to close this.

**Comment by abrennan89** [comment]
@samodell I checked this with @markusthoemmes and he said that "`N+1` instead of `N` in this line should fix it https://github.com/knative/docs/blob/master/docs/serving/samples/autoscale-go/autoscale.go#L35" - I am happy to take this one and fix it along with other changes when I am working on autoscaler docs?
