### ISSUE TITLE
Adding new documentation(help/contributor/new-docs/_index.md)

### ISSUE THREAD

**Issue by ellenevans** [knative/docs#3500]
## Actual Behavior
Broken link 
Submit your contribution to GitHub
If you are not familiar with GitHub, see our [[working with GitHub guide]] to learn how to submit documentation changes.

The link currently points to a .md file, not the served html.

## Steps to Reproduce the Problem

1.
1.
1.

## Additional Info
**Additional context**

**Install information:**
 - Platform (GKE, IKS, AKS, etc.):
 - Knative Version:

**Comment by RichieEscarez** [comment]
This needs to go in https://github.com/knative/website/pull/288
