### ISSUE TITLE
[1.0] Fully document pingsources.sources.knative.dev

### ISSUE THREAD

**Issue by abrennan89** [knative/docs#3507]
@n3wscott commented on [Mon Feb 22 2021](https://github.com/knative/eventing/issues/4916)

Related to https://github.com/knative/docs/issues/3268
The following work needs to be validated for pingsources.sources.knative.dev to be ready for 1.0:
- [x] Getting Started demo using the component.
- [x] Sample minimum of component
- [ ] Sample complete resource of component
- [ ] Fully documented features and options, including
    - [ ] Explanation of resource.
    - [ ] All spec fields
    - [ ] All status fields
    - [ ] Any magic labels or annotations that apply.
    - [x] With kubectl cli
    - [x] With kn cli

**Comment by abrennan89** [comment]
@n3wscott is there anything still missing from https://knative.dev/docs/eventing/sources/pingsource/ now from this list?
Can you provide details for anything else that needs to be added please?

**Comment by n3wscott** [comment]
* [ ]  Sample complete resource of component
* [ ]  Fully documented features and options, including  
     * [ ]  All spec fields
     * [ ]  All status fields
     * [ ]  Any magic labels or annotations that apply.

I think these are the remaining items for pingsource based on v0.23 of https://knative.dev/docs/eventing/sources/ping-source/

I think we are mainly missing this page: https://dev-knative.netlify.app/development/eventing/sources/sinkbinding/reference/

**Comment by abrennan89** [comment]
We can probably also check for https://github.com/knative/eventing/issues/4865 as part of this that PingSource is v1 throughout docs.
At least 1 place it's not that needs an update:  https://dev-knative.netlify.app/development/eventing/samples/parallel/multiple-branches/

**Comment by abrennan89** [comment]
>I think we are mainly missing this page: https://dev-knative.netlify.app/development/eventing/sources/sinkbinding/reference/

@n3wscott can you please provide input / link to source files for that?

**Comment by n3wscott** [comment]
@abrennan89 I created that from using kubectl describe on sinkbinding.
