### ISSUE TITLE
dead link

### ISSUE THREAD

**Issue by Morriz** [knative/docs#3512]
On https://knative.dev/docs/install/upgrade-installation/ there is a link to the operator upgrade instructions, which does not exist: https://knative.dev/docs/install/upgrade-installation-with-operator.md

**Comment by Morriz** [comment]
This is a poor solution imo as I can't find information to the operator upgrade instructions at all ;(

**Comment by abrennan89** [comment]
@Morriz this was fixed in #3515 - Operator upgrade docs are here: https://knative.dev/docs/upgrade/upgrade-installation-with-operator/
