### ISSUE TITLE
Prerequisites(docs/install/prerequisites.md)

### ISSUE THREAD

**Issue by RobinsChens** [knative/docs#3513]
## Expected Behavior

it doesn't work 

## Actual Behavior

![image](https://user-images.githubusercontent.com/11987492/116533873-73130b00-a914-11eb-8cec-f6ce66040885.png)

## Steps to Reproduce the Problem
![image](https://user-images.githubusercontent.com/11987492/116533984-950c8d80-a914-11eb-8467-7b1fc2555d54.png)

1.
1.
1.

## Additional Info
**Additional context**

**Install information:**
 - Platform (GKE, IKS, AKS, etc.):  alicloud
 - Knative Version:   v0.21.0

**Comment by dprotaso** [comment]
the logs you posted aren't for the component that's crash looping - can you capture logs for the `autoscaler `deployment

**Comment by abrennan89** [comment]
This doesn't really look like an issue with docs/install/prerequisites as much as general installation problems.
Please ask for troubleshooting help in the Knative Slack (most like #serving-questions would help) and open an issue requesting a specific docs change if there is one required. Thanks.
