### ISSUE TITLE
Use pre-existing gateway instead of knative-ingress-gateway (istio)

### ISSUE THREAD

**Issue by Vafilor** [knative/docs#3524]
**Describe the change you'd like to see**

Additional doc to describe how to use a pre-existing gateway instead of the `knative-ingress-gateway` when using istio.

I wanted to use a pre-existing gateway instead of the default `knative-ingress-gateway`, because the existing gateway already had TLS set up. 

I couldn't find a clear way to do this in the documentation. I tried modifying `knative-ingress-gateway` to use TLS, but that creates a domain issue with istio since the other gateway already uses it.

In the end, I did the following:

1. Edit the `configmap config-istio / knative-serving`
    add `gateway.istio-system.ingressgateway: istio-ingressgateway.istio-system.svc.cluster.local`
Where istio-system.ingressgateway  is `<namespace>.<gateway-name>`

That gateway will be added and used instead of the default (I think): https://github.com/knative-sandbox/net-istio/blob/8a3cf7e23bc14a27218bddaf0a3757c4d64f891a/pkg/reconciler/ingress/config/istio.go#L100

2. Restart the networking-istio pod for changes to take effect
3. Finally,  make sure to edit the  config-network config map to have your domain match.

I set mine to
`domainTemplate: {{.Name}}-{{.Namespace}}.{{.Domain}}`
Instead of the default
` {{.Name}}.{{.Namespace}}.{{.Domain}}`

Which caused subdomain issues.

**Additional context**
* istio v1.9.1
* knative v0.22.0

**Comment by nak3** [comment]
> I wanted to use a pre-existing gateway instead of the default knative-ingress-gateway, because the existing gateway already had TLS set up.

Hi @Vafilor I think this doc https://knative.dev/docs/serving/setting-up-custom-ingress-gateway/ covers some of the steps. Could you please review it and let us know if we should add something?
(I feel that our doc is difficult to hit the search for some reason...)

**Comment by Vafilor** [comment]
Hi @nak3, thanks for the reply! Sorry for taking so long on my end.

If i'm understanding that guide correctly, it allows you to point the `knative-ingress-gateway` to a different service. 
That's not quite what I'm looking for.

In my case, I already have a Gateway set up, it looks something like this

`ingressgateway`
```spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        - '*'
      port:
        name: http
        number: 80
        protocol: HTTP
      tls:
        httpsRedirect: true
    - hosts:
        - '*'
      port:
        name: https
        number: 443
        protocol: HTTPS
      tls:
        credentialName: <credential_name>
        mode: SIMPLE
```

Which is pretty close to the `knative-ingress-gateway`. 

So, instead of creating a separate gateway `knative-ingress-gateway` I would like to have knative  use the `ingressgateway` above.

Let me know if I'm misunderstanding.

Thanks!

**Comment by nak3** [comment]
@Vafilor Thank you for the explanation. It's clear.
Actually the configuration is same place but the docs does not explain about the Gateway :sweat: I will update the docs.

So if you want to use your own gateway named `my-gateway` in `my-namespace` namespace, you can configure the `config-istio` configmap to:

```
$ kubectl edit cm -n knative-serving config-istio
```
```
  gateway.my-namespace.my-gateway: "istio-ingressgateway.istio-system.svc.cluster.local"
```

`config-istio` configmap explains it in the comment line https://github.com/knative-sandbox/net-istio/blob/release-0.23/config/config.yaml#L42-L49 but it should be documented.
