### ISSUE TITLE
Knative Serving(docs/serving/_index.md)

### ISSUE THREAD

**Issue by xtreme-sameer-vohra** [knative/docs#3543]
## Expected Behavior
Clicking [More Samples Link](https://knative.dev/docs/serving/#more-samples-and-demos) here works

## Actual Behavior
Its throws a 404

## Steps to Reproduce the Problem

1. Visit link above
1. Click the More Samples Link

**Comment by nak3** [comment]
This is same issue with https://github.com/knative/docs/pull/3487. 
As `README.md` was changed to `index.md`, we need to remove `README.md`.

Not only samples link, but also all `README.md` link grep-ed by:
```
$ grep -rH "\/README.md)" | grep -v https
```
need to be updated.

cc @evankanderson

**Comment by abrennan89** [comment]
@nak3 Added a PR to fix this and some of the others, but there are lots so it'll probably all be fixed over time, not as one issue.

**Comment by nak3** [comment]
Thank you!
