### ISSUE TITLE
Add basic instructions on how to start to serve the website to the README

### ISSUE THREAD

**Issue by gabo1208** [knative/docs#3549]
## Expected Behavior
Add basic instructions on how to start to serve the website to the README

## Actual Behavior
No instructions in the readme file

## Steps to Reproduce the Problem

1. Go to the readme file

**Comment by omerbensaadon** [comment]
Oooo this is a great catch... 

/assign

**Comment by snneji** [comment]
The [README](https://github.com/knative/docs#readme) also has a lot of broken links. I think it would be a good idea to fix those and remove stuff about Hugo while adding the Mkdocs instructions.
