### ISSUE TITLE
Fixed navigation menu nav links color

### ISSUE THREAD

**Issue by gabo1208** [knative/docs#3561]
## Expected Behavior
- Navigation nav links should be visible to the user

## Actual Behavior
- Nav links are invisible except for the active one

## Steps to Reproduce the Problem

1. Go to a mobile resolution
2. Open the top nav menu

**Comment by omerbensaadon** [comment]
Fixed by #3571

**Comment by omerbensaadon** [comment]
Somehow, this problem is back?

**Comment by gabo1208** [comment]
Seems that some css broke the "inherit" color for the nav item links, fixing it
