### ISSUE TITLE
Enable knobots on `mkdocs` branch

### ISSUE THREAD

**Issue by omerbensaadon** [knative/docs#3565]
## Description: 

---
## Story
```
As Carlos the Contributor
I want all the PRs submitted against the mkdocs branch to be properly tested by GH Actions
So that I can submit PRs with confidence.
```

## Acceptance Criteria
`Submitting a PR`
```
GIVEN I submit a PR to to the mkdocs branch of docs
WHEN I look at the PR after I've submit
THEN I see that the GH Actions have been triggered by the PR   
```

**Comment by omerbensaadon** [comment]
@evankanderson could use your help on this!

**Comment by csantanapr** [comment]
I asked in productivity channel in Slack for help on this

**Comment by markusthoemmes** [comment]
To be clear: This isn't about knobots (which are doing repo external things like cross-repo updates) but rather the in-repo checks that run per PR? If so, you can update those in https://github.com/knative-sandbox/.github

**Comment by omerbensaadon** [comment]
@markusthoemmes we have found this as well, what file specifically do we edit to ensure the branch "mkdocs" in /docs/ gets a check?

**Comment by csantanapr** [comment]
Thanks @markusthoemmes 
Yes this issue is about updating the github actions centrally. 

The problem is there are two repos named ".github" and is not clear which is the source of truth the one Knative-sandbox or Knative org

It looks like your saying Knative-sandbox

**Comment by markusthoemmes** [comment]
FWIW, the mkdocs branch (AFAIK) doesn't get any propagations automatically you could also just update the actions on the branch for the same effect.

**Comment by csantanapr** [comment]
/close
with PR #3582
