### ISSUE TITLE
De-Risk hosting multiple versions of the Knative website

### ISSUE THREAD

**Issue by omerbensaadon** [knative/docs#3573]
## Description: 
This is a story for de-risking multiple versions using MkDocs. **This story only requires that the previous versions build, not that they must be constantly up-to-date based on cherrypicked PRs to the respective `release-{version}` branches.** 

That functionality will be covered in a different story. 

---
## Story
```
As Daniela the Developer
I want to see previous versions of the Knative.dev website
So that I can see documentation relevant to the version I have deployed
```

## Acceptance Criteria
✅ `Version Dropdown`
```
GIVEN I am on the Knative.dev homepage (https://knative.github.io/docs/docs/)
WHEN I look at the header 
THEN I see a version dropdown with the "Development" version selected
(EDIT) AND I see a big black banner letting me know I am on an old, unsupported version
```

⚙️ `Multiple Versions Present`
```
GIVEN I am on the Knative.dev homepage (https://knative.github.io/docs/docs/)
WHEN I click on the Version Dropdown
THEN I see the last 4 releases (0.22-0.19), Archives, and Pre-Release as options 
AND Pre-Release is greyed out
```
^ ⚙️ Missing N-4 versions (0.19)

⚙️`Visit Older Versions`
```
GIVEN I have clicked on the Version Dropdown 
WHEN I click on an older version (i.e. 0.19) 
THEN I see the content which lives on the release-{version} (i.e. 0.19) branch in Github 
AND it renders in the old Hugo format 
```
^⚙️  Not rendered in old Hugo format, switched to MkDocs rendering 

## Known Issues and Considerations: 
- [x] For this implementation, we do not need to support cherrypicking of old PRs, we will cover that in a later issue.

**Comment by csantanapr** [comment]
This is being deploy now on https://beta-knative.netlify.app/v0.22-docs/

I think we can do this with {baseurl} to return back to https://beta-knative.netlify.app/docs

**Comment by omerbensaadon** [comment]
I see a thin black bar on the top of our (Pre-Release) version,  just noting it here.

**Comment by julz** [comment]
> I see a thin black bar on the top of our (Pre-Release) version, just noting it here

I think you probably still have an old version of extra.css in your browser cache, this is the new bit that hides that: https://github.com/knative/docs/blob/mkdocs/docs/stylesheets/extra.css#L47-L51
