### ISSUE TITLE
How to compile knative source code

### ISSUE THREAD

**Issue by yiqinguo** [knative/docs#3598]
How to compile knative source code？

**Comment by NovaHe** [comment]
Generally, there is a `DEVELOPMENT.md` in the project root directory, which will be explained in detail.
e.g.  [knative/serving](https://github.com/knative/serving/blob/main/DEVELOPMENT.md)

**Comment by abrennan89** [comment]
I think this one is out of scope of the docs repo, since this information as per @novahe 's comment is usually contained in the development readme or the related engineering repo, and is more related to dev contribution than end user docs.
