### ISSUE TITLE
Previous release docs should be updated to release branches with sslip.io default domain

### ISSUE THREAD

**Issue by julz** [knative/docs#3612]
Related to #3574, which updated the text in docs.

For releases before 0.23 (which already includes this fix) we should update the release branches in website/ to point at the latest patch releases of serving, to pick up the cherry-picks of the fixed default-domain job from https://github.com/knative/serving/pull/11298.

**Comment by abrennan89** [comment]
@julz presumably this is just to update the docs here https://knative.dev/v0.22-docs/install/install-serving-with-yaml/#configure-dns  for older versions than 0.23?

re "to point at the latest patch releases of serving" - can you provide the URL to point at these to update the command? Thanks.

**Comment by abrennan89** [comment]
@julz since the website has been updated to include the note about older versions not being maintained, I think it's OK to close this and just focus on 0.24+ going forward. Feel free to reopen if you think this is incorrect. Thanks.
