### ISSUE TITLE
Configure beta.knative.dev to work instead of https://beta-knative.netlify.app/

### ISSUE THREAD

**Issue by omerbensaadon** [knative/docs#3623]

**Comment by csantanapr** [comment]
After a very extensive scientific discussion between @RichieEscarez, @csantanapr, and @julz on what color to pain the shed we decided that the best option to make progress is to leave the website using the hostname `dev-knative.netlify.app` for now and when we are ready then make the netlify change to point to the docs repo to move the mkdocs to knative.dev

TLDR; Will use https://dev-knative.netlify.app for now until we move to https://knative.dev
Without any DNS change.
