### ISSUE TITLE
Fix all broken links in development version

### ISSUE THREAD

**Issue by csantanapr** [knative/docs#3629]
Many links are broken on new mkdocs site https://dev-knative.netlify.app/development/

**Comment by omerbensaadon** [comment]
This will be part of the Sanity Checks for Serving, Eventing, and Reference in Early Beta 

Sanity Checks for client, concepts, sample content and community samples in Late Beta

**Comment by omerbensaadon** [comment]
You can feel free to close this if that is A-OK with you, or keep it for posterity in case we miss something! Up to you

**Comment by csantanapr** [comment]
I thought there was only one milestone Beta, not two early Beta and late Beta. 
I didn't see the issues you mentioned stating they will cover link checking too that that's part of the definition of “Sanity Check.”

I'm ok if you want to close this as a duplicate once the other issues splitting this work are created.

**Comment by csantanapr** [comment]
/close
duplicate of #3643 and #3644
