### ISSUE TITLE
Page icons not displaying correctly on Safari/Mac

### ISSUE THREAD

**Issue by gabo1208** [knative/docs#3665]
<img width="1792" alt="Screen Shot 2021-05-25 at 1 55 43 PM" src="https://user-images.githubusercontent.com/4516177/119554183-00098280-bd62-11eb-8db4-68e861ebc365.png">

**The icon should display correctly in all of the browsers**
 Icons appear to be incomplete when using Safari/Mac browser

**Additional context**
Safari Version 14.1.1 (16611.2.7.1.4)
Intel MacBook Pro OS Version 11.4

**Comment by soham283** [comment]
Hello Omer,
I would like to work on this issue, can you please open this issue to me

**Comment by omerbensaadon** [comment]
@soham283 let's get #3672 closed first before I assign you to this one 👍🏼

**Comment by soham283** [comment]
#3672 has been solved PR has been accepted for that issue (#3689). Can you please Assign me this issue @omerbensaadon

**Comment by omerbensaadon** [comment]
CC: @gabo1208

**Comment by soham283** [comment]
please assign me the issue @gabo1208 or @omerbensaadon

**Comment by gabo1208** [comment]
Sure thing! /assign @soham283

**Comment by omerbensaadon** [comment]
Closed by #3740
