### ISSUE TITLE
Add the style guide Google doc to the contributor guide

### ISSUE THREAD

**Issue by snneji** [knative/docs#3671]
Add new style rules and any other additional information from the "Knative Styleguide Braindump" Google doc to the Knative contributor guide.

Styleguide Google doc: 
https://docs.google.com/document/d/1tigolRzKhronvgoAJfszE-XHWWd0LQ8o_j0D73O9KvM/edit#heading=h.gkysxvbx0rpt

Knative Style Guide in the contributor guide:
https://knative.dev/help/contributor/how-to/styleguide/

**Comment by omerbensaadon** [comment]
hey I am already in this area so I am going to move it into MkDocs
