### ISSUE TITLE
Logo on the homepage is glitchy on first load

### ISSUE THREAD

**Issue by omerbensaadon** [knative/docs#3672]
## Expected Behavior
When I load https://dev-knative.netlify.app/ I should see a the banner without any glitches

## Actual Behavior
When you first load the page, you see the knative logo flash against a white background before being put in the banner where it is supposed to render

## Steps to Reproduce the Problem

1. Go to https://dev-knative.netlify.app/
1. Switch between any tab and the homepage quickly
1. See the bug 

## Additional Info
![ezgif-6-060cd997d6c4](https://user-images.githubusercontent.com/16281246/119989441-2ebb6f00-bf95-11eb-85b8-022a296a49b5.gif)

**Comment by omerbensaadon** [comment]
CC: @markusthoemmes @shinigambit

**Comment by soham283** [comment]
Hello Omer,
I would like to work on this issue can you assign it to me

**Comment by omerbensaadon** [comment]
Awesome 🎉, thanks for your contribution! We are targeting Friday, June 4th for closing out this Milestone, do you reckon you could deliver something by early next week? 

/assign @soham283
