### ISSUE TITLE
Enable the website to build with Material for MkDocs Insiders

### ISSUE THREAD

**Issue by omerbensaadon** [knative/docs#3674]
Since I have already paid for this, and it has some nifty features which do not negatively impact the contributor experience, I reckon we should enable this. 

See: https://squidfunk.github.io/mkdocs-material/insiders/ 

PS: someone will have to pair with me to figure out how to do this since I own the access to the MkDocs Insiders repo

**Comment by omerbensaadon** [comment]
Moved to Late Beta

**Comment by abrennan89** [comment]
@julz @omerbensaadon is this still relevant? I think Omer doesn't have access to this anymore?

**Comment by omerbensaadon** [comment]
I still have access to this, but it seems like we're not using it... Closing
