### ISSUE TITLE
Infinite redirect loop in the netlify preview.

### ISSUE THREAD

**Issue by vaikas** [knative/docs#3678]
## Expected Behavior
In my PR:
https://github.com/knative/docs/pull/3677

netlify bot gives this link:
😎 Browse the preview: https://deploy-preview-3677--dev-knative.netlify.app

Clicking on it I'd expect to see the preview.

## Actual Behavior
Clicking on the link results in an infinite redirect loop.

If you curl it you get a permalink, in this case:
https://60af832540c4f100084e6e7a--dev-knative.netlify.app

Which seems to work.

## Steps to Reproduce the Problem

1. Open the PR: https://github.com/knative/docs/pull/3677
1. Look at helpful bot message, click on it
1. Observe that it doesn't work.

## Additional Info
**Additional context**

**Install information:**
 - Platform (GKE, IKS, AKS, etc.):
 - Knative Version:

**Comment by omerbensaadon** [comment]
@vaikas thanks for opening this! 

/assign @csantanapr

**Comment by omerbensaadon** [comment]
This is fixed @julz
