### ISSUE TITLE
Hello World - Python(docs/eventing/samples/helloworld/helloworld-python/_index.md)

### ISSUE THREAD

**Issue by vaikas** [knative/docs#3679]
## Expected Behavior
The sample to create a Broker also.

## Actual Behavior
The yaml does not create a Broker.

## Steps to Reproduce the Problem

1.
1.
1.

## Additional Info
**Additional context**
https://stackoverflow.com/questions/67720835/knative-eventing-newobservedgenfailure-error-for-helloworld-samples-trigger/67722535#67722535

**Install information:**
 - Platform (GKE, IKS, AKS, etc.):
 - Knative Version:

**Comment by NovaHe** [comment]
/assign 
I will fix it

**Comment by boramalper** [comment]
@vaikas When you use [this `sample-app.yaml`](https://github.com/boramalper/docs/blob/2a2364fb8e94176a1b02cf68a578e36f848cbdf7/docs/eventing/samples/helloworld/helloworld-python/sample-app.yaml) instead, do you still experience the same error?
