### ISSUE TITLE
Document "upgrading kn" 

### ISSUE THREAD

**Issue by omerbensaadon** [knative/docs#3686]
**Describe the change you'd like to see**
Currently, there is not documentation (AFAIK) that explains how to upgrade kn. This is especially painful via homebrew since we'v changed from `master` > `main`

You need to run 

```
brew uninstall kn
brew untap knative/client --force
brew tap knative/client
brew install kn
```

**Additional context**
I will probably write this myself, but opening an issue to track. I do need info from @knative/client-wg-leads as to what other methods exist to upgrade that may need to be documented?

**Comment by navidshaikh** [comment]
Usually `brew upgrade kn` would do. 
We'd to tap `knative/client` afresh if user had tapped `knative/client` before our migration to main branch. (local copy of master branch refs are now gone in upstream)
+1 to doc it here, also README of the repo https://github.com/knative/homebrew-client/blob/main/README.md covers that too.

**Comment by rhuss** [comment]
According to https://github.com/Homebrew/brew/pull/10423 a 

```
brew tap --repair
```

should be sufficient.

**Comment by xtreme-sameer-vohra** [comment]
> According to [Homebrew/brew#10423](https://github.com/Homebrew/brew/pull/10423) a
> 
> ```
> brew tap --repair
> ```
> 
> should be sufficient.

Thanks @rhuss 
That command recognizes the branch name change. I had to run `brew update` subsequently to get the formulae list updated. Without it, brew was still seeing v0.21 as the latest version.

**Comment by xtreme-sameer-vohra** [comment]
> **Describe the change you'd like to see**
> Currently, there is not documentation (AFAIK) that explains how to upgrade kn. This is especially painful via homebrew since we'v changed from `master` > `main`
> 
> You need to run
> 
> ```
> brew uninstall kn
> brew untap knative/client --force
> brew tap knative/client
> brew install kn
> ```
> 
> **Additional context**
> I will probably write this myself, but opening an issue to track. I do need info from @knative/client-wg-leads as to what other methods exist to upgrade that may need to be documented?

The simplifed flow can be
```
brew tap --repair
brew update
brew upgrade kn
```
