### ISSUE TITLE
Small text size in tables and notes

### ISSUE THREAD

**Issue by snneji** [knative/docs#3694]
# Issue
The text in tables and notes seems to be smaller than the text on the rest of the page. This issue might cause an accessibility issue for some users. 

Increase the size of the text in tables and notes to match the rest of the page.

# Examples

**Screenshot of table formatting:**

<img width="739" alt="Screen Shot 2021-05-28 at 18 14 25" src="https://user-images.githubusercontent.com/33425661/120303679-f97d8c80-c2c6-11eb-948d-1dd41e0fc823.png">

**Screenshot of note formatting:**
<img width="715" alt="Screen Shot 2021-06-01 at 11 38 37" src="https://user-images.githubusercontent.com/33425661/120310629-7e1fd900-c2ce-11eb-93c2-a890f95339e7.png">

# Resources
CSS file for customizing the layout can be found here: https://github.com/knative/docs/blob/mkdocs/docs/stylesheets/extra.css

**Comment by soham283** [comment]
I would like to work on the issue, please can you (@snneji) assign me the issue ?

**Comment by snneji** [comment]
Sure that would be great!

/assign @soham283

**Comment by soham283** [comment]
@snneji please review my PR
