### ISSUE TITLE
Update style for H4 headings

### ISSUE THREAD

**Issue by snneji** [knative/docs#3696]
# Issue
H4 headings look like bold text. It would be nice for these headings to have a distinctive style. 

# Example

**Screenshot of H4 formatting:**
(https://knative.dev/docs/developer/eventing/sources/sinkbinding/reference/#cloudevent-overrides)

<img width="739" alt="Screen Shot 2021-05-28 at 18 18 33" src="https://user-images.githubusercontent.com/33425661/120304186-77419800-c2c7-11eb-8309-6ed9e9dc80dc.png">

# Resources
The CSS file for customizing the layout can be found here: https://github.com/knative/docs/blob/mkdocs/docs/stylesheets/extra.css

**Comment by soham283** [comment]
I would like to work on this issue, @snneji can you please assign this issue ?

**Comment by snneji** [comment]
Hi @soham283, I assigned you to this issue. I believe you can also assign yourself to issues using the `/assign` command in a comment. The Knative prow robot then assigns you to the issue.

**Comment by soham283** [comment]
please review the pr #3767  @snneji and @omerbensaadon

**Comment by snneji** [comment]
Done in #3767
