### ISSUE TITLE
Fix formatting issues in Feature Flags doc

### ISSUE THREAD

**Issue by psschwei** [knative/docs#3703]
Based on discussion in #3666, there's a couple of formatting updates we can make to [docs/serving/feature-flags.md](https://github.com/knative/docs/blob/mkdocs/docs/serving/feature-flags.md):

1. Full examples for yaml samples rather than snippets (for example, [here](https://github.com/knative/docs/blame/mkdocs/docs/serving/feature-flags.md#L104-L121) and [here](https://github.com/knative/docs/blame/mkdocs/docs/serving/feature-flags.md#L129-L141))
2. Using code blocks instead of quotes for key values (i.e. `enabled` instead of "enabled", for example [here](https://github.com/knative/docs/blame/mkdocs/docs/serving/feature-flags.md#L208-L209) and [here](https://github.com/knative/docs/blame/mkdocs/docs/serving/feature-flags.md#L248))

/kind mkdocs
/kind style
/kind good-first-issue

**Comment by abrennan89** [comment]
I think wrt the snippets of code, `...` has been added now in each of them to show that it's just an excerpt, so that's acceptable IMO?

The code text > quotes does still need to be updated though.

**Comment by abrennan89** [comment]
Relates to #3710 since this should be in the admin guide (configmap docs).
