### ISSUE TITLE
Logo does not render correctly in Safari

### ISSUE THREAD

**Issue by omerbensaadon** [knative/docs#3706]
## Expected Behavior
I expect the logo to render as it does in chrome

## Actual Behavior
The aspect ratio is off 

![image](https://user-images.githubusercontent.com/16281246/120391211-b6d6a700-c2fc-11eb-8f7e-e3a18b2955a5.png)

## Steps to Reproduce the Problem

1. Open Safari
1. Go to the Knative Beta Site 
1. See funky logo

**Comment by soham283** [comment]
please assign me this issue
