### ISSUE TITLE
Add wait-for-drain to AuthorizationPolicy for system paths used by Knative

### ISSUE THREAD

**Issue by yanniszark** [knative/docs#3760]
## Expected Behavior

In page https://knative.dev/v0.22-docs/serving/istio-authorization/#allowing-access-from-system-pods-by-paths, the given AuthorizationPolicy gives access to paths `/metrics` and `/healthz`.  I expected the given AuthorizationPolicy to also include the `/wait-for-drain` path. Knative uses this path to wait until all requests in the queue are complete before terminating a Pod.

## Actual Behavior

The included Authorization policy does not include the `/wait-for-drain` path.

**Comment by csantanapr** [comment]
This issue is not specific to mkdocs new site
/remove-kind mkdocs

**Comment by csantanapr** [comment]
@dprotaso could you triage handle this?

**Comment by abrennan89** [comment]
cc @nak3 @houshengbo @markusthoemmes is this something you can maybe help to provide information for?
