### ISSUE TITLE
[SPIKE] Which content re-use plugin should we use? 

### ISSUE THREAD

**Issue by omerbensaadon** [knative/docs#3769]
Recently, we've discussed a couple of content re-use plugins (Snippets, mdx-include, etc.) which of these plugins should we use? 

Factors to consider: 
- Ease of use by current docs writers (UX of leveraging snippets) 
- Ability to fetch from remote repos (important for things like #3673 
- We are already using Snippets so there would be minimal logistic effort to move off of that tool

**Comment by omerbensaadon** [comment]
https://github.com/cmacmackin/markdown-include#configuration
https://github.com/neurobin/mdx_include
https://facelessuser.github.io/pymdown-extensions/extensions/snippets/

**Comment by snneji** [comment]
@abrennan89 are you still interested in working on this?

**Comment by abrennan89** [comment]
@snneji I was never working on / assigned to this, but it's still something we need, or at least that needs to be documented properly.

**Comment by snneji** [comment]
Could you remind why we want to change the content reuse plugin we use? What are the issues with the one we're currently using that will need to be solved by a new plugin?

**Comment by abrennan89** [comment]
I think the biggest issue was not having stuff like offsets for headings, let's put a pin in this for now and revisit whether it still needs to be looked at when we have less on our plate.
