### ISSUE TITLE
Event Delivery lacks retry info

### ISSUE THREAD

**Issue by matzew** [knative/docs#3773]
**Describe the change you'd like to see**

Event delivery doc (https://knative.dev/docs/eventing/event-delivery/) has very little information on retry.

> `retry` specifies the number of times that event delivery is retried before the event is sent to the dead letter sink.

I think it would be value for developers to learn more about, when/how a retry is triggered, what status codes are relevant here etc

**Additional context**

**Comment by abrennan89** [comment]
@knative/eventing-wg-leads @matzew can ya'll provide details for this?
