### ISSUE TITLE
There is a mistake in the installation procedure of Strimzi.

### ISSUE THREAD

**Issue by taiju** [knative/docs#3783]
There is a mistake in the installation procedure of Strimzi.

The API version of Strimizi has been changed in the following commit.
https://github.com/knative/docs/pull/3603/files

However, the version of Strimzi Operator used in the Strimzi installation procedure has not been changed, so following the procedure will result in a validation error.
https://github.com/knative/docs/tree/83877ca0f686886bf036288e7712bd884303de8e/docs/eventing/samples/kafka#setting-up-apache-kafka

Specifically, the following error will occur.
`no matches for kind "Kafka" in version "kafka.strimzi.io/v1beta2`

In addition, the configuration file itself has not been able to keep up with the incompatible changes, and parts that were changed to be written in `array` are still in `map`.

See the `Redesign of the .spec.kafka.listeners section` in the following document.
https://github.com/strimzi/strimzi-kafka-operator/releases/tag/0.20.0

## Expected Behavior

can be installed

## Actual Behavior

cannot be installed

**Comment by taiju** [comment]
Sorry, I didn't see the PR below. So you're modifying it to change to an external link, rather than updating the content?
https://github.com/knative/docs/pull/3781

**Comment by abrennan89** [comment]
@taiju probably yeah, a lot of the docs around this were out of date anyway, e.g. the script and related docs were installing a very old version, and I think it makes more sense to point out to those docs than to try to maintain our own separate version of strimzi docs.

**Comment by taiju** [comment]
@abrennan89 Thanks!
For maintainability, linking to the documentation is probably the best way to go.
However, it would be nice if the installation instructions for Kafka were also written here.
Because Knative Eventing is also attractive because it can transparently handle Kafka as a backend, so it would be nice to be able to install it without Kafka expertise.
