### ISSUE TITLE
Populate `kn plugins` page with existing `kn` plugins

### ISSUE THREAD

**Issue by omerbensaadon** [knative/docs#3786]
## Description: 
We currently have a `kn plugins` page which is empty (https://dev-knative.netlify.app/development/client/kn-plugins/). 

It would be nice if we could populate it with a table of the current plugins available to `kn` (found here: https://github.com/knative-sandbox?q=kn&type=&language=&sort=) 

---

## Story
```
As Daniela the Developer
I want to know what plugins are available for kn
So that I can better leverage the kn CLI
```

## Acceptance Criteria

- [ ] `See all available plugins`
```
GIVEN I access client/kn-plugins/ 
WHEN I look below the first paragraph
THEN I see a table with all of the names of currently available plugins
AND THEN I see a link to the Github repo where the plugin is hosted
```
`Sample md Table` 
|`kn` Plugin | Description |
|---|---|
|[Plugin_name](Link to GH Repo)|...|

---

## Known Issues and Considerations: 
https://github.com/knative-sandbox?q=kn&type=&language=&sort=

## Who should probably pick up this issue? 
- [x] Existing Contributors 
- [x] New Contributors

**Comment by abrennan89** [comment]
I think we'd want eng folks to provide some input here wrt to the status of each of the plugin types and how ready they are to be included, maybe use those status badges that show the version / alpha etc on the pages covering these?

**Comment by abrennan89** [comment]
This seems to be a duplicate ot #3534 - OK to close this one, @omerbensaadon ?

**Comment by omerbensaadon** [comment]
@abrennan89 sorry I am bad at GH notifications. Fine to close this one since I am assuming you're the one working on it!
