### ISSUE TITLE
[DOCS SPIKE] What should we do with all of the Concept topics? (`/concepts/`, `/eventing/*`, `/serving/*`

### ISSUE THREAD

**Issue by omerbensaadon** [knative/docs#3787]
## Description: 
We have this weird page (https://knative.dev/docs/concepts/), Eventing and Serving Concepts (usually the README in each of the components) and concepts for which we don't have concept pages (Traffic Splitting, for example)

This Docs [Spike](https://en.wikipedia.org/wiki/Spike_(software_development)) is to flesh out a desired state for where these Concepts should live. 

At the very least, we should figure out where to put the orphan "DuckTypes" page, but ideally we could have include this in the existing [Documentation Information Architecture](https://miro.com/app/board/o9J_lGgYxFs=/)

## Who should probably pick up this issue? 
- [x] Existing Contributors 
- [ ] New Contributors

**Comment by abrennan89** [comment]
@omerbensaadon related? https://miro.com/app/board/o9J_lGgYxFs=/?openComment=3074457358287748889

**Comment by omerbensaadon** [comment]
To that comment in particular? I don't reckon, I am just wondering on how we want to use "Concepts..."

Should we concentrate all of our explanatory docs under that heading and have everything else be process/guides?

**Comment by abrennan89** [comment]
@omerbensaadon this page is actually gone now I think, we can probably close this issue since we're doing card sort and other strategy stuff
