### ISSUE TITLE
Decompose `mkdocs.yml` into `mkdocs.yml` + `navigation` + `redirects`

### ISSUE THREAD

**Issue by omerbensaadon** [knative/docs#3797]
## Description: 
We would like to split up the mkdocs.yml into `main`, `navigation`, and `redirects` in order to make it more manageable + scriptable. 

---

## Story
```
As Carlos the Contributor 
I want mkdocs.yaml split into three different files 
So that mkdocs.yaml is less of a cluster 
And is nicer to look at and work with 
```

## Acceptance Criteria

- [ ] `Separate mkdocs.yml`
```
GIVEN I have pulled the PR for this issue to my local machine
WHEN I look at the /docs files
THEN I see that mkdocs.yml has been separated into `mkdocs.yml`, `navigation` and `redirects`
```

---

- [ ] `Sanity Check`
```
GIVEN I have pulled the PR for this issue to my local machine
WHEN I do `mkdocs serve` in my CLI
THEN the website renders locally without error 
AND the site the PR preview renders without error 
```

## Who should probably pick up this issue? 
- [x] Existing Contributors 
- [x] New Contributors

**Comment by benmoss** [comment]
Not sure this is possible with mkdocs by itself, we'd have to go into a tool like `jq` or `ytt` or something, do we want this that bad?

**Comment by julz** [comment]
I think it is as of mkdocs 1.2, see https://github.com/mkdocs/mkdocs/pull/2422 and the linked comment
