### ISSUE TITLE
🛑 Make existing redirects work in `mkdocs`

### ISSUE THREAD

**Issue by omerbensaadon** [knative/docs#3799]
## Description: 
In the old version of the Knative site, redirects were done with with [front-matter](https://gohugo.io/content-management/front-matter/), we must now move all of the redirects from front-matter to the `redirects` section of the mkdocs.yml 

---

## Story
```
As Ursula the User 
I want all existing redirects to work on the new Knative site 
So that I can get the information I am looking for
```

## Acceptance Criteria

- [ ] `All existing redirects work in mkdocs`
```
GIVEN I am on the new mkdocs site
WHEN I try any of the existing pages which have had redirects configured in front-matter 
THEN the redirect works 
```

---

## Nice to Have Acceptance Criteria
- [ ] `Remove front-matter`
```
GIVEN I look at any existing document 
WHEN I look at the first few lines 
THEN I don't see front-matter anymore 
```

## Who should probably pick up this issue? 
- [x] Existing Contributors 
- [ ] New Contributors

**Comment by csantanapr** [comment]
Could someone point on an example on this front-matter redirect in the knative hugo site, is this located the docs or website repo?

**Comment by julz** [comment]
https://github.com/knative/docs/blame/mkdocs/docs/client/README.md#L7

My script which should hopefully mostly automate this is at https://github.com/julz/redirectredirects
