### ISSUE TITLE
Communicate to users that the `mkdocs` site is in public beta, link them to docs issues for feedback

### ISSUE THREAD

**Issue by omerbensaadon** [knative/docs#3800]
## Description: 
While we've done a great job on the MkDocs Site, we want users to understand that they are using a site that is recently "hot off the presses" in order to incentivize users to provide feedback on the site as well as excuse any "work in progress" sections. 

Looks like Material for MkDocs has something called an ["announcement bar"](https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-header/#announcement-bar) which we can leverage! 

---

## Story
```
As Ursula the User 
I want to understand that I am using a Beta version of the Knative Site
So that set my expectations are set accordingly 
```

## Acceptance Criteria

- [ ] `Visit the Site`
```
GIVEN I have started a fresh session on the Knative site 
WHEN I look up at the top of the page 
THEN I see a banner letting me know the site is in Beta
AND I see the text below: 
```

`Welcome to the new Knative.dev!` ⚠️ `Pardon our progress, if you find any issues with this site, please submit them here!`

---
- [ ] `Click Banner`
```
GIVEN I have started a fresh session on the Knative site 
AND I see the banner at the top of the page
WHEN I click on the banner anywhere except the "x" 
THEN https://github.com/knative/docs/issues/new/choose opens in a new tab
```

----
- [ ] `Click the x` 
```
GIVEN I have started a fresh session on the Knative site 
AND I see the banner at the top of the page
WHEN I click the "x" on the banner
THEN the banner disappears 
```

## Who should probably pick up this issue? 
- [x] Existing Contributors 
- [x] New Contributors

**Comment by omerbensaadon** [comment]
We may want to soften the language here and not use "Beta"

**Comment by csantanapr** [comment]
Do not use the word `Beta` just say that the website is new provide feedback if you like it or something not working

**Comment by omerbensaadon** [comment]
CC: @csantanapr @julz

**Comment by csantanapr** [comment]
mkdocs already supports a banner, easy to configure

**Comment by csantanapr** [comment]
here are the docs to implement "Announcement bar" https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-header/?h=header#announcement-bar

**Comment by gabo1208** [comment]
https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-header/#announcement-bar Here it is
