### ISSUE TITLE
🛑 Render Old Versions of Knative.dev as static HTML 

### ISSUE THREAD

**Issue by omerbensaadon** [knative/docs#3801]
## Description: 
Since we don't want to have to move everything over to `mkdocs`, we're forced to live with a "Frankenstein's Monster" for old versions of the website (newest version = `mkdocs`, all previous versions = `Hugo` ) 

---

## Story
```
As Pyotr Alekseevich the Production User 
I want to see old versions of Knative documentation on the website 
So that I am assured the older version of Knative which I have in production has documentation
```

## Acceptance Criteria
- [x] `Visit old versions`
```
GIVEN I have loaded the current version on the Knative site (rendered in mkdocs) 
WHEN I select an older version of the documentation from the version drop-down
THEN I am taken to a rendering of the old Hugo site 
```

---

- [x] `Come back to current version`
```
GIVEN I am accessing an older version of the Knative site (rendered in Hugo) 
WHEN I click on the current version from the version drop-down
THEN I am taken back to the current version of the Knative site (rendered in mkdocs`) 
```

## Who should probably pick up this issue? 
- [x] Existing Contributors 
- [ ] New Contributors

**Comment by omerbensaadon** [comment]
@omerbensaadon make sure to add old version similar to K8s in a new AC

**Comment by csantanapr** [comment]
build the last 0.24 and development will be in mkdocs, 0.23, 0.22, 0.19, with hugo
