### ISSUE TITLE
Homepage should feature at least 3 customer logos

### ISSUE THREAD

**Issue by xtreme-sameer-vohra** [knative/docs#3809]
**Describe the change you'd like to see**
At least 3 customer (not vendor) logos on the website homepage.
This is from [Knative GA Requirements doc](https://docs.google.com/document/d/1mC_nDpLIycqiBn5Om1tvbcY3yyAR3WUNXcHiyloEzhg/edit?ts=609d1aaf#heading=h.rbnr61t4qtv8)

**Comment by aijamalnk** [comment]
@xtreme-sameer-vohra doesn't look like I can assign this issue to myself. Could you assign it to me please?

**Comment by abrennan89** [comment]
@xtreme-sameer-vohra this looks like it's taken care of now by the **Trusted by:** section?
If so, could you close the issue please? I'm not sure if there's a PR to link for this that was missed @aijamalnk ?

**Comment by aijamalnk** [comment]
@abrennan89 this issue is about end user logos. Our Knative content work and case studies should address it. I will close the issue once we deliver them.

**Comment by evankanderson** [comment]
https://github.com/knative/docs/pull/4406

/close
