### ISSUE TITLE
Add a page in the community section for End-user community

### ISSUE THREAD

**Issue by xtreme-sameer-vohra** [knative/docs#3810]
**Describe the change you'd like to see**
A page in [knative.dev/community](https://knative.dev/community) highlighting the end-user community where additional users can add testimonials.
This is from [Knative GA Requirements doc](https://docs.google.com/document/d/1mC_nDpLIycqiBn5Om1tvbcY3yyAR3WUNXcHiyloEzhg/edit?ts=609d1aaf#heading=h.rbnr61t4qtv8)

**Comment by aijamalnk** [comment]
@xtreme-sameer-vohra doesn't look like I can assign this issue to myself. Could you assign it to me please?

**Comment by evankanderson** [comment]
I think linking to https://github.com/knative/community/issues/696 is probably the right plan now.

**Comment by omerbensaadon** [comment]
I think this is done RE: what Evan said
