### ISSUE TITLE
Split kubectl commands using <<EOF into two steps

### ISSUE THREAD

**Issue by snneji** [knative/docs#3813]
The current method for documenting `kubectl` commands YAML using `kubectl apply -f - <<EOF...` does not work for Windows users.

To fix this issue, do the following:

- [x] Update style rule in the [Documenting YAML](https://dev-knative.netlify.app/development/help/contributor/style-guide/documenting-code/) section of the style guide. File location: https://github.com/knative/docs/blob/mkdocs/docs/help/contributor/style-guide/documenting-code.md

     The new steps should be similar to the following:

   >1. Create a YAML file...
   >     ```
   >     # YAML FILE CONTENTS
   >     ```
   > 2. Apply the YAML file...
   >     ```
   >     kubectl apply --filename <filename>.yaml
   >     ```

- [x] Search the knative/docs repo for kubectl commands that use the `<<EOF` format. Update these commands to follow the new style rules.

     - Update all commands in the docs
     - Optional: Update commands in `tutorial` and `blog` folders 

See this [Slack thread](https://knative.slack.com/archives/C9CV04DNJ/p1623783139041200) for the discussion.

**Comment by snneji** [comment]
@abrennan89 should I also edit the docs in the [/tutorials/katacoda](https://github.com/knative/docs/tree/mkdocs/tutorials/katacoda) directory? I'm not sure if I should edit them because they have `{{execute}}` after each YAML snippet. Also I'm not sure where these docs are published.

**Comment by abrennan89** [comment]
Probably better to ask @csantanapr or @sbawaska because I really don't know anything about the Katacoda stuff 🙂

**Comment by sbawaska** [comment]
The katacoda tutorial runs inside linux containers, so no need to update them.
