### ISSUE TITLE
[EPIC] Clean up Kafka docs

### ISSUE THREAD

**Issue by abrennan89** [knative/docs#3817]
There are multiple open issues for Kafka / Strimzi docs. This epic is an attempt to group them together so that I can multitask on the docs work.

- [x] #4058
- [x] #3783
- [x] #3078
- [x] #3079 
- [x] #4082 
- [x] #3583 
- [x] #3077 
- [x] #3081 
- [x] #2262

**Comment by devguyio** [comment]
That sounds great @abrennan89 and thanks for pinging. I would like to sync more and help~

**Comment by snneji** [comment]
@abrennan89 which issues are part of this epic?

**Comment by abrennan89** [comment]
@snneji I've already added a bunch of issues above, do you have Zenhub? Maybe otherwise you can't see them, I'm not sure?
