### ISSUE TITLE
[build] provide a simple build sample for Build docs

### ISSUE THREAD

**Issue by ahmetb** [knative/docs#382]
## Expected Behavior

![image](https://user-images.githubusercontent.com/159209/45235681-903fca80-b28e-11e8-9391-47e6588cea7e.png)

I expected this link at https://github.com/knative/docs/tree/01f02a9ca6413f907a09a37d6085cb1dd32bf0d9/build#simple-build-samples to lead to a simple Knative Build example.

## Actual Behavior

It leads to https://github.com/knative/build/tree/846036c8b91df25fa57da4d48a8ae5f9129c81f0/test which has a lot of test cases. 

By taking a simple look, I can't tell which sample am I supposed to click on as a first example.

## Proposed solution

Link to (and/or create) a simple Knative Build example.

**Comment by RichieEscarez** [comment]
Build to be deprecated
