### ISSUE TITLE
Style Guide Tweak -- remove code formatting and style guide use ambiguities

### ISSUE THREAD

**Issue by RichardJJG** [knative/docs#3827]
1. Remove code formatting from example in https://dev-knative.netlify.app/development/help/contributor/style-guide/style-and-formatting/#documenting-knative-api-objects
It misled one engineer and it bleeds into our entirely separate rule on when to apply code formatting.

1. Spell out that, in the event of clashes, the Knative Style Guides overrules the K8s Style Guide.
Again, an engineer didn't realize this.

**Comment by RichardJJG** [comment]
kind/style

**Comment by RichardJJG** [comment]
/kind/style

**Comment by julz** [comment]
FWIW I'd suggest also explicitly saying in the Code Formatting one that in other cases (including where the k8s guide would say you should) you shouldn't use code formatting (unless I missed a sentence somewhere that says this). Even just adding the word "only" in the initial paragraph would satisfy my pedantry here ;)

**Comment by RichardJJG** [comment]
@julz, thanks, I was thinking the same thing.

**Comment by RichardJJG** [comment]
kind:docs

**Comment by omerbensaadon** [comment]
@RichardJJG 

/label kind/style 👍🏼

**Comment by omerbensaadon** [comment]
/label kind/style 

@RichardJJG 

👍🏼
