### ISSUE TITLE
Document DomainClaims and administrator management of DomainMapping

### ISSUE THREAD

**Issue by evankanderson** [knative/docs#3835]
## What is changing? (Please include as many details as possible.)

Administrators can control which namespaces may use a custom domain for DomainMappings by setting `autocreateClusterDomainClaims` to `false` in the `config-network` ConfigMap, and then manually creating [ClusterDomainClaim objects](https://github.com/knative/networking/blob/main/pkg/apis/networking/v1alpha1/domainclaim_types.go#L64) to assign domain names to specific namespaces.

This isn't documented anywhere, and I only picked it up by accident in a @markusthoemmes / @julz chat. 😁 

## How will this impact our users?

Administrators will have the ability to control which namespaces may use custom domains, and which custom domains may be used on the cluster at all. (This should go in "Administrator > Serving" guide somewhere reasonable.)

## In what release will this take happen (to the best of your knowledge)?

v0.20 ?

## Context
Link to associated PRs or issues from other repos here.

1. https://github.com/knative/networking/pull/326

**Comment by julz** [comment]
I have it on my list to do this

/assign
