### ISSUE TITLE
Style Guide: Prevent the correct terms in Word and Phrase List from breaking across several lines

### ISSUE THREAD

**Issue by RichardJJG** [knative/docs#3840]
Some phrases in the Correct Term column break across several lines, such as "Knative Service". Breaking correct terms on to two lines is confusing.

**Comment by abrennan89** [comment]
Probably related to #3837 ?
cc @julz @evankanderson

**Comment by evankanderson** [comment]
We might need to use `&nbsp;` for the spaces to avoid breaks
