### ISSUE TITLE
Style Guide -- Define how we use admonitions

### ISSUE THREAD

**Issue by RichardJJG** [knative/docs#3847]
MkDocs supports many types of admonitions (info boxes): https://squidfunk.github.io/mkdocs-material/reference/admonitions/#supported-types

Specify in https://knative.dev/development/help/contributor/style-guide/style-and-formatting/

1. Which types we permit
2. The rules for using those types

**Comment by abrennan89** [comment]
@snneji @RichardJJG would either of you be able to work on this one?

**Comment by RichardJJG** [comment]
> @snneji @RichardJJG would either of you be able to work on this one?

Yep, and we've assigned this high priority.
