### ISSUE TITLE
BuildTemplate apiVersion/syntax/fields not explained

### ISSUE THREAD

**Issue by ahmetb** [knative/docs#386]
See https://github.com/knative/docs/blob/0310b0c07b3824d47bb8100f342d82e78b1f4079/build/builds.md which explains the `Build` object.

See https://github.com/knative/docs/blob/0310b0c07b3824d47bb8100f342d82e78b1f4079/build/build-templates.md which explains the `BuildTemplate` object.

The `BuildTemplate` one is lacking:

1. Important fields like `apiVersion` and `kind` (user should not guess these, even though we have the build-templates examples repo)
2. Field descriptions (e.g. `workingdir`)

About point #2 the docs say:

> The steps and volumes parameters are just like in a Build resource

however `workingdir` field is not documented in `Build` object documentation.

**Comment by RichieEscarez** [comment]
Thanks @ahmetb, will get around to filling out the config files in entirety for clarity/accuracy (in the templates topic) and also add links to the `workingdir` ref in [k8s](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.10/#container-v1-core).

**Comment by RichieEscarez** [comment]
Build to be deprecated
