### ISSUE TITLE
[AFTER GO LIVE] Change name of `mkdocs` to `main`, fix {{ branch }} to point to `main` instead of `mkdocs`

### ISSUE THREAD

**Issue by omerbensaadon** [knative/docs#3862]
Due to changes in #3860, we'll have to change this variable to point to the `main` branch instead of the `mkdocs` branch before we "go live" with the new version of the Knative site.

**Comment by julz** [comment]
think given we decided (in slack just now :)) to release from mkdocs and swap the branches some time after (since we have to wait till the old site is no longer up) we can pull this one out of blocks-release
