### ISSUE TITLE
Add status fields to reference page for event source docs

### ISSUE THREAD

**Issue by snneji** [knative/docs#3863]
Document the following for APIServerSource, SinkBinding, and ContainerSource:

- All status fields
- Any magic labels or annotations that apply.

This is a spin off from PR #3812

**Comment by abrennan89** [comment]
Hey @snneji - thanks for taking this on.
Is there a PR open for this that can be linked, or do you need any help from devs etc. to complete this?

**Comment by snneji** [comment]
Hi @abrennan89, I need to work out how to present this info. Will submit a PR soon.
