### ISSUE TITLE
Create new “Eventing concepts” section

### ISSUE THREAD

**Issue by abrennan89** [knative/docs#3866]

**Comment by snneji** [comment]
@abrennan89 Is there more info you can provide about this one? Could you add a description? Also we are not sure how high priority this is.

**Comment by abrennan89** [comment]
@snneji this was pulled out from #1923 - it used to be just a one line sub-task in a list, so this is all the information there ever was 🤷🏻‍♀️ I didn't request it originally, it came from something Richie asked for. Since it's quite generic though we can maybe just close it.

**Comment by snneji** [comment]
@abrennan89 sure, close it if you think it's OK.
