### ISSUE TITLE
Add ‘kn’ CLI to the Getting Started and append “with event delivery” to title

### ISSUE THREAD

**Issue by abrennan89** [knative/docs#3867]
Converted to issue from #1923 check list item
/assign @omerbensaadon 
I'll let you decide whether this one is required still Omer since it's part of the Getting Started

**Comment by omerbensaadon** [comment]
Thank you for splitting up that issue! 

I actually don't see this in the issue you've linked so IDK what this means 😅

**Comment by snneji** [comment]
@omerbensaadon @abrennan89 Does [this section](https://dev-knative.netlify.app/development/getting-started/install-knative-quickstart/#install-the-knative-cli) in the getting started guide cover this issue?

**Comment by omerbensaadon** [comment]
I would feel comfortable closing this

**Comment by snneji** [comment]
@abrennan89 Since Omer thinks this is OK to close, could you close this?
