### ISSUE TITLE
Build.spec.workingdir field is not documented

### ISSUE THREAD

**Issue by ahmetb** [knative/docs#387]
According to https://github.com/knative/docs/blob/0310b0c07b3824d47bb8100f342d82e78b1f4079/build/build-templates.md, the `steps[]` field accepts a field named `workingdir`.

However this is not documented at https://github.com/knative/docs/blob/0310b0c07b3824d47bb8100f342d82e78b1f4079/build/builds.md#syntax

(Off-topic, this field probably should be called `workingDir` or `workingDirectory` for API/naming consistency?)

**Comment by RichieEscarez** [comment]
Closing. Build to be deprecated.
