### ISSUE TITLE
Istio listed as a prerequisite on the knative with operators install page

### ISSUE THREAD

**Issue by AngeloDanducci** [knative/docs#3871]
**Describe the change you'd like to see**
Even though Istio is the current default I think it makes sense to mention the other networking layers [here](https://knative.dev/v0.22-docs/install/knative-with-operators/#prerequisites) as any should be able to satisfy as a networking layer prerequisite.

I can't find this exact text in the repo, appears to be [a nested md file that itself is generated somewhere else](https://github.com/knative/docs/blame/8ef708900f48c8ee56f4ab2456c7cb3ac3749147/docs/admin/install/knative-with-operators.md#L9)?

**Comment by nak3** [comment]
Thank you for the report!

The snippet is here [prerequisites.md](https://github.com/knative/docs/blob/mkdocs/docs/snippets/prerequisites.md) and the prerequisite of Istio was removed in the latest (`mkdoc`) branch.
So the doc from next release (v0.24) fixes the issue. Here is the preview of the doc - https://dev-knative.netlify.app/development/admin/install/knative-with-operators/#prerequisites

**Comment by omerbensaadon** [comment]
@AngeloDanducci Thanks for the issue! @nak3 thanks for the quick response. 

Closing this, let me know if there is further action needed :)

**Comment by omerbensaadon** [comment]
I've opened https://github.com/knative/docs/issues/3878 as a result of the confusion here, thanks for surfacing this!
