### ISSUE TITLE
Replace all **NOTE:** text in Channels subheading (/eventing/channels/*) to "info" Admonitions

### ISSUE THREAD

**Issue by omerbensaadon** [knative/docs#3879]
**Describe the change you'd like to see**
See title! 

Formatting 

```
!!! info 
<tab> <tab> {all text after "NOTE:" (delete "NOTE:")}
```

**Additional context**

**Comment by snneji** [comment]
These docs are currently located at this URL: https://dev-knative.netlify.app/development/eventing/channels/
