### ISSUE TITLE
Clean up yaml metadata

### ISSUE THREAD

**Issue by julz** [knative/docs#3882]
The YAML metadata was used by Hugo but isn't needed anymore since #3881 and should be cleaned up. Leaving this till after release out of an abundance of caution in case we end up needing to regenerate anything etc.

**Comment by abrennan89** [comment]
>Leaving this till after release

Which release? 😄

**Comment by julz** [comment]
> Which release? 😄 

Heh, well, at the risk of massively tempting fate (😬), I'd say the transition has gone pretty well and we're unlikely to want to move back anytime soon so.. probably good to remove them any time now
