### ISSUE TITLE
[mkdoc] Yaml URL misses prefix "v" and micro version in v0.23 page

### ISSUE THREAD

**Issue by nak3** [knative/docs#3885]
## Expected Behavior

The URL for yaml in installation page is not correct.

For example, https://dev-knative.netlify.app/docs/install/install-serving-with-yaml/#install-the-serving-component

### CURRENT
```
kubectl apply -f https://github.com/knative/serving/releases/download/0.23/serving-crds.yaml
```

### TOBE
```
kubectl apply -f https://github.com/knative/serving/releases/download/v0.23.0/serving-crds.yaml
```

## Actual Behavior

It seems the URL was defined by `artifact`:
https://github.com/knative/docs/blob/0435903a210b752879b12b3da5af2537895e6429/hack/macros.py#L20

and `{version}` causes the problem. So, most probably 0.24 page will experience the same issue.

## Steps to Reproduce the Problem

1. Go to https://dev-knative.netlify.app/docs/install/install-serving-with-yaml/#install-the-serving-component
1. Try `kubectl apply -f https://github.com/knative/serving/releases/download/0.23/serving-crds.yaml` in the page.
1. You will get 404 error.

**Comment by snneji** [comment]
/high
/assign @julz 
since you are working on this issue
