### ISSUE TITLE
Clean up Operator install docs in admin guide

### ISSUE THREAD

**Issue by abrennan89** [knative/docs#3890]
## Expected Behavior

Knative Serving is installed successfully by following the steps [here](https://knative.dev/development/admin/install/knative-with-operators/)

## Actual Behavior

- Istio requirement for default ingress is missing, should be part of prerequisites. Seems to have been removed at some point.
- Options for alternative ingresses are further down in the document, after KnativeServing CRD is already installed. These should be called out earlier since they're a dependency / specified as part of the CRD.

## Steps to Reproduce the Problem

1. Follow the documentation
1. Get an error when checking the CRD status, no additional information given to troubleshoot (questions were answered in Slack)

## Additional Info

**Install information:**
 - Platform (GKE, IKS, AKS, etc.): kind
 - Knative Version: latest

Related Slack conversation: https://knative.slack.com/archives/C0186KU7STW/p1625065727145300

**Comment by snneji** [comment]
I think some of the comments in #4480 might also be relevant
