### ISSUE TITLE
Add a favicon for the new site

### ISSUE THREAD

**Issue by abrennan89** [knative/docs#3892]
**Describe the change you'd like to see**
The old version of the site had a nice little Knative favicon which isn't there in the new version:
![image](https://user-images.githubusercontent.com/40172997/124017940-ebe22200-d9ac-11eb-9353-7051f3769652.png)

This looks pretty straightforward to add: https://squidfunk.github.io/mkdocs-material/setup/changing-the-logo-and-icons/#favicon

**Comment by julz** [comment]
Oh weird, we actually [are already setting that](https://github.com/knative/docs/blob/mkdocs/mkdocs.yml#L252), but I think the hacks we're doing to combine the old Hugo blog together with the new site broke it, should be a super easy fix though

**Comment by julz** [comment]
ha, no, even simpler: I forgot to copy it over when I reapplied the changes from my personal fork to the real repo 🤦
