### ISSUE TITLE
Run mkdocs in strict mode in a GitHub action

### ISSUE THREAD

**Issue by julz** [knative/docs#3899]
This would be a nice easy way to find out about broken links/formatting etc in PRs without breaking the real build or previews. There are currently 14 broken link warnings that will need fixing (via #3897) before we can do this.

Strict mode can be enabled via `mkdocs build --strict`, and will cause mkdocs to error on warnings (such as broken links, bad formatting, missing redirect targets).

/good-first-issue

**Comment by csantanapr** [comment]
This github action contains the recipe for the mkdocs dependencies https://github.com/knative/docs/blob/mkdocs/.github/workflows/knative-mkdocs.yaml
