### ISSUE TITLE
Add correct IBM Logo svg to the Knative site 

### ISSUE THREAD

**Issue by omerbensaadon** [knative/docs#3907]
## Expected Behavior
There should be a correct svg for IBM on the homepage

## Actual Behavior
I just yanked the IBM Cloud logo off the internet, I don't know if IBM wants their IBM logo or their Cloud logo? 

## Steps to Reproduce the Problem

1. Visit the homepage 
1. Go to "Trusted By"

**Comment by maximilien** [comment]
On it @omerbensaadon… remember this week and part of next are vacation so still waiting on response. The one from Web site should be OK for now. Thanks.

**Comment by omerbensaadon** [comment]
@maximilien ah gotcha, no problem!

**Comment by maximilien** [comment]
OK @omerbensaadon and team, I have the logos. Bunch so not sure which works for your needs. How do you want me to share? PR? Attachment here? Slack? Email? Let me know. Best.

**Comment by omerbensaadon** [comment]
Drop em here and let us know which one you prefer!

SVG is ideal :)

**Comment by maximilien** [comment]
GH won't accept anything but JPG or GIF so assume these are OK. I also have EPS that I could upload and share somewhere else and link here. Hope this works.

![ibm2](https://user-images.githubusercontent.com/39187/124669330-12013980-de67-11eb-9a5d-d4f9ebe079f5.jpg)
![ibmneg_blurgb](https://user-images.githubusercontent.com/39187/124669332-1299d000-de67-11eb-8132-ca4ef64af9ba.jpg)
![ibmneg_white](https://user-images.githubusercontent.com/39187/124669334-13326680-de67-11eb-84f5-92eecf09f78a.jpg)
![ibmpos_black](https://user-images.githubusercontent.com/39187/124669335-13cafd00-de67-11eb-912b-e1ff1769cac6.jpg)
![ibmpos_blurgb](https://user-images.githubusercontent.com/39187/124669337-13cafd00-de67-11eb-8605-ee1ffa6d71aa.jpg)

**Comment by omerbensaadon** [comment]
Sorry for the bother, can you email an SVG to ***@***.***

**Comment by omerbensaadon** [comment]
My github handle @ gmail ^
