### ISSUE TITLE
[SPIKE] Investigate what needs to be rewtitten or moved from "Help" Section (knative.dev/help)

### ISSUE THREAD

**Issue by omerbensaadon** [knative/docs#3908]
Currently, there is a massive amount of support documentation at http://knative.dev/help. 

Not all of it is strictly necessary. 

Acceptance of this issue would simply require a ToDo list of things to move over or rewrite.

**Comment by xtreme-sameer-vohra** [comment]
Tree at https://knative.dev/help/
- [ ] Contributor guides
  - [ ] Join
  - [ ] New docs
    - [ ] Docs template
    - [ ] _index.md template
  - [ ] New blog post
    - [ ] Blog template
  - [ ] How-tos
    - [ ] Using GitHub
    - [ ] Content structure
    - [ ] Front matter
    - [ ] Style guide
    - [ ] Formatting standards
    - [ ] Shortcodes
    - [ ] Code samples
  - [ ] Preview Website
- [ ] Maintainer guides
  - [ ] Release process
  - [ ] Generating API docs
  - [ ] Repo maintenance
- [ ] FAQs

**Comment by xtreme-sameer-vohra** [comment]
@omerbensaadon lmk if ☝️ is sufficient

**Comment by omerbensaadon** [comment]
@xtreme-sameer-vohra awesome thank you for this!! 

Going to close this and open a new issue for this :)
