### ISSUE TITLE
[GO LIVE] Make knative.dev point to the `mkdocs` branch

### ISSUE THREAD

**Issue by omerbensaadon** [knative/docs#3911]
**Describe the change you'd like to see**
When I visit knative.dev I should see the new site not the old one! 

**Additional context**
N/A

**Comment by csantanapr** [comment]
To go live edit the netlify config for "knative.dev", go to Deploy Settings and change 3 things.
1. Set git repository to github.com/knative/docs
2. Unset build script (the build script is specify in netfliy config file `netlify.toml`
3. Set branch to mkdocs
![image](https://user-images.githubusercontent.com/1094878/124641496-c6e22900-de5c-11eb-8469-351fbd953beb.png)

**Comment by omerbensaadon** [comment]
thank you @csantanapr!!

**Comment by omerbensaadon** [comment]
WOOOO DONE
