### ISSUE TITLE
Buncha broken links

### ISSUE THREAD

**Issue by benmoss** [knative/docs#3926]
https://github.com/benmoss/docs/runs/2975487385?check_suite_focus=true has a bunch of broken links, need to comb through those and fix em

/assign
/kind bug cleanup

**Comment by benmoss** [comment]
Not exactly, the PR action only fails if a file that's being changed has broken links

**Comment by julz** [comment]
Hmm. But this does mean if anyone edits a file that happens to contain an existing broken link they have to fix up the whole file or they'll get an error they didn't introduce right?

**Comment by julz** [comment]
Looking at some of these broken links, I think they may unfortunately be reporting bad links that are valid mkdocs syntax, e.g. `[✖] ../../../../serving/using-a-custom-domain` (and a few others). There are currently actually only 3 _real_ broken internal links in the build, based on #3931 and many more than that being reported here..

**Comment by benmoss** [comment]
I think you might be wrong, https://dev-knative.netlify.app/development/serving/getting-started-knative-app/ has a broken link to "using a custom domain"

**Comment by julz** [comment]
hmm I don't think that file is actually in the nav at all, it looks like an old page that never got deleted but is still being built

**Comment by julz** [comment]
(you'll notice it doesn't have a sidebar on the left, and is not in nav.yml)

**Comment by benmoss** [comment]
i'm afraid it's beyond my pay grade to know how to deal with broken links in dead documentation that is still being rendered on the docs site

**Comment by julz** [comment]
Having said that https://dev-knative.netlify.app/development/serving/using-subroutes/ does indeed have a broken link, and I think I know why. I think what's happening here is #3399 broke redirects :( Which means some links that were relying on redirects to work, don't. The link to private routes [should have been redirected]( https://github.com/knative/docs/blob/mkdocs/config/redirects.yml#L74), but was not. Unfortunately I _do_ think this is a problem: when we fix it so redirects in redirects.yml work those links will be valid..

**Comment by julz** [comment]
oops wrong link, I mean #3928

**Comment by benmoss** [comment]
hmm, i tested one redirect and it worked, let me see

**Comment by benmoss** [comment]
yeah it seems broken now too, it must have been because i was relying on mkdocs serve which still was serving with old configuration

**Comment by benmoss** [comment]
hmm i'm bisecting and that link appears broken before the config change was made :/

**Comment by julz** [comment]
you're right - that link _was and is_ broken -- looks like the mkdocs link check doesn't complain about links that dont link to the markdown file but instead to the directory, that's a pain
