### ISSUE TITLE
Automatically create a GitHub issue for reviewing an engineer's merged PR

### ISSUE THREAD

**Issue by RichardJJG** [knative/docs#3942]
**Describe the change you'd like to see**
When an engineer's PR is merged, a GitHub issue is automatically created with the title "Review [name of PR]" and with a link to the PR in the issue's description.

**Additional context**
https://knative.slack.com/archives/C9CV04DNJ/p1625480959205300

TL;DR we want to lower the bar to /lgtm engineers' PRs ("Does this PR break anything? No? Then we'll merge it.") but of course we still want to edit the merged changes thoroughly. 

Creating such "review" issues automatically will keep these merged-but-imperfect changes from going unnoticed.

**Comment by snneji** [comment]
@RichardJJG do you think we should mention that this is a style review - just to make it clear (to new users) that the review is not for technical information. Maybe mention in the issue title eg "Style review <PR-#>" or make sure the automation adds the style label?

**Comment by abrennan89** [comment]
@evankanderson could you or do you know anyone who could help with automation for this?

**Comment by evankanderson** [comment]
Should this be a reference to PR ##, or a reference to the new/substantially changed pages?

What's the criteria for "submitted by an engineer"? Is this an allowlist of people whose PRs don't trigger this behavior, a `/command`, or something else?

Any thoughts on what constitutes a "substantial" change that might be worth review? Markdown pages with at least 40% changed content?

Once we know the answers to the above, we should be able to write a post-submit action that can do this (assuming we can figure out the permissions).

**Comment by RichardJJG** [comment]
@evankanderson 
>Should this be a reference to PR ##, or a reference to the new/substantially changed pages?
The PR -- it's not efficient to review an entire page when the PR only changes, say, a short paragraph.

>What's the criteria for "submitted by an engineer"? Is this an allowlist of people whose PRs don't trigger this behavior, a /command, or something else?
I like the allowlist idea. It's automatic and the list would be short, unambiguous, and easily updated.

**Comment by abrennan89** [comment]
>The PR -- we want the issue to point explicitly to the changes that need review.

+1

>I like the allowlist idea. The reviews would be generated automatically and the list would be short, unambiguous, and easily updated (currently me, Samia, Ashleigh, and Maxim Svistunov).

I think it could just be me, you and Samia for now until Max starts really contributing to the project.

>I don't want such a barrier. Sure, some Style Review issues will be generated for tiny changes that don't require a second look, but that's better than anything falling through the cracks.

+1 - I would rather we just open issues to review everything than miss a paragraph of text getting a review because it was just shy of the mark for triggering this. It's no harm to just close issues for smaller changes that don't need a review.

**Comment by snneji** [comment]
I think the requirements mentioned in the comments so far are good enough to get this going. We can test the automation for a while and make changes if necessary if there are things we don't like about how it works.

**Comment by snneji** [comment]
Do we still want to do this?

**Comment by abrennan89** [comment]
I'd love to but I'm not sure how. @evankanderson did you still want to help with this one?
