### ISSUE TITLE
Move "help" section over to `mkdocs`

### ISSUE THREAD

**Issue by omerbensaadon** [knative/docs#3943]
As part of #3908 @xtreme-sameer-vohra did a cursory look through the help section to see what was needed to complete for the new site. 

---

## Legend
- Move over: The page should be moved to the new site
- Re-write: The page has Hugo references and needs to be updated for the new site
- Assess: Needs an assessment with someone with more knowledge of the website than myself 😁 

## Tree at https://knative.dev/help/
- [x] Contributor guides
  - [] Join -> Move over
  - [ ] New docs -> Move over
    - [x] Docs template  -> Re-write for Mkdocs
    - [ ] _index.md template -> Re-write for Mkdocs
  - [x] New blog post -> Move over
    - [x] Blog template -> Re-write for Mkdocs
  - [ ] How-tos
    - [x] Using GitHub -> Move over
    - [ ] Content structure -> Re-write if our process for docs versioning is different with the new site OR Move over
    - [x] Front matter -> Re-write for Mkdocs
    - [x] ~~Style guide~~  -> Already present on [Voice & Lang](https://dev-knative.netlify.app/development/help/contributor/style-guide/voice-and-language/) &  [Formatting Standards](https://dev-knative.netlify.app/development/help/contributor/style-guide/style-and-formatting/)
    - [x] Formatting standards -> Merge with [new formatting guide](https://dev-knative.netlify.app/development/help/contributor/style-guide/style-and-formatting/)
    - [ ] Shortcodes -> Assess if applicable to Mkdocs
    - [x] Code samples -> Move over
  - [x] ~~Preview Website~~ -> Already present on [Mkdocs Contributor Guide](https://dev-knative.netlify.app/development/help/contributor/mkdocs-contributor-guide/)
- [ ] Maintainer guides
  - [ ] Release process -> Move over
  - [ ] Generating API docs -> Move over
  - [ ] Repo maintenance -> Re-write for Mkdocs
- [ ] FAQs -> Move over

**Comment by abrennan89** [comment]
@snneji @xtreme-sameer-vohra is there any work left to do for this one?
I think it would be nice to get all the mkdocs migration stuff finished entirely so we can go back to focusing on docs content.

**Comment by xtreme-sameer-vohra** [comment]
> @snneji @xtreme-sameer-vohra is there any work left to do for this one? I think it would be nice to get all the mkdocs migration stuff finished entirely so we can go back to focusing on docs content.

Hey @abrennan89 
https://knative.dev/help/  is a 404 now and my memory is a bit fuzzy since it has been so long so I'd defer to you both. 
This issue was auditing the old site and seeing whats missing in the current site. From a quick glance and assuming the new help page is https://knative.dev/docs/help/contributor/, I don't see the FAQ or Maintainer guides sections present.

**Comment by snneji** [comment]
I think we have done most of these tasks. I've just submitted https://github.com/knative/docs/pull/4544 to move the contributor guides from Hugo to MkDocs. That's the last thing we currently plan to move over to the website.

I'm not sure how much of the maintainer guides (https://github.com/knative/docs/tree/main/help/maintainer) need to be updated for MkDocs. These files document the release process for the website. They are not relevant to general users and so will remain in GitHub only. 

I think it's OK to close this one.
