### ISSUE TITLE
[mkdocs] Knative logo area behaves odly

### ISSUE THREAD

**Issue by cardil** [knative/docs#3945]
Hovering over the Knative logo shouldn't cause it to fade out. Fading out logo is sending the signal that clicking it isn't available. That may cause confusion among the users. If we want to keep the effect, it should be subtle, not drastic.

Also, the Knative text next to the logo isn't clickable. That's a standard thing to make it clickable, so users use it to return to the homepage.

https://user-images.githubusercontent.com/540893/124590584-964dbf80-de5b-11eb-83ca-7b0fe1b47234.mp4

## Expected Behavior
Knative logo hover effect is removed or tuned down to be subtle. Knative text next to the logo is linked the same way as logo.

## Actual Behavior
Knative logo is fading out drastically, and Knative text next to it isn't clickable.

## Steps to Reproduce the Problem

1. Visit upcoming site at https://dev-knative.netlify.app/development/ or any subpage
1. Hover the mouse on Knative logo in the header
1. Try clicking Knative next to the knative logo

## Additional Info
/kind mkdocs

**Comment by cardil** [comment]
Maybe instead of fading out, we case animate a little rotation on hover. Like this?

https://user-images.githubusercontent.com/540893/124592905-47555980-de5e-11eb-897c-41ea2ccb0df7.mp4

**Comment by omerbensaadon** [comment]
@cardil yes yes yes x100, that is so much cooler. If you've got this locally, can you ship this before tomorrow?

**Comment by cardil** [comment]
Yes, I can.

/assign
