### ISSUE TITLE
Update blue/green deployment example with `kn` usage

### ISSUE THREAD

**Issue by rhuss** [knative/docs#3951]
The blue-green deployment examples in `developer/serving/traffic-management.md` uses `kubectl` and direct manipulation of `Route` elements. This use case/sample is covered by `kn` directly to provide a much more streamlined user experience. We should refactor the sample to us `kn` without confusing people with the internal implementation details.

@navidshaikh @dsimansk Could we already do a Blue Green deployment as described in this sample with `kn` or do we need some changes in `kn` ? Ideally we should be able to implement this sample with as less `kn` commands as needed (i.e. for each step in the blue green deployment one command, that should be not too hard to memorize)

**Comment by rhuss** [comment]
Related PR: https://github.com/knative/docs/pull/3825

**Comment by abrennan89** [comment]
Fixed in https://github.com/knative/docs/pull/3825/files#diff-1a8e531397364eff3d8858cb05dd280f845c135d5da46faa8e9008634b874cc1R70

Let's open a different issue if the behavior of traffic management needs an update later
