### ISSUE TITLE
Align `/admin/install/knative-with-operators` to Style Guide (`/help/contributor/style-guide/`)

### ISSUE THREAD

**Issue by omerbensaadon** [knative/docs#3956]
@snneji has already commented on what needs to change on the original PR here: https://github.com/knative/docs/pull/3891

**Comment by snneji** [comment]
Can be dealt with as part of https://github.com/knative/docs/issues/3813

**Comment by snneji** [comment]
@omerbensaadon could you close this. I'm fixing this topic in a PR for #3813.

**Comment by snneji** [comment]
Closing as this will be fixed as part of #3813.
