### ISSUE TITLE
Tear down `https://dev-knative.netlify.app/`

### ISSUE THREAD

**Issue by omerbensaadon** [knative/docs#3977]
We don't need this site anymore since we launched the new knative.dev

**Comment by omerbensaadon** [comment]
/assign @RichieEscarez 

Richie, I actually can't delete this as I am not an owner. Do you mind tearing it down in Netlify?

**Comment by RichieEscarez** [comment]
I think Carlos made those changes?

**Comment by omerbensaadon** [comment]
I just can’t delete it because I am not an owner, neither is Carlos…

**Comment by RichieEscarez** [comment]
Gotcha, thanks for explaining. Ill delete it now.
