### ISSUE TITLE
Rename homepage to `Home` instead of `Knative`

### ISSUE THREAD

**Issue by omerbensaadon** [knative/docs#3982]
<img width="1084" alt="Screen Shot 2021-07-08 at 2 39 58 PM" src="https://user-images.githubusercontent.com/16281246/124974151-76a0cd80-dffa-11eb-9001-e5d289e21fb7.png">

Knative - Knative looks a bit weird

**Comment by omerbensaadon** [comment]
I actually can't find where this name is set

**Comment by julz** [comment]
I think https://github.com/knative/docs/blob/mkdocs/docs/index.md probably
