### ISSUE TITLE
Style Guide: Add rollout and time-based to the word list for docs contributors

### ISSUE THREAD

**Issue by abrennan89** [knative/docs#3997]
Add "rollout" (not roll-out) and "time-based" (not time based) to the word list.
Follow up from #3990

**Comment by soham283** [comment]
@abrennan89 I would like to work on this issue,
can you please give the example where the changes are supposed to be done ?

**Comment by abrennan89** [comment]
Hi @soham283 , thank you!
You can find the word list here: https://knative.dev/docs/help/contributor/style-guide/word-and-phrase-list/

**Comment by abrennan89** [comment]
Hi @soham283 - do you still plan to work on this issue?
Let me know if you're stuck or need help. Thanks.

**Comment by soham283** [comment]
@abrennan89 , @snneji can you please review #4313 ?
Revert if any changes needed 
(Sorry for submitting late PR)
