### ISSUE TITLE
Broken link on Kubernetes services page

### ISSUE THREAD

**Issue by psschwei** [knative/docs#4013]
I noticed a broken link on one of the docs pages. It's the link to code samples in the "What's Next" section on the Kubernetes services page: https://knative.dev/docs/serving/knative-kubernetes-services/

When clicked, the link gives a 404. It appears that the link is incorrect (it goes to https://knative.dev/docs/serving/knative-kubernetes-services/samples/ but really should be https://knative.dev/docs/serving/samples/, i.e. without the `knative-kubernetes-services` part).

Though when I checked the source, the link actually redirects back to the `samples/` directory, which I assume is what is supposed to happen. Don't have a build environment for the docs set up, so wasn't able to dig into it any further...

**Comment by snneji** [comment]
I think it would be nice to also improve the link text in that section. They should be more descriptive than "here".
