### ISSUE TITLE
Style Guide: Document how to use feature state shortcodes

### ISSUE THREAD

**Issue by RichardJJG** [knative/docs#4022]
This [Slack thread](https://knative.slack.com/archives/C9CV04DNJ/p1623911093061800) explains why we should probably bring back feature state shortcodes at some point.

If we do, we need to document how to use them in the style guide and/or the doc templates.

**Comment by julz** [comment]
We did this in https://github.com/knative/docs/pull/3913 so maybe this issue is just about adding them to style guide
