### ISSUE TITLE
Bazel commands in logging plugin setup

### ISSUE THREAD

**Issue by RichieEscarez** [knative/docs#403]
In the "Setting up a logging plugin" topic, there are bazel commands without context. 
https://github.com/knative/docs/blob/master/serving/setting-up-a-logging-plugin.md

Are you required to install and use bazel in these steps?

`# In case there is no change with the controller code`
**`bazel run config:controller.delete`**
`# Deploy the configuration for sidecar`
`kubectl apply --filename config/config-observability.yaml`
`# Deploy the controller to make configuration for sidecar take effect`
**`bazel run config:controller.apply`**

I found this commit, which removed bazel commands from knative/serving: https://github.com/knative/docs/commit/3840c7a74cf89e02bf9d4654b889fe76c895814b

Can these bazel commands just be removed too or do you need to replace these steps with other commands?

/assign @yanweiguo
-->

**Comment by yanweiguo** [comment]
It can be replaced with other commands. I'll update it. Thanks for finding these out-of-date commands.

**Comment by mattmoor** [comment]
Thanks, @yanweiguo !
