### ISSUE TITLE
Broken link to "Knative contributor's guide" on knative/doc page

### ISSUE THREAD

**Issue by kimikuri** [knative/docs#4032]
## Expected Behavior
When I clicked the link to "Knative contributor's guide" in the "Get Started" section on https://github.com/knative/docs/,  https://github.com/knative/docs/blob/mkdocs/docs/help/contributor/README.md should be shown. 

## Actual Behavior
The link gives a 404 (broken link). 

## Steps to Reproduce the Problem
1. Click the link to "Knative contributor's guide" in the "Get Started" section on https://github.com/knative/docs/

## Additional Info
I think that it should be https://github.com/knative/docs/blob/mkdocs/docs/help/contributor/README.md.  
If I'm correct, I will make the pull request about this issue.

**Comment by nak3** [comment]
> I think that it should be https://github.com/knative/docs/blob/mkdocs/docs/help/contributor/README.md.
> If I'm correct, I will make the pull request about this issue.

I think it makes sense. But let's double-check with @RichardJJG or somebody. 
@RichardJJG Do you have any thoughts?

**Comment by RichardJJG** [comment]
Fixing now -- thank you, @kimikuri and @nak3!

**Comment by RichardJJG** [comment]
Fixed through https://github.com/knative/docs/pull/4049
