### ISSUE TITLE
Style Guide: Establish standard for link paths

### ISSUE THREAD

**Issue by RichardJJG** [knative/docs#4033]
A standard for writing link paths would help:
1. Keep the link checker bot happy.
2. Reduce likelihood of errors (yes, link checker can catch them, but they still slow us down)
3. Reduce cognitive load (it's easier to follow a standard than make a judgement call every time)

Add the following to the style guide:
* .md should be in every internal link
* we should link to files, not folders: `[Kafka Broker](../kafka-broker/README.md)` instead of `[Kafka Broker](../kafka-broker)`
* links are case-sensitive: link to `README.md`, not `readme.md`
* links should be Markdown, not HTML (tip: if you want links to open in a new window, you can use the following markdown `[link](../blah/README.md){target=_blank}`)

I've put this issue on the agenda for the DUX working group meeting on 27 July, 2021.

**Comment by snneji** [comment]
Apparently linking to folders causes issues with the link checker. I vote that we should link to the `README.md` file.

**Comment by RichardJJG** [comment]
> Apparently linking to folders causes issues with the link checker. I vote that we should link to the `README.md` file.

Confusingly, though, I find that putting the readme in the URL doesn't work. 
For example, https://knative.dev/docs/eventing/readme.md gives a 404 whereas https://knative.dev/docs/eventing/ works fine.

Do you know the cause for this oddity, @julz?

**Comment by julz** [comment]
I think it's just how static html websites work: the way directory-based URLs (i.e. `/eventing/`) are made is that when you access `/eventing/` the web server gives you`/eventing/index.html` (because obviously a directory itself isn't a file that can be shown). People tend to use the `/foo/` version of a link to not expose the details of the filename (e.g. so if you used `index.php` one day the links wouldn't change. Mkdocs converts both README.md and index.md into index.html when it builds the site, so that's why index happens to work in the URL (although that should ~never be a fact a user of the site, or a writer of the docs, cares about or sees)

**Comment by RichardJJG** [comment]
Thanks, @julz. The solution, then, is https://knative.dev/docs/eventing/index.html ?

That works and it satisfies link checker bot's demand to link only to files with extensions. (I'm guessing the link checker doesn't care specifically about `.md`, just that there's a valid extension.)

It also works when the file is named readme and not index: https://knative.dev/docs/index.html

**Comment by julz** [comment]
Sorry, no, Im being unclear. The link checker requires you to link to the _source_ file (that's why it requires an extension - not because it just likes extensions, because it looks at the source). Linking to directories, and linking to index, work because those URLs happen to be what the source files (ie the .md files) are built in to in the final output website, but the link checker can't easily check them, because it runs during the build, not after it. Basically, link to the *actual .md file on the actual disk*, the same file you would open in an editor (or on GitHub) to edit the page :).

**Comment by RichardJJG** [comment]
@julz, ah, okay, so the rule would be to include .md in every path EXCEPT for index and readme files (for which you just write `index` without an extension)?

https://knative.dev/docs/<some-folder>/index
https://knative.dev/docs/<some-folder>/<some-file-that-is-not-index-or-readme>.md

As best I can tell this is the only standard for creating link paths that
a) works
b) appeases the link checker

**Comment by julz** [comment]
No I think the rule should always be to link to the .md file. In absolutely every case. Is there an example of one that doesn't work this way?

**Comment by RichardJJG** [comment]
> No I think the rule should always be to link to the .md file. In absolutely every case. Is there an example of one that doesn't work this way?

Yes: https://knative.dev/docs/eventing/index.md

**Comment by julz** [comment]
To be clear you shouldn't ever add "knative.dev" since that will break PR previews when the site is built to a different url. Just link to the md file with a relative link.

**Comment by julz** [comment]
Can you show me the source link to that that doesn't work when you try to link to the md page?

**Comment by julz** [comment]
Oh wait in the example the link should be to README.md because that's what the page is (https://github.com/knative/docs/blob/mkdocs/docs/eventing/README.md), so `[foo](./README.md)`.

**Comment by RichardJJG** [comment]
> Oh wait in the example the link should be to README.md because that's what the page is (https://github.com/knative/docs/blob/mkdocs/docs/eventing/README.md), so `[foo](./README.md)`.

True, but https://knative.dev/docs/eventing/readme.md doesn't work either. That said, you might have pointed out the problem with `https://knative.dev`. I'm going to try with a relative link in staging.

**Comment by julz** [comment]
Yeah just use a relative link to the readme.md, it'll be converted to the right link (ie the directory) in the build.

**Comment by RichardJJG** [comment]
**Learn more about Knative Eventing and Eventing Sources.** in https://knative.dev/docs/eventing/samples/ does seem to work, thanks, yeah.

When I make my own relative link to a readme.md file in staging it doesn't work, though, which is why I've been getting so confused. From what you're saying, though, I guess that's to be expected because of the whole site-loading business.

Ideally everything should function in staging just as it would live, but in reality relative links in staging are liable to be faulty because the site hasn't been fully built yet...? Am I on the right lines?

**Comment by julz** [comment]
I'm not really sure what you mean by "staging" tbh. It should all just work. Can you give me an example of a source code link (in a markdown page, on a branch) that doesn't work, and exactly the circumstances in which it doesn't work?

**Comment by RichardJJG** [comment]
Ah, my trial link works now -- nevermind. That's strange. Maybe the site was just slow to load -- it loaded the link text but not the link functionality...? Thanks again for clarifying all this, @julz -- the standard really should be just to link to the specific file and extension. I can see now that that should be fine in all cases.

**Comment by snneji** [comment]
Just incase it wasn't mentioned here, I've found that the link to `README.md` is case sensitive. If you use lowercase `readme.md`, it won't work. Uppercase `README.md` works fine (unless you have other things wrong with your link, such as using the wrong folder structure at the beginning).
