### ISSUE TITLE
gcloud-project-ID should be used for KO_DOCKER_REPO environment setup

### ISSUE THREAD

**Issue by arvtiwar** [knative/docs#404]
## Expected Behavior
In https://github.com/knative/serving/blob/master/DEVELOPMENT.md#environment-setup page
KO_DOCKER_REPO is set to 'gcr.io/my-gcloud-project-name' (export KO_DOCKER_REPO='gcr.io/my-gcloud-project-name') which create issues while applying the build from KO. IT should be set to  "gcr.io/my-gcloud-project-ID"

Note: "this documentation bug"
## Actual Behavior

KO_DOCKER_REPO is set to 'gcr.io/my-gcloud-project-name'

## Steps to Reproduce the Problem
Just build the serving and "ko apply" while will produce below error

2018/09/20 16:20:59 error processing import paths in “config/webhook.yaml”: no token in bearer response:
{“errors”:[{“code”:“DENIED”,“message”:“Token exchange failed for project ‘pknative’. Please enable Google Container Registry API in Cloud Console at https://console.cloud.google.com/apis/api/containerregistry.googleapis.com/overview?project=pknative before performing this operation.“}]}

**Comment by RichieEscarez** [comment]
GCP project "name" and "ID" are different values but wondering if thats the cause since the error indicates that the API is disabled?

**Comment by arvtiwar** [comment]
The way I see is, when you use the project-name it won't find any container registry, hence says API is disabled.
I would suggest someone should validate

**Comment by RichieEscarez** [comment]
If that is the case, then the error message should be improved to clarify the real cause. 

I'm curious if you actually have another project with name "pknative"? If not, Im wondering why this error instead does not say that the project name does not exist?

**Comment by mattmoor** [comment]
We should update `export KO_DOCKER_REPO='gcr.io/my-gcloud-project-name'` to use `id` vs. `name`.

We should probably also clarify that this is: `gcloud config get-value project`.

@arvtiwar Up for a PR?
