### ISSUE TITLE
Add note for developer installation instructions

### ISSUE THREAD

**Issue by trisberg** [knative/docs#4050]
**Describe the change you'd like to see**

I think there should be additional notice on the Getting started page for more advanced developer installations pointing to the Administration pages.

**Additional context**

I was used to using the instructions for the YAML install in the old docs. With the new layout I had a hard time finding them in the Administration section. Since I'm a developer, I only looked at getting started and developer pages.

**Comment by abrennan89** [comment]
There is actually an existing note on the first page that links to the admin guide: https://knative.dev/docs/getting-started/#before-you-begin

Our structure might not be clear enough at the minute overall; we are revisiting whether having the admin vs dev guides is a good idea and will be looking into better structures soon.
