### ISSUE TITLE
Wrong version for strimzi-kafka-operator

### ISSUE THREAD

**Issue by xinydev** [knative/docs#4058]
## Expected Behavior

https://knative.dev/docs/eventing/samples/kafka/

There is no `apiVersion: kafka.strimzi.io/v1beta2` in strimzi-kafka-operator(0.16.2) 

strimzi spi: 
https://github.com/strimzi/strimzi-kafka-operator/blob/5ccb3a88f7060a27d579d299f520639a7be81a37/api/src/main/java/io/strimzi/api/kafka/model/Kafka.java#L33-L52

We need upgrade to  0.20.0+(at least) for strimzi-kafka-operator for using `v1beta2`

## Steps to Reproduce the Problem

1. https://knative.dev/docs/eventing/samples/kafka/
## Additional Info
**Additional context**

**Install information:**
 - Platform (GKE, IKS, AKS, etc.):
 - Knative Version: 0.24

**Comment by abrennan89** [comment]
Is this covered by https://github.com/knative/docs/pull/4028 already?
I think it's better to point out to upstream Strimzi docs rather than have to keep maintaining our own separate install docs for it.

**Comment by xinydev** [comment]
> Is this covered by #4028 already?
> I think it's better to point out to upstream Strimzi docs rather than have to keep maintaining our own separate install docs for it.

Thanks!
/close
