### ISSUE TITLE
Update the help/maintainer files 

### ISSUE THREAD

**Issue by RichardJJG** [knative/docs#4062]
1. Update the `help/maintainer` files (some content likely still applies, but the Hugo stuff, of course, doesn't).
1. Move the folder to within `docs/help/`.
1. Delete the old, and now empty, `help` folder.

**Comment by snneji** [comment]
I think there's some Hugo related stuff in `docs-release-process.md` and `docs-repo-maintanence.md`. This should be cleaned up, so yes to step 1. 

Not sure whether we need to move this info inside the docs folder though (ie steps 2 & 3). This info looks like it is specifically to help people to do releases so not many people will need to look at it.
