### ISSUE TITLE
Suggested improvements to the Getting Started

### ISSUE THREAD

**Issue by ReggieCarey** [knative/docs#4067]
The Knative getting started documentation seems to be fixated on installing kubernetes using one method or another.  It would be nice to have that in a prerequisites section.  Getting knative installed on an existing K8s is probably more valuable to readers without the k8s installation tool specifics. Ideally, installation via kubectl or helm or via an operator as provided on operatorhub.io.

Knative is a great product.

**Additional context**

**Comment by omerbensaadon** [comment]
Thank you for your deedback @ReggieCarey! 

This sounds like two separate issues... 

#1 Having an easy way to "Get Started" w/ Knative which isn't dependent on KinD

#2 Having completed install instructions for kn on Linux, instead of redirecting to release pages. (@psschwei I think has already done this or was going to...?) 

I'll open an issue for #2, have I characterized #1 correctly?

**Comment by psschwei** [comment]
>     2. Having completed install instructions for kn on Linux, instead of redirecting to release pages. (@psschwei I think has already done this or was going to...?)

I don't believe I've touched the "Install `kn`" section of the docs in anything I've done. Perhaps we could link to the [client docs](https://github.com/knative/client/blob/main/docs/README.md#installing-kn) or maybe even update the Client release page to include a link to the install instructions?

>     1. Having an easy way to "Get Started" w/ Knative which isn't dependent on KinD
>  Ideally, installation via kubectl or helm or via an operator as provided on operatorhub.io.

I believe the first/third options are provided in the [administrator "Installing Knative" guide](https://knative.dev/docs/admin/install/) for users who want to install on [A/E/G/I]KS or a bespoke cluster. 

Thinking out loud here, but it might be a good idea to add a brief summary before the "Before you begin" section about what the goal of the quickstart process is -- to spin up a local Knative cluster for developers to experiment with. Then a link to other install methods (i.e. the admin guide) if this doesn't fit your use case. (To be fair, I think this is the goal of the warning about experimentation vs. production, but I could see how one might be confused if they just wanted to install on a hosted cluster to experiment with Knative...)

**Comment by abrennan89** [comment]
@omerbensaadon are you still working on this one?

**Comment by omerbensaadon** [comment]
I'm not convinced there's an action here... I'd be ok to close it
