### ISSUE TITLE
[EPIC] Work on snippets infrastructure

### ISSUE THREAD

**Issue by abrennan89** [knative/docs#4069]
TO DO:

- [x] #3769 
- [x] #4556
    -  Eg [offset functionality](https://github.com/cmacmackin/markdown-include#configuration) so that snippets can be included at the correct heading level in different places.
- [ ] #4557
- [ ] #4558
- [ ] QUESTION: Is a generic snippets folder the best way to store these, or should we have snippets organized by topic to make them easier to find?

This is just a brain dump for now, we can split these into individual issues in the epic as we assign / work on them.

Setting this as critical priority for the following reasons:

- It would save us massive amounts of duplication in docs if we get our snippets properly in order.
- Somewhat prevents reorg of content not having this ironed out, e.g. what when something needs to be included in both admin and dev guides? If we want to get rid of the serving and eventing sections, we need this soon.
- The longer we take to do this, the more cleanup there will be to do from folks adding duplicate / additional content that should be part of a snippet.

**Comment by snneji** [comment]
@abrennan89 Has there been a decision on which snippets plugin we want to use? If so can we close https://github.com/knative/docs/issues/3769?

**Comment by snneji** [comment]
Hi @abrennan89, I would like to create the issues for this epic. Are you happy for me to create issues from the TO DO list?
Is there anything else you would want added?

**Comment by abrennan89** [comment]
@snneji I think that's fine to go ahead with, thanks

**Comment by abrennan89** [comment]
Work to move sections to snippets is ongoing. I don't think this epic is required anymore.
