### ISSUE TITLE
Style Guide: add to word list avoiding "should"

### ISSUE THREAD

**Issue by snneji** [knative/docs#4079]
Add to the [Knative Word and Phrase list](https://knative.dev/development/help/contributor/style-guide/word-and-phrase-list/) to avoid using "should" in documentation.

**Comment by sankalp-r** [comment]
@snneji I would like to work on this.

**Comment by snneji** [comment]
Hi @sankalp-r! Sorry I missed your message. Do you still want to work on this one?

**Comment by sankalp-r** [comment]
@snneji Yes, I am still interested to work.

Correct Term: shall
Incorrect Term: should
Notes: Use "shall" if some requirement is mandatory.

@snneji Is this fine?

**Comment by RichardJJG** [comment]
@sankalp-r, it's simply best to avoid "should" as far as possible. 

We can copy the [Google Style rule](https://developers.google.com/style/word-list#letter-s) but be less verbose about it.
