### ISSUE TITLE
Apply new style rule

### ISSUE THREAD

**Issue by snneji** [knative/docs#4087]
The [Knative word and phrase list](https://knative.dev/development/help/contributor/style-guide/word-and-phrase-list/) has a new rule to avoid using "below" and "above" to refer to a position in the docs. 

Search the Knative docs for uses of these words and replace "below" with "following" or "later", and "above" with "earlier" or "preceding".

**Comment by RichardJJG** [comment]
Oh, sorry, I completely missed that you were assigned to this, @snneji. I wasn't trying to usurp you. =P

**Comment by snneji** [comment]
That's fine! I've got my name on too much anyway. I'm happy you picked this up.
