### ISSUE TITLE
Should be able to use <username> rather than {username} in hello world sample

### ISSUE THREAD

**Issue by snneji** [knative/docs#4089]
**Describe the change you'd like to see**
I would like to be able to use `<>` instead of `{}` for placeholders in code samples. (This is to align with the Knative style rule for [referencing variables in code blocks](https://knative.dev/docs/help/contributor/style-guide/documenting-code/#referencing-variables-in-code-blocks).)

**Additional context**
I tried to update a code sample in PR #4083 to use `<>`, but it caused one of the tests to fail. 
Slack thread: https://knative.slack.com/archives/C9CV04DNJ/p1627656696003000

**Comment by julz** [comment]
oops, this fell off my list, let me look at it

/reopen
/remove-lifecycle stale

**Comment by julz** [comment]
oh actually, looks like the tests are disabled now since https://github.com/knative/docs/pull/4300 so this should be fine?

**Comment by snneji** [comment]
If you think it's fine, feel free to close the issue.

**Comment by julz** [comment]
Okie, you should be able to change `<username>` to `{username}` now, if you hit any problems do re-open!

/close
