### ISSUE TITLE
Style Guide: Add standard reference for our Docs repo to the Word and Phrase List

### ISSUE THREAD

**Issue by RichardJJG** [knative/docs#4108]
An engineer (antoineco) pointed out that we refer to our Docs repository differently throughout the docs and that maybe we should standardize. And, sure, why not?

| Correct Term                                   | Incorrect Term(s)                             |
|----------------------------------|-----------------------------------|
| \`knative/docs\` GitHub repository | Knative Docs repo<br>Docs repo  |

The Word and Phrase list is at
docs/help/contributor/style-guide/word-and-phrase-list.md

**Comment by abrennan89** [comment]
We should probably do this for all repos actually, e.g. knative sandbox, others?

**Comment by RichardJJG** [comment]
> We should probably do this for all repos actually, e.g. knative sandbox, others?

Yep, good idea. I've added a note to the rule saying just that.
