### ISSUE TITLE
Need Install Guide For AWS EKS

### ISSUE THREAD

**Issue by msidd111** [knative/docs#411]
There is no install Guide for AWS EKS. I would like to assess Knative for our Serverless needs if it is supported on EKS.

**Comment by mattmoor** [comment]
/unassign @mattmoor 
/assign @mchmarny 

I would expect https://github.com/knative/docs/blob/master/install/Knative-with-any-k8s.md to work, but I have no sense for the readiness of EKS for this.  Mark is this something you can try out?

**Comment by mchmarny** [comment]
/unassign @mchmarny
/assign @ahmetb 

Ye, I think this is mostly about validation. Ahmet, can you help on this?

**Comment by devops2201** [comment]
I am interested in creating a guide and I can work on this

**Comment by ahmetb** [comment]
Thanks all for signing up to do this, I'll let you decide who has more time or experience to work on it. Feel free to refer to [existing docs for other services](https://github.com/knative/docs/blob/master/install/README.md) for styling of the guide. Also feel free to request code review from each other. 😉 

/unassign

**Comment by fadeojo** [comment]
I used [this](https://github.com/knative/docs/blob/master/install/Knative-with-any-k8s.md) from the docs and it all worked on EKS as of today. I also deployed the `helloworld-go` service and was able to query it.

**Comment by fadeojo** [comment]
@ahmetb I updated my [comment](https://github.com/knative/docs/issues/411#issuecomment-440453185).

**Comment by RichieEscarez** [comment]
Closing due to age.
