### ISSUE TITLE
`About sinks` Page Should Contain Open Source Examples

### ISSUE THREAD

**Issue by JeffNeff** [knative/docs#4112]
**Describe the change you'd like to see**
I would like to see more open-source examples of Sinks included with the explanation of Sinks in the developer documentation, specifically `/docs/developer/eventing/sinks`. Triggermesh has two examples [here](https://github.com/triggermesh/bringyourown/tree/master/targets) that I think would be a good fit, however, I would like to see several more included if possible.

**Comment by abrennan89** [comment]
Hey @JeffNeff - thanks for raising this!
I think for now it's OK to add your PR and let it close this issue, but maybe this can be raised in the TOC or DUX WG calls directly to get some input from others on whether they have other examples to follow up with.
I'm wary of keeping issues open where there is no plan to work on them in the community, or for example if nobody else has any other sinks to add.

**Comment by abrennan89** [comment]
@JeffNeff do you still plan to work on this or should I close the issue perhaps?
