### ISSUE TITLE
Reference links broken in "getting-started-knative-app.md"

### ISSUE THREAD

**Issue by orionHong** [knative/docs#4119]
## Expected Behavior
`Resource Types documentation` should point to https://github.com/knative/specs/blob/main/specs/serving/overview.md#service.

`Serving spec documentation` should point to https://github.com/knative/specs/blob/main/specs/serving/knative-api-specification-1.0.md.

## Actual Behavior
`Resource Types documentation` points to https://github.com/knative/serving/blob/main/docs/spec/overview#service and gets a 404 error.
`Serving spec documentation` points to https://github.com/knative/serving/blob/main/docs/spec/spec and gets a 404 error.

## Steps to Reproduce the Problem

1. Go to https://knative.dev/docs/serving/getting-started-knative-app/#creating-your-deployment-with-yaml.
1. Clicks on `Resource Types documentation` and `Serving spec documentation` under `Creating your Deployment with YAML` section.

**Comment by sebgoa** [comment]
@snneji are you working on this ? you can ask @JeffNeff to fix it :)

**Comment by snneji** [comment]
> @snneji are you working on this ? you can ask @JeffNeff to fix it :)

I'm not working on it right now so I don't mind unassigning myself.

**Comment by snneji** [comment]
Thanks for picking this up @JeffNeff :)

**Comment by abrennan89** [comment]
YAML section no longer exists
