### ISSUE TITLE
Style guide update: Don't include md filename in HTML links

### ISSUE THREAD

**Issue by abrennan89** [knative/docs#4126]
Our style guide should include guidelines on using `a href` HTML links in docs without the .md filenames as an exception.
(Slack thread: https://knative.slack.com/archives/C9CV04DNJ/p1629320206058100)

For example, using a link like:
```
<a href="../../eventing" target="blank_">Knative Eventing</a>
```
will work to have a link that opens in a new window. If you add the README.md as follows:
```
<a href="../../eventing/README.md" target="blank_">Knative Eventing</a>
```
it will break the link.

cc @RichardJJG @snneji @omerbensaadon @julz

**Comment by RichardJJG** [comment]
I recommend changing the rule to simply: "Always use Markdown instead of HTML."
I count only 25 HTML links in the Docs folder; it's an easy clean-up issue.

@julz, there's no reason to ever write links in HTML, right? MkDocs is built for Markdown, after all.

**Comment by julz** [comment]
The only use case I know of (I don't know if there's a markdown way of doing this -- there might be, I can research a bit) is to open links in a new window (like @abrennan89's example of `target="_blank"` above)

**Comment by julz** [comment]
Neat! Turns out there _is_ a way to do this in mkdocs markdown -- looks like we can use a link like this:

~~~~
[link](../blah/README.md){target=_blank}
~~~~

Assuming that works we could put that in the style guide instead.

**Comment by RichardJJG** [comment]
Thanks as ever for the quick response, @julz!

I've created a related clean-up issue: https://github.com/knative/docs/issues/4129#issue-974482749.

**Comment by abrennan89** [comment]
This is awesome folks thank you! FYI @omerbensaadon 🙂 
I will close this issue now since we have #4129 instead
