### ISSUE TITLE
Re-write HTML links in Markdown

### ISSUE THREAD

**Issue by RichardJJG** [knative/docs#4129]
**Describe the change you'd like to see**
Re-write all the HTML links in the Docs folder in Markdown. I count 25 HTML links at present.

HTML links that specify opening a new window can be written in Markdown:
`<a href="../blah/README" target="blank_">link</a>`
becomes
`[link](../blah/README.md){target=_blank}`

**Reasoning**
The simpler and more uniform we can make links, the better: easier maintenance, reduced chance of problems, better for the link checker bot, etc.

**Additional context**
This is a spin-off from https://github.com/knative/docs/issues/4126

**Comment by snneji** [comment]
@RichardJJG Should we also update the style guide to mention this?

**Comment by RichardJJG** [comment]
> @RichardJJG Should we also update the style guide to mention this?

Yes, the relevant issue is https://github.com/knative/docs/issues/4033.
