### ISSUE TITLE
Add .md to internal links in the admin folder

### ISSUE THREAD

**Issue by snneji** [knative/docs#4132]
Add `.md` to every relative link in the files in the [`docs/admin/`](https://github.com/knative/docs/tree/mkdocs/docs/admin) folder. (Do not add it to absolute links.)

**Detail:** Many of our internal links lack the .md extension. That made sense for Hugo but it doesn't for MkDocs and our link checker bot.

**Comment by RichardJJG** [comment]
Markdown: `\]\((?!http|#)`
HTML: `<a href=.(?!http|#)`
