### ISSUE TITLE
wrong version of kubernetes in prerequisites.md

### ISSUE THREAD

**Issue by RafalSkolasinski** [knative/docs#4177]
According to 

https://github.com/knative/eventing/blob/0c41e6d42127ec22cfc17c565dd90d2b89e578f8/vendor/knative.dev/pkg/version/version.go#L33-L36

the minimum version of kubernetes now is 0.19.

The bump from 0.18 seems to happened around knative 0.24 release.

This is not reflected in the https://github.com/knative/docs/blob/mkdocs/docs/snippets/prerequisites.md
nor on the webiste:
- https://knative.dev/docs/admin/install/serving/install-serving-with-yaml/
- https://knative.dev/docs/admin/install/eventing/install-eventing-with-yaml/

**Comment by sebgoa** [comment]
you are right, it is even in the release notes for 0.24: https://github.com/knative/serving/releases/tag/v0.24.0

**Comment by snneji** [comment]
Already dealt with in #4196
