### ISSUE TITLE
A subject example for SinkBinding of CronJob uses invalid image and deprecated API version

### ISSUE THREAD

**Issue by cardil** [knative/docs#4178]
A subject example for SinkBinding of CronJob uses invalid image 

https://github.com/knative/docs/blob/001cd9bd29f345114fe324446cb0eb194f771d28/docs/developer/eventing/sources/sinkbinding/getting-started.md#L157

```bash
$ skopeo inspect docker://gcr.io/knative-releases/knative.dev/eventing-contrib/cmd/heartbeats
FATA[0000] Error parsing image name "docker://gcr.io/knative-releases/knative.dev/eventing-contrib/cmd/heartbeats": reading manifest latest in gcr.io/knative-releases/knative.dev/eventing-contrib/cmd/heartbeats: manifest unknown: Failed to fetch "latest" from request "/v2/knative-releases/knative.dev/eventing-contrib/cmd/heartbeats/manifests/latest".

$ skopeo list-tags docker://gcr.io/knative-releases/knative.dev/eventing-contrib/cmd/heartbeats 
{
    "Repository": "gcr.io/knative-releases/knative.dev/eventing-contrib/cmd/heartbeats",
    "Tags": []
}
```

It also uses the deprecated API version of `batch/v1beta1`. The `batch/v1` should be used instead.

https://github.com/knative/docs/blob/001cd9bd29f345114fe324446cb0eb194f771d28/docs/developer/eventing/sources/sinkbinding/getting-started.md#L140

```
W0903 12:59:03.239558  958779 warnings.go:70] batch/v1beta1 CronJob is deprecated in v1.21+, unavailable in v1.25+; use batch/v1 CronJob
```

**Comment by cardil** [comment]
For image problem we could link to https://knative.dev/docs/eventing/samples/container-source/#prepare-the-heartbeats-image but building that image is super cumbersome. It is used in multiple places in the docs, just like the event-display image is. 

I think we should prebuild heartbeats image and publish it the same as we are publishing event-display image.

**Comment by cardil** [comment]
Hmm, This page has even more problems. 

https://github.com/knative/docs/blob/001cd9bd29f345114fe324446cb0eb194f771d28/docs/developer/eventing/sources/sinkbinding/getting-started.md#L212-L216

This command also seems not to work. There are a couple of problems with it:

- subject here uses `Job:batch/v1` but above example uses `CronJob:batch/v1beta1`
- subject uses label selector of `app=heartbeat-cron`, but above cron job example doesn't have such label
- it uses namespace of `sinkbinding-example`, but both previous example didn't specify namespace, thus are using current one
- uses HTTP address, and not plausible one, but easily could be shortened to just `event-display` to address that ksvc

I believe it should:

- use the same `kind:apiVersion` for subject as example above. That is `CronJob:batch/v1` (do not use deprecated one)
- instead of using label selector, use cron job name, so just `heartbeat-cron`
- don't specify namespace
- use simply `--sink event-display`

**Comment by cardil** [comment]
I think resolving this must be preceded by fixing of https://github.com/knative/eventing/issues/5710.

**Comment by snneji** [comment]
Hi @cardil, the first step of this procedure is to [create a namespace](https://knative.dev/docs/developer/eventing/sources/sinkbinding/getting-started/#create-a-namespace) for the SinkBinding and all related resources. The example namespace in this step is `sinkbinding-example`. 

Is the problem that the instructions for Creating a subject and Creating a sink do not include a namespace? If so, would it make sense to add the namespace to those instructions so that they are in the same namespace as the SinkBinding object? Also, would having all resources in this namespace be better for [cleanup](https://knative.dev/docs/developer/eventing/sources/sinkbinding/getting-started/#cleanup)?

**Comment by abrennan89** [comment]
@JeffNeff do you still plan to work on this one?

**Comment by snneji** [comment]
Closing because the image has since been updated to `gcr.io/knative-nightly/knative.dev/eventing/cmd/heartbeats`. @cardil, you can reopen if you disagree that this fixes your issue.
