### ISSUE TITLE
Eventing Getting Started Guide Clarifications

### ISSUE THREAD

**Issue by GarrettPoore** [knative/docs#4197]
**Describe the change you'd like to see**
I'm new to knative and just walked through the getting started guide and ran into a few things that could have been clearer.

- The guide doesn't mention exactly what needs installed, just that knative eventing needs installed. I installed the only required yamls from the [admin guide](https://knative.dev/docs/admin/install/eventing/install-eventing-with-yaml/) (just crds and core), but the guide also requires `in-memory-channel.yaml` and `mt-channel-broker.yaml`. Which are marked as optional.
  - Creating a broker without those "optional" two just hangs forever without giving an error, so it was not clear what was missing.
- None of the yamls after the broker have a namespace in them, yet the commands to list the resources do

Side Note: The contributing guidelines for this repo has a bunch of 404 links.

**Comment by RichardJJG** [comment]
I think we can solve this simply by re-naming this section to "Tour" or "Knative in a Nutshell" or something similar. "Getting Started" sounds too much like "Install Knative", which isn't what this section is really about.
