### ISSUE TITLE
[Epic] Reorganise docs content

### ISSUE THREAD

**Issue by snneji** [knative/docs#4230]
The navigation for the site is a bit confusing at the moment. The site has (at least) the following issues:

1. It's hard to find crucial content such as installing.
2. Half the docs are in admin/dev guides and the other half in eventing/serving guides. We need to decide which strategy makes more sense.

To deal with this we need to:
- [x] #4296
- [x] #4386
- [x] #4380
- [x] #4344
- [x] #4376 
- [x] #4377

**Comment by omerbensaadon** [comment]
Removed #4378 since we would consider this major overhaul done. 

Not worth blocking on this issue
