### ISSUE TITLE
Issues with collector.yaml file in the Metrics documentation of Administration guide

### ISSUE THREAD

**Issue by dhruvbehl** [knative/docs#4233]
## Expected Behavior
Currently i see 2 issues in the documentation of Metrics section under the Administration guide and 1 issue in the https://github.com/knative/docs/blob/mkdocs/docs/admin/collecting-metrics/collector.yaml file

1. Currently the github project has already migrated to main branch naming convention. Hence changes to be made in the https://github.com/knative/docs/blob/mkdocs/docs/admin/collecting-metrics/README.md file where collector.yaml should be sourced from https://raw.githubusercontent.com/knative/docs/main/docs/install/collecting-metrics/collector.yaml or from the same branch where the documentation resides ie `mkdocs` ie https://github.com/knative/docs/blob/mkdocs/docs/admin/collecting-metrics/collector.yaml 

2. The collector.yaml in https://raw.githubusercontent.com/knative/docs/master/docs/install/collecting-metrics/collector.yaml, https://raw.githubusercontent.com/knative/docs/main/docs/install/collecting-metrics/collector.yaml has an error that results in decoding issue while creating the otel-collector Deployment. Because the service.extension[0] expects type 'string' and receives a map.

3. https://github.com/knative/docs/blob/mkdocs/docs/admin/collecting-metrics/collector.yaml file has a problem in `line 19` where zpages being of type map is missing a :

## Actual Behavior
1. `collector.yaml` file mentioned in the step 2 of Setup the collector seems to be coming from the `master` branch

2.  service.extension[0] in https://raw.githubusercontent.com/knative/docs/master/docs/install/collecting-metrics/collector.yaml, https://raw.githubusercontent.com/knative/docs/main/docs/install/collecting-metrics/collector.yaml has type map

3. zpages on `Line 19` of https://github.com/knative/docs/blob/mkdocs/docs/admin/collecting-metrics/collector.yaml file is a string

## Steps to Reproduce the Problem

1. Goto README.md at https://github.com/knative/docs/blob/mkdocs/docs/admin/collecting-metrics/README.md 
2. Try following instructions on https://github.com/knative/docs/blob/mkdocs/docs/admin/collecting-metrics/README.md  and the deployment fails to create pod with `CrashLoopBackOff` due to the error seen in the logs ie `service.extension[0]` expects type 'string' got unconvertible type 'map[string]interface {}'`
3. Same steps as 2 for the error (3)

## Additional Info
**Additional context**

**Install information:**
 - Platform (GKE, IKS, AKS, etc.):
 - Knative Version: v0.20.0

**Comment by dhruvbehl** [comment]
If the bug seems legit i have a solution that i would like to discuss and contribute back to the project.

**Comment by csantanapr** [comment]
Hi please submit a PR with your suggested fixes.

**Comment by csantanapr** [comment]
Don't why `health_check` which is a string would cause an error
```
service:
  extensions: [health_check,pprof,pages]
```
But create a PR and we can discuss in the PR

cc @evankanderson

**Comment by dhruvbehl** [comment]
> Don't why `health_check` which is a string would cause an error
> 
> ```
> service:
>   extensions: [health_check,pprof,pages]
> ```
> 
> But create a PR and we can discuss in the PR
> 
> cc @evankanderson

Currently in the doc the collector.yaml referenced is https://raw.githubusercontent.com/knative/docs/master/docs/install/collecting-metrics/collector.yaml which currently seems to be down (404). 

I suggest to use either 

https://raw.githubusercontent.com/knative/docs/main/docs/install/collecting-metrics/collector.yaml (from the main branch)
or
https://github.com/knative/docs/blob/mkdocs/docs/admin/collecting-metrics/collector.yaml (from the mkdocs branch)

Even in these 2 files there are few issues where `service.extension` needs a array of string but in these files we have a map which gives decoding error during deployment.

Let me send a PR soon for further discussion

**Comment by dhruvbehl** [comment]
@csantanapr @evankanderson Please have a look at this PR draft https://github.com/knative/docs/pull/4235

**Comment by csantanapr** [comment]
Use the mkdocs branch, that the current one

**Comment by dhruvbehl** [comment]
> Use the mkdocs branch, that the current one

The documentation published on still uses the collector.yaml from the master branch. 

Refer step (2) of Set up the collector section under https://knative.dev/docs/admin/collecting-metrics/

Please have a look at my suggestion in the PR raised

**Comment by dhruvbehl** [comment]
Will be raising a PR for the fix soon

**Comment by dhruvbehl** [comment]
@csantanapr @evankanderson @abrennan89 Please review the fix https://github.com/knative/docs/pull/4267

**Comment by abrennan89** [comment]
>Use the mkdocs branch, that the current one

It's actually the main branch now so any PR might need to be updated
