### ISSUE TITLE
Migrate blog from hugo to mkdocs

### ISSUE THREAD

**Issue by csantanapr** [knative/docs#4243]
With the [recent changes](https://twitter.com/squidfunk/status/1437456678753026049?s=20) and example for mkdocs-material blog. I think we can take a stab on converting the [knative blog](https://knative.dev/blog/) from hugo to mkdocs.

The mkdocs-material blog => https://squidfunk.github.io/mkdocs-material/blog/

**Comment by csantanapr** [comment]
cc @omerbensaadon

**Comment by csantanapr** [comment]
cc @julz

**Comment by julz** [comment]
Oh wow 😍.

**Comment by psschwei** [comment]
I should be able to help with this

**Comment by omerbensaadon** [comment]
Legend! thank you Paul
