### ISSUE TITLE
Openshift: Add Knative-Eventing to the script

### ISSUE THREAD

**Issue by matzew** [knative/docs#425]
## Expected Behavior

the script for openshift installs all, `build`, `serving` and `eventing`

## Actual Behavior

currently it only installs `build` and `serving`

**Comment by matzew** [comment]
I will work on this tomorrow /cc @bbrowning

**Comment by samodell** [comment]
@matzew  This issue and #430 still seem relevant. Any plans to update the OpenShift install?
