### ISSUE TITLE
Document ingress class annotation

### ISSUE THREAD

**Issue by julz** [knative/docs#4255]
**Describe the change you'd like to see**

Document - I'd suggest a page called "Configuring the Ingress Class for a specific Knative Service" or "Overriding the default Ingress Class for a Knative Service" but docs writer input greatly appreciated here) how a user can use the [`network.knative.dev/ingress.class`](https://github.com/knative/serving/blob/d207fa3a92ace22f56ad123a75809a8b0495c88b/vendor/knative.dev/networking/pkg/apis/networking/register.go#L36) annotation to set a specific networking extension to be used for a Knative Service. 

Document that if not specified the value from the networking config map, set at install time, is used.

**Comment by salaboy** [comment]
Ok, looking a bit at the existing documentation this sounds like it should go here: 

https://github.com/knative/docs/tree/main/docs/developer/serving/services

And that the section will look pretty much like: https://github.com/knative/docs/blob/main/docs/developer/serving/services/private-services.md

I will start a PR to review the content, as it is not 100% clear how much needs to be documented

**Comment by salaboy** [comment]
@julz @abrennan89 I've just created a PR to get this started, comments/feedback appreciated.
