### ISSUE TITLE
The RBAC for eventing API Source doesn't seem to work

### ISSUE THREAD

**Issue by dprotaso** [knative/docs#4287]
The RBAC here says you only need access to `events`
https://knative.dev/docs/developer/eventing/sources/apiserversource/getting-started/

After deploying an `APISource` it actually gives me warning stating it needs access to `pods` and `apps/deployments` before the source becomes `Ready`

/assign @lionelvillard

**Comment by lionelvillard** [comment]
@dprotaso lmk if this is working for you now. If not, please reopen this issue, thx.
