### ISSUE TITLE
Openshift: use 0.1.1 release instead of latest

### ISSUE THREAD

**Issue by matzew** [knative/docs#430]
## Expected Behavior

Openshift doc/script use `latest`, but should use a versioned install (current `0.1.1`)

## Actual Behavior

usage of latest, which is not the desired approach

**Comment by matzew** [comment]
See also comment from @bbrowning here:
https://github.com/knative/docs/pull/424#issuecomment-425268455

**Comment by RichieEscarez** [comment]
A docs release has been created for the 0.1.x releases. Please target this change at https://github.com/knative/docs/releases/tag/v0.1.x

The 'master' branch now reflects the 0.2.0 release of the serving component.

**Comment by RichieEscarez** [comment]
That doc now use "latest" version.
