### ISSUE TITLE
Create an overview page for PingSource and for ContainerSource

### ISSUE THREAD

**Issue by snneji** [knative/docs#4305]
## Background
The sections for [PingSource](https://knative.dev/development/developer/eventing/sources/ping-source/) and  [ContainerSource](https://knative.dev/development/developer/eventing/sources/containersource/) should have similar content and navigation structure to [ApiServerSource](https://knative.dev/development/developer/eventing/sources/apiserversource/) and [SinkBinding](https://knative.dev/development/developer/eventing/sources/sinkbinding/) .

## Task
1.  Write overview pages for the following event sources: 
    1. [PingSource](https://knative.dev/development/developer/eventing/sources/ping-source/)
    1. [ContainerSource](https://knative.dev/development/developer/eventing/sources/containersource/)

    Explain the event source and what it can be used for, similar to the [ApiServerSource](https://knative.dev/development/developer/eventing/sources/apiserversource/) and [SinkBinding](https://knative.dev/development/developer/eventing/sources/sinkbinding/) overview pages.
    
2. Update the PingSource and ContainerSource navigation to match ApiServerSource and SinkBinding.

**Comment by abrennan89** [comment]
@sureshkumarAQ apologies that you weren't assigned, just saw this comment today. Would you still like to work on this issue?
