### ISSUE TITLE
YAML referenced in Logging Documentation goes to 404

### ISSUE THREAD

**Issue by lamw** [knative/docs#4315]
## Expected Behavior
The referenced YAML for deployment is successful

## Actual Behavior
The referenced YAML goes to 404

## Steps to Reproduce the Problem

In [Logging](https://knative.dev/docs/admin/collecting-logs/) documentation, the referenced YAML in Step 1 points to `https://github.com/knative/docs/raw/main/docs/admin/install/collecting-logs/fluent-bit-collector.yaml` but this gives 404. Looking at the repo, it looks like it should have been `https://raw.githubusercontent.com/knative/docs/main/docs/admin/collecting-logs/fluent-bit-collector.yaml`

## Additional Info
**Additional context**
N/A

**Install information:**
N/A

**Comment by psschwei** [comment]
In the current version of the docs (1.2), this link appears to work as expected, so going to go ahead and close this.
