### ISSUE TITLE
Clean up PR #4297 (configuring the knative-ingress-gateway gateway and istio-ingressgateway-service)

### ISSUE THREAD

**Issue by snneji** [knative/docs#4329]
Edit #4297 for style and fix formatting. Ensure the text follows the [Knative Style Guide](https://github.com/knative/docs/tree/main/contribute-to-docs/style-guide).

Change the new sections to have steps as suggested in this comment: https://github.com/knative/docs/pull/4297#pullrequestreview-769041758.

Sections to edit: 
- https://knative.dev/docs/install/operator/configuring-serving-cr/#replace-the-default-istio-ingressgateway-service
- https://knative.dev/docs/install/operator/configuring-serving-cr/#replace-the-knative-ingress-gateway-gateway

**Comment by abrennan89** [comment]
@snneji it looks like there are PRs linked to this, can this issue be closed? Is there more work to do?

**Comment by snneji** [comment]
This still needs to be done. I added the links to the locations to edit to the issue description. I think it would be better to have a numbered list of steps instead of the headings with step numbers.
