### ISSUE TITLE
[EPIC] Consolidate Docs Contribution Content and Remove Hugo Site

### ISSUE THREAD

**Issue by omerbensaadon** [knative/docs#4339]
### Context
At the moment, our Docs contributor content is sort of peppered all of over the place and not very easy to find. We've decided in the last few DUX meetings that we would move all content relevant to contributing into Github. This story details what all needs to be moved! 

---

### Story 
**As a** new contributor
**I want** to have a single place where I can find all of the information relevant to creating a contribution
**So that** I can easily find all of the information relevant to contributing
**And so that** I have confidence that my contribution is aligned with existing contributors 

### Acceptance Criteria
All child issues are completed 
```
GIVEN I look at the child issues section of this epic 
WHEN I examine the checklist items 
THEN I see they are all complete
```

### Child Issues
- [x] #4342
- [x] #4343
- [x] #4394
- [x] #4515

**Comment by snneji** [comment]
@omerbensaadon I've added this to the roadmap. What priority level do you think this epic is? Do we want to do this now or next?

**Comment by snneji** [comment]
All tasks completed

**Comment by omerbensaadon** [comment]
🥳
