### ISSUE TITLE
Update instructions for creating a blog post

### ISSUE THREAD

**Issue by psschwei** [knative/docs#4340]
After migrating the blog to mkdocs ( #4298 ), we need to update our doc on [how to create blog posts](https://github.com/knative/docs/blob/main/docs/help/contributor/creating-blog-posts.md).

For mkdocs, users will need to:

* create their blog post in the relevant folder : `/blog/docs/<type>` (note that currently blog posts are in `/blog/<type>`, and those `type/` directories were moved inside of a `docs/` directory in the `blog/` directory... that's a lot of directories :smile: )
* update the `/blog/docs/config/nav.yml` file to add your blog post to the site

This _probably_ means we can't use the UI anymore, so users would need to use the usual creating a PR process (i.e. fork the repo, etc.)

**Comment by snneji** [comment]
@psschwei It seems that we have 2 locations with instructions for the blog: in the [blog README](https://github.com/knative/docs/blob/main/blog/README.md), and in the [docs contributor guide](https://github.com/knative/docs/blob/main/contribute-to-docs/what-to-contribute/creating-blog-posts.md).

I see that you updated information in the blog README in https://github.com/knative/docs/pull/4416. Maybe the blog README can be the home for the instructions for updating the blog and the docs contributor guide should just link to the blog README?

**Comment by psschwei** [comment]
> Maybe the blog README can be the home for the instructions for updating the blog and the docs contributor guide should just link to the blog README?

Yeah, I think that makes sense. I'll make a PR.
