### ISSUE TITLE
Create a new page for installing the Knative Quickstart

### ISSUE THREAD

**Issue by omerbensaadon** [knative/docs#4345]
### Context 
Once #4344 is delivered, this page should be created 

### Story 
**As a** Knative user 
**I want** to have the option to install the Knative Quickstart
**So that** I can leverage a local installation of Knative separate from the Getting Started Guide 

### Acceptance Criteria
- [ ] Create new page for the Knative Quickstart, link out to the Getting Started guide at the end of the install 
```
GIVEN I am currently in the "Install Knative" section of the site 
AND I have clicked on the "Knative Quickstart" page from the left-side navigation 
WHEN I scan the page 
THEN I see all of the pre-requisites and steps to install the Knative Quickstart taken from https://knative.dev/docs/getting-started/
AND THEN I see that it is leveraging the install-kn.md and quickstart-install.md files from docs/snippets 
```

**Comment by snneji** [comment]
Would we also keep this content on the [Knative Quickstart page](https://knative.dev/docs/getting-started/#install-the-knative-quickstart-environment) in the getting started guide?
