### ISSUE TITLE
New Knative Blog Posts don't have authors

### ISSUE THREAD

**Issue by omerbensaadon** [knative/docs#4363]
## Expected Behavior
When someone posts a blog, I expect to see an author and a link out to their socials 

## Actual Behavior
It's not clear who the author is for Blog Posts

## Steps to Reproduce the Problem

1. Load a blog post 
1. Try and find the author

**Comment by psschwei** [comment]
remove-lifecycle stale

**Comment by snneji** [comment]
I also noted that Knative blog posts don't have a date on them. I think dates are important so could we add them as part of this issue?

**Comment by psschwei** [comment]
Looks like there is a plan for mkdocs to support blog authors as part of adding better support for blogs: https://github.com/squidfunk/mkdocs-material/issues/3353

Might be worth weighing in on the issue if there's anything specific we'd like to see.

**Comment by abrennan89** [comment]
Update blogs in Articles folder to include author names and date and remove Hugo front matter

**Comment by snneji** [comment]
Example: https://github.com/knative/docs/blob/main/blog/docs/articles/distributed-tracing.md

**Before:**

<img width="779" alt="Screen Shot 2022-06-21 at 18 38 32" src="https://user-images.githubusercontent.com/33425661/174865246-306d1c1a-19ee-41b3-a56e-8ac3e06084a1.png">


**After** (using the info from the frontmatter to add title, author, and date):

<img width="796" alt="Screen Shot 2022-06-21 at 18 33 39" src="https://user-images.githubusercontent.com/33425661/174864678-323a815e-55b2-4cca-9efa-62a681bf2b28.png">
