### ISSUE TITLE
Kubernetes Service is not created in the Go RESTful example

### ISSUE THREAD

**Issue by zzvara** [knative/docs#4372]
Documentation states in `docs/serving/samples/rest-api-go/`, that a Kubernetes Service will be created as well, but it is not with v0.26.0 installed through Kubernetes Operator as the docs guided.

**Comment by snneji** [comment]
@nak, would you be able to help?

**Comment by nak3** [comment]
Hi @zzvara Sorry for the delay. The sample `rest-api-go` was outdated and it was supposed to be removed as per https://github.com/knative/docs/issues/2053 https://github.com/knative/docs/issues/2053#issuecomment-651524070

We will remove the page but do you have anything trouble for REST app with Knative? The REST app should not need any special setting on Knative side.

**Comment by zzvara** [comment]
@nak3 yes, the issue was in general as with the `rest-api-go` and custom, home-brew examples that for none of the `Knative` `Services` had a Kubernetes `Service`, therefore I could not call it internally from the cluster and could not expose it using `traefik`.

Quick backstory: I attempted to migrate Kubeless functions to Knative because of the problem of container-mutability with Kubeless: Kubeless containers when restarted for any reason often fail to install their function and its dependencies during the restart process. However, with Knative I stumbled upon a similar issue that of Kubeless: lack of good examples, tutorials, docs, and as you pointed out, outdated.

Anyway, KNative seems to be a great, high-level composition toolset for K8S micro-services. Amazing! I'm still wondering how to create Kubernetes `Service` for a Knative micro-service because only `Deplyoment` was created for me.

**Comment by nak3** [comment]
Hi @zzvara
I guess that your Knative Service has an issue around networking layer.
Could you please share:
- The output of `$ kubectl get all -o yaml`
- What ingress are you using [in this list](https://knative.dev/docs/install/serving/install-serving-with-yaml/#install-a-networking-layer) - istio, kourier, contour?

**Comment by zzvara** [comment]
@nak3 I tried Kourier, Contour, Ambassador as well. A Kubernetes Service would have been nice without another layer of routing, security, and load balancing (e.g. Ambassador). However, Ambassador did not register the Knative service as an App for routing. (Again, this is based on the `docs/serving/samples/rest-api-go/` and custom Apps.)

```
NAME      STATUS   ROLES                  AGE    VERSION
sigma01   Ready    control-plane,master   631d   v1.21.5
sigma02   Ready    control-plane,master   631d   v1.21.5
sigma03   Ready    <none>                 631d   v1.21.5
sigma04   Ready    <none>                 631d   v1.21.5
```

```
Linux sigma01 5.10.69-flatcar #1 SMP Wed Sep 29 20:48:40 -00 2021 x86_64 Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz GenuineIntel GNU/Linux
```

If I could try out a Java tutorial for example that is proven to work/not outdated, I would be happy to make a run at it again.

**Comment by nak3** [comment]
Okay @zzvara Please let us know if there is any issue with non-oudated tutorial. I am closing this issue as rest-api-go example was outdated and removed.
