### ISSUE TITLE
Create a new section for the website called "Code Samples"

### ISSUE THREAD

**Issue by snneji** [knative/docs#4378]
### Context 
During the Card Sort, many folks grouped the code samples under a "Code samples" section, see https://miro.com/app/board/o9J_l1Iv2e4=/ 

### Story 
**As a** Knative user 
**I want** to have a go-to place for Knative code samples
**So that** I can more easily find all of the samples

### Acceptance Criteria
- [x] Create new site-wide Subheading
```
GIVEN I have arrived at the Knative homepage 
WHEN I look at the top Nav 
THEN I see a "Code samples" tab to the right of "Knative Eventing" 
```

---

- [x] Move all code samples from the Serving and Eventing guides including `samples.md` as the overview page.
```
GIVEN I have clicked on the "Code samples" tab 
WHEN I look at the left-hand side navigation
THEN I see all of the content that is currently under "Code samples" in the Serving and Eventing guides 
AND WHEN I look at the Serving and Eventing guides 
THEN I see that content no longer appears there
```

---

- [ ] Match directory structure to site structure 
```
GIVEN All of the above changes have been made
WHEN I look at the file structure 
THEN it makes sense considering the site changes that have been made
```

---

- [ ] Fix existing links to this content 
```
GIVEN all of the content has already been moved from elsewhere into the Code samples section
WHEN I try to access any URL linking to the content's previous location
THEN I am taken the to content's new location
```

**Comment by abrennan89** [comment]
@snneji I think this can be closed now, not sure if there's anything left to do first?
