### ISSUE TITLE
Create new, more barebones Community section within the MkDocs Site

### ISSUE THREAD

**Issue by omerbensaadon** [knative/docs#4394]
**Describe the change you'd like to see**
In order to remove the last bits of Hugo functionality, we'll need to recreate the Community Section in the MkDocs site. 

I've submitted https://github.com/knative/community/issues/796 which is approved by Steering which enables us to link out to the Github Repo when needed. 

**Additional context**
- [x] Community Communications (Slack, Dev List, etc.) 
- [x] Community Calendar 
- [x] Working Groups 
- [x] Twitter 
- [x] StackOverflow questions 
- [x] Share Code Samples
- [x] Contribution Guidelines (Link out to the contribution guidelines on Github, may also want to make a redirect from https://knative.dev/community/contributing/ to the file in Github)

**Comment by aslom** [comment]
@omerbensaadon do you have link to details how MkDocs would work wit Knative docs and github repos?

**Comment by omerbensaadon** [comment]
@aslom I would defer to the process change (https://github.com/knative/community/issues/796) which I think answers that question? 

Looks like Samia is already on it with a PR... do you have any specific questions I can answer?
