### ISSUE TITLE
Release docs for Knative v1.0

### ISSUE THREAD

**Issue by csantanapr** [knative/docs#4417]
- Make sure to remove last release 0.23 (last hugo yay)
- Dropdown should have `v1.0` in versions
- Adjust to have the URL that point to GitHub yamls to use `knative-v1.0.0` instead of `v1.0.0` like `https://github.com/knative/serving/releases/download/knative-v1.0.0/serving-core.yaml`

cc @omerbensaadon @julz 

/assign

**Comment by julz** [comment]
* make sure to check download links for past and current version in preview before merging :)
