### ISSUE TITLE
We need to add another way to configure credentials  for private image registry

### ISSUE THREAD

**Issue by zhaojizhuang** [knative/docs#4420]
/kind doc

## Expected Behavior

Besides `default service account` , we should add another way to configure credentials  for private image registry in doc,
see 
- https://github.com/knative/serving/issues/5866
- https://github.com/knative/serving/blob/e4c7848e2e347b8ee4dc66eb8272a280b270e5cd/vendor/k8s.io/api/core/v1/types.go#L3043

add to this page https://knative.dev/docs/serving/deploying/private-registry/

**Comment by dprotaso** [comment]
Documenting the ability to set an image pull secret on the PodSpec would be useful documentation.

**Comment by snneji** [comment]
The link above is broken. Is this the correct page: https://knative.dev/docs/serving/deploying-from-private-registry/
