### ISSUE TITLE
Move Eventing getting started page to getting started guide

### ISSUE THREAD

**Issue by snneji** [knative/docs#4440]
## Context

The Eventing docs has an extra [Eventing getting started](https://knative.dev/docs/eventing/getting-started/) page (location in repo: [`eventing/getting-started.md`](https://github.com/knative/docs/blob/main/docs/eventing/getting-started.md)). 
This page provides a `kubectl` command line based getting started tutorial, whereas the current [getting started](https://knative.dev/docs/getting-started/getting-started-eventing/) guide seems to be GUI based.

## Acceptance criteria

- Move the page to the [Getting started](https://knative.dev/docs/getting-started/getting-started-eventing/) guide. Maybe split into multiple pages.

(update WG meeting Feb 15, 2022) 
- Ensure the tutorial uses the `kn` CLI
- Simplify to filter on something like fruit
- Remove current Eventing tutorial (CloudEventsPlayer).

_(updated after discussing at the Docs and UX working group meeting)_

**Comment by csantanapr** [comment]
I think it should be deleted, and anything useful from it incorporate into the main eventing getting started https://knative.dev/docs/getting-started/getting-started-eventing/

**Comment by csantanapr** [comment]
Let's discuss on wg meeting and decide which option to move forward

**Comment by abrennan89** [comment]
Duplicate page is removed, but there's a follow up action here to remove the cloud player app thing and replace it with a nice simple eventing tutorial that uses kn and maybe just shows how to add a couple of different triggers
