### ISSUE TITLE
how to uninstall 

### ISSUE THREAD

**Issue by cforce** [knative/docs#445]
Description howto delete all generated ressources on any kubernetes.
Actually running
`kubectl -n istio-system delete po,svc,daemonsets,replicasets,deployments,rc,secrets --all`
almost does that, but still some service account secrets are left over, that seems to be undeletable (recreated again) .  Did not get behind that secret ;)

**Comment by RichieEscarez** [comment]
@evankanderson is there a recommended approach for completely removing all Knative resources from a cluster?

**Comment by RichieEscarez** [comment]
duplicate: https://github.com/knative/docs/issues/533
