### ISSUE TITLE
Update the outfit7 logo with the provided one

### ISSUE THREAD

**Issue by csantanapr** [knative/docs#4450]
Two places the logo shows up, replace with new logo file
![image](https://user-images.githubusercontent.com/1094878/140586127-edb0da17-489a-4a52-b052-7b1207c078ce.png)

![image](https://user-images.githubusercontent.com/1094878/140586162-9cbf5cdf-5101-4edf-8d9f-e1404e8b360d.png)

With this new file:
![Outfit7_Logo_Red](https://user-images.githubusercontent.com/1094878/140586091-c4fb08be-5b0d-460e-93f3-d0224b6cacf1.png)

**Comment by matthiasgubler** [comment]
@csantanapr I'm kind of confused. In  #4456 I updated the logo to the one you provided. By reviewing the preview https://deploy-preview-4456--knative.netlify.app/docs/about/case-studies/outfit7/ I thought it looks quite similar, so I did a couple of file-compares with the old and new one and there was no difference, even though the PR says that the new file is 8.94 KB bigger. However, are you sure you provided the correct file?

**Comment by csantanapr** [comment]
oh so sorry @matthiasgubler I didn't see you were already working on this with an open PR 🤦 

I provided the correct file. The thing to compare is is the URLs, the new file only shows in main you need to select pre-release

To the naked eye they look identical. I just grab the file they sent me in a zip file
