### ISSUE TITLE
Document Kafka Broker commit offset interval

### ISSUE THREAD

**Issue by pierDipi** [knative/docs#4460]
## What is changing? (Please include as many details as possible.)

The committed offset is a pointer to the last record that a
the consumer has successfully processed.

We're committing the offset every [`auto.commit.interval.ms`]
milliseconds.

Users can change the interval by changing the
`config-kafka-broker-data-plane` ConfigMap
that is introduced in:
https://knative.dev/docs/eventing/broker/kafka-broker/#kafka-producer-and-consumer-configurations

Note: this is using the Kafka consumer configuration
with the same name [`auto.commit.interval.ms`] but we use it
even without setting `enable.auto.commit` to true.

[`auto.commit.interval.ms`]: https://kafka.apache.org/documentation/#consumerconfigs_auto.commit.interval.ms

## In what release will this take happen (to the best of your knowledge)?

- 0.26
- 1.0
- 1.1

## Context
Link to associated PRs or issues from other repos here.

1. https://github.com/knative-sandbox/eventing-kafka-broker/pull/1405

## Additional info

/kind eventing

**Comment by abrennan89** [comment]
@pierDipi can you please provide some additional information about this feature to help document it?
