### ISSUE TITLE
Installationguide for Knative Serving via operator is not working

### ISSUE THREAD

**Issue by matthiasgubler** [knative/docs#4468]
## Expected Behavior
I can follow the guideline step by step and the result is a nice and clean installation of Knative Serving with an arbitrary network layer.

## Actual Behavior
We installed it up until this part of the documentation:
https://knative.dev/docs/install/operator/knative-with-operators/#:~:text=Check%20the%20status%20of%20Knative%20Serving%20Custom%20Resource%3A

And we got an error instead of a ready instance. By checking the logs, we saw the message that istio is missing. For me this implies, that istio should be installed in beforehand.

```
{"severity":"INFO","timestamp":"2021-11-11T07:26:45.306424703Z","logger":"knative-operator.event-broadcaster","caller":"record/event.go:282","message":"Event(v1.ObjectReference{Kind:\"KnativeServing\", Namespace:\"knative-serving\", Name:\"knative-serving\", UID:\"1bd34580-0143-4799-9d80-bd5fd1635bc4\", APIVersion:\"operator.knative.dev/v1alpha1\", ResourceVersion:\"2163\", FieldPath:\"\"}): type: 'Warning' reason: 'InternalError' please install istio or disable the istio ingress plugin: no matches for kind \"Gateway\" in version \"networking.istio.io/v1alpha3\"","knative.dev/pod":"knative-operator-57887499b8-nxkd7"}
```

## Steps to Reproduce the Problem

1. Follow the manual on a fresh kubernetes instance (1.20+) up until the mentioned text
2. Check the status of Knative Serving with `kubectl get KnativeServing knative-serving -n knative-serving` 
3. See an error and validate it via `stern knative`

## Additional Info
**Additional context**
I created a PR #4467 because of a different output we got. But maybe this is because something in the order of the installation changed

**Install information:**
 - Platform (GKE, IKS, AKS, etc.): Kubernetes local in Docker
 - Knative Version: latest

**Comment by matthiasgubler** [comment]
Fyi: after installing istio KnativeServing was marked as ready

**Comment by nak3** [comment]
Umm... Documentation mentions it in https://knative.dev/docs/install/operator/knative-with-operators as:

1. Install Istio.
2. To configure Knative Serving to use Istio, copy the following YAML into a file:

@matthiasgubler Can we close this issue and work on https://github.com/knative/docs/pull/4467 ?

**Comment by matthiasgubler** [comment]
Regarding usability I would not just close it. In comparision with the "plain" yaml installation (https://knative.dev/docs/install/serving/install-serving-with-yaml/), the operation guide mentions istio after the validation of the result. That means the expected result in the guide never aligns with the documentation. A colleague of mine was installing it step by step and failed right there. This took him a good amount of time to find out, that he first needed to install istio.

I would suggest to align the documentation with the yaml-based one and provide the "verify steps" after the installation of istio. I could open a PR for that later aswell.

**Comment by houshengbo** [comment]
@matthiasgubler There used to be an instruction in the prerequisite, saying installing istio.
However, after knative is enabled with multiple ingresses, people complained that knative does not depend on istio, so need to remove that. Then it seemed the removal led to more confusion.

**Comment by matthiasgubler** [comment]
@houshengbo what would you then suggest to do, that qe don't have two different suggestions of installation paths in the different kind of installation-doc?

**Comment by houshengbo** [comment]
@matthiasgubler I put a link in the PR you submitted.
