### ISSUE TITLE
Fix broken formatting in Installing guide

### ISSUE THREAD

**Issue by snneji** [knative/docs#4477]
Review the webpages in the Installing guide and fix formatting issues such as:
- incorrect bullet points or numbering
- broken tab formatting

The following issues need to be fixed:
- [x] https://knative.dev/docs/install/installing-istio/#choosing-an-istio-installation “Installing Istio without sidecar injection(Recommended default installation)” missing a space before the opening parenthesis.
- [x] https://knative.dev/docs/install/installing-istio/#verifying-your-istio-install incorrect formatting for the tip. Correct formatting uses the opening tip tag (`!!! tip`), followed by a new line, and then 4 spaces before the tip text. 
For example:
    ```
    !!! tip
        Tip text …
    ```
- [x]  https://knative.dev/docs/install/upgrade/upgrade-installation-with-operator/#rollback-to-an-earlier-version tab formatting is broken. To fix, indent the lines 126-146 and 150-170 by an extra 4 spaces.
- [x] https://knative.dev/docs/install/uninstall/#uninstalling-optional-serving-extensions Broken numbering in the "TLS with cert-manager" tab. To fix, check for correct indentation of the code snippet (8 spaces).
- [x] https://knative.dev/docs/install/uninstall/#uninstalling-optional-eventing-extensions broken numbering in Apace Kafka sink tab. To fix, check for correct indentation of the code snippet (8 spaces).
- [ ] **Extra Credit:** Add code tags around the names of the YAML files in the tables on the following pages:
    - https://knative.dev/docs/install/yaml-install/serving/serving-installation-files/
    - https://knative.dev/docs/install/yaml-install/eventing/eventing-installation-files/

**Comment by Subhasish-Behera** [comment]
@snneji I would like to work on this issue. It would be great if you could kindly show me around the folders where changes have to be made.
