### ISSUE TITLE
Fix broken formatting in Serving guide

### ISSUE THREAD

**Issue by snneji** [knative/docs#4478]
Review the webpages in the Serving guide and fix formatting issues such as incorrect bullet points or numbering and broken tab formatting etc.

**Comment by snneji** [comment]
Locations to fix:
https://knative.dev/docs/serving/autoscaling/concurrency/#hard-limit
https://knative.dev/docs/serving/services/creating-services/#procedure
https://knative.dev/docs/serving/services/service-metrics/ — add code tags
https://knative.dev/docs/serving/load-balancing/target-burst-capacity/#setting-the-target-burst-capacity
https://knative.dev/docs/serving/using-a-tls-cert/#obtaining-a-tls-certificate
https://knative.dev/docs/serving/using-auto-tls/#enabling-auto-tls
https://knative.dev/docs/serving/using-auto-tls/#provising-certificates-per-namespace-wildcard-certificates
https://knative.dev/docs/serving/setting-up-custom-ingress-gateway/
https://knative.dev/docs/serving/observability/metrics/serving-metrics/ - add code tags

**Comment by hamees-sayed** [comment]
@snneji I would like to work on this issue. If you could kindly show me around the folders where changes have to be made.
Thank you

**Comment by snneji** [comment]
Hi @hamees-sayed, thanks for volunteering to work on this!

I've added instructions for each item listed. You don't have to fix all items, just do as many as you can, and check them off the list. You should find that all the files that need to be updated for this issues are in the `docs/serving/` folder in this repo. The file names are in the URL. 

For more information on how to edit the docs, see the [**docs contributor guide**](https://github.com/knative/docs/tree/main/contribute-to-docs#knative-docs-contributor-guide).

Let me know if you have any more questions!

**Quick tip:** If you are struggling to find a page, you can use GitHub help you find it. 
1. Navigate to the page you want to change on the Knative website. 
2. Click the pencil icon ("edit this page") at the top right of the page. <img width="958" alt="Screen Shot 2022-03-01 at 14 53 28" src="https://user-images.githubusercontent.com/33425661/156192484-dd0388f4-39ea-4eb0-bd95-60b623949caa.png">
3.  Use GitHub to show you the filepath for the page you want to edit. <img width="712" alt="Screen Shot 2022-03-01 at 14 51 53" src="https://user-images.githubusercontent.com/33425661/156192920-b672cfad-f612-4d32-82b0-98022deeef86.png">

**Comment by hamees-sayed** [comment]
Thank you so much @snneji

**Comment by hamees-sayed** [comment]
@snneji first formatting is done, kindly check it

**Comment by snneji** [comment]
@hamees-sayed Thanks for your help on this one. 🙂 I made a comment on your issue to fix that warning note #4803. Do you think you'll be able to pick that issue up as well?

**Comment by hamees-sayed** [comment]
@snneji sure, I might do it later today after I am done with my studies, I thought of raising it as an issue just in case. 😅

**Comment by hamees-sayed** [comment]
@snneji I pretty much fixed all the broken formatting, if you could review the PR.
Thank you :)

**Comment by snneji** [comment]
Fixed in https://github.com/knative/docs/pull/4806
