### ISSUE TITLE
Fix broken formatting in Eventing guide

### ISSUE THREAD

**Issue by snneji** [knative/docs#4479]
Review the webpages in the Eventing guide and fix formatting issues.

TO DO
- [x] Remove definition list in https://knative.dev/docs/eventing/#common-use-cases
- [x] fix bulleted list https://knative.dev/development/eventing/accessing-traces/#example — 
- [x] Format https://knative.dev/docs/eventing/custom-event-source/custom-event-source/publish-event-source/ as numbered steps
- [x] Fix broken note formatting https://knative.dev/docs/eventing/event-delivery/#broker-support — 
- [x] links should not be headings https://knative.dev/development/eventing/flows/sequence/ — 
- [x] Fix broken numbering https://knative.dev/docs/eventing/getting-started/#creating-event-consumers
- [x] Fix indentation https://knative.dev/docs/eventing/getting-started/#sending-events-to-the-broker
- [x] Remove definition list in https://knative.dev/docs/eventing/sinks/#about-sinks
- [x] 1. fix random number in step and 2. turn URL into a link https://knative.dev/development/eventing/observability/metrics/collecting-metrics/#setting-up-prometheus —
- [x] replace tiny h5 and h6 headings with different formatting https://knative.dev/development/eventing/troubleshooting/ —

**Comment by abrennan89** [comment]
@snneji is there anything else to be added to this list or is this issue ready to assign?

**Comment by snneji** [comment]
Hi @abrennan89, thanks for adding your items. I added a few items to the list that I noticed when doing the reorg.

**Comment by abrennan89** [comment]
The last point

>  replace tiny h5 and h6 headings with different formatting https://knative.dev/development/eventing/troubleshooting/ —

Is difficult to do without rewriting the whole section. I've tried to make these higher level headings for now, but I think this section needs a rewrite anyway / lots of editing under another issue.
