### ISSUE TITLE
Update website to new major version v8 of material-mkdocs

### ISSUE THREAD

**Issue by csantanapr** [knative/docs#4491]
We have being waiting to get support for [code annotations](https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#code-annotations)
![image](https://user-images.githubusercontent.com/1094878/142051866-3f125e0d-5f5b-4da9-b3c7-bcfe0ba6c031.png)

It looks like it would be included in [v8](https://github.com/squidfunk/mkdocs-material/releases/tag/8.0.0b1), currently, we use v7 we need to look at the [breaking changes](https://github.com/squidfunk/mkdocs-material/issues/3219)

/kind mkdocs

**Comment by csantanapr** [comment]
If you have intentions to work on this issue, wait until the first official release of v8.

@julz is this something I think you will enjoy working since you have the most experience with the build and structure

**Comment by csantanapr** [comment]
this is ready to be work on, martial mkdocs 8.x is now GA
https://squidfunk.github.io/mkdocs-material/changelog/#material-for-mkdocs

**Comment by julz** [comment]
I doubt this will make it to the top of my todo list soon and it's something other people could pick up, so I'll unassign myself and assign if I actually end up getting some time

/unassign
