### ISSUE TITLE
create a table with all the possible annotations for serving CR

### ISSUE THREAD

**Issue by csantanapr** [knative/docs#4506]
As I do more demos is hard to find what all the possible values config that can be put on a knative service

Let's use this issue to find all the annotations and links to the respective docs on the website. 
The idea is to have an index table.

After discussing with @dprotaso he agrees this is a good idea.

**Comment by dprotaso** [comment]
/unassign @dprotaso

I'm not actively working on this and all the annotations should be documented in other parts of the website as part of our 1.0 work
