### ISSUE TITLE
Where to find yaml cases for Services (Route, etc.) (including most configurations)  

### ISSUE THREAD

**Issue by fengqi2019** [knative/docs#4531]
Hello, where to find yaml cases for Services (Route, etc.) (including most configurations)  ?

**Comment by nak3** [comment]
Probably you are looking for this page https://knative.dev/docs/reference/api/serving-api/ ?

**Comment by snneji** [comment]
Hi @fengqi2019, did @nak3  answer your question? If so, you can close this issue.
