### ISSUE TITLE
Docs are missing Getting Started for developer contributors

### ISSUE THREAD

**Issue by aslom** [knative/docs#4538]
For new developers that want to work on Knative, finding exactly what they need to do is not easy. I have described the problem in details and listed different entrypoints in google doc: https://docs.google.com/document/d/1mFY2QdXUvhCORyVkhJtBOqWeYGOIxmJ-ltSPXWZRU3E/edit?usp=sharing

**Describe the change you'd like to see**
Docs like https://www.kubernetes.dev/docs/guide/ - maybe reference them and add only in what ways Knative is different then linking to specific projects for their own ways they have differences?

**Additional context**
Kubernetes docs: https://www.kubernetes.dev/docs/guide/
Related to https://github.com/knative/docs/issues/4339 ?

**Comment by kvmware** [comment]
Related issue https://github.com/knative/test-infra/issues/2946

**Comment by snneji** [comment]
@aslom I made PR https://github.com/knative/docs/pull/4544 that moves the contributor information onto the MkDocs site. 

I'm wondering whether it would be clearer if the link "Join the community" would say something like "Contribute to Knative"?

**Comment by abrennan89** [comment]
@snneji maybe the Community link should just be renamed to Contributing? https://knative.dev/docs/community/contributing/
Community doesn't really mean anything if you're not contributing anyway IMHO

**Comment by snneji** [comment]
@abrennan89 I like that. It's shorter than my suggestion above and still makes it clear what info can be found in the section.
