### ISSUE TITLE
istio is not configured with knative-serving properly if official knative istio controller is used

### ISSUE THREAD

**Issue by VinayGoudCheguri** [knative/docs#4550]
I have tried installing knative-serving and then configuring istio already existing in the cluster by applying the knative-istio-controller from (https://github.com/knative/net-istio/releases/download/knative-v1.0.0/net-istio.yaml). But, I end up with the IstioNotConfigured error.
 
I resolved this by adding a 3rd party knative-istio-controller from (https://github.com/knative/serving/blob/main/third_party/istio-latest/net-istio.yaml). I request the developers to look into it and resolve the issue with the official knative istio controller.

I'm using 
knative-v1.0.0
Istio-v1.9.5

**Comment by nak3** [comment]
Could you elaborate on `IstioNotConfigured` error? I think Knative Resources does not set the status.
The official release is a little bit behind the `third_party/istio-latest/net-istio.yaml` but it is same release actually.

**Comment by VinayGoudCheguri** [comment]
@nak3 Unfortunately I do not have any snapshots or error logs to share. But I remember, when I describe the knative service
I got the following output.

```
message: Ingress has not yet been reconciled.
reason: IngressNotConfigured
status: Unknown
```

**Comment by nak3** [comment]
Okay so `IngressNotConfigured` not `IstioNotConfigured`. There are several reasons but I don't see any problem in the official 1.0 release yaml. If no logs from your end, I think it is difficult to investigate the issue unfortunately.

**Comment by VinayGoudCheguri** [comment]
okay
