### ISSUE TITLE
SPIKE: Create a list of sections in the docs that should be snippets

### ISSUE THREAD

**Issue by snneji** [knative/docs#4557]
## Context

To prevent duplication in docs we are implementing a snippets feature.

## Tasks

1. Create a list of sections in the docs that should be snippets, where these should be reused / could reduce duplication. 
2. Do one of the following:
   - Implement the snippets for the identified sections, OR 
   - Make a new issue to implement snippets if the sections need heading offset and the offset feature has not yet been implemented in #4556.

**Comment by abrennan89** [comment]
Added Concepts section and updated Revision, Garbage collection, serving and eventing snippets:
- https://github.com/knative/docs/pull/5156
- https://github.com/knative/docs/pull/5155
- https://github.com/knative/docs/pull/5183
more to come

**Comment by abrennan89** [comment]
https://github.com/knative/docs/pull/5114 - the PDB part of this should be a snippet (note to self)

**Comment by abrennan89** [comment]
The docs keep growing so I think rather than trying to make this a list, let's just fix them as we go.
