### ISSUE TITLE
Samples listening on 8080 instead of $PORT

### ISSUE THREAD

**Issue by steren** [knative/docs#456]
https://github.com/knative/docs/tree/master/serving/samples/helloworld-go listens on a hardcoded 8080.
But what the Knative runtime contract says is to listen on the port defined by the `PORT` env var.

**Comment by steren** [comment]
Others are doing this too, for example, the Ruby one is overriding the PORT env var in the Dockerfile: https://github.com/knative/docs/blob/master/serving/samples/helloworld-ruby/Dockerfile#L11

**Comment by steren** [comment]
@averikitsch @rgregg let's collaborate on this, using this issue to coordinate

**Comment by steren** [comment]
CC @grayside

**Comment by steren** [comment]
@mchmarny @samodell, when reviewing samples, make sure they do not hardcode 8080, as captured in the [runtime contract](https://github.com/knative/serving/blob/master/docs/runtime-contract.md#process)

**Comment by averikitsch** [comment]
Hello World Samples Reviewed: 
- [ ] Clojure
- [ ] C#
- [ ] Elixir
- [x] Go - @grayside 
- [ ] Haskell
- [ ] Java
- [x] Node.js - @grayside 
- [ ] PHP - @grayside ?
- [x] Python
- [ ] Ruby - @averikitsch 
- [ ] Rust

**Comment by grayside** [comment]
Opened a fix for PHP and I have work almost ready for Haskell and C#.

**Comment by grayside** [comment]
Is this issue limited to helloworld samples or should it encompass updates to ensure $PORT is respected by all samples?

**Comment by steren** [comment]
Let's keep this issue for the hello world, and open other ones for other samples. Hello world are the highest priority as we want to showcase in a few places.

**Comment by samodell** [comment]
@mikehelmick I see that you added the Elixir sample; would you be interested in making updates to that sample in line with this issue? We'd appreciate it!
