### ISSUE TITLE
Release docs for Knative v1.1

### ISSUE THREAD

**Issue by csantanapr** [knative/docs#4562]
Cut a release for 1.1

remaining versions would be main, 1.1, 1.0, 0.26, 0.24

Dependencies:

- [x] New community tab/pages revamp
- [x] Service 1.1
- [x] Eventing 1.1
- [x] Kn CLI 1.1
- [x] Operator 1.1
- [x] Kn Plugins 1.1 and Homebrew released

/assign

**Comment by csantanapr** [comment]
✅  New community is ready https://knative.dev/docs/community/

**Comment by csantanapr** [comment]
✅ Serving 1.1 ready https://github.com/knative/serving/releases/tag/knative-v1.1.0

**Comment by csantanapr** [comment]
💹 Eventing 1.1 ready https://github.com/knative/eventing/releases/tag/knative-v1.1.0

**Comment by csantanapr** [comment]
✅ Client (Kn CLI) 1.1 ready https://github.com/knative/client/releases/tag/knative-v1.1.0

**Comment by csantanapr** [comment]
✅ Kn homebrew plugins 1.1 ready https://github.com/knative-sandbox/homebrew-kn-plugins/pull/55

**Comment by csantanapr** [comment]
Operator v1.1 is not cut

**Comment by csantanapr** [comment]
✅ Operator 1.1 is ready https://github.com/knative/operator/releases/tag/knative-v1.1.0

**Comment by csantanapr** [comment]
Knative v1.1 Site is live ✨
https://knative.dev 🚀

**Comment by mcastilho** [comment]
Hey Carlos @csantanapr,

The links for the crds and core yamls are wrong. 

The urls below are not found
https://github.com/knative/serving/releases/download/release-1.1/serving-crds.yaml 

Shouldn't it be
https://github.com/knative/serving/releases/download/knative-v1.1.0/serving-crds.yaml

and so on..... for all the links

**Comment by csantanapr** [comment]
Your correct @mcastilho let me double check what went wrong

re-opening

cc @psschwei

**Comment by csantanapr** [comment]
It should be fix now @mcastilho 
![image](https://user-images.githubusercontent.com/1094878/146453686-e6b53ff8-0926-4036-9a73-a277fc084ae3.png)
