### ISSUE TITLE
 Knative 1.1 release notes blog post

### ISSUE THREAD

**Issue by csantanapr** [knative/docs#4570]
Consolidate all components and write a blog post similar to https://knative.dev/blog/releases/announcing-knative-v1-0-release/

**Comment by pierDipi** [comment]
@csantanapr let's make sure we thank release leads in the blog post!
It's a lot of work that deserves a mention!

**Comment by csantanapr** [comment]
>@csantanapr let's make sure we thank release leads in the blog post!
It's a lot of work that deserves a mention!

That's a great idea @pierDipi 👍

**Comment by FeynmanZhou** [comment]
Hi @csantanapr @pierDipi , how's this blog post going? I would like to write a piece of news on infoq.com to introduce Knative 1.1 and spread it to the community, this blog might be a good reference for me.

**Comment by csantanapr** [comment]
@FeynmanZhou Hi I was out on vacation and will be doing this week since no one picked this one up.
Take into account that next week is the release of 1.2

/assign
