### ISSUE TITLE
website banner for v1.0 doesn't show warning

### ISSUE THREAD

**Issue by csantanapr** [knative/docs#4593]
The warning message should show for the last oldest versions in this case 1.0, 0.26, and 0.25

Only shows up for 0.26 and 0.25 but not 1.0

https://knative.dev/v1.0-docs/
![image](https://user-images.githubusercontent.com/1094878/146453430-7692c887-9d8a-4fbb-afa0-975f55984ae0.png)

https://knative.dev/v0.26-docs/
https://knative.dev/v0.25-docs/
![image](https://user-images.githubusercontent.com/1094878/146453405-0379644c-49f3-49d1-a6fb-a58502a0ee65.png)

cc @psschwei

**Comment by psschwei** [comment]
Updating [overrides/main.html](https://github.com/knative/docs/blob/main/overrides/main.html#L7-L19) as follows should fix the issue:

```
{% block announce %}
{% if config.extra.version_warning %}
<div class="versionwarning" style="margin: .6rem auto; padding: 0 .8rem">
  <h1>⚠ You are viewing an archived snapshot of the documentation for Knative version: {{ config.extra.knative_version }}</h1>
  <p>
  Knative {{ config.extra.knative_version }} documentation is no longer actively maintained. The documentation you are currently viewing is a static snapshot. For up-to-date documentation, see <a href="{{ base_url }}/../docs/">the latest version</a>.
  </p>
</div>
{% else %}
<div class="versionwarning" style="display: flex; justify-content: center;">
  <p>Knative is 1.0! 🎉  Check out our announcement on the <a href=https://knative.dev/blog/articles/knative-1.0/>Knative Blog<a/></p>
</div>
{% endif %}
{% endblock %}
```

That _may_ need to be cherry-picked back into the 1.0 branch for the change to show up...

**Comment by psschwei** [comment]
Will PR later this evening

/assign
