### ISSUE TITLE
Update home page banner v1.1

### ISSUE THREAD

**Issue by csantanapr** [knative/docs#4596]
The default home page and version is now the new version v1.1 and it display a banner about the v1.0 milestone and links to the blog post. 

We should update the banner now. 

Some options:
- No banner
- Banner with a message about joining the Cncf with link to blog post
- Banner announcing new version v1.1 and links to the v1.1 release notes blog post (to be written soon)

**Comment by csantanapr** [comment]
cc @snneji @psschwei

**Comment by psschwei** [comment]
I think I like either a CNCF banner or no banner. I'd put the CNCF option slightly ahead, but I am a little worried about counting chickens before they've hatched...

Whatever option we decide, one change we'll need to make is to make sure that the old version warning is part of the announce block in `overrides/main.html`, i.e.

```
{% block announce %}
<!-- old version warning ->
<!-- banner on current version -->
{% endblock %}
```

(the old version warning being outside the announce block was what was causing it not to show on the 1.0 docs)

**Comment by snneji** [comment]
I vote for no banner. If we think joining the CNCF is very important for users to be alerted to, I would be OK with that option. 

Reasoning: 
- I think that a banner should be a temporary item for very important information. 
- I don't think we should always have a banner for the latest release. 
- It might just be me but I tend to ignore banners that are permanently at the top of a website, so I wouldn't notice if the info in the banner had changed. 
- Also, I'm not a fan of the look of the banner.

**Comment by snneji** [comment]
FYI @abrennan89 if you have an opinion on this matter, feel free to add it. 🙂

**Comment by psschwei** [comment]
>     * I think that a banner should be a temporary item for very important information.
> 
>     * I don't think we should always have a banner for the latest release.
> 
>     * It might just be me but I tend to ignore banners that are permanently at the top of a website, so I wouldn't notice if the info in the banner had changed.

+1

**Comment by csantanapr** [comment]
Sounds good let's remove the banner, next big announcement when we get accepted to cncf then we can put the banner up 
In this case we have time to design a more good looking banner and maybe some knative and cncf logos dancing of joy 😊

**Comment by csantanapr** [comment]
+1 remove banner from v1.1 and main

**Comment by psschwei** [comment]
I'll do it

/assign
