### ISSUE TITLE
Broken link in https://github.com/knative-sandbox/eventing-kogito/blob/main/README.md

### ISSUE THREAD

**Issue by hbelmiro** [knative/docs#4609]
Broken link in https://github.com/knative-sandbox/eventing-kogito/blob/f5f647f0e8411d87a08d225d2a1aeb61e9202aed/README.md?plain=1#L175

I'm creating a PR to correct it.

**Comment by snneji** [comment]
Closing as PR https://github.com/knative-sandbox/eventing-kogito/pull/68 has been merged
