### ISSUE TITLE
Broken link in the docs

### ISSUE THREAD

**Issue by souenzzo** [knative/docs#4610]
## Expected Behavior

From this URL

https://knative.dev/docs/reference/api/serving-api/#serving.knative.dev/v1.Service

When I click in this field `metadata Kubernetes meta/v1.ObjectMeta` I expect to be in a valid page with the docs for this field/object

## Actual Behavior

The anchor href is`https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#objectmeta-v1-meta` 
After some redirects I end up at `https://v1-18.docs.kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#objectmeta-v1-meta`
That shows me `Not Found - Request ID: 01FR6EDYAZ1M5KKN7YFJYWHC90` text/plain error

## Steps to Reproduce the Problem

1. click in https://knative.dev/docs/reference/api/serving-api/#serving.knative.dev/v1.Service
1. click in `metadata Kubernetes meta/v1.ObjectMeta` 
1.

## Additional Info
**Additional context**

**Install information:**
 - Platform (GKE, IKS, AKS, etc.): website/docs
 - Knative Version: website at 2021-12-30

**Comment by dprotaso** [comment]
yup that's it

**Comment by abrennan89** [comment]
@souenzzo these docs are actually updated automatically from the API spec, see the thread in Slack for details: https://knative.slack.com/archives/C0186KU7STW/p1642780832027500

Closing this issue since it will be updated once the changes to the API spec are merged. Not a docs issue.
