### ISSUE TITLE
Code Example for Updating Tags

### ISSUE THREAD

**Issue by BubbaJoe** [knative/docs#4626]
Hello, I just started using knative and i really like it. One thing that confuses me is the concept of tags in knative. Basically i want to control how rollbacks and deployments are relative to specific revisions using tags.

Use case: I want to have 2 tags: `current` and `prev`. Basically, i want to set `@current` to `prev`, and set revision123 tag to `current`. Also I want to avoid using the `@latest` revision, because there will be new revisions coming in frequently, and `current`/`prev` will most likely never be `@latest`

It would be nice to have more documentation and code examples on tags, so `kn` and `yaml`. I've seen the examples from blue /green docs, but i don't think they cover this use case.

**Comment by snneji** [comment]
Hi @BubbaJoe, thanks for submitting this issue. @nader-ziada, since you're on-call for knative.party this week, do you have a solution for this use case?

**Comment by nader-ziada** [comment]
hi @BubbaJoe 

Did you follow the example here in the docs https://knative.dev/docs/getting-started/first-traffic-split/ 

and this sample here https://github.com/knative/docs/tree/main/code-samples/serving/tag-header-based-routing 

As far as I understand you should be able to achieve your goal.

**Comment by BubbaJoe** [comment]
@nader-ziada After doing a bit more research and testing. It seems that you can't reference a tag just by adding `@`. This only works with `@latest`.

I thought this was possible, perhaps this would be a cool feature though.

**Comment by snneji** [comment]
Hi @BubbaJoe, do you feel like your issue has been resolved or would you like a documentation change/clarification? If you feel like your issue is resolved you can close this docs issue. 

If you'd like to suggest a change to the tag feature, you can do so in the Serving repo: https://github.com/knative/serving/issues
