### ISSUE TITLE
Docs broken links

### ISSUE THREAD

**Issue by lionelvillard** [knative/docs#4644]
from https://github.com/knative/eventing/issues/5867

**Describe the bug**
There are broken links in documentation markdown files.

 **Expected behavior**
No broken link in documentation

 **To Reproduce**
https://gist.github.com/ahuret/4529b7c50eeff488d4e06b2a1bfdf644

 **Knative release version**

 **Additional context**
Add any other context about the problem here such as proposed priority

/cc @ahuret

**Comment by abrennan89** [comment]
@snneji can you split this up into smaller issues? There is a huge list of broken links in that gist and I think it's too much to assign to one person at a time.

**Comment by snneji** [comment]
@lionelvillard the files in the gist look like they are in the Eventing repo. Should this issue be moved to Eventing?
