### ISSUE TITLE
rust samples do not terminate locally with ^C

### ISSUE THREAD

**Issue by grayside** [knative/docs#466]
## Expected Behavior

When using Docker to run a container based on the helloworld-rust sample, it is possible to terminate the container using ^C instead if solely relying on `docker stop`.

## Actual Behavior

Rust binaries do not respect ^C and a non-detached docker run will hold the foreground.

## Steps to Reproduce the Problem

1. cd serving/samples/helloworld-rust
2. docker build --tag hellorust .
3. docker run --rm -p 8080:8080 hellorust
4. ^C^C^C^C^C

## Additional Info

I gave https://github.com/Detegr/rust-ctrlc a quick try but it didn't help. It seems to be related to Docker signal propagation to the rust base image.

This is unlike most other helloworld samples, and makes it more difficult for developers to explore the rust sample.

**Comment by RichieEscarez** [comment]
We should also consider adding mention that the steps for using Docker to build the container image is the local alternative to creating/using a build template with the Knative Build component to run on-cluster image builds -> we need to better highlight that the on-cluster build option is possible (and that using local Docker is not the only way).

This is the one example i know of (haven't looked to find others): https://github.com/knative/docs/tree/master/serving/samples/source-to-url-go

**Comment by RichieEscarez** [comment]
These files have moved to /community: https://github.com/knative/docs/tree/master/community/samples/serving

Closing due to age.
