### ISSUE TITLE
Graphic updates for the Home page

### ISSUE THREAD

**Issue by csantanapr** [knative/docs#4669]
We wanted to add some diagrams and icons to the home page.

Here is the guidance for the design provided by the contractor Lionsway we worked with.
[Home Page Design Updates Jan-2022.pdf](https://github.com/knative/docs/files/7936851/Home.Page.Design.Updates.Jan-2022.pdf)

And they also provided the graphics assets
[Knative Web Assets.zip](https://github.com/knative/docs/files/7936849/Knative.Web.Assets.zip)

**Comment by csantanapr** [comment]
These icons have 2 states, they change with mouse over
![image](https://user-images.githubusercontent.com/1094878/151054219-73e8d944-1f6d-4c52-851f-66dc0118065b.png)

**Comment by gabo1208** [comment]
I'm helping with this, but anyone interested ping me to see if I can help you and how we can distribute the work :)
