### ISSUE TITLE
helloworld-haskell has no logging

### ISSUE THREAD

**Issue by grayside** [knative/docs#467]
## Expected Behavior

All helloworld samples should have some basic logging indicating the application has successfully started. It is more optional to have logging of individual requests but that is also standard.

## Actual Behavior

Haskell has no stdout/stderr logging.

## Steps to Reproduce the Problem

1. cd serving/samples/helloworld-haskell
2. docker build --tag hello-haskell .
3. docker run --rm -p 8080:8080 hello-haskell
4. See no log output.

**Comment by samodell** [comment]
Haskell was moved into the community samples folder and isn't considered one of our top-priority languages, so closing this for now.
