### ISSUE TITLE
Update monitoring installation guides as part of 0.2 release

### ISSUE THREAD

**Issue by mdemirhan** [knative/docs#469]
Monitoring components are getting refactored (https://github.com/knative/serving/pull/2169) and the installation instructions need to reflect the changes that will be pulled as part of 0.2 release.

**Comment by RichieEscarez** [comment]
I will incorporate this into my efforts around revising the logging and monitoring topics (#447)

**Comment by RichieEscarez** [comment]
Fixed by #763 (observability plugins now use manifest files)
