### ISSUE TITLE
Quickstart command for minikube doesn't work

### ISSUE THREAD

**Issue by snneji** [knative/docs#4696]
## Expected Behavior
Running the command `kn quickstart minikube` as documented works.

## Actual Behavior
Running `kn quickstart minikube` results in error: 

```
Error: unknown command "minikube" for "kn-quickstart"
Run 'kn-quickstart --help' for usage.
unknown command "minikube" for "kn-quickstart"
Error: exit status 1
```
However, the command `kn-quickstart minikube` does work.

## Steps to Reproduce the Problem

1. Follow the instructions to install minikube, kn, and the quickstart plugin on https://knative.dev/docs/getting-started/ 
1. Run `kn quickstart minikube` 

## Additional Info
**Additional context**
Interestingly, both `kn quickstart kind` and  `kn-quickstart kind` work for me.

**Install information:**
 - quickstart plugin v1.2.0
 - kn v1.2.0

**Comment by psschwei** [comment]
Hmmm.... it works as expected for me

```bash
$ kn quickstart version
Version:      v1.2.0
Build Date:   2022-01-26 14:12:59
Git Revision: 8ec0ac6

$ kn quickstart minikube
Running Knative Quickstart using Minikube
Minikube version is: v1.25.1

☸ Creating Minikube cluster...

```

I wonder if you have multiple versions of the plugin installed (?) -- do `kn quickstart version` and `kn-quickstart version` show the same output?

**Comment by snneji** [comment]
I get the following output:

```
$ kn-quickstart version
Version:      v1.2.0
Build Date:   2022-01-26 14:12:59
Git Revision: 8ec0ac6
```

```
$ kn quickstart version
Version:
Build Date:
Git Revision:
```

**Comment by psschwei** [comment]
Ok, that looks like `kn` isn't finding the v1.2 version of the plugin (the no version/date/revision info was something we fixed a few releases back). 

Check if the quickstart listed by `kn plugin list` matches the location of `which kn-quickstart`. 

My guess is you probably need to `brew upgrade` the plugin rather than `brew install`, since you had a version on there previously.

**Comment by snneji** [comment]
Yep, that seemed to be the problem, thanks! I got rid of the old install I still had. 

Do you think this needs to be documented or is this an edge case?

**Comment by psschwei** [comment]
It's probably worth putting in a note about upgrading, similar to [what we do for `kn`](https://github.com/knative/docs/blob/main/docs/snippets/install-kn.md?plain=1#L10-L11)
