### ISSUE TITLE
Creating services page has broken formatting

### ISSUE THREAD

**Issue by abrennan89** [knative/docs#4703]
## Expected Behavior

Formatting on numbered steps and tabs correct

## Actual Behavior

https://knative.dev/docs/serving/services/creating-services/
The numbered steps and tabs on this page appear to be broken

## Steps to Reproduce the Problem

1. Go to https://knative.dev/docs/serving/services/creating-services/

**Comment by tomleah** [comment]
Hi, I'm happy to take a look at this as a first issue 😄 

I see the numbered steps problem, but what do you mean by the tabs being broken?

**Comment by abrennan89** [comment]
Hey @tomleah - the tabs for YAML and CLI should be side by side tabs instead of one after the other. 
![image](https://user-images.githubusercontent.com/40172997/155415192-42e27657-6535-4e1a-8dad-e48bb8298a19.png)

Here's an example of how the tabs should look: https://knative.dev/docs/serving/services/http-protocol/#overriding-the-default-http-behavior

Thanks!

**Comment by tomleah** [comment]
Thanks @abrennan89! 

Something like this then?

![image](https://user-images.githubusercontent.com/5465397/155416177-a7490c41-0a84-4e03-88e4-316b7f06f2c1.png)

**Comment by abrennan89** [comment]
Exactly 🙂
