### ISSUE TITLE
Consider paring down the serving examples?

### ISSUE THREAD

**Issue by krancour** [knative/docs#471]
Considering that Knative Serving doesn't really care at all what's inside your container... why are there so many "Hello, World!" examples?

I could maybe understand the purpose behind this if each happened to be demonstrating the use of a different buildpack, but that doesn't seem to be the case since the documentation for each seems to show pre-building and publishing the images with `docker build` and `docker push`.

Aren't these potentially adding maintenance burden without adding much concrete value?

I'd even go as far as to propose that these distract from the few examples that are more meaningful because they're demonstrating something more unique, such as source-to-URL, source-to-URL with a private repo, a working GitHub webhook, etc.

**Comment by krancour** [comment]
I think that makes good sense. 👍

**Comment by samodell** [comment]
I like Dewitt's suggestion. This would also be a good topic for the Documentation working group meeting, if you wanted to bring it up there.

**Comment by RichieEscarez** [comment]
It was recently brought to my attention that not all samples (including "Hello World") utilize the on-cluster container image build through the Knative Build component, nor mention that having the Build component installed is a requirement (especially now that Serving 0.2 no longer has a Build component dependency). When these files get reorganized, we should also take into account how to communicate which sample require the Build component (easier) and which require you to build the container image locally (more steps).

**Comment by RichieEscarez** [comment]
Status: This is partially in progress as part of the website restructure: https://github.com/knative/docs/tree/release-0.3/docs/serving/samples/hello-world

Todo: Clarify and communicate which Hello World samples utilize the Knative Build component (vs. Docker build/push)
