### ISSUE TITLE
kn install snippet suggests both `brew install` and `brew upgrade`

### ISSUE THREAD

**Issue by starpit** [knative/docs#4727]
## Expected Behavior

I wasn't sure whether to categorize this as a bug or a feature request... 

The documentation suggests that users should try both `brew install kn` *and* `brew upgrade kn`. Whereas `brew install` will check for upgrades by default. From the standpoint of understandability, the current site renders these as two consecutive code blocks, giving the appearance the *both* should be executed.

Screenshot of current knative docs web site:

<img width="631" alt="Screen Shot 2022-02-10 at 7 38 01 PM" src="https://user-images.githubusercontent.com/4741620/153520585-19d44ca4-d0f6-40a7-9b3f-3733625004ce.png">

From the `brew install -h` output:

```
Usage: brew install [options] formula|cask [...]

Install a formula or cask. Additional options specific to a formula may be
appended to the command.

Unless HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK is set, brew upgrade or brew
reinstall will be run for outdated dependents and dependents with broken
linkage, respectively.
```

## Actual Behavior

I think we can reduce clutter and potential for confusion by suggesting only `brew install kn`. Thoughts?

## Steps to Reproduce the Problem

n/a

## Additional Info
**Additional context**

**Install information:**
 - Platform (GKE, IKS, AKS, etc.): any
 - Knative Version: any

**Comment by snneji** [comment]
I can add "Do one of the following" before the command to show that you don't have to do both. 

The second bullet point was added to fix an issue where running `brew install` while having an existing install caused the new version to install as well as leaving the old version available.

**Comment by starpit** [comment]
Howdy! That makes sense. What about putting it under an expandable section? To me, this would make it even more clear that the instal/upgrade dischotomy is a discrete choice to be made?
<img width="723" alt="Screen Shot 2022-02-15 at 12 53 59 PM" src="https://user-images.githubusercontent.com/4741620/154120603-c40d1175-985c-403e-a6da-a93d51942178.png">

**Comment by snneji** [comment]
Hi @starpit, we made the decision to not use a note because notes are easy to ignore. 

Also, we would like users to use the upgrade command instead of the install command in the case of having an existing install. Having the note after the install command might mean that users only read the note _after_ running the install command.

Do you think this suggestion would fix the issue:

<img width="856" alt="Screen Shot 2022-02-17 at 12 07 18" src="https://user-images.githubusercontent.com/33425661/154478723-f792c57b-446f-4987-8dc2-c996d4ad2d2f.png">

**Comment by starpit** [comment]
Hiya, thanks for the consideration!

The underlying issue we are addressing is this: how can a human (or machine) consumer of the documentation know which code blocks are a) **necessary** versus b) **optional** versus c) one from a selection of **choices**.

Almost universally, the knative documentation expresses choice via a Tab UI. You screenshot shows an example of this. And optional code blocks are nicely represented nested inside of closed tip sections.

This install-versus-upgrade scenario is another choice, in this case a sub-choice of the main Homebrew choice. However, you have inconsistently rendered it using natural language rather than a Tab UI.

As a consequence, a machine consumer of the system would not be able to know to offer the user this as a choice, because it won't got through the effort of trying to parse out natural language to figure out what's really being asked.

I think most humans are the same. When we are consuming documentation like this, we tend to just copy and paste the code blocks, with a bit less attention to the details... precisely because we assume that the documentation is rendered in such a way that choice is expressed explicitly via UI elements, e.g. via a Tab UI.

How about this idea?

<img width="717" alt="Screen Shot 2022-02-17 at 7 29 11 AM" src="https://user-images.githubusercontent.com/4741620/154482030-a75473e9-89b4-4119-b5f5-6e116e31385c.png">

**Comment by abrennan89** [comment]
Docs are now updated: https://knative.dev/docs/install/quickstart-install/#install-the-knative-cli
