### ISSUE TITLE
Serving Defaults configmap should document the field names being defaulted.

### ISSUE THREAD

**Issue by mattmoor** [knative/docs#4732]
**Describe the change you'd like to see**
I noticed that the default entries like `revision-timeout-seconds` here: https://knative.dev/docs/serving/configuration/config-defaults/ to not actually specify the fields being defaulted.

**Additional context**
I really like the way this was solved in autoscaling where it talks about global configuration as well as per-revision: https://knative.dev/docs/serving/autoscaling/scale-bounds/#lower-bound

**Comment by mattmoor** [comment]
cc @dprotaso

**Comment by csantanapr** [comment]
@mattmoor your referring to the examples having the 3 versions?
Like this one?
![image](https://user-images.githubusercontent.com/1094878/154191774-efcfa8fd-2dc2-423a-bcd5-f0c872f5777f.png)

**Comment by mattmoor** [comment]
Yeah, but even when the example isn't there the bit above that has the different categories consistently: 
<img width="683" alt="image" src="https://user-images.githubusercontent.com/2442466/154200687-9427ea8a-c4c6-4880-8ca0-ec06a1d04176.png">
