### ISSUE TITLE
Wrong output on traffic split example tab

### ISSUE THREAD

**Issue by gabo1208** [knative/docs#4736]
**Describe the change you'd like to see**
https://knative.dev/docs/getting-started/first-traffic-split/#splitting-traffic
The spected output when you click the kubectl tab is wrong, it keeps the same output as the one on the kn CLI tab, i.e. it shows the TRAFFIC column that is specific to kn CLI

**Comment by snneji** [comment]
Hi, Thanks for the noticing this. I'm going to move that output under the `kn` tab. I'm currently working on a PR to edit this tutorial and will fix this as part of that PR.

/assign
