### ISSUE TITLE
Make it clear that Knative doesn't limit the use of different Kubernetes runtimes

### ISSUE THREAD

**Issue by csantanapr** [knative/docs#4738]
Feedback from CNCF TOC member Emily Fox during CNCF due diligence review.
>Emily Fox - KCCN Co-Chair Today at 10:14 AM
@dims - Do you know if knative has any plans to extend Knative Functions (in development) to leverage some form of container isolation or be compatible with it? I don't see any references to this in their issues or DD doc, however i did come across #12533 (recently opened) to explore true multi-tenancy.

>[Emily Fox](https://app.slack.com/team/U033865RGBW)  [23 minutes ago](https://knative.slack.com/archives/CUU6LEMRT/p1644938991445259?thread_ts=1644851983.040169&cid=CUU6LEMRT)
Thanks all for the discussion, I’d love to see some of this referenced in the existing docs to ensure users are aware that there are not limitations in this regard.

We could add in the docs some information to make users aware that there is no limitations on terms of Kuberentes runtime, that they can use any runtime supported by the Kubernetes cluster they install Knative.
The user can configure this in their Knative Service annotation
https://deploy-preview-4715--knative.netlify.app/development/serving/configuration/feature-flags/#kubernetes-runtime-class
```
apiVersion: serving.knative.dev/v1
kind: Service
...
spec:
  template:
    spec:
      runtimeClassName: myclass
...
```
This will set the runtimeClassName on the Pod to be created. 

Maybe we add a sentence under [Serving](https://deploy-preview-4715--knative.netlify.app/development/serving/services/#additional-resources) or maybe a blog post on how to configure a runtime and use it in Knative for example "gvisor"

**Comment by abrennan89** [comment]
It looks like this was asked specifically wrt Functions, so it would be dependent IMO on https://github.com/knative/docs/issues/5038 and the outcome of SC discussions about how Functions is marketed, how it fits into our docs overall etc.
Marking as blocked for now until this information is available.
