### ISSUE TITLE
eventing-kafka-controller.yaml not found

### ISSUE THREAD

**Issue by yedamao** [knative/docs#4786]
## Expected Behavior
get the yaml file successfully
## Actual Behavior
```
kubectl apply --filename https://github.com/knative-sandbox/eventing-kafka-broker/releases/download/knative-v1.2.0/eventing-kafka-controller.yaml
error: unable to read URL "https://github.com/knative-sandbox/eventing-kafka-broker/releases/download/knative-v1.2.0/eventing-kafka-controller.yaml", server reported 404 Not Found, status code=404
```

## Steps to Reproduce the Problem

1. kubectl apply --filename https://github.com/knative-sandbox/eventing-kafka-broker/releases/download/knative-v1.2.0/eventing-kafka-controller.yaml

## Additional Info
**Additional context**
change the tag number to v1.2.3, it installed successfully.

**Install information:**
 - Platform (GKE, IKS, AKS, etc.):
 - Knative Version:

**Comment by pierDipi** [comment]
Hi @yedamao, thanks for reporting!

Please use the latest patch release `knative-v1.2.3` 
```
kubectl apply --filename https://github.com/knative-sandbox/eventing-kafka-broker/releases/download/knative-v1.2.3/eventing-kafka-controller.yaml
```
