### ISSUE TITLE
Sentence in knative serving doc in incomplete.

### ISSUE THREAD

**Issue by hamees-sayed** [knative/docs#4803]
Under the "Warning" before the word "challenge" a sentence is missing. The sentence that has to be added is "_Provisioning a certificate_ _per namespace only works with DNS-01_ challenge. "

Link: https://knative.dev/development/serving/using-auto-tls/#provising-certificates-per-namespace-wildcard-certificates

**Comment by snneji** [comment]
Seems like we need to fix the note formatting here. 🙂 

The correct syntax is as follows: After opening the note with `!!! warning`, you must add a new line and indent the note text by 4 spaces, for example:

```
!!! warning
    Add note text here.
```
