### ISSUE TITLE
Doc request: Describe User Authentication with Istio for the Knative broker

### ISSUE THREAD

**Issue by matzew** [knative/docs#4824]
Document how to protect a Knative Broker with JSON Web Token (JWT) and Istio, using the `AuthorizationPolicy` and `RequestAuthentication` types from istio

**Comment by abrennan89** [comment]
@matzew it depends on whether admin permissions are required for any of the steps included here?
For now I will put it in the developer section, but let me know if you think it requires admin permissions.
