### ISSUE TITLE
Add github action to trigger the netlify build for release branches

### ISSUE THREAD

**Issue by csantanapr** [knative/docs#4840]
Currently the netlify build is triggered only when a change is committed to the `main` branch but not when is committed to one of the release branches.

We can create a github action that triggers on a push to a `release-*` branch and do `curl` to the endpoint to netlify to trigger a build using the `main` branch

Reference: [Netlify Build Hooks](https://docs.netlify.com/configure-builds/build-hooks/)

**Comment by psschwei** [comment]
I'll give this a try...

/assign
