### ISSUE TITLE
Add install link to Eventing and Serving overview pages

### ISSUE THREAD

**Issue by snneji** [knative/docs#4848]
## Task

Add a link to the installation docs on the [Serving overview](https://knative.dev/docs/serving/) and [Eventing overview](https://knative.dev/docs/eventing/) pages.

**Comment by jasonsmithio** [comment]
I'd be happy to take it

**Comment by abrennan89** [comment]
Seems like it was closed by https://github.com/knative/docs/pull/4853 but the magic words weren't used to link them
