### ISSUE TITLE
`ingress.class` or `ingress-class` in config-network config map

### ISSUE THREAD

**Issue by Legion2** [knative/docs#4855]
The "Install a networking layer" documentation describes how to set the correct ingress class in the config-network config map for the different network options (kourier, istio and contour). However, the documentation is inconsistent:
kourier: 
```
'{"data":{"ingress.class":"kourier.ingress.networking.knative.dev"}}'
```
contour:
```
'{"data":{"ingress-class":"contour.ingress.networking.knative.dev"}}'
```
`ingress.class` vs `ingress-class`, what is the correct key?

**Describe the change you'd like to see**
The documentation should be consistent. If both options are valid, choose one for the documentation. If not both options are valid, replace the invalid option with the correct one.

May also add this to the istio section, to make the default value explicit.

**Comment by nak3** [comment]
Thank you for your report.
https://github.com/knative/docs/pull/4858 and https://github.com/knative/docs/pull/4859 will fix it.
