### ISSUE TITLE
kubectl apply -f filename.yaml

### ISSUE THREAD

**Issue by Subhasish-Behera** [knative/docs#4870]
its not working while using this doc: https://knative.dev/docs/eventing/getting-started/
kubectl apply -f filename.yaml
error: unable to recognize "knativereq3.yaml": no matches for kind "Broker" in version "eventing.knative.dev/v1"

**Comment by psschwei** [comment]
How did you install Knative?

Which part of that page is causing the issue?

**Comment by Subhasish-Behera** [comment]
Thanks for quick response.
I haven't installed knative yet.
I have just created the event example namespace.
Then I created a yaml file knativereq.yaml in which I copied the yaml code
from https://knative.dev/docs/eventing/getting-started/.
Then when I  tried kubectl apply I got the error : unable to recognize
knativereq.yaml . No matches for kind broker in version '
eventing.knative.dev/v1'

**Comment by psschwei** [comment]
Ok, that's why. You'll need to install Knative before running any of the steps from that page.

I'd recommend using our [quickstart](https://knative.dev/docs/install/quickstart-install/) tool... it sets up a Knative cluster locally using either Kind or Minikube in just a couple of minutes.

**Comment by Subhasish-Behera** [comment]
Got it. Sorry I am a noob. Will try it immediately.

**Comment by psschwei** [comment]
No worries, we all were at one time or another :smile:
