### ISSUE TITLE
Usability pain point: Cannot link to a tab within a page

### ISSUE THREAD

**Issue by RichieEscarez** [knative/docs#4873]
Several pages include a tabbed table, for example: https://knative.dev/docs/install/yaml-install/serving/install-serving-with-yaml/#install-a-networking-layer

But if there is a specific requirement other than the default tab, the page does not allow linking to a specific tab so show the required context/option.

Can anchors or page behaviors be improved to help get Knative users to the only the relevant/require info?

**Comment by abrennan89** [comment]
I've opened an issue for Material for this after discussions on Twitter about it, but for now I don't think there's really anything we can do on this.

Issue: https://github.com/squidfunk/mkdocs-material/issues/3976
