### ISSUE TITLE
Update website to be dual license

### ISSUE THREAD

**Issue by csantanapr** [knative/docs#4878]
With the move to the CNCF there is this CNCF IP Policy stipulation
https://github.com/cncf/foundation/blob/main/charter.md#11-ip-policy

(f) All documentation will be received and made available by the CNCF under the Creative Commons Attribution 4.0 International License.

Please update the footer of the website to state the license Documentation Distributed under [CC BY 4.0]
link to a file served on the website with the License. 
The default Apache 2 LICENSE file can remain in the github repo and an additional license can be added to the `docs/...` directory for the rendered documentation.

**Comment by lance** [comment]
Related: https://github.com/knative/community/pull/985

The recommendation from CNCF is to have a `LICENSE` and `LICENSE-docs` file
