### ISSUE TITLE
Wrong API version in KinD cluster spec for local knative dev

### ISSUE THREAD

**Issue by dgeorgievski** [knative/docs#4880]
## Expected Behavior
Able to create a KinD Knative cluster using the spec defined in the documentatoin
https://knative.dev/blog/articles/set-up-a-local-knative-environment-with-kind/#step-1-setting-up-your-kubernetes-deployment-using-kind

## Actual Behavior
Failed KinD cluster creation

```
$ cat > clusterconfig.yaml <<EOF
kind: Cluster
apiVersion: kind.sigs.k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
    ## expose port 31380 of the node to port 80 on the host
  - containerPort: 31080
    hostPort: 80
    ## expose port 31443 of the node to port 443 on the host
  - containerPort: 31443
    hostPort: 443
EOF

$ kind create cluster --name knative --config clusterconfig.yaml
ERROR: failed to create cluster: unknown apiVersion: kind.sigs.k8s.io/v1alpha4

$ kind version
kind v0.11.1 go1.16.6 darwin/amd64
```

## Steps to Reproduce the Problem
See above

## Additional Info
**Additional context**
Fixed the issue by replacing KinD clsuter API to
`apiVersion: kind.x-k8s.io/v1alpha4`

**Install information:**
 - Platform (GKE, IKS, AKS, etc.): Kind v0.11.1
 - Knative Version: 1.0.0

**Comment by psschwei** [comment]
Since the quickstart plugin is now the recommended way to set up Knative on Kind, maybe we want to sunset this blog post?
