### ISSUE TITLE
Installing the Knative quickstart plugin using binary is missing steps that links it as a plugin to kn

### ISSUE THREAD

**Issue by achyutm6** [knative/docs#4884]
**Describe the change you'd like to see**
In the docs at - https://knative.dev/docs/install/quickstart-install/#install-the-knative-quickstart-plugin . The "Using a binary" section is missing steps to link the kn-quickstart plugin to kn cli. I would suggest adding steps which are clearly mentioned in the kn-plugin-quickstart to this doc to avoid any confusion.

```
You can install it as a plugin of the kn client to run:
Copy the kn-quickstart binary to a directory on your PATH (for example, /usr/local/bin) and make sure its filename is kn-quickstart
Run kn plugin list to verify that the kn-quickstart plugin is installed successfully
```

**Comment by snneji** [comment]
Hi @achyutm6, is the missing step:
> Rename the file to remove the OS and architecture information. For example, rename kn-quickstart-darwin-amd64 to kn-quickstart.
