### ISSUE TITLE
"Installing Knative using the Operator" not working

### ISSUE THREAD

**Issue by hbelmiro** [knative/docs#4885]
The [Installing Knative using the Operator](https://knative.dev/docs/install/operator/knative-with-operators/) guide is not working.
When I reach the step [Verify the Knative Serving deployment](https://knative.dev/docs/install/operator/knative-with-operators/#verify-the-knative-serving-deployment) and run the following command:

````
kubectl get deployment -n knative-serving
````

It shows me the following output:

````
No resources found in knative-serving namespace.
````

I tried first with Kourier, but when I try to fetch it's external IP:
````
$ kubectl --namespace knative-serving get service kourier

Error from server (NotFound): services "kourier" not found
````

So, I tried with Istio:

````
$ kubectl get deployment -n knative-serving

No resources found in knative-serving namespace.
````

## Additional Info

**Install information:**
 - Platform (GKE, IKS, AKS, etc.): Minikube
 - Knative Version: 1.3.1
 - Fedora 35

**Comment by snneji** [comment]
Hi @houshengbo, would you be able to help out on this one?

**Comment by houshengbo** [comment]
I need more information on this issue.
What does the knative serving CR look like when installing knative serving?
Is knative operator running?
What is the log of knative-operator?

**Comment by hbelmiro** [comment]
@houshengbo I don't have that environment anymore. I was able to create the cluster by using the quickstart plugin.
Thank you.
