### ISSUE TITLE
The  Service URL of cloudevents player app in the tutorial section-->knative eventing-->using knative service as a source is not working.

### ISSUE THREAD

**Issue by Subhasish-Behera** [knative/docs#4886]
## Steps to Reproduce the Problem

1.
1.
1.

## Additional Info
**Additional context**

**Install information:**
 - Platform (GKE, IKS, AKS, etc.):
 - Knative Version:

**Comment by snneji** [comment]
Hi @Subhasish-Behera, are you using minikube or kind?

**Comment by Subhasish-Behera** [comment]
Understandable. I am using minikube .
