### ISSUE TITLE
in doc-->eventing-->developer topics-->Event source-->kafka source, there is a error 

### ISSUE THREAD

**Issue by Subhasish-Behera** [knative/docs#4891]
in the command :cd knative-docs/code-samples/eventing/Kafka/source. there actually exists no directory called source inside kafka.Instead there is a directory called binding where already a file event-display.YAML is present.So there are 3 problems
1. in the instructions It is instructed to make a file but actually not needed.
2. The file in event _display.yaml there is no namespace: default
3. even after adding namespace its not working
![Screenshot 2022-04-01 031900](https://user-images.githubusercontent.com/92573882/161155270-dcb24d0c-33a3-48b2-b4ea-34f59d45a98e.png)
 
plz comment if my issue is valid

**Comment by snneji** [comment]
Hi @pierDipi, since your on call on Knative.party, could you help out on @Subhasish-Behera's questions? 

I'm also wondering whether step 1 of the [Create a Service](https://knative.dev/docs/eventing/sources/kafka-source/#create-a-service) procedure is even required since the YAML files seem to be provided in the docs.

**Comment by Subhasish-Behera** [comment]
Hello @snneji, I was thinking if I could make any PR regarding this issue . I am a beginner to open source . I would like to start with this issue.

**Comment by snneji** [comment]
@Subhasish-Behera yes, we would welcome you to create a PR to fix this issue! 

If you would like information on how to get started working on the Knative documentation, see the [docs contributor guide](https://github.com/knative/docs/tree/main/contribute-to-docs), especially the getting started section of the guide.

**Comment by pierDipi** [comment]
Hi @Subhasish-Behera, I think we can just remove step 1 [1] in https://knative.dev/docs/eventing/sources/kafka-source/#create-a-service because there is no need to close the code samples to follow the example.

exactly this [1]
```
Clone the sample code GitHub repository, and navigate to the local directory of the repository:


git clone -b "release-1.3" https://github.com/knative/docs knative-docs

cd knative-docs/code-samples/eventing/kafka/source
```

**Comment by pierDipi** [comment]
If you get stuck on something or need help with a contribution, feel free to ask any questions!
