### ISSUE TITLE
Eventing Sugar Controller Integration

### ISSUE THREAD

**Issue by xtreme-sameer-vohra** [knative/docs#4896]
## What is changing? (Please include as many details as possible.)
The sugar reconciler has been integrated into the base eventing controller and is now controlled by two LabelSelector fields.

## How will this impact our users?
The Sugar controller can be used much more flexibly with the changes. The Sugar controller's legacy behaviour can be replicated, however the steps to do that will change.
The changes also require an update to our [Sugar Controller Installation & Usage docs](https://knative.dev/docs/eventing/sugar/#trigger-example)

## In what release will this take happen (to the best of your knowledge)?
v1.4

## Context
Link to associated PRs or issues from other repos here.
1. PR - https://github.com/knative/eventing/pull/6027

**Comment by odacremolbap** [comment]
@xtreme-sameer-vohra just notice this doc update is pending while the release is happening next week.
Would you have cycles for this?

**Comment by xtreme-sameer-vohra** [comment]
Hey @odacremolbap 
Thanks for the heads up 😬 , I'll take a look at this week.
