### ISSUE TITLE
Clarify the text on the homepage Developer and Cluster Admin buttons

### ISSUE THREAD

**Issue by snneji** [knative/docs#4905]
## Background
The buttons on the homepage currently say "Developer? Start Here!" and "Cluster Administrator? Start Here!". We have received feedback that this might be confusing if a user does not know which persona they are. Also, it does not tell the user where the buttons will take them.

## Task
Rename the buttons to describe were they will take the user: 
- Developer Button → Reword to say something like “Try the tutorial”
- Cluster Administrator Button → Reword to say something like “Install Knative on your cluster”

(Note: the URLs should stay the same.)

For example:
 
<img width="1056" alt="Screen Shot 2022-04-05 at 18 34 34" src="https://user-images.githubusercontent.com/33425661/161816215-d36917e6-4fc2-4ec1-b106-728486a6b326.png">

**Comment by karnatisrinivas** [comment]
If this is open, I would like to work on this!
