### ISSUE TITLE
Old Hugo website is still available

### ISSUE THREAD

**Issue by snneji** [knative/docs#4907]
The old Hugo website is still available at this location https://knative-v1.netlify.app/docs/ with docs for Knative versions 0.16 - 0.19

Shut down the site and create a redirect for any bookmarks/links users have to this old site.

**Comment by csantanapr** [comment]
Even if we want to, we don't own the domain or site for `knative-v1.netlify.app` we only own `knative.netlify.app` where we host the site today and this one doesn't have any hugo

**Comment by psschwei** [comment]
v0.19 was released in Nov 2020... maybe it was set up by one of the previous WG leads on a different account?

**Comment by psschwei** [comment]
The Hugo site also shows up in DuckDuckGo search results. For example, on a search for "knative/serving", it's the third result. Doesn't show up in Google though.

**Comment by csantanapr** [comment]
@RichieEscarez  Do you know if you have a personal or google netlify account this host `https://knative-v1.netlify.app/`?

**Comment by RichieEscarez** [comment]
Deleted. That was one of the initial staging sites we used to test build and website changes.

/close

**Comment by csantanapr** [comment]
Wow mystery solved ! Thanks @RichieEscarez
