### ISSUE TITLE
Broken links on setting-up-a-logging-plugin.md

### ISSUE THREAD

**Issue by ahmetb** [knative/docs#494]
https://github.com/knative/docs/blob/74ed0fd04aa8474111eff7ac470f9cae9d93882c/serving/setting-up-a-logging-plugin.md#configure-the-daemonset-for-stdoutstderr-logs

All links are broken in the `Configure the DaemonSet for stdout/stderr logs` section. Looks like they've been moved around.

**Comment by RichieEscarez** [comment]
Will fix this as part of #447

**Comment by RichieEscarez** [comment]
Closing - Fixed in master: https://github.com/knative/docs/blob/master/serving/setting-up-a-logging-plugin.md#configure-the-daemonset-for-stdoutstderr-logs
