### ISSUE TITLE
Broker Spec Link broken

### ISSUE THREAD

**Issue by embano1** [knative/docs#4942]
This link is broken:

https://github.com/knative/docs/blob/a3af1117802d6c70b403c32ebbcf173d95214114/docs/eventing/broker/README.md?plain=1#L55

Question: should it point to https://github.com/knative/specs/blob/main/specs/eventing/overview.md#broker since `broker.md` does not exist anymore?

**Comment by antoineco** [comment]
Addressed in #4970.
