### ISSUE TITLE
Update minimum CPU recommendation

### ISSUE THREAD

**Issue by psschwei** [knative/docs#4944]
We currently list the minimum system requirements as 2 CPU / 4 GB RAM in the [prereqs snippet](https://github.com/knative/docs/blob/main/docs/snippets/prerequisites.md?plain=1#L5), but as we've [seen with the quickstart plugin](https://github.com/knative-sandbox/kn-plugin-quickstart/issues/224#issuecomment-1086754010), 2 CPUs is not enough to install both Serving and Eventing. 

We should consider bumping the min recommended number of CPUs to 3. Open question as to whether we should only bump it in the "prototyping" section (see link above) or also update the ["multiple nodes" line in the "production" section](https://github.com/knative/docs/blob/main/docs/snippets/prerequisites.md?plain=1#L14).

**Comment by hamees-sayed** [comment]
I'd like to work on it! I believe we should update it in both prototype and production section since it is a fixed requirement for both production as well as prototyping.

**Comment by psschwei** [comment]
That's great @hamees-sayed !  You can assign the issue to yourself by writing `/assign @hamees-sayed` in a comment.
