### ISSUE TITLE
eventing-->developer topics --->custom-event-source--->Using Knative sample repository--->create a controller ,I am getting a error which says generate-group.sh does not exist

### ISSUE THREAD

**Issue by Subhasish-Behera** [knative/docs#4947]
![Screenshot-3](https://user-images.githubusercontent.com/92573882/166107225-89b69a6d-be43-4491-95bf-11cf24cec5d3.png)

**Comment by abrennan89** [comment]
@knative/eventing-wg-leads can you PTAL and let us know if any doc update is required here. Thanks.

**Comment by abrennan89** [comment]
Issue moved to [knative/eventing #6439](https://github.com/knative/eventing/issues/6439) via [**ZenHub**](https://www.zenhub.com/)
