### ISSUE TITLE
Is there any sample about websocket in the project?

### ISSUE THREAD

**Issue by wangXing2** [knative/docs#498]
## Expected Behavior
Hope  some examples about how to configure websocket.

## Actual Behavior
I have tried some experiments about using websocket, but failure.  I don't know whether knative support it or my configuration is error.

## Steps to Reproduce the Problem
nothing

**Comment by WLun001** [comment]
Any websocket sample?

**Comment by wangXing2** [comment]
I don't know yet.

**Comment by wangXing2** [comment]
> Any websocket sample?

I don't know yet.

**Comment by RichieEscarez** [comment]
Sample about websocket as an Eventing source https://github.com/knative/eventing-contrib/tree/master/cmd/websocketsource
