### ISSUE TITLE
Add introduction page for Serving in getting started / quickstart

### ISSUE THREAD

**Issue by abrennan89** [knative/docs#4994]
Currently only Eventing has a page like this: https://knative.dev/docs/getting-started/getting-started-eventing/

Serving goes straight into creating a service without providing the same sort of introduction.

**Describe the change you'd like to see**

Add a page similar to this for Serving.

OR

Should we reconsider having this info in the tutorial at all, and instead point out to the overview docs (e.g. https://knative.dev/docs/serving/) for conceptual information?
Either way this should be equal and consistent for both components, i.e. either both should have an overview page as well as an intro / concepts page in the tutorial, or neither should have a conceptual page like this in the tutorial and all that info should be in the overview which we point out to instead.

**Comment by rolfedh** [comment]
I'm coaching @AmanSarraf a bit on the Kubernetes localization project for Hindi. Kindly let me know if I can help out with anything.

**Comment by AmanSarraf** [comment]
I added a getting-started-serving page, 
![2022-07-22_04-45](https://user-images.githubusercontent.com/90839355/180330449-6d05fe52-5063-4a1a-b2ea-213e990bf868.png)

I want to add the footer like other pages with the next and previous topics listed and also how to link this standalone page with others

**Comment by abrennan89** [comment]
@AmanSarraf AFAIK they should be added by default - can you open a PR with the changes and link it to this issue so I can take a look?

**Comment by abrennan89** [comment]
I think this issue is sort of obsolete now, since we're revisiting how we do the quickstart and tutorials in general, in light on [conversations](https://knative.slack.com/archives/C9CV04DNJ/p1661535428082209) on Slack and the addition of Functions.
