### ISSUE TITLE
Document knative operator to serving version mapping

### ISSUE THREAD

**Issue by psschwei** [knative/docs#4997]
Consolidation of https://github.com/knative/operator/issues/1096 and https://github.com/knative/serving/issues/12989

From the serving issue: 

Hi, we don't see any documentation on which knative-serving resources are supported by the operator, and assumed that it would be one-on-one compatible. However, they are not and it is confusing:

| operator version | serving version | compatible? |
| --- | --- | --- |
| 1.4.1 | 1.4.1 | NO |
| 1.4.1 | 1.4.0 | YES |
| 1.3.2 | 1.3.2 | NO |
| 1.3.2 | 1.3.1 | YES |

Can we PLEASE get such a matrix published somewhere in your knative.dev docs? Trial and error approach here is costing us all time and frustration.

**Comment by psschwei** [comment]
FYI @houshengbo

**Comment by houshengbo** [comment]
We only align the patch number on 0, like x.x.0.
Knative operator can evolve in each minor release to fix some major bugs, so 1.4.1 does not necessarily mean to install 1 serving or eventing 1.4.1. It can be knative operator's pace to release 1.4.1, but only install 1.4.0 serving, since serving does not have 1.4.1.

**Comment by Morriz** [comment]
So how can a new version of knative-serving resource be deployed by the operator then? I presume we can somehow, otherwise we'd be left in the cold and vulnerable?

**Comment by Morriz** [comment]
Ok, after careful reading of what you say @houshengbo, I understand there is no logical connection between the operator version and the `knative-(eventing|serving)` versions? Even though they seem related? Then indeed we would need a compatibility table/matrix, right?

**Comment by abrennan89** [comment]
@houshengbo added a PR for this for 1.5; if required an issue should be opened to add a table for each version going forward. This should be maintained by eng IMO, not docs.
