### ISSUE TITLE
Adds links to files on the installation files pages

### ISSUE THREAD

**Issue by psschwei** [knative/docs#4998]
We currently have pages that describe the various files needed to install serving/eventing via yaml files:

https://knative.dev/docs/install/yaml-install/serving/serving-installation-files/
https://knative.dev/docs/install/yaml-install/eventing/eventing-installation-files/

However, right now these page simply show the file name, which may leave users wondering where they can find these files:

<img width="471" alt="image" src="https://user-images.githubusercontent.com/44698588/171901582-2c1c344a-2474-4808-85f4-1b2f8f0716c6.png">

It would be nice to replace the text with links to said files. In theory, this should be able to be done like we do for the installing via yaml docs (here's [serving](https://github.com/knative/docs/blob/5fa1d67ec65fff536b473dcb12b256e4c06a950c/docs/install/yaml-install/serving/install-serving-with-yaml.md?plain=1#L14) as an example).

**Comment by Aryan-Deshpande** [comment]
Hey is this issue being worked on, would like to work on this too. New to knative, and I'd like to get started on contributing 😄 .

**Comment by abrennan89** [comment]
@Aryan-Deshpande as far as I know nobody is working on this, I can assign you if you're still interested? Thanks.

**Comment by abrennan89** [comment]
@snneji are you still working on this one or can we unassign it for someone else to pick up?

**Comment by hokandil** [comment]
Hi all , can I work on this? if yes , could you assign it to me?

**Comment by Aryan-Deshpande** [comment]
> @snneji are you still working on this one or can we unassign it for someone else to pick up?

Hey extremely sorry for the late reply, I'll be interested in taking up the issue !.

**Comment by YashPimple** [comment]
Hello, @psschwei I have made a PR to this issue since this issue was stale for quite a long period of time, and since no one was working do check it out.
