### ISSUE TITLE
Document on Knative.dev about installing via Gateway

### ISSUE THREAD

**Issue by carlisia** [knative/docs#5040]
## What is changing? (Please include as many details as possible.)

Work is being done to get `net-gateway-api` to beta in Knative.

## In what release will this take happen (to the best of your knowledge)?
v1.6.0

## Context
Link to associated PRs or issues from other repos here.

1. [Gateway API Roadmap](https://github.com/orgs/knative-sandbox/projects/10/views/1)

**Comment by carlisia** [comment]
Hey @abrennan89, thanks for double checking this. 

I will close this issue then. If in the future we have a need and use case for adding the documentation to the site we'll create a new issue and explain the reason for the exception.

**Comment by evankanderson** [comment]
We absolutely document `net-istio` and `net-kourier` here, for example:

https://knative.dev/docs/install/yaml-install/serving/install-serving-with-yaml/#install-a-networking-layer

It's also mentioned here (possibly wrongly, it doesn't mention `kourier` or `contour`): https://knative.dev/docs/serving/knative-kubernetes-services/

Istio is also documented here: https://knative.dev/docs/serving/using-a-tls-cert/#manually-adding-a-tls-certificate and search claims 18 total pages with "Istio" on them.

**Comment by abrennan89** [comment]
@carlisia @evankanderson if this still needs to be documented please provide some draft docs / information.

@evankanderson re the above comment, I just meant we don't document specific mention of the plugins AFAIK, which makes things even more confusing, we just talk about needing a networking layer (those docs are already a mess IMO that need a good clean up) and istio etc as options scattered throughout docs.
