### ISSUE TITLE
Document on all hops encrypted amongst internal and external services in Knative

### ISSUE THREAD

**Issue by nak3** [knative/docs#5041]
## What is changing? (Please include as many details as possible.)

Once https://github.com/knative/serving/pull/13005 was merged, we should add the documentation about the feature.
(I am going to create the draft docs so please allow me to write the detail later.)

## How will this impact our users?

Currently there are no docs about internal TLS. When we document it, users can refer to the usage and so on.

## In what release will this take happen (to the best of your knowledge)?

- Serivng 1.6

## Context
Link to associated PRs or issues from other repos here.

- https://github.com/knative/serving/pull/13005
- https://github.com/knative/serving/issues/11906

**Comment by abrennan89** [comment]
@nak3 any update on this one?
