### ISSUE TITLE
Contribute to knative, asks to fill out the Google Contributor License Agreement (CLA)

### ISSUE THREAD

**Issue by nainaz** [knative/docs#5047]
## Expected Behavior
Since Knative has moved to CNCF, we should update the section about appropriate contributions form.

[EDIT: June 28 2022]  link should be to https://easycla.lfx.linuxfoundation.org/#/ and should read, "CNCF Contributor License Agreement" instead of "Google Contributor License Agreement".

## Actual Behavior
Contribute to Knative section is asking to fill out the  [Google Contributor License Agreement (CLA)](https://cla.developers.google.com/)
https://knative.dev/docs/community/contributing

## Steps to Reproduce the Problem

1. Click on Contributions welcome on Knative.dev Home page
2. Pre requisite section talk about filling out https://knative.dev/docs/community/contributing/

## Additional Info
**Additional context**

**Install information:**
 - Platform (GKE, IKS, AKS, etc.):
 - Knative Version:

**Comment by abrennan89** [comment]
Need info from TOC about new CNCF CLA. Update community and contributing pages.

**Comment by lance** [comment]
The CLA will be EasyCLA whenever we get final set up from CNCF. For the time being, it's still Google CLA but could change at any moment. When it does, the link should be to https://easycla.lfx.linuxfoundation.org/#/ and should read, "CNCF Contributor License Agreement" instead of "Google Contributor License Agreement".

**Comment by lance** [comment]
> @lance is there a community issue tracking this or can someone let us know when it changes?

https://github.com/knative/community/issues/952 is probably the best issue to follow regarding this. I will also send an email to knative-dev when this changes.

**Comment by nainaz** [comment]
Woohoo!!
Great news

Thank you,
-N

**Comment by nainaz** [comment]
Added the information in the issue as well.

**Comment by abrennan89** [comment]
Docs here also need to be updated: https://github.com/knative/community/blob/main/CONTRIBUTING.md#contributor-license-agreements
