### ISSUE TITLE
Addition of how to contribute to functions on Contribute to Knative section/page

### ISSUE THREAD

**Issue by nainaz** [knative/docs#5048]
**Describe the change you'd like to see**
We should add the section on how to contribute to Knative Functions on Contribute to Knative section. In additon to Serving, Eventing and CLI 

**Additional context**

Here is the link to contributing guide for Functions for now : https://github.com/knative-sandbox/kn-plugin-func/blob/main/docs/CONTRIBUTING.md

**Comment by snneji** [comment]
Link to functions: 

Add link here: https://knative.dev/docs/community/contributing/#contribute-to-the-code
