### ISSUE TITLE
[CLI] Document using kn to create an ApiServerSource

### ISSUE THREAD

**Issue by abrennan89** [knative/docs#5057]
Update the docs here https://knative.dev/docs/eventing/sources/apiserversource/getting-started/ to include steps for using `kn`

**Comment by abrennan89** [comment]
Reference: https://github.com/knative/client/blob/main/docs/cmd/kn_source_apiserver.md

**Comment by amaanq** [comment]
Asking for clarification, it seems like the main docs page shows an example on how to create the source with kn (step 6), so I'm not sure what else exactly needs to be documented for using kn

**Comment by aslom** [comment]
From what I see the last part about deletion of namespace could be replaced by `kn source apiserver delete`? And kubectl version of deleting apiserver CR? @lionelvillard
