### ISSUE TITLE
[CLI] Document using kn to create a PingSource

### ISSUE THREAD

**Issue by abrennan89** [knative/docs#5058]
Update the docs here https://knative.dev/docs/eventing/sources/ping-source/ to include `kn` examples

**Comment by abrennan89** [comment]
Reference: https://github.com/knative/client/blob/main/docs/cmd/kn_source_ping.md

**Comment by abrennan89** [comment]
@amaanq any update on this one?

**Comment by amaanq** [comment]
Just created a PR for this, looking for a review now

**Comment by aslom** [comment]
I did quick review LGTM @amaanq @abrennan89 @snneji  @lionelvillard  - adding base64 encoding to examples shows how to use kn CLI to get the same result as using YAML
