### ISSUE TITLE
How does a eventing source plugin looks like and how it is different to other plugins ? (i.e using a manifest)

### ISSUE THREAD

**Issue by abrennan89** [knative/docs#5067]

**Comment by abrennan89** [comment]
@knative/eventing-wg-leads @knative/client-wg-leads this came from a list of requirements for kn plugin docs that I think was originally asked for by Roland. Please provide information for this if there is anything to document, otherwise let's close this issue.

**Comment by rhuss** [comment]
A source plugin has the following characteristics:

* It is named grouped below `kn source`. 
* It has CRUD  sub-commands ("create", "update", "delete", "list", "describe" and maybe "apply")
* It has a mandatory `--sink` option following the sink format

Not sure what else, any ideas @dsimansk ?
