### ISSUE TITLE
Document new traffic-isolation net-kourier experimental feature

### ISSUE THREAD

**Issue by lionelvillard** [knative/docs#5079]
## What is changing? (Please include as many details as possible.)
There is a new experimental feature in [net-kourier](https://github.com/knative-sandbox/net-kourier) for isolating Knative services traffic.

## How will this impact our users?
They can install Knative in a multi-tenant environment.

## In what release will this take happen (to the best of your knowledge)?
1.16

## Context
Link to associated PRs or issues from other repos here.

https://github.com/knative-sandbox/net-kourier/pull/852

**Comment by abrennan89** [comment]
@lionelvillard since we don't currently document any part of `net-kourier` in knative.dev AFAIK, is the intention here to document it [here](https://github.com/knative-sandbox/net-kourier) or create a new docs section in the website for `net-kourier`?

**Comment by lionelvillard** [comment]
@abrennan89 I was not aware there is no net-kourier doc in knative.dev. I will start by updating the net-kourier doc. 

Thanks for pointing this out!
