### ISSUE TITLE
PVC support 

### ISSUE THREAD

**Issue by giladk1221** [knative/docs#5083]
Hi,
I would like any sample examples for PVC support in Service YAML.
I want to configure the PV/PVC for SMB/NFS shares and I didn't see any references for those configurations.

It will be very helpful to see some examples(step by step) of how to configure it well like your desired configuration.

waiting for any update.

Thanks
Gilad

**Comment by abrennan89** [comment]
@giladk1221 I don't have bandwidth to pick this up right now, but there is some information in our Red Hat documentation here about enabling PVC for Knative Serving: https://docs.openshift.com/container-platform/4.10/serverless/admin_guide/serverless-configuration.html#serverless-enabling-pvc-support_serverless-configuration

Hope this helps for now.

@skonto @knative/serving-wg-leads anyone have any additional info that can be added here to form a full docs example beyond what we have in our docs? I'll write this up properly for knative.dev when I have a chance but might need more info unless this solves the issue.

**Comment by abrennan89** [comment]
I actually found this right after also: https://knative.dev/docs/serving/configuration/feature-flags/#kubernetes-persistentvolumeclaim-pvc

The RH docs have an example of the Service etc though which might be more useful.

**Comment by zzuchen** [comment]
> @giladk1221 I don't have bandwidth to pick this up right now, but there is some information in our Red Hat documentation here about enabling PVC for Knative Serving: https://docs.openshift.com/container-platform/4.10/serverless/admin_guide/serverless-configuration.html#serverless-enabling-pvc-support_serverless-configuration
> 
> Hope this helps for now.
> 
> @skonto @knative/serving-wg-leads anyone have any additional info that can be added here to form a full docs example beyond what we have in our docs? I'll write this up properly for knative.dev when I have a chance but might need more info unless this solves the issue.

I want to mount the NFS shares for my pod in knative v0.23.0，but the pvc is supported after knative v1.2，could you please tell me how to solve the problem?
