### ISSUE TITLE
Add documentation for annotations and config strings, including release versions

### ISSUE THREAD

**Issue by xtaje** [knative/docs#5090]
**Describe the change you'd like to see**

Add documentation for annotations and configmap strings, including their release versions.
Changes to string formats should also be documented as part of release notes.

**Additional context**
The PRs below change the annotations strings used for autoscaling (e.g. minScale -> min-scale, min-scale -> scale-min), or the configmaps (camel case -> kebab-case).

These changes are currently not documented anywhere, which makes it hard to determine when something has changed, or the effect an upgrade might have. Also some people might not be able to upgrade to the latest versions of knative. When a string is misspelled, there is no warning or way to detect it.

https://github.com/knative/serving/pull/12329
https://github.com/knative/serving/issues/12932
https://github.com/knative/serving/pull/12071/files

**Comment by abrennan89** [comment]
These types of changes should be documented by developers in the release notes for each release, not in the core docs.
