### ISSUE TITLE
Update the blog template to remove Hugo frontmatter

### ISSUE THREAD

**Issue by abrennan89** [knative/docs#5099]
## Expected Behavior
Blog template should reflect the format used here https://github.com/knative/docs/pull/5059/files

## Actual Behavior
Blog template still includes old Hugo frontmatter. Leaving this in increases work for docs either during content reviews or afterwards if something is merged using this template and then needs to be cleaned up.

**Comment by snneji** [comment]
@abrennan89  Do you mean this template here: https://github.com/knative/docs/blob/main/contribute-to-docs/templates/template-blog-entry.md#copy-the-template

**Comment by abrennan89** [comment]
No idea tbh, thought I saw an older one at one point with the hugo frontmatter but maybe it was somewhere else.

Either way, the one you're linking to looks like it's missing the author info, date etc and is different to what's [actually being used in the docs](https://knative.dev/blog/articles/eventing-rabbitmq-announcement/) as we decided a while back on the WG call, so either all the existing blogs need to be updated again to match this template, or the template should be updated to match what's actually used in practice.

I don't mind what we use as long as it's consistent and folks have a template that actually aligns with what's on the site.

**Comment by snneji** [comment]
@abrennan89, Do you think we should keep that table with tracking info about reviews and approvals? I'm not sure it's needed since reviews will be logged in GH.

**Comment by abrennan89** [comment]
Nah I think it can be removed

**Comment by abrennan89** [comment]
@snneji it looks like the PR is opened against your fork instead of the docs repo. Would you mind fixing it and we can get this merged then? 🙂

**Comment by AmanSarraf** [comment]
Hi @abrennan89, I want to work on this issue

**Comment by dprotaso** [comment]
@AmanSarraf are you still working on this?
