### ISSUE TITLE
Move Brokers to own top lvl section in Eventing

### ISSUE THREAD

**Issue by abrennan89** [knative/docs#5106]
![image](https://user-images.githubusercontent.com/40172997/179233026-66b649b5-e7da-496a-9d84-9af39fe06646.png)
The current docs layout provides no real advantages since there's no user story to follow - why would a user look in the admin vs developer section if they just want to know about brokers, and how to configure and then use them?

I will follow this up with an issue for each main conceptual section, but this issue is to move the broker docs all to one section on their own at a top level under Eventing > Brokers.

**Comment by ArtemChekunov** [comment]
Hi guys,

I found that the documentation is referencing https://github.com/google/knative-gcp/blob/main/docs/examples/cloudpubsubsource/README.md

but the repository was archived after Knative accepted as a CNCF incubating project

so, the question is: will the cloudpubsubsource be supported in the future?
