### ISSUE TITLE
serving/samples/helloworld: Kotlin fails to load logger at runtime

### ISSUE THREAD

**Issue by grayside** [knative/docs#515]
## Expected Behavior

When the Kotlin application comes up, a logging library is loaded and used to perform basic request logging.

## Actual Behavior

On startup, this error message is displayed:

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

My understanding is that the build.gradle is responsible for creating a fat jar, bundling all the dependencies, perhaps this line is failing?

```
 from { configurations.compile.collect { it.isDirectory() ? it : zipTree(it) } }
```

## Steps to Reproduce the Problem

1. git clone git@github.com:knative/docs
2. cd serving/samples/helloworld-kotlin
3. docker build --tag kn-helloworld-kotlin
4. docker run --rm -p 9092:9090 -e PORT=9090 -e TARGET=kotlin kn-helloworld-kotlin

## Preliminary Research

* https://www.anexinet.com/blog/six-ways-to-package-a-java-application-with-gradle/
* https://medium.com/@preslavrachev/kotlin-basics-create-executable-kotlin-jars-using-gradle-d17e9a8384b9
* https://imperceptiblethoughts.com/shadow/plugins/

/cc @pzmrzy

**Comment by RichieEscarez** [comment]
Closing due to age of the issue and the fact that these files have been touched several times since this issue was first opened
