### ISSUE TITLE
serving/samples/helloworld-elixir: build failure

### ISSUE THREAD

**Issue by grayside** [knative/docs#517]
## Expected Behavior

Docker build works and produces an operable container.

## Actual Behavior

Docker build fails on dep/compile step. Because the docker build itself is critically broken, it is not possible to test other changes to this sample until fixed.

```
Step 8/22 : RUN mix do deps.get, deps.compile, compile
 ---> Running in 6bb6660bed8b
** (Mix.Config.LoadError) could not load config config/prod.secret.exs
    ** (File.Error) could not read file "/opt/app/config/prod.secret.exs": no such file or directory
    (elixir) lib/file.ex:310: File.read!/1
    (mix) lib/mix/config.ex:189: Mix.Config.read!/2
    (mix) lib/mix/config.ex:233: anonymous fn/3 in Mix.Config.read_wildcard!/2
    (elixir) lib/enum.ex:1899: Enum."-reduce/3-lists^foldl/2-0-"/3
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
    (stdlib) erl_eval.erl:878: :erl_eval.expr_list/6
    (stdlib) erl_eval.erl:404: :erl_eval.expr/5
```

## Steps to Reproduce the Problem

1. git clone git@github.com:knative/docs
2. cd serving/samples/helloworld-elixir
3. docker build --tag kn-helloworld-elixir .

**Comment by RichieEscarez** [comment]
Note: this file has moved to the "community" folder: https://github.com/knative/docs/tree/master/community/samples/serving/helloworld-elixir

**Comment by RichieEscarez** [comment]
Closing due to age of the issue and that these files have been touched several times since this was first opened.
