### ISSUE TITLE
Document the kn plugin directory

### ISSUE THREAD

**Issue by rhuss** [knative/docs#5171]
* The `kn` plugin directory is `~/.config/kn/plugins` on Linux and macOS, and on `%APPDATA%\kn\plugins` (I think this information is also missing on https://knative.dev/docs/client/kn-plugins/#manually-install-a-plugin where it is only mentioned that it can be put on the $PATH

_Originally posted by @rhuss in https://github.com/knative/docs/pull/5167#discussion_r942620187_

**Comment by abrennan89** [comment]
The plugin directory config and how to use it is documented here: https://knative.dev/docs/client/configure-kn/
