### ISSUE TITLE
Add Functions to Existing Tutorial

### ISSUE THREAD

**Issue by lance** [knative/docs#5205]
**Describe the change you'd like to see**
The existing tutorial does not include Knative Functions. It would be nice to have something there by KubeCon in October. This request is to add a section in the left-hand menu called "Using Knative Functions" or similar which is an introduction to the technology, including a tutorial.

**Additional context**
For the time being, this supercedes https://github.com/knative/docs/issues/5038 as it will be easier and quicker to complete by the end of October. Leaving 5038 open, however, for long-range planning.

An example of the proposed section

![image](https://user-images.githubusercontent.com/15952/187521293-1dda3768-45ce-47fb-bc28-bd92ae65696f.png)

/kind enhancement
/kind functions

**Comment by abrennan89** [comment]
Not sure if this link is related? https://miro.com/app/board/o9J_lAlC520=/
I don't know who owns this doc, just found it when I was clearing out bookmarks

**Comment by lance** [comment]
> Not sure if this link is related? https://miro.com/app/board/o9J_lAlC520=/ I don't know who owns this doc, just found it when I was clearing out bookmarks

I cannot access the link
