### ISSUE TITLE
How Kubernetes version is necessary to install Operator 1.3.x or low?

### ISSUE THREAD

**Issue by julioNico** [knative/docs#5225]
**Where is the documentation for operator v1.3 and older releases?**
On the page https://knative.dev/docs/install/operator/knative-with-operators/ or https://knative.dev/docs/ we have only informations about Knative v1.4 or newer.

I need this informations like this link https://knative.dev/docs/install/operator/knative-with-operators/ but abount v1.3 and older.

**Additional context**
I am upgrading the Knative 0.26.x in kubernetes 1.21.x, but I don't no if Operator v1.3 is compatible with kubernetes 1.21.x.

**Comment by abrennan89** [comment]
We only provide docs on knative.dev for the last 3 Knative versions. Currently those versions are 1.4+
If you want to view docs for older versions, you will need to go to the older branch in the docs repo and view the markdown files for the version you want, e.g. https://github.com/knative/docs/blob/release-1.3/docs/install/operator/knative-with-operators.md
