### ISSUE TITLE
Create a single, central doc about configuring default channel configmaps

### ISSUE THREAD

**Issue by abrennan89** [knative/docs#5226]
Currently there are separate docs for the Operator and regular CRs, plus kafka docs:
- https://knative.dev/docs/install/operator/configuring-eventing-cr/
- https://knative.dev/docs/eventing/configuration/kafka-channel-configuration/
- https://knative.dev/docs/eventing/configuration/channel-configuration/

**Describe the change you'd like to see**
1. There should be a similar section to https://knative.dev/docs/eventing/brokers/ but for Channels under Eventing, as well as under Concepts > Eventing resources (e.g. https://knative.dev/docs/concepts/eventing-resources/brokers/)
2. Configuration info for channels should be grouped, and tabs provided for different config types (i.e. Operator vs YAML) instead of entirely different sections and pages.
3. Documented config options should show the standard, default MT broker examples, as well as Kafka examples, so that Kafka channel docs can be combined here too.

@snneji  any thoughts on what's proposed here?

**Comment by KiranPatil30** [comment]
Hii Sir , Can you assign this issue to me?

**Comment by abrennan89** [comment]
Let's wait for @snneji 's input before we go ahead with this one

**Comment by KiranPatil30** [comment]
Ok
