### ISSUE TITLE
Document use of `kn service create --force`

### ISSUE THREAD

**Issue by abrennan89** [knative/docs#5227]
From @rhuss 

`knative service create --force` is to entirely overwrite an existing service, which means delete it first and then recreate it. This is in contrast to `kn service update`, which updates individual fields on an existing installation. You would use it in scripts to ensure that you have a fresh service even if a service with this name already exists. That's useful e.g. for CI runs when you are not sure that the previous run has been cleaned up properly (which can happen when a CI tests fails).

Also it's different to `kn service apply` as it does not merge on an existing service, that might have been changed by a third party. It just overwrites any changes that had happened. It's a sledgehammer.

**Comment by Atharv-Nalwade** [comment]
This is my first time to open source this issue will help me start my journey into open source
Can I get assigned to this issue

**Comment by Harini1023** [comment]
I would really wish to work on this issue and document use of <b>kn service create force </b>. Could you please assign this issue.

**Comment by evankanderson** [comment]
(You can use `/assign` to assign the issue to yourself)

**Comment by keshavcodex** [comment]
hey @afzal442 are you still working on it?

**Comment by afzal442** [comment]
Hi, r u able to find and run `knative service create --force` ? I'm assigning to u as well.
/assign @keshavcodex

**Comment by keshavcodex** [comment]
hey @abrennan89 i need some help in this, in which path do i need to explain about `kn service create --force`

**Comment by dprotaso** [comment]
/unassign @Harini1023 

@keshavcodex @afzal442 are you still working on this issue?

**Comment by keshavcodex** [comment]
Hey @dprotaso i wrote this, but can you tell me where should add this file, and what should be the name of this file.

**Comment by keshavcodex** [comment]
Hey @evankanderson  can you tell me where should I add this file, and what should be the name of this file.

**Comment by evankanderson** [comment]
I suspect it might make sense to put it in https://knative.dev/docs/client/ as a new file, possibly "using the CLI in automation".

**Comment by xiangpingjiang** [comment]
@keshavcodex 
hello, are you still working on it?

**Comment by satyampsoni** [comment]
@keshavcodex are you still working on it?

**Comment by keshavcodex** [comment]
> @keshavcodex are you still working on it?

No

**Comment by gouthamhusky** [comment]
Hi @evankanderson, this seems to a long standing open issue. To be clear, do we  want to document the use of `kn service create --force` command > alone? I see no references to other commands like `service update` etc.
