### ISSUE TITLE
Advanced language pack docs

### ISSUE THREAD

**Issue by abrennan89** [knative/docs#5287]
Follow up from https://github.com/knative/docs/issues/5265

Add docs for:

- Language pack inventory page
- Writing your own language pack

**Comment by abrennan89** [comment]
Removing my assignment since this is additional content required that I can't provide, it's separate to the PR that I have open atm that adds basic language pack docs, since it's a more advanced use case (building your own).

**Comment by dprotaso** [comment]
/unassign @lance 
/assign @lkingland 

unsure if you still want this
