### ISSUE TITLE
Missing step in knative functions tutorial

### ISSUE THREAD

**Issue by gabriel-rh** [knative/docs#5308]
**Describe the change you'd like to see**

While working through the knative functions tutorial (https://knative.dev/docs/getting-started/build-run-deploy-func/)

```
~ $ func create -l go hello
Created go function in /home/user1/hello

~ $ func run
Error: stat /home/user1/func.yaml: no such file or directory
```

It looks like I need to change directory  - this may be obvious to knative users, but for beginners, it should be added to the steps in the tutorial.

```
~ $ ls ~/hello/
func.yaml  go.mod  handle.go  handle_test.go  README.md

~ $ cd hello

~/hello $ func run
   Building function image
```

**Additional context**
N/A

**Comment by lance** [comment]
Thanks for your bug reports @gabriel-rh - super helpful! For this one, the page does say this just before the command is shown.

> Run the function locally, by running the command **inside the project directory**:

(emphasis added)

We originally did have `cd hello` but thought the text worded the way it is was enough. Obviously, it's not 👍
