### ISSUE TITLE
Could not create knative service

### ISSUE THREAD

**Issue by jagadhees-ravi** [knative/docs#5339]
Hi,

I tried to create knative service by following the helloworld-python tutorial. I followed every step, but I am getting error. Kindly help me resolve it. I am pasting the error message for reference.

"Configuration "helloworld-python" does not have any ready Revision. Error: RevisionFailed: Revision "helloworld-python-00001" failed with message: Unable to fetch image "docker.io/<my-docker-username>/helloworld-python": failed to resolve image to digest: Get "https://index.docker.io/v2/": x509: certificate signed by unknown authority."

OS: Windows
Docker-Desktop version: 4.13.1
knative version: 1.8.0

Thanks in advance !

**Comment by dprotaso** [comment]
You'll have to push the images to a real registry and update the `image` property to where you pushed it

ie. `docker.io/{username}/helloworld-python` you should replace `{username}` with your own docker user name
