### ISSUE TITLE
Install Knative by quickstart and minikube fail

### ISSUE THREAD

**Issue by MrZLeo** [knative/docs#5343]
## Expected Behavior
Install finish without error

## Actual Behavior
```
$ kn quickstart minikube                                                                                               
Running Knative Quickstart using Minikube
Minikube version is: v1.28.0

☸ Creating Minikube cluster...

Using the standard minikube driver for your system
If you wish to use a different driver, please configure minikube using
    minikube config set driver <your-driver>

😄  [knative] minikube v1.28.0 on Fedora 34
✨  Automatically selected the docker driver. Other choices: ssh, none
📌  Using Docker driver with root privileges
👍  Starting control plane node knative in cluster knative
🚜  Pulling base image ...
🔥  Creating docker container (CPUs=3, Memory=3072MB) ...
🎁  Preparing Kubernetes v1.24.3 on CRI-O 1.24.3 ...
    ▪ Generating certificates and keys ...
    ▪ Booting up control plane ...
    ▪ Configuring RBAC rules ...
🔗  Configuring CNI (Container Networking Interface) ...
🔎  Verifying Kubernetes components...
    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v5
🌟  Enabled addons: storage-provisioner, default-storageclass
E1201 06:18:10.042354 2317906 pod_ready.go:66] WaitExtra: waitPodCondition: timed out waiting for the condition
E1201 06:18:10.043839 2317906 pod_ready.go:66] WaitExtra: waitPodCondition: error getting pod "coredns-6d4b75cb6d-szmmw" in "kube-system" namespace (skipping!): pods "coredns-6d4b75cb6d-szmmw" not found
E1201 06:22:10.646325 2317906 pod_ready.go:66] WaitExtra: waitPodCondition: timed out waiting for the condition

❌  Exiting due to GUEST_START: wait 6m0s for node: extra waiting: timed out waiting 6m0s for all system-critical and pods with labels [k8s-app=kube-dns component=etcd component=kube-apiserver component=kube-controller-manager k8s-app=kube-proxy component=kube-scheduler] to be "Ready"

╭───────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                           │
│    😿  If the above advice does not help, please let us know:                             │
│    👉  https://github.com/kubernetes/minikube/issues/new/choose                           │
│                                                                                           │
│    Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│                                                                                           │
╰───────────────────────────────────────────────────────────────────────────────────────────╯

Error: creating cluster: existing cluster: new cluster: minikube create: piping output: exit status 80
Usage:
  kn-quickstart minikube [flags]

Flags:
  -h, --help                        help for minikube
      --install-eventing            install Eventing on quickstart cluster
      --install-serving             install Serving on quickstart cluster
  -k, --kubernetes-version string   kubernetes version to use (1.x.y)
  -n, --name string                 minikube cluster name to be used by kn-quickstart (default "knative")

creating cluster: existing cluster: new cluster: minikube create: piping output: exit status 80
Error: exit status 1
```

## Steps to Reproduce the Problem

1. `minikube delete --all`
2. configurate minikube to use cri-o: `minikube config set container-runtime crio`
test:
```
$ minikube config view
- container-runtime: cri-o
```
3. install with quickstart
```
$ kn quickstart minikube
```
And I got that error.

## Additional Info
I am not sure whether I have done it right to config a new container runtime. My goal is change the container runtime of Knative.

**Comment by psschwei** [comment]
Quickstart isn't designed to support a wide range of configuration options -- it's mostly to get you an environment set up so you can start getting hands on with Knative. If you need a more fine-tuned setup, it'd probably be better to configure your cluster first and then use either the YAML or Operator install methods (https://knative.dev/docs/install/).

That said, I see you're using the docker driver for minikube. As docker uses containerd, I could image this causing some problems when trying to use cri-o as a minikube runtime. Might be better to try using a VM runtime or podman instead.

FWIW, cri-o worked for me with the following settings:

```
$ minikube config view
- container-runtime: crio
- cpus: 6
- driver: kvm2
- kubernetes-version: 1.25.3
- memory: 16384
```

(cpus/memory can probably be lowered, I've got mine set that high for reasons unrelated to quickstart)

**Comment by MrZLeo** [comment]
> https://knative.dev/docs/install/

Thanks for your help! But I actually run Knative in a AWS ec2 instance, so it seems have only docker, ssh, none three driver. Maybe I don't configure it correctly, I will try a VM runtime like kata or other latter. As for yaml, I am really new in K8s and Knative, so I am not sure which yaml file should I change to(since there are many steps to install Knative :( ).

**Comment by MrZLeo** [comment]
@psschwei

Thanks for your help! But I actually run Knative in a AWS ec2 instance, so it seems have only docker, ssh, none three driver. Maybe I don't configure it correctly, I will try a VM runtime like kata or other latter. As for yaml, I am really new in K8s and Knative, so I am not sure which yaml file should I change to(since there are many steps to install Knative :( ).

**Comment by MrZLeo** [comment]
@psschwei 

oh, I don't think VM works for AWS ec2... Looks like I don't have other choice but docker? :(

**Comment by MrZLeo** [comment]
`Podman` works fine for me!!
Thank you again! : )
```
$ minikube config view
- container-runtime: cri-o
- driver: podman
- kubernetes-version: 1.25.3
```

**Comment by psschwei** [comment]
Glad you got it working. Going to close this, feel free to reopen if necessary.
