### ISSUE TITLE
Will knative support workload's  pvc or nfs

### ISSUE THREAD

**Issue by jimmyforrest** [knative/docs#5361]
## What is changing? (Please include as many details as possible.)

https://knative.dev/docs/serving/convert-deployment-to-knative-service/#benefits
"our workload uses only Secret and ConfigMap volumes."

## How will this impact our users?

I want to use pvc or nfs as volume in my workload, and use knative autoscaling

## In what release will this take happen (to the best of your knowledge)?
Ex. v0.2-v0.3

## Context
Link to associated PRs or issues from other repos here.

1.
1.
1.

**Comment by jimmyforrest** [comment]
I find this https://knative.dev/docs/serving/configuration/feature-flags/#kubernetes-emptydir-volume

**Comment by zzuchen** [comment]
> I find this https://knative.dev/docs/serving/configuration/feature-flags/#kubernetes-emptydir-volume

hello, I want to mount the NFS shares for my pod in knative v0.23.0，but the pvc is supported after knative v1.2，could you please tell me how to solve the problem?
