### ISSUE TITLE
applying yaml with gcp eventsource gives error with missing key

### ISSUE THREAD

**Issue by sebgoa** [knative/docs#539]
## Expected Behavior

Applying the manifest leads to a running controller in `knative-sources` namespaces

## Actual Behavior

controller does not start because we don't create the google secret key:

```
 MountVolume.SetUp failed for volume "google-cloud-key" : secrets "gcppubsub-source-key" not found
```

## Steps to Reproduce the Problem

1. Follow https://github.com/knative/docs/tree/master/eventing

```
 kubectl apply --filename https://storage.googleapis.com/knative-releases/eventing-sources/latest/release-with-gcppubsub.yaml
```

**Comment by RichieEscarez** [comment]
I believe this was fixed in #558
