### ISSUE TITLE
Provided reference docs for definition

### ISSUE THREAD

**Issue by viveksahu26** [knative/docs#5403]
**Describe the change you'd like to see**

There are some definition in the docs which are not common for beginners friendly. Such as stateless in the [docs](https://knative.dev/docs/getting-started/about-knative-functions/#about-knative-functions)(line-no:3). So, to understand those definition either reference to that definition should be provided by Knative in a separate definition list or link to the docs written by others vendors on same definition should be provided.  

**Additional context**

**Comment by dprotaso** [comment]
/assign @lance 

This is referring to functions
