### ISSUE TITLE
Subtitle in knative.dev homepage looks strange

### ISSUE THREAD

**Issue by aliok** [knative/docs#5407]
## Steps to Reproduce the Problem

1. "Knative is an Open-Source Enterprise-level solution to build Serverless and Event Driven Applications" is the title, which makes sense. The phrase below it kind of looks strange to me: "Serverless Containers in Kubernetes environments."
2. Is that subtitle a sentence?
1. <img width="1519" alt="Screenshot 2023-02-04 at 01 46 24" src="https://user-images.githubusercontent.com/376732/216725351-a5e282a3-c4cd-4847-b2d7-4a55d3c8e7ad.png">

## Additional Info
**Additional context**

**Install information:**
 - Platform (GKE, IKS, AKS, etc.):
 - Knative Version:

**Comment by vishalsingh2972** [comment]
@aliok can you assign this to me if its still available, also what would you like me to add in place of "Serverless Containers in Kubernetes environments."?

**Comment by aliok** [comment]
@knative/technical-oversight-committee Any text you can think of?

**Comment by psschwei** [comment]
I feel like that _might_ be a question for @knative/steering-committee ... but if not, we can add it to the TOC board so it gets discussed on this week's call.

**Comment by vishalsingh2972** [comment]
I felt this was more appropriate - "Knative is a way to run serverless applications without having to manage servers."

**Comment by vishalsingh2972** [comment]
I felt these were more appropriate - "Knative is a way to run serverless applications without having to manage servers." or simply "Serverless platform that makes it easy to build, deploy, and scale event-driven microservices."

**Comment by vishalsingh2972** [comment]
I feel these would be more appropriate - "Knative is a way to run serverless applications without having to manage servers." or simply "Serverless platform that makes it easy to build, deploy, and scale event-driven microservices."

**Comment by nainaz** [comment]
Delete "Serverless Containers in Kubernetes environments."

**Comment by aliok** [comment]
> SC committee recommends: Delete "Serverless Containers in Kubernetes environments."

Ok, that's confirmed.

About the text in blue... There was a discussion to mention not only "build" but "scale, run and build".

Let's take it offline:

@vishalsingh2972 's suggestion is good. @nainaz wanted to merge the existing one and the suggested one, such as

"Knative is an Open-Source Enterprise-level solution to build, deploy, and scale event-driven microservices."

OR

"Knative is an Open-Source Enterprise-level solution to build, deploy, and scale event-driven applications." (no microservices mentioned)

The point is that "serverless" is not included in the text above.

@knative/steering-committee

**Comment by aliok** [comment]
I am addressing the subtitle with this PR: https://github.com/knative/docs/pull/5633

For the title discussion, I've created a separate ticket: https://github.com/knative/docs/issues/5634
