### ISSUE TITLE
Eventing Samples Shouldn't Require `ko`

### ISSUE THREAD

**Issue by bbrowning** [knative/docs#541]
## Expected Behavior

I should be able to apply all yaml in the Eventing samples using `kubectl.

## Actual Behavior

Some of the yaml requires `ko` and a working Go developer environment because they reference container images that aren't actually published anywhere.

## Steps to Reproduce the Problem

Follow the instructions for any of the eventing samples and note the usage of `ko`.

**Comment by RichieEscarez** [comment]
Looks like there are [two remaining samples that still use `ko`](https://github.com/knative/docs/search?q=ko&unscoped_q=ko).

**Comment by RichieEscarez** [comment]
Closing this now since our "how-tos" topics no longer require ko (there remains only a couple of code samples).
