### ISSUE TITLE
Support for other languages: Docs

### ISSUE THREAD

**Issue by bluefriday** [knative/docs#5414]
I wonder if there are plans to support other languages for Knative docs.

If it is possible, in case of Korean, I'd like to translate it.

**Comment by dprotaso** [comment]
cc @knative/steering-committee

**Comment by nainaz** [comment]
Hello @bluefriday Apologies for missing this issue.
We would love to have the translations in other languages. 
Let me know how we can help.

**Comment by nainaz** [comment]
How to provide support for different languages.

**Comment by akshayamadhuri** [comment]
@nainaz   i would also like to contribute can you give some more details

**Comment by nainaz** [comment]
Open a doc issue to support other languages for docs.

**Comment by akshayamadhuri** [comment]
@nainaz  Sure
