### ISSUE TITLE
istio injection

### ISSUE THREAD

**Issue by sebgoa** [knative/docs#543]
question:

In the installation docs: https://github.com/knative/docs/blob/master/install/Knative-with-any-k8s.md
it says to enabled istio injection in the default namespace

Is that restricted to the `default` namespace intentionally or is it supposed to mean that we need to enabled istio injection in all the namespaces where we plan to run knative services ?

**Comment by tcnghia** [comment]
You'd need to enable Istio injection in all the namespaces that you want to use Istio sidecars.  Knative Serving was tested with and without sidecar injection, so enabling sidecar injection is not strictly required.

**Comment by sebgoa** [comment]
Right, so in the docs what is meant is that if you want to deploy a knative service in the default namespace and use sidecar injection then you need to label the namespace with `istio-injection: enabled`

**Comment by tcnghia** [comment]
Yes, that is correct.  We should update the doc if that is not clear.

**Comment by RichieEscarez** [comment]
Docs have been updated here (explains Istio namespace requirement in detail): https://github.com/knative/docs/blob/master/install/Knative-custom-install.md#installing-istio-1

**Comment by sebgoa** [comment]
I don't think the docs are clear enough. If you read the docs:

> If you chose to install the Istio service mesh with automatic sidecar injection, you must label the default namespace with istio-injection=enabled:

This makes it sounds like labeling the `default` namespace **alone** will enable Istio service mesh in all namespaces. Which to my knowledge is wrong.

I would expect a sentence like:

"To enable the Istio service mesh in a given namespace, label that specific namespace with istio-injection=enabled"

**Comment by samodell** [comment]
@sebgoa  We'd really appreciate it if you opened a PR to change that sentence. Agree that your wording is clearer.
