### ISSUE TITLE
Image of helloworld-go is 781 MB

### ISSUE THREAD

**Issue by hajs** [knative/docs#5440]
The documentation at https://knative.dev/development/serving/services/creating-services/ suggests to try out knative serving with a simple hello-world service.

Unfortunately the referenced image `gcr.io/knative-samples/helloworld-go:latest` seems to be a lot larger than necessary because it also contains the tooling. Docker tells me that this image was built 4 years ago.

I have looked into https://github.com/knative/docs/tree/main/code-samples/serving/hello-world/helloworld-go

If I build that image it is only 72 MB big.

Perhaps you can push the updated image to the registry?

**Comment by abrennan89** [comment]
@dprotaso can we transfer this issue to the community repo entirely? It's not really a docs issue.

**Comment by dprotaso** [comment]
Sure -
