### ISSUE TITLE
Verifying image signatures

### ISSUE THREAD

**Issue by pguerin3** [knative/docs#5494]
## Actual Behavior
When verifying image signatures using the following from the documentation:
```
# download the yaml file, this example uses the serving manifest
curl -fsSLO https://github.com/knative/serving/releases/download/knative-v1.9.0/serving-core.yaml
cat serving-core.yaml | grep 'gcr.io/' | awk '{print $2}' > images.txt
input=images.txt
while IFS= read -r image
do
  COSIGN_EXPERIMENTAL=1 cosign verify -o text "$image" | jq
done < "$input"
```

I get errors as follows:
``
Error: --certificate-identity or --certificate-identity-regexp is required for verification in keyless mode
main.go:74: error during command execution: --certificate-identity or --certificate-identity-regexp is required for verification in keyless mode
``

## Additional Info
Cosign v2.0.0 has been released and they mention in the blog the following
https://github.com/sigstore/cosign/blob/main/CHANGELOG.md
```
COSIGN_EXPERIMENTAL=1 is no longer required
```

When I remove COSIGN_EXPERIMENTAL, there errors about missing certificate-identity and certificate-oidc-issuer.
So I can guess the correct syntax, and change the cosign line to read like this:
```
cosign verify -o text "$image" --certificate-identity "signer@knative-nightly.iam.gserviceaccount.com" --certificate-oidc-issuer "https://accounts.google.com" | jq
```

However that also doesn't work either and I get the errors
```
Error: no matching signatures:
none of the expected identities matched what was in the certificate, got subjects [signer@knative-releases.iam.gserviceaccount.com] with issuer https://accounts.google.com
```

**Install information:**
 - Platform (GKE, IKS, AKS, etc.): Oracle CLoud Kubernetes service
 - Knative Version: latest

**Comment by BobyMCbobs** [comment]
made an update for this in #5568.
