### ISSUE TITLE
Decide on an icon set for diagrams and create a key for icons

### ISSUE THREAD

**Issue by abrennan89** [knative/docs#5503]

**Comment by evankanderson** [comment]
Someone from RedHat provided a set of icons a few years back for IDE purposes:

https://github.com/knative/community/tree/main/icons

**Comment by abrennan89** [comment]
Tbh I feel like those are a bit over-complicated and not really intuitive. I'd like to see us use something more simple, but if the general consensus is that folks are happy with those, I guess we could use them.

Could we transfer this issue to the community repo maybe and have the TOC decide? Whatever we choose should be used consistently I think, so it would be good to have the decision more visible than just the docs WG.
