### ISSUE TITLE
A command line is missing in the Quickstart Tutorial

### ISSUE THREAD

**Issue by waltforme** [knative/docs#5542]
**Describe the change you'd like to see**
In the quickstart tutorial, specifically the section [Using Triggers and sinks](https://knative.dev/docs/getting-started/first-trigger/), there is a GUI to show the CloudEvent (with ID '2'). But there is not a command line to do the same thing, i.e. check the CloudEvent being sent and received.

In the previous section [Using a Knative Service as a source](https://knative.dev/docs/getting-started/first-source/), however, there are **both** a GUI to send a CloudEvent (with ID '1') **and** a command line to do the same thing.

Therefore, the two consecutive sections are not consistent, in the sense that a command line exists in [Using a Knative Service as a source](https://knative.dev/docs/getting-started/first-source/) but not in [Using Triggers and sinks](https://knative.dev/docs/getting-started/first-trigger/).

In addition, for any user who exercises the tutorial in an environment which lacks a GUI, it may become difficult for him/her to complete the tutorial.

**Additional context**
Screenshot for [Using a Knative Service as a source](https://knative.dev/docs/getting-started/first-source/). We can see there is a command line:
![image](https://user-images.githubusercontent.com/8633434/235357547-24107471-ef7e-4a16-a228-edccb8122b6f.png)

Screenshot for [Using Triggers and sinks](https://knative.dev/docs/getting-started/first-trigger/). There is not a command line:
![image](https://user-images.githubusercontent.com/8633434/235357570-cdf8c618-8936-4953-9d58-78c98f3655b2.png)

**Comment by dprotaso** [comment]
cc @dsimansk @rhuss is there CLI support to view cloud events or would you just need to print logs?

**Comment by rhuss** [comment]
We have a `kn-plugin-event` that easily allows to send CE from outside but also from within the cluster to an arbitrary sink. However, I don't think it can yet act as a sink to visualize CloudEvents that it receives (but please correct me, @cardil ).

For now we have the image `gcr.io/knative-releases/knative.dev/eventing-contrib/cmd/event_display` which can be used in a KService and connected as a sink (it will print out the events in the log) and [Sockeye](https://github.com/n3wscott/sockeye) from @n3wscott which has a nice Web UI for visualizing CloudEvents.
