### ISSUE TITLE
Github sample should link to where I can find the list of event types

### ISSUE THREAD

**Issue by mattmoor** [knative/docs#555]
All the sample seems to receive are pull-request level events, not including comments.

I'd love to see a link [from here](https://github.com/knative/docs/tree/master/eventing/samples/github-source#create-event-source-for-github-events) that shows how to make this sensitive to other events.

**Comment by mattmoor** [comment]
I believe the answer is the "Webhook event names" from [here](https://developer.github.com/v3/activity/events/types/)

**Comment by RichieEscarez** [comment]
Should link to the overview page (revised since this bug was first opened): https://github.com/knative/docs/tree/master/eventing#sources

**Comment by RichieEscarez** [comment]
https://knative.dev/docs/eventing/sources/
