### ISSUE TITLE
Autoscaling Metrics doesn't explain/show HPA custom metrics support clearly

### ISSUE THREAD

**Issue by dprotaso** [knative/docs#5566]
We technically support custom metrics with the HPA but it's not clear in these docs

https://knative.dev/docs/serving/autoscaling/autoscaling-metrics/

> and "custom" metrics are only supported on revisions that use the HPA class.

Techncially "custom" should be "<custom-metric-name>" to hint that the user should type the metric they want.

Secondly, the examples tab for custom metrics is buried all the way to the right. Might want to make the tab headers shorter so it doesn't get cut off

/good-first-issue

**Comment by achiverram28** [comment]
Hey , I am very deep Cloud Native enthusiast and having been learning Kubernetes in a much depth  manner . I found this issue as good first issue . I would love to understand and contribute to it . Could you help me with this as I am really interest in contributing to cloud native projects.

**Comment by dprotaso** [comment]
I think it would be great if the documentation were updated here

https://github.com/knative/docs/edit/main/docs/serving/autoscaling/autoscaling-metrics.md

The tabs are too long - so maybe changing
https://github.com/knative/docs/blob/8b88ea6e99069f1d6ed3ca24b301399a1088af53/docs/serving/autoscaling/autoscaling-metrics.md?plain=1#L22

To drop the `per-revision` prefix and the `configuration` suffix - thus leaving  `Concurrency`

Do that for all the tabs

Also on this line 
https://github.com/knative/docs/blob/8b88ea6e99069f1d6ed3ca24b301399a1088af53/docs/serving/autoscaling/autoscaling-metrics.md?plain=1#L18

this 
> and \`"custom"\` metrics are only supported
should be

> and custom metrics are supported

**Comment by achiverram28** [comment]
@dprotaso Can you have a look at the pr and let me know about your reviews?
