### ISSUE TITLE
usage of cosign in the document is incompatible with the existing version.

### ISSUE THREAD

**Issue by SiyangShao** [knative/docs#5567]
**part of the command listed under install knative is no longer supported**.
https://knative.dev/docs/install/yaml-install/serving/install-serving-with-yaml/#verifying-image-signatures
The command here is:
```
while IFS= read -r image
do
  COSIGN_EXPERIMENTAL=1 cosign verify -o text "$image" | jq
done < "$input"
```
However, under cosign 2.0 (which has been published in Feb 23, 2023), it has been changed. 
According to the news here:
https://blog.sigstore.dev/cosign-2-0-released/
COSIGN_EXPERIMENTAL=1 is no longer required to have identity-based (“keyless”) signing and transparency.]
Verification now requires identity flags, --certificate-identity and --certificate-oidc-issuer.
If we simply run the command listed, there would be an error
```
Error: --certificate-identity or --certificate-identity-regexp is required for verification in keyless mode
main.go:74: error during command execution: --certificate-identity or --certificate-identity-regexp is required for verification in keyless mode
```

**Comment by SiyangShao** [comment]
And when I changed the command into:
```
cosign verify -o text "$image" --certificate-identity signer@knative-nightly.iam.gserviceaccount.com --certificate-oidc-issuer accounts.google.com | jq
```
as it said that signing identity(Subject) for our releases is signer@knative-nightly.iam.gserviceaccount.com and the Issuer is https://accounts.google.com, it reflected that 
```
Error: no matching signatures:
none of the expected identities matched what was in the certificate, got subjects [signer@knative-releases.iam.gserviceaccount.com] with issuer https://accounts.google.com
main.go:69: error during command execution: no matching signatures:
```

**Comment by BobyMCbobs** [comment]
made an update for this in #5568.
