### ISSUE TITLE
Figure out how to handle blog metadata

### ISSUE THREAD

**Issue by lance** [knative/docs#5588]
The metadata in the front-matter for the blog was meant to be removed, however, this results an some unfortunate navigation display, and eliminates information from being propagated to the page's `meta` tags.

See: https://github.com/knative/docs/pull/5583

I propose that we use front-matter for the description and author fields. Drop the other fields, and use a top-level `h1` heading instead of `title` and `linkTitle` in the front-matter.

**Comment by Karthika506** [comment]
I would like to work on this issue. Can you please assign it to me
