### ISSUE TITLE
Change the names of knaitive-sandbox to knative-extensions

### ISSUE THREAD

**Issue by Leo6Leo** [knative/docs#5666]
## Expected Behavior
As the organization name changed to knative-extensions, the names in the knative doc should be updated to reflect that change as well. https://github.com/knative-extensions

/good-first-issue

**Comment by hirentimbadiya** [comment]
i'd like to work on this.

**Comment by taniaduggal** [comment]
Can anyone give more context to the issue?

**Comment by Leo6Leo** [comment]
It seems like some cache problem on my end. All the names have been updated. Thanks for your willingness to help! @hirentimbadiya @taniaduggal
