### ISSUE TITLE
Secret format in KafkaSource documentation

### ISSUE THREAD

**Issue by rajibmitra** [knative/docs#5668]
**Describe the change you'd like to see**
The current documentation for KafkaSource does not clearly mention that only PEM-formatted credentials are supported. Users with JKS credentials might face issues when trying to integrate their Kafka clusters.

**Expected behavior**
The documentation should clearly state the supported formats and provide guidance on how to convert JKS to PEM if needed.

**Additional context**
I had a discussion with the Knative OSS team and confirmed that JKS is not directly supported. The mapping should be "keystore" into "key" and "truststore" into "cert" when converting to PEM.

**Comment by rajibmitra** [comment]
@pierDipi  please let me know if this looks good to you. thanks

**Comment by Cali0707** [comment]
@rajibmitra thanks for creating this issue! Would you want to work on this and update the docs?

**Comment by rajibmitra** [comment]
sure @Cali0707

**Comment by Cali0707** [comment]
Thanks @rajibmitra !!
/assign @rajibmitra

**Comment by Cali0707** [comment]
Hey @rajibmitra any updates here? Can I help with anything?
