### ISSUE TITLE
Remove KafkaBinding documentation code sample

### ISSUE THREAD

**Issue by pierDipi** [knative/docs#5682]
This page https://github.com/knative/docs/blob/main/code-samples/eventing/kafka/binding/README.md is outdated, we need to remove it and its references

## Expected Behavior

Content removed

## Steps to Reproduce the Problem

1. Go to https://github.com/knative/docs/blob/main/code-samples/eventing/kafka/binding/README.md

## Additional Info

/good-first-issue

**Additional context**

**Install information:**
 - Platform (GKE, IKS, AKS, etc.):
 - Knative Version: `main`, `release-1.11`, `release-1.10`

**Comment by MeenuyD** [comment]
Hello @pierDipi I would like to work on this issue can I work on this

**Comment by MeenuyD** [comment]
Should we have to remove the whole file?

**Comment by CodesbyUnnati** [comment]
I am a new contributor and this is my first PR 😃 , so wanted to pick up this good-first-issue. Sorry @MeenuyD for highjacking the issue 😢
 @pierDipi Please review the PR and let me know if I need to do some other changes.
