### ISSUE TITLE
Change navigation bar on Knative Eventing

### ISSUE THREAD

**Issue by matzew** [knative/docs#5701]
Look at https://knative.dev/docs/eventing/

The navigation bar for Knative Eventing is really  "odd":
* Resources
  * Broker
  * Trigger
* Developer Topics
  * Sources
  * and more

So.. why... is there a) `Resources` and b) why is `Broker/Trigger` not a "developer topic" ?

**Comment by Cali0707** [comment]
@matzew see my comment here: https://github.com/knative/docs/issues/5703#issuecomment-1771509151

UX WG will conduct interviews with users and come up with a better, cohesive structure for the docs

**Comment by Cali0707** [comment]
@matzew this should be resolved by #5914 

Would you be able to TAL and see if the new changes make sense?
