### ISSUE TITLE
Dates on blog posts

### ISSUE THREAD

**Issue by predmond** [knative/docs#5704]
**Describe the change you'd like to see**
It would be convenient if blog posts showed the date they were published.

**Additional context**
https://knative.dev/blog/releases/announcing-knative-v1-11-release/ doesn't say when the release post was published.

**Comment by Leo6Leo** [comment]
+1, and currently all the dates in the blog post articles are hard-coded.
e.g https://knative.dev/blog/articles/getting-started-blog-p0/

**Comment by Cali0707** [comment]
@Leo6Leo do you have any ideas how we could make those dates non-hardcoded? I think

**Comment by Leo6Leo** [comment]
@Cali0707  Because our Knative website is powered by Material for MkDocs, this is what I found.

https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/?h=date#document-dates

**Comment by Cali0707** [comment]
@Leo6Leo do you think you have the capacity to take this on?

**Comment by Leo6Leo** [comment]
> @Leo6Leo do you think you have the capacity to take this on?

I would add the good-first-issue label for this issue

/good-first-issue

**Comment by Leo6Leo** [comment]
**Problem**
Currently, as found by @predmond , all the release notes don't have the date that post is published. Also all the dates in the blog post is hard-coded.

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Which persona is this feature for? Developer

**Exit Criteria**
Have the dynamic date on all the articles, blog posts, release notes on the knative website.

**Time Estimate (optional):** 
How many developer-days do you think this may take to resolve?
1

**Additional context (optional)**
As current Knative website is powered by Material for MkDocs, you might find this helpful. [Link](https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/?h=date#document-dates)


/good-first-issue

**Comment by prushh** [comment]
Hey all, I created a draft PR where I used the plugin you suggested.

Is it okay to have the _last update_ and _creation_ date at the bottom of each page? In this case, I must remove the **Date** field from the beginning of all articles.
