### ISSUE TITLE
Change homepage diagram 

### ISSUE THREAD

**Issue by zainabhusain227** [knative/docs#5720]
**Describe the change you'd like to see**
The current homepage diagram has an inaccessible color scheme. We should update the website to have more cohesive and higher contrast colors.

**Additional context**
cc @mmejia02 to add the svg file for new diagram

**Comment by vinfinity7** [comment]
![image](https://github.com/knative/docs/assets/122719607/4fca55b2-6435-40e7-98e6-ddfa52ce4efe)
can you please elaborate which image , i believe this ?

**Comment by mmejia02** [comment]
Hi @vinfinity7, yes it is that one!  Here is an svg of the diagram with the same font as the rest of the website and different colours.
![Frame 70(2)](https://github.com/knative/docs/assets/143516624/64470511-f01a-4159-8d86-3367258941d6)

**Comment by Cali0707** [comment]
@vinfinity7 or anyone else who works on this - please use the SVG provided above be @mmejia02

**Comment by vinfinity7** [comment]
yes @Cali0707 , assign me this under hacktober fest

**Comment by vinfinity7** [comment]
@Cali0707 please review the pr and suggest me if it needs some changes

**Comment by vinfinity7** [comment]
@Cali0707 the task is completed as i assume , review the changes i did
