### ISSUE TITLE
Move from materialx.emoji.twemoji to material.extensions.emoji.twemoji

### ISSUE THREAD

**Issue by Cali0707** [knative/docs#5723]
## Expected Behavior

The verify mkdocs test passes with no warnings.

## Actual Behavior

```
INFO    -  DeprecationWarning: 'materialx.emoji.twemoji' is deprecated.
Material emoji logic has been officially moved into mkdocs-material
version 9.4. Please use Material's 'material.extensions.emoji.twemoji'
as mkdocs_material_extensions is deprecated and will no longer be
supported moving forward. This is the last release.
```

**Comment by ReToCode** [comment]
Produces errors like https://github.com/knative/docs/actions/runs/6665935389/job/18116510881?pr=5739

See what Kenjiro already tried and the issue with it:
- https://github.com/knative/docs/pull/5727
- https://github.com/knative/docs/pull/5730

**Comment by ReToCode** [comment]
https://github.com/knative/docs/pull/5730#issuecomment-1775139175

/assign
