### ISSUE TITLE
Facing issue while deploying knative application on minikube

### ISSUE THREAD

**Issue by navinag1989** [knative/docs#5747]
I tried installing knative application following the documentation (https://knative.dev/docs/serving/autoscaling/autoscale-go/) on minikube. However, to run knative app on minikube requires some additional steps which are not mentioned in docs. I found the additional steps in the doc - https://github.com/csantanapr/knative-minikube/blob/master/README.md
I feel we should include these steps in knative docs. It will be helpful for beginners.

**Comment by ReToCode** [comment]
Hey, the link you mentioned is a specific example to test autoscaling capabilities of Knative. It is probably better to start with https://knative.dev/docs/getting-started/quickstart-install/ which should explain all the relevant bits. It is not necessary to set up everything by yourself, as we have the `kn quickstart` plugin available.
