### ISSUE TITLE
Install of KNative on vanilla kubernetes uses too much memory & CPU resources

### ISSUE THREAD

**Issue by stevef1uk** [knative/docs#575]
Installing KNative on a machine with 22Gb RAM
Linux ubuntu 4.18.0-11-generic #12-Ubuntu SMP Tue Oct 23 19:22:37 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-24T06:54:59Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.1", GitCommit:"4ed3216f3ec431b140b1d899130a69fc671678f4", GitTreeState:"clean", BuildDate:"2018-10-05T16:36:14Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}

When following these instructions: https://github.com/knative/docs/blob/master/install/Knative-with-any-k8s.md

The result is all memory is used swapd active and the elastic log search Pod is using a very high amount of CPU with the machine basically maxed out. This is before deploying any sample applications!

**Comment by RichieEscarez** [comment]
There are now custom install instructions that allow you to reduce the Knative footprint, including the amount of resources needed: https://github.com/knative/docs/blob/master/install/Knative-custom-install.md
