### ISSUE TITLE
Errors when deploying newest version of Knative CRDs

### ISSUE THREAD

**Issue by gunpuz** [knative/docs#5759]
## Expected Behavior

Knative CRDS would deploy without STDERRs

## Actual Behavior

Standart error is reported about incorrect CRD: 

```ps1
> kubectl apply -f https://github.com/knative/serving/releases/download/knative-v1.12.0/serving-crds.yaml
customresourcedefinition.apiextensions.k8s.io/certificates.networking.internal.knative.dev unchanged
customresourcedefinition.apiextensions.k8s.io/configurations.serving.knative.dev unchanged
customresourcedefinition.apiextensions.k8s.io/clusterdomainclaims.networking.internal.knative.dev unchanged
customresourcedefinition.apiextensions.k8s.io/ingresses.networking.internal.knative.dev unchanged
customresourcedefinition.apiextensions.k8s.io/metrics.autoscaling.internal.knative.dev unchanged
customresourcedefinition.apiextensions.k8s.io/podautoscalers.autoscaling.internal.knative.dev unchanged
customresourcedefinition.apiextensions.k8s.io/revisions.serving.knative.dev unchanged
customresourcedefinition.apiextensions.k8s.io/routes.serving.knative.dev unchanged
customresourcedefinition.apiextensions.k8s.io/serverlessservices.networking.internal.knative.dev unchanged
customresourcedefinition.apiextensions.k8s.io/services.serving.knative.dev unchanged
customresourcedefinition.apiextensions.k8s.io/images.caching.internal.knative.dev unchanged
The CustomResourceDefinition "domainmappings.serving.knative.dev" is invalid: status.storedVersions[0]: Invalid value: "v1alpha1": must appear in spec.versions
```

## Steps to Reproduce the Problem

1. `kubectl apply -f https://github.com/knative/serving/releases/download/knative-v1.12.0/serving-crds.yaml`

**Comment by jasonsmithio** [comment]
I just deployed on a GKE cluster without issue. Tell me more about your setup

**Comment by gunpuz** [comment]
What info would be usefull?

**Comment by jasonsmithio** [comment]
What version of kubernetes? Where is it hosted (MiniKube, GKE, EKS, etc.)? What else is installed on the cluster (specifically at the time of deploying knative)

**Comment by gunpuz** [comment]
Its hosted on Ubuntu: `microk8s`
Kubernetes version: `1.28`

There is already some custom services, helm charts... , including Knative Serving, Knative Eventing

**Comment by ReToCode** [comment]
v1alpha1 version of DomainMapping was deprecated in 1.11, see https://github.com/knative/serving/releases/tag/knative-v1.11.0. It looks like you were still using them when migrating to version 1.12 which will cause the error. Make sure you update your DomainMapping objects to the new version before installing 1.12.

**Comment by gunpuz** [comment]
What is the recommended upgrade procedure? Is there any docs for this? You could give some hint, please :)

**Comment by jasonsmithio** [comment]
I would assume just updating the domainmapping yamls to reflect the new API

https://knative.dev/docs/serving/services/custom-domains/#procedure

**Comment by dprotaso** [comment]
So serving has a post install job after upgrading that needs to run

eg. https://github.com/knative/serving/releases/download/knative-v1.12.1/serving-post-install-jobs.yaml

This typically will set things up for the next release. If you run that job now prior to upgrading you should be fine.

We sorta mention it in the link below but I think we could do a better job documenting it

https://knative.dev/docs/install/yaml-install/serving/serving-installation-files/

**Comment by ReToCode** [comment]
/assign 

I'll add a bit more to the [update docs](https://knative.dev/docs/install/upgrade/upgrade-installation/#upgrade-existing-resources-to-the-latest-stored-version).

@gunpuz this job will migrate the existing objects on the cluster, but you still need to update the version in your own instances of `DomainMapping` if you store them in git or similar (like GitOps, ArgoCD).

**Comment by gunpuz** [comment]
@ReToCode so should we reopen this issue then?

For example:

### Step 1: Add older Knative
```ps1
kubectl apply -f https://github.com/knative/serving/releases/download/knative-v1.10.2/serving-crds.yaml
kubectl wait --for=condition=Established --all crd
kubectl apply -f https://github.com/knative/serving/releases/download/knative-v1.10.2/serving-core.yaml
kubectl apply -f https://github.com/knative/net-kourier/releases/download/knative-v1.10.0/kourier.yaml

#kubectl patch configmap/config-network --namespace knative-serving --type merge --patch '{"data":{"ingress-class":"kourier.ingress.networking.knative.dev"}}'
# Adjustment for PowerShell
kubectl patch configmap/config-network --namespace knative-serving --type merge --patch '{\"data\":{\"ingress-class\":\"kourier.ingress.networking.knative.dev\"}}'

# Wait for Knative to become ready before starting knative services
kubectl wait --for=condition=ready --timeout=60s -n knative-serving --all pods
kubectl wait --for=condition=ready --timeout=60s -n kourier-system --all pods
```


## Step 2: Update to newer Knative

```ps1
kubectl apply -f https://github.com/knative/serving/releases/download/knative-v1.12.2/serving-crds.yaml
kubectl wait --for=condition=Established --all crd
kubectl apply -f https://github.com/knative/serving/releases/download/knative-v1.12.2/serving-core.yaml
kubectl apply -f https://github.com/knative/net-kourier/releases/download/knative-v1.12.1/kourier.yaml
```

Check if error is reported:
>The CustomResourceDefinition "domainmappings.serving.knative.dev" is invalid: status.storedVersions[0]: Invalid value: "v1alpha1": must appear in spec.versions


## Step 3: Run post install job

```ps1
kubectl create -f https://github.com/knative/serving/releases/download/knative-v1.12.2/serving-post-install-jobs.yaml
```

> job.batch/storage-version-migration-serving-f87s5 created


## Step 4: Check this migration job logs to see anything interesting

```ps1
{"severity":"INFO","timestamp":"2023-12-05T09:09:30.6460017Z","caller":"logging/config.go:80","message":"Unable to read vcs.revision from binary"}
{"severity":"INFO","timestamp":"2023-12-05T09:09:30.6467751Z","logger":"storage-migrator","caller":"migrate/main.go:69","message":"Migrating 5 group resources"}
{"severity":"INFO","timestamp":"2023-12-05T09:09:30.6468262Z","logger":"storage-migrator","caller":"migrate/main.go:72","message":"Migrating group resource services.serving.knative.dev"}
{"severity":"INFO","timestamp":"2023-12-05T09:09:30.6593467Z","logger":"storage-migrator","caller":"migrate/main.go:72","message":"Migrating group resource configurations.serving.knative.dev"}
{"severity":"INFO","timestamp":"2023-12-05T09:09:30.666545Z","logger":"storage-migrator","caller":"migrate/main.go:72","message":"Migrating group resource revisions.serving.knative.dev"}
{"severity":"INFO","timestamp":"2023-12-05T09:09:30.6756363Z","logger":"storage-migrator","caller":"migrate/main.go:72","message":"Migrating group resource routes.serving.knative.dev"}
{"severity":"INFO","timestamp":"2023-12-05T09:09:30.6784452Z","logger":"storage-migrator","caller":"migrate/main.go:72","message":"Migrating group resource domainmappings.serving.knative.dev"}
{"severity":"INFO","timestamp":"2023-12-05T09:09:30.6817267Z","logger":"storage-migrator","caller":"migrate/main.go:82","message":"Migration complete"}
```

Only thing that is "unusual" is - `Unable to read vcs.revision from binary` 


## Step 5: Run step 2 to check if error got away

**Comment by ReToCode** [comment]
Hm you can not update from 1.10 to 1.12 (see https://knative.dev/docs/install/upgrade/). Does the same thing occur when you do it 1.10 -> 1.11 -> 1.12?
