### ISSUE TITLE
Website colour adjustments

### ISSUE THREAD

**Issue by mmejia02** [knative/docs#5765]
New colours for the website were chosen to be more accessible and maintain brand consistency. The original dark and light blue used on the website are not the same ones used on the logo. The hex colours and screenshot of current website are below.

![image](https://github.com/knative/ux/assets/143516624/08422549-3061-4e1e-940f-cf4bafafd91f)

![image](https://github.com/knative/ux/assets/143516624/2f0fbc7c-5d7d-4e89-a853-7e2e5730be55)

As such the blues were changed to match the logo, but the dark blue was slightly darkened to have sufficient colour contrast to be used as a background colour. 

In order for the light blue to be accessible as a background we will need to change the button text to be 18.7 px. but this would be a next step.

Conclusion: Change the root website dark and light blue to the following hex codes:

Light Blue: 6593C8
Dark blue: 0D4984

**Comment by asr2003** [comment]
@Cali0707 Could I change the entire root website dark and light blue as per mentioned HEX Codes

Light Blue: 6593C8
Dark blue: 0D4984

**Comment by Cali0707** [comment]
Hey @asr2003 yeah, that sounds like a good approach to me! As a bit of help, since we are using mkdocs I would recommend checking out https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#custom-colors for more info on how to set the root colours of the site

**Comment by asr2003** [comment]
Thanks, @Cali0707 . I have done with setup and went through the codebase to better understand current status of project after getting assign of this issue . Now I have got a brief idea about this project. I will now ahead to work on this issue and submit a PR soon :)

**Comment by Cali0707** [comment]
Hey @rohitsrma it looks like @asr2003 is already working on this issue. Would you be interested in working on something else instead?

**Comment by rohitsrma** [comment]
Hello @Cali0707, I'm really sorry for assigning myself.

@asr2003 I've made the changes locally to resolve this issue. So, if you need any help i would be more than happy to do.

**Comment by rash1411** [comment]
#assign
