### ISSUE TITLE
Routing across multiple Knative services for HTTPS/TLS

### ISSUE THREAD

**Issue by mhebbel2** [knative/docs#5800]
**Describe the change you'd like to see**
I would like to have this documentation:
https://github.com/knative/docs/tree/main/code-samples/serving/knative-routing-go

but for TLS/HTTPS case. The documents do not seem to work for HTTPS.

**Comment by ReToCode** [comment]
The documentation for TLS/HTTPS will be reworked with https://github.com/orgs/knative/projects/63/views/1. But it will take some more time to finish.
