### ISSUE TITLE
Update the copyright year in knative website

### ISSUE THREAD

**Issue by Leo6Leo** [knative/docs#5802]
**Describe the change you'd like to see**
Update the year in the knative website. Currently it is Copyright © 2022 The Knative Authors
![image](https://github.com/knative/docs/assets/36619969/f926c13b-d82e-42df-a9c2-8947754e950c)

**Additional context**

/good-first-issue
/help-wanted

**Comment by 8rxn** [comment]
Some easy fixes to start this year's contributions!

**Comment by professorabhay** [comment]
Hey, @Leo6Leo! I would like to resolve it!
