### ISSUE TITLE
quickstart refers to non-existent ghcr.io/knative/helloworld-go 

### ISSUE THREAD

**Issue by ferringb** [knative/docs#5803]
## Expected Behavior

The expected behaviour is that the documentation quickstart at https://knative.dev/docs/getting-started/first-service/#__tabbed_1_1  is usable ;)

The referenced container images for either example no longer exist- it looks like y'all wiped your knative/helloworld-go repo.

## Actual Behavior

Docker pull fails.

## Steps to Reproduce the Problem

1. `kn service create hello \
--image ghcr.io/knative/helloworld-go:latest \
--port 8080 \
--env TARGET=World`
2. docker pull ghcr.io/knative/helloworld-go:latest

## Additional Info
**Additional context**
You probably can use a sha256 locked reference to docker.io/strm/helloworld-http rather than implementing your own go version.

**Comment by ReToCode** [comment]
This works fine, are you sure that you can connect to the registry?

```
docker pull ghcr.io/knative/helloworld-go:latest
latest: Pulling from knative/helloworld-go
Digest: sha256:d2af882a7ae7d49c61ae14a35dac42825ccf455ba616d8e5c1f4fa8fdcf09807
Status: Image is up to date for ghcr.io/knative/helloworld-go:latest
ghcr.io/knative/helloworld-go:latest
```

The image is here: https://github.com/knative/docs/pkgs/container/helloworld-go

**Comment by ferringb** [comment]
@ReToCode pardon the noise, re-running it now I can confirm no issue.  Can't say I'm sure what the hell broke in the network pathing on my end, but something clearly did.

Pardon the noise, closing this out since it's invalid.
