### ISSUE TITLE
The fancy note box is not showing on Configure Broker defaults doc page

### ISSUE THREAD

**Issue by Leo6Leo** [knative/docs#5810]
## Expected Behavior

Normally, when we are using `!!! note` in the doc, the doc website should render the content in the fancy note box as shown below. 
![image](https://github.com/knative/docs/assets/36619969/4710b731-6a73-4094-a3d9-4893e4d469b0)

## Actual Behavior
Currently in the [Configure Broker Defaults doc](https://knative.dev/docs/eventing/configuration/broker-configuration/#configuring-the-default-broker-class-for-namespaces:~:text=!!!%20note%20Be%20aware%20that%20different%20Broker%20classes%20usually%20require%20different%20configuration%20ConfigMaps.%20See%20the%20configuration%20options%20of%20the%20different%20Broker%20implementations%20on%20how%20their%20referenced%20ConfigMaps%20have%20to%20look%20like%20(e.g.%20for%20MTChannelBasedBroker%20or%20Knative%20Broker%20for%20Apache%20Kafka).) page, it is not properly rendered.

![image](https://github.com/knative/docs/assets/36619969/0d6c146c-aaf4-430e-a891-3f74c2a48bd4)

## Steps to Reproduce the Problem
Directly visit the link provided above

## Additional Info
**Additional context**

**Install information:**
 - Platform (GKE, IKS, AKS, etc.):
 - Knative Version:

/help-wanted

**Comment by professorabhay** [comment]
Is there any update in the formatting rule? 
This rendering error occurs only on that mentioned page or all the pages are affected using the same syntax 🤔

**Comment by Leo6Leo** [comment]
> Is there any update in the formatting rule? This rendering error occurs only on that mentioned page or all the pages are affected using the same syntax 🤔

Not quite sure. I didn't get a chance to check other pages. I just find this error while I was working on some feature and reading the doc I linked above!

**Comment by professorabhay** [comment]
No problem, I debug that. PR will merge soon.
Kindly take a look
