### ISSUE TITLE
Adding the button "Edit on GitHub" to all docs

### ISSUE THREAD

**Issue by Leo6Leo** [knative/docs#5811]
**Describe the change you'd like to see**
Like k8s documentation, there is an option for people to edit the doc page on GitHub. And that will provide a easier way for people to report and make suggestions on the currentl knative docs.

After clicking on the "Edit this page" button, you will be redirected to the raw markdown file that associated with the doc page.

![image](https://github.com/knative/docs/assets/36619969/17aee181-89e6-4e39-8267-80aea43a18f6)

**Additional context**

/help

**Comment by professorabhay** [comment]
Hey, @Leo6Leo ! I would like to work on this. 
Needed Time - 5 days to raise PR

**Comment by Leo6Leo** [comment]
sure! thanks for the help!

/assign @professorabhay

**Comment by professorabhay** [comment]
Hey @Leo6Leo,
After exploring the code and reading the guidelines I found that there is no common component that is rendering on all the pages, except the footer and nav but adding the button in it is not a user-friendly approach. K8s use Hugo Server to manage this dynamically. 
I am planning to add the functionally on all the pages separately. 
Is there any thing you want to suggest? 
And I also want to know that is there any slack community or something where I can get connect with other developers and seek for help.

**Comment by Leo6Leo** [comment]
@professorabhay Hey Anhay! Thanks for your prompt reaction on the issue! I appreciate your thorough exploration of the code and understanding the guidelines. You're right, adding a common component to all pages except for the footer and nav could be challenging and may not be the most user-friendly and developer-friendly approach. 

Given the situation, I would suggest considering the possibility of implementing a Hugo shortcode or a similar feature. This way, you could create a reusable component that can be easily added to individual pages without the need to modify each page separately. It's more efficient and maintains the consistency of the site. But if that involves breaking changes or too much work, I would just suggest discard this issue and not pursuing it.

Regarding your question about a community platform, yes, there is a Slack community where you can connect with other developers and seek help. You can join the Knative Slack community for discussions and support. Here's the link you can use to get started: [Blog](https://knative.dev/blog/articles/getting-started-blog-p2/#community).

Let me know if you need further assistance or have any more questions!

**Comment by professorabhay** [comment]
I'll update you regarding this soon.

**Comment by Leo6Leo** [comment]
As this this relates to the UI change in the knative.dev website, will need approval from Knative Steering Committee.

/cc @knative/steering-committee

**Comment by YashPimple** [comment]
Hi @professorabhay are you still on the ticket since i would like to give it a try
