### ISSUE TITLE
Documenent Eventing trust-manager integration

### ISSUE THREAD

**Issue by pierDipi** [knative/docs#5815]
**Describe the change you'd like to see**

Add trust-manager integration, Knative Eventing components will add to the trusted Certificate Authorities (CAs) any PEM-encoded CA certificates in any `ConfigMap` in the `knative-eventing` namespace labeled with `networking.knative.dev/trust-bundle=true`

**Additional context**

- https://github.com/knative/eventing/pull/7532

**Comment by ReToCode** [comment]
Content might be shared with https://github.com/knative/docs/pull/5804

**Comment by pierDipi** [comment]
This is done https://knative.dev/development/eventing/features/transport-encryption/#configure-additional-ca-trust-bundles
