### ISSUE TITLE
Missing sugar controller download yaml

### ISSUE THREAD

**Issue by claudio4j** [knative/docs#5826]
**Describe the bug**

The [1.12 documentation to install sugar controller in yaml mode](https://knative.dev/docs/install/yaml-install/eventing/install-eventing-with-yaml/#install-optional-eventing-extensions), says to install using the cli:
```
kubectl apply -f https://github.com/knative/eventing/releases/download/knative-v1.12.3/eventing-sugar-controller.yaml
```
But the eventing-sugar-controller.yaml doesn't exist in that release
https://github.com/knative/eventing/releases/tag/knative-v1.12.3

**Comment by pierDipi** [comment]
We need to remove the separate sugar controller installation steps.

/good-first-issue
