### ISSUE TITLE
Update eventing OIDC docs that EKB supports OIDC

### ISSUE THREAD

**Issue by creydr** [knative/docs#5857]
Currently we list only that OIDC is supported in eventing-core with the MTChannelBasedBroker and InMemoryChannel.
Since we have OIDC support in eventing-kafka-broker (EKB) too, we can add a support matrix in the OIDC docs, showing for which Broker classes / Broker implementations and Channels OIDC is supported (currently for the MTChannelBasedBroker, eventing-kafka-broker, InMemoryChannel and KafkaChannel).

## In what release will this take happen (to the best of your knowledge)?
Ex. v1.14

## Context
Project dashboard: https://github.com/orgs/knative/projects/66

## Additional Information:
* Current OIDC documenation: https://knative.dev/docs/eventing/experimental-features/sender-identity/
* Eventing OIDC project: https://github.com/orgs/knative/projects/66/views/4
* EKB issues for OIDC: https://github.com/orgs/knative/projects/66/views/4?filterQuery=repo%3A%22knative-extensions%2Feventing-kafka-broker%22
* Useful links for Knative Docs style guide: https://github.com/knative/docs/blob/main/contribute-to-docs/README.md#style
* Overview of Knative Docs Contributor guide: https://github.com/knative/docs/blob/main/contribute-to-docs/README.md

**Comment by UtkarshUmre** [comment]
I am interested in working on this. Could you please assign it to me?

**Comment by creydr** [comment]
> I am interested in working on this. Could you please assign it to me?

Hello @UtkarshUmre,
great you're interested in taking this. You can assign the issue to yourself by commenting `/assign`.
Also take a look at the following resources to get started with writing docs:
* Knative Docs style guide: https://github.com/knative/docs/blob/main/contribute-to-docs/README.md#style
* Overview of Knative Docs Contributor guide: https://github.com/knative/docs/blob/main/contribute-to-docs/README.md

/assign @UtkarshUmre

**Comment by creydr** [comment]
Hey @UtkarshUmre,
as I don't watch the PRs in knative/docs repository, feel free to ping me, when you have a PR up.

**Comment by creydr** [comment]
Hello @UtkarshUmre,
any updates on this? Anything we can help you with on this?

**Comment by UtkarshUmre** [comment]
Apologies for any inconvenience, but I'm currently occupied. Regrettably, I won't be able to address this issue.

**Comment by creydr** [comment]
> Apologies for any inconvenience, but I'm currently occupied. Regrettably, I won't be able to address this issue.

No problem. Thanks anyhow for offering help initially. I unassigned you, so somebody else can pick this up. Feel free to assign it to you again, when you have time.

**Comment by jyizheng** [comment]
I am happy to take a look at this issue

**Comment by creydr** [comment]
> I am happy to take a look at this issue

Awesome @jyizheng. I am assigning this issue to you then. 
/assign @jyizheng 

For future issues: you can assign to yourself, be simply commenting `/assign`

**Comment by creydr** [comment]
Hey @jyizheng,
any updates on this? Do you need any more information to get started with this?

**Comment by creydr** [comment]
@jyizheng as I didn't hear anything back from you, I am unassigning you, to make this issue free for other contributors. Feel free to assign it back to you, in case you find time for it.
