### ISSUE TITLE
Eventing samples are overly complex

### ISSUE THREAD

**Issue by mattmoor** [knative/docs#586]
_These are some of my own reflections on the Knative Eventing model having largely ignored things during the high-churn development of the past several months, and coming to it with relatively fresh eyes over the past week or so.  I'm inclined to take a crack at simplifying the Github example to illustrate some of the simplifications outlined here, and see if/how much they actually simplify things._

---

For the simplistic example of the Github source example (and most of the other samples we have, which are similarly simple) we introduce far more concepts than necessary (or that we take advantage of).

Let's assume that I come in with some understanding of `knative/serving` (I do!).  To trigger my `Service` via events, we introduce 3-4 new resources: `Channel[Provisioner]`, `Subscription`, and the `GithubSource`.  I'll admit, this gave me pause and took me a while to wrap my head around.

---

This is overly complex (for this simple case) because we can achieve the **same** result by dropping the `Channel[Provisioner]` and `Subscription`, and making the `GithubSource`:

```yaml
apiVersion: sources.eventing.knative.dev/v1alpha1
kind: GitHubSource
metadata:
  name: githubsourcesample
spec:
  ...
  sink:
    apiVersion: serving.knative.dev/v1alpha1
    kind: Service
    name: github-message-dumper
```

This introduces a **single** new concept, which is a MUCH more graduated introduction to eventing.

---

I think that in addition to the simple samples that should showcase event sources with a more gentle grade, we should have clear examples that introduce `Channels` in a similarly graduated way.

I'd start with the simplest case: **fanout**.  AIUI Github limits webhooks, so to run a whole bunch of services that consume the same webhook, we can share these by pushing the events from a single webhook into an on-cluster `Channel`, which fans out to multiple `Subscriptions`.  I take advantage of this in the half-dozen github.com/mattmoor/knobots bots.

With the simple subscription case under our belt, I'd graduate further to: **composition**.  This is an incredibly powerful feature, and I'd love to see a dedicated sample that walks through it (building on earlier lessons) because **_I_** need a graduated intro to it!

**Comment by sebgoa** [comment]
I tend to agree. When I brushed up on the new eventing, I had to take pen and paper and write down the various objects to see how they related.

The docs puts some emphasis on ops related tasks with quite a bit of discussion towards Channels and Channels provisioners. These could indeed be totally omitted with a _passthrough_ from the source to a service.

We might also consider a subscription from a source directly to a service bypassing the channel.

I want to help with the docs but grasping those concepts and testing took some time.

**Comment by mattmoor** [comment]
@sebgoa for me as well :)

**Comment by justingrayston** [comment]
I also think that for anyone coming from a Serverless Event based world all of these samples feel really ops heavy. I am still to get the IoT Core running and debugging what isn't working is a nightmare. One simple yaml to rule them all, like we have a service.yaml for serving would be great.

**Comment by mattmoor** [comment]
cc @evankanderson @vaikas-google @grantr @scothis @markfisher
