### ISSUE TITLE
Sample App: ML service - Inappropriate language filter

### ISSUE THREAD

**Issue by Leo6Leo** [knative/docs#5917]
### Problem

Create a container image that contains a python application that connected to a simple inappropriate language filter model. When container start running, the application should have the URL endpoint to pass in the input, and the output from the model should be returned as JSON.

The model will take the text comment as input, and tell whether the text is:
- "good": which means doesn't contain any inappropriate language 
- "bad": which means does contain any inappropriate language 

You can find more detail in the [design doc here](https://docs.google.com/document/d/1dYvNdHFf4qoiIbWWOWMLAXDAFpEjjRsa9lP27tpqPTI).

### [Persona:](https://github.com/knative/eventing/blob/main/docs/personas.md)
Which persona is this feature for?
Administrators and developers

### Exit Criteria
- A container image that contains a python application that connected to a simple inappropriate language filter model
- A detailed documentation that explains it and include the setup guide. 

**Time Estimate** (optional):
How many developer-days do you think this may take to resolve? 
1-2

**Comment by Leo6Leo** [comment]
Hey @tico88612! Thanks for taking on this issue! Feel free to reach out for help if you have any questions!

**Comment by Leo6Leo** [comment]
Hey @tico88612 , do you need any help with the issue?

**Comment by tico88612** [comment]
Hi @Leo6Leo 

Should I follow PR #5904 to implement an Inappropriate language filter?

**Comment by Leo6Leo** [comment]
@tico88612 Yes, that's correct. Let do it in that way for now, but it might subject to change, as we might brainstorm more new ideas along the way.

But feel free to think about any new ways to implement it, as long as it can best demonstrate knative's feature!
