### ISSUE TITLE
Sample App: Notification Service: Adding the tutorial on how to create the slack workspace

### ISSUE THREAD

**Issue by Leo6Leo** [knative/docs#5921]
### Problem
Write a text-based tutorial with screenshots on how to create the testing slack workspace. A walkthough video will be a plus.

### [Persona:](https://github.com/knative/eventing/blob/main/docs/personas.md)
Which persona is this feature for?
Administrators and developers

### Exit Criteria
- A clear documentation on how to create a free testing slack workspace and set up the webhook, crete the necessary channels.

**Time Estimate** (optional):
How many developer-days do you think this may take to resolve? 
1-2

**Comment by prashantrewar** [comment]
Hey @Leo6Leo, I want to give it a try. Please help me or suggest some more on this issue.

Thank you!

**Comment by Leo6Leo** [comment]
Hey @prashantrewar , thanks for your willingness to help. The main goal for this issue is to create a clear documentation on how to set up the testing slack workspace. I am envisioning it as a step by step tutorial, from creating the free slack account to what channels need to be created in the workspace, to how to create slack App and set the correct webhook...

Let me know if you have any questions, and feel free to ask in the [CNCF slack! ](https://cloud-native.slack.com/archives/C04LGHDR9K7)

**Comment by ctmphuongg** [comment]
\assign
