### ISSUE TITLE
K8S 1.11.x Serving logging doesn't work

### ISSUE THREAD

**Issue by justingrayston** [knative/docs#593]
## Expected Behavior
Following the instructions for [GKE](https://github.com/knative/docs/blob/master/install/Knative-with-GKE.md#creating-a-kubernetes-cluster) it uses the latest version of K8S by default. You should be able to deploy a full working Knative install (serving, build, eventing with logging, trace etc )

## Actual Behavior
I followed the instructions, and after a bit of debugging, I went to Kabana and realised that it was complaining about non-matching indexes for logstash-* This is because fluent-d deamon set failes to start due to these issues. 

https://github.com/knative/serving/issues/2218

https://github.com/kubernetes/kubernetes/pull/65643

## Steps to Reproduce the Problem

1. Install GKE on latest
2. Deploy a simple helloworld app
3. Make requests
4. Go to Kabana - no matching indexes for logstash-*
5. Note fluent-d deamon failed to start dues to namespace restrictions.

## Additional Info
Would be great if someone could verify. I am just doing a test on 1.10.x but if this is the case, perhaps we need to temporarily update the docs while the namespace issues are resolved?

**Comment by justingrayston** [comment]
Confirmed that installing version on GKE I get a working DeamonSet.

```
kubectl get DaemonSet -n knative-monitoring
NAME            DESIRED   CURRENT   READY     UP-TO-DATE   AVAILABLE   NODE SELECTOR                              AGE
fluentd-ds      3         3         3         3            3           beta.kubernetes.io/fluentd-ds-ready=true   6m
```

**Comment by RichieEscarez** [comment]
@mdemirhan is there a minimum version of k8s that we need to state as required to avoid the fluentd daemonset issue?

**Comment by mdemirhan** [comment]
This is an issue with the newer versions. I will send a PR for a fix shortly for this one.

**Comment by mdemirhan** [comment]
The PR will be for the head. Do you want to have a patch for the current release as well?

**Comment by RichieEscarez** [comment]
> The PR will be for the head. Do you want to have a patch for the current release as well?

HEAD in the docs repo reflects the current release. If this is a change for v0.2.next, we should not merge until thats available.

**Comment by justingrayston** [comment]
Should we at least update the docs to state if you want logging, don't use K8S 1.11.x until we have a fix to save anyone doing what I did and scratching my head as to why it wasn't working?

**Comment by RichieEscarez** [comment]
@mdemirhan has this been resolved?

**Comment by mdemirhan** [comment]
Yes, this is resolved.
