### ISSUE TITLE
Add the best use case example for different Knative Features

### ISSUE THREAD

**Issue by Leo6Leo** [knative/docs#5932]
## Description
There's a need for practical examples to better understand the use cases of Knative's components. The questions such as when will be the best time to use Knative Service? What situation would not be a good idea to use it? What are the best examples to use it?...

For example, you may not want to use Knative service to deploy a database that aren't HTTP request based.

This could better help the users to connect their current existing applications, and allow them to make connections between Knative and the gap in their application.

## Expected Outcomes
- Examples illustrating best practices for using Knative components.

**Comment by Leo6Leo** [comment]
@jasonsmithio  Hello Jason, thanks for the help! Feel free to put it in the way you suggested! And regarding where to be put in the end, you can bring it up for a discussion in the UX WG meeting, I hope that helps! 

Feel free to join the CNCF slack #knative-ux as well.

**Comment by Leo6Leo** [comment]
@jasonsmithio Are there anything I could help you with on this issue?

**Comment by jasonsmithio** [comment]
Apologies, I got side tracked a bit. I will go ahead and push something by Monday, July 15.
