### ISSUE TITLE
Sample App: Use Secret instead of plaintext for slack sink webhook

### ISSUE THREAD

**Issue by Leo6Leo** [knative/docs#5943]
https://github.com/knative/docs/blob/39c58935cf7e24184ced97bf80aed8affc49a00a/code-samples/eventing/bookstore-sample-app/slack-sink/slack-sink-camel-pipe.yaml#L20

Use Secret instead of plaintext for the webhook URL in the slack sink

**Comment by asr2003** [comment]
/assign

cc: @Leo6Leo

**Comment by Leo6Leo** [comment]
@asr2003  Hello Ambati, thank you for your willingness to work on this issue! It has been completed already, but I forget to update the issue. Apologize for the inconvenience!
