### ISSUE TITLE
Sample App: Code clean up

### ISSUE THREAD

**Issue by Leo6Leo** [knative/docs#5950]
### Problem
We need to tidy up our sample app code. This includes:

Making sure all names (like variables and services) are consistent.
Checking that all code files are in the right folders.
Using the best coding practices.

### [Persona:](https://github.com/knative/eventing/blob/main/docs/personas.md)
Which persona is this feature for?
Administrators and developers

### Exit Criteria
- A clean code base

**Time Estimate** (optional):
How many developer-days do you think this may take to resolve? 
1-2

**Comment by rash1411** [comment]
#assign
