### ISSUE TITLE
Provide more example usage for channel-configuration in the doc

### ISSUE THREAD

**Issue by Leo6Leo** [knative/docs#5956]
## Actual Behavior
https://deploy-preview-5618--knative.netlify.app/docs/eventing/configuration/channel-configuration/

In this part of the doc, it would be really helpful to provide the sample configuration for other channels.

## Additional Info
**Additional context**

**Install information:**
 - Platform (GKE, IKS, AKS, etc.):
 - Knative Version:

**Comment by rash1411** [comment]
#assign
