### ISSUE TITLE
[Kubernetes Eventing sample] Source cannot reach the K8s API

### ISSUE THREAD

**Issue by askmeegs** [knative/docs#597]
## Expected Behavior

I installed Knative serving and eventing on a GKE cluster, and wanted to create a subscription for Kubernetes events using this [sample](https://github.com/knative/docs/tree/master/eventing/samples/kubernetes-event-source). 

I expected to:
- Create the Channel, ServiceAccount, Source, and Subscription
- Create some Kubernetes events by running a busybox pod
- View the `message-dumper` service logs, and see events pulled from the channel to my Subscription 

## Actual Behavior

I was able to successfully run all the commands in that guide, but the Source pod logs returned an error:

```
➜  kubernetes-event-source kubectl logs testevents-vhxjz-zg77h-8488dbd49f-ztpgz source
E1127 15:41:31.098875       1 reflector.go:205] github.com/knative/eventing-sources/pkg/adapter/kubernetesevents/adapter.go:72: Failed to list *v1.Event: Get https://10.19.240.1:443/api/v1/namespaces/default/events?limit=500&resourceVersion=0: dial tcp 10.19.240.1:443: connect: connection refused
```

And the `message-dumper` logs are empty:

```
➜  kubernetes-event-source kubectl logs -l serving.knative.dev/service=message-dumper -c user-container

```

I think the problem might be that the Kubernetes API seems to be running at:
```
Kubernetes master is running at https://35.199.187.252
```

But the Source is trying to hit `10.19.240.1` instead. [This is the line of code](https://github.com/knative/eventing-sources/blob/master/pkg/adapter/kubernetesevents/adapter.go#L72) that produces the error. I think that in `NewForConfig`, the K8s client created is getting a bad IP for the API, but not sure where from.

## Steps to Reproduce the Problem

1. Follow the Kubernetes eventing sample up to the "Create Events" step 
2. View the event Source pod logs (name: `testevents...`)

## Additional Info

Environment: Google Kubernetes Engine, 3-node cluster 
Kubernetes Version: `v1.11.2-gke.18`

**Comment by xpepermint** [comment]
The command below returns an empty result on Docker for Mac K8S:

`kubectl logs -l serving.knative.dev/service=event-display -c user-container` 

Errors:
```
Broker's Trigger channel not found
Trigger reconciliation failed: failed to find Broker's Trigger channel
```
