### ISSUE TITLE
We should add our LinkedIn page link to follow us section of our website

### ISSUE THREAD

**Issue by nainaz** [knative/docs#5972]
**Describe the change you'd like to see**
In the Follow us section we should have the link to our Linkedin page as well
https://www.linkedin.com/company/knative
**Additional context**

**Comment by shivamgupta2020** [comment]
@nainaz I created a PR regarding this. Following is the result. Please review it.
![image](https://github.com/knative/docs/assets/91847638/0acc2f80-2cec-4999-90c3-b141bad074ff)

**Comment by TenzDelek** [comment]
@nainaz  @shivamgupta2020  it would be also a plus to add it in the footer as well!!
<img width="1112" alt="image" src="https://github.com/knative/docs/assets/122612557/56e9c694-a3f6-49a9-9d5b-17e65ad2810a">

**Comment by shivamgupta2020** [comment]
@TenzDelek Footer has been there. I only changed what's next section.
![image](https://github.com/knative/docs/assets/91847638/54d718ae-1229-4433-983e-e3493ce4440c)

**Comment by TenzDelek** [comment]
What I mean is to add the LinkedIn link in the footer as well. Might be relevant to do so.

**Comment by shivamgupta2020** [comment]
Updated in recent commit:
![image](https://github.com/knative/docs/assets/91847638/12eb971f-9463-4bff-a5d3-455ec826fbe3)

**Comment by shivamgupta2020** [comment]
@nainaz can u review the PR and merge it.

**Comment by DhairyaMajmudar** [comment]
@aliok @nainaz if it is okay can I continue working on this issue ?
This will be my approch https://github.com/knative/docs/pull/5976#issuecomment-2132778103

**Comment by aliok** [comment]
@DhairyaMajmudar , work is pretty much done in https://github.com/knative/docs/pull/5976#issuecomment-2152156703
