### ISSUE TITLE
Add new CNCF case study to Knative website

### ISSUE THREAD

**Issue by aliok** [knative/docs#5986]
https://www.cncf.io/case-studies/ibmwatsonxassistant/

Tasks:

- Place it on https://knative.dev/docs/ homepage:
![Screenshot 2024-05-22 at 11 15 44](https://github.com/knative/docs/assets/376732/55d67356-52c2-492f-8237-059a43b7df30)

- Place it on https://knative.dev/docs/about/case-studies/ page
- Add a separate page, similar to https://knative.dev/docs/about/case-studies/sva/

**Comment by rohitsrma** [comment]
Hello @aliok, I would like to work on this!

**Comment by rash1411** [comment]
#assign
