### ISSUE TITLE
Minor Grammatical Errors throughout the Documentation

### ISSUE THREAD

**Issue by shivansh-bhatnagar18** [knative/docs#5990]
## Expected Behavior
The entire documentation of the Knative Website contains some minor grammatical errors.

## Actual Behavior
The documentation should be free from these grammatical errors ( though these errors may cause no major harm it is always a good practice to write correct and grammatically correct English ) 

## Steps to Reproduce the Problem

1. Surf through each of the docs and check the grammatical mistakes with the help of Grammarly/Manually
2. Avoid the technical terms and replace the grammatical errors.

![Screenshot from 2024-05-23 00-51-23](https://github.com/knative/docs/assets/117429248/1b9180a6-4d56-40ca-b9af-f909752fbadd)
![Screenshot from 2024-05-23 00-42-22](https://github.com/knative/docs/assets/117429248/1f0e894b-eea5-474d-8dee-b1c42d22c421)

**Comment by nafisreza** [comment]
Opening an issue just for grammar mistakes? I think the documentation team is already working hard behind this. You should try to raise an issue that actually improves the project.

**Comment by shivansh-bhatnagar18** [comment]
Well,  there were a few issues but I didn't know that these come under a separate team who looks after it.  I hope that they look into it. Thanks for the clarification.
