### ISSUE TITLE
Add Toggle Button for Light/Dark Mode

### ISSUE THREAD

**Issue by theDeviser** [knative/docs#5995]
**Describe the change you'd like to see**
Currently, the Knative only supports a single theme. With the growing preference for customizable user interfaces, it would be beneficial to introduce a toggle button that allows users to switch between light and dark modes.

**Additional context**
Many users prefer different themes based on their environment and personal preferences. Some users find dark mode easier on the eyes, especially in low-light conditions, while others prefer light mode during the day. Integrating a toggle button for switching between light and dark modes will enhance user experience and accessibility.

**Comment by nafisreza** [comment]
Good observation. Awaiting confirmation from the UX team if they have this feature planned in the upcoming versions. 
Thanks!

**Comment by arthurkay** [comment]
/reopen

Is there someone working on this, or the issue has been abandoned. If no one is actively working on it, I'd like to take it up.
