### ISSUE TITLE
Bug: Inconsistent display of Marque in Windows

### ISSUE THREAD

**Issue by TenzDelek** [knative/docs#5996]
## Issue

- it has came to my notice that the home screen of the doc website where we have the marque effect for the (trusted by) section is being rendered inconsistently.
In Windows 11, I have checked with all Browsers(brave, chrome, Firefox, edge) and is rendering as below
-in windows-
<img width="1248" alt="image" src="https://github.com/knative/docs/assets/122612557/afa6e8de-8e27-486f-b7ec-267a8ac03a1c">

## Expected Behavior
-in macOS , and mobile device it is rendering as below:

![WhatsApp Image 2024-05-27 at 11 51 19 PM](https://github.com/knative/docs/assets/122612557/2ac40cd5-0115-4936-879f-ebcfcd82a844)

it looks like the marque is being block or something else is hindering this behaviour?

**Comment by shivamgupta2020** [comment]
@TenzDelek Can u specify the steps to produce this bug? On my machine, I can't find any bug like that, it works fine for me on all browsers in both windows and Ubuntu.

**Comment by TenzDelek** [comment]
> @TenzDelek Can u specify the steps to produce this bug? On my machine, I can't find any bug like that, it works fine for me on all browsers in both windows and Ubuntu.

I don't think there is a step for this behavior. It is more like a bug or either my machine is acting weird. What windows you use? Mine is windows 11.

**Comment by shivamgupta2020** [comment]
I'm also using Windows 11 but I haven't encountered this bug yet. On Ubuntu 22.04 too, I haven't encountered it.
I used Brave, Edge, Firefox browser.

**Comment by shivamgupta2020** [comment]
If possible can u share video?

**Comment by TenzDelek** [comment]
Hmm interesting, will share the video in a few minutes

**Comment by TenzDelek** [comment]
https://github.com/knative/docs/assets/122612557/83a43de8-3821-47ea-a7ef-1311da5a976a

**Comment by shivamgupta2020** [comment]
@TenzDelek , how are you checking this on both Windows 11 and macOS? Are you using different devices or a VM?

**Comment by TenzDelek** [comment]
I have 2 machine👍

**Comment by shivamgupta2020** [comment]
Currently I'm not able to reproduce this bug. So I suggest u put this in slack discussion, so that other members can check on this issue and provide their feedback.

**Comment by TenzDelek** [comment]
Yup, maybe something wrong from my end.
