### ISSUE TITLE
Convert PNG Logos in Case Study Section to Next-Gen Formats

### ISSUE THREAD

**Issue by theDeviser** [knative/docs#5997]
**Describe the change you'd like to see**
All the logos in the case study section of the website should be converted from PNG format to next-gen formats like .webp or .svg . This change will help improve the website's performance by reducing image file sizes and enhancing load times. 

**Additional context**
The current use of PNG images for logos in the case study section leads to larger file sizes and slower page load times, which can negatively impact user experience. Next-gen image formats like WebP and SVG offer better compression and quality, making them ideal for improving website performance. WebP is particularly useful for raster graphics, while SVG is perfect for scalable vector graphics. Implementing these changes will not only enhance performance but also contribute to better SEO rankings and overall user satisfaction.

the effect of the above issue on the website's performance
![image](https://github.com/knative/docs/assets/92399093/8e0d3f42-7d83-4c37-b96f-35bfa80adc06)

**Comment by theDeviser** [comment]
I would like to work on this issue if approved by the maintainers

**Comment by shivamgupta2020** [comment]
Hi @theDeviser ,
I think a similar issue has already been raised (#5981).You can join that discussion and provide your valuable inputs there.
