### ISSUE TITLE
Proposal: IBM Case Study to Knative Website

### ISSUE THREAD

**Issue by nrrso** [knative/docs#6057]
CNCF Case Study:

https://www.cncf.io/case-studies/ibmwatsonxassistant/

I think this is an interesting case study to list at https://knative.dev/docs/about/case-studies/ 

Need to consider the following points though to proceed:
* Point of Contact for IBM approval
* Other Case Studies of IBM already existing? Which to link? 
* Potential Social Media post?

cc @nainaz @aliok @knative/ux-wg-leads

**Comment by Cali0707** [comment]
I like the idea of adding this to the case studies section, we currently have a blog post linking to the case study but I think the case studies section should also contain this reference

**Comment by Leo6Leo** [comment]
> I like the idea of adding this to the case studies section, we currently have a blog post linking to the case study but I think the case studies section should also contain this reference

+1

**Comment by nrrso** [comment]
Was already done in #5987
