### ISSUE TITLE
Update the button border radius on Tutorial page

### ISSUE THREAD

**Issue by Leo6Leo** [knative/docs#6064]
## Expected Behavior
![image](https://github.com/user-attachments/assets/f80f57c1-d522-4956-99b6-3277507542ed)

## Actual Behavior

**The "Get started" buttons on the page should have the same border radius as the one shown on the home page.**

![image](https://github.com/user-attachments/assets/d9026773-b48b-4dc2-9e6d-24400463e65b)

## Additional Info
**Additional context**
`border-radius:0.7rem;` is used for the home page css. [[Link to the css file of this change](https://github.com/ShravaniAK/Knative_docs/blob/fa84f4262fc83af7bfc7aa592fbc6574c04cb444/overrides/assets/stylesheets/home.css#L105)]

/help-wanted
/good-first-issue

**Comment by rissh** [comment]
Hey @Leo6Leo,

I'm planning to work on this issue. Can you please assign me this issue?
Please feel free to provide any suggestions or guidance as I work on this task. I'm open to feedback and would appreciate any insights you might have.

Thank you!

**Comment by Leo6Leo** [comment]
/assign @rissh  Thank you for your help! Just a side note: if you could finish this as early as possible, that would be really appreciated, as we hope to make this merged before the Knative 1.15 release. (Tomorrow)

@pranay911 And feel free to provide PR review @rissh 's PR when it is ready

Don't hesitate to reach out for help anytime

**Comment by rissh** [comment]
Yes sure, I will do it.
