### ISSUE TITLE
Elements are not center aligned in the pre-release version of the website

### ISSUE THREAD

**Issue by Leo6Leo** [knative/docs#6066]
## Expected Behavior
The following items need to be vertically center aligned according to the [Design files](https://www.figma.com/design/3arTeN4tR3byPKSkrzTibp/Knative-Website?node-id=281-2598&t=Fju8Zi0eTYMbRaw4-0)

## Actual Behavior

![image](https://github.com/user-attachments/assets/36c7de26-3fe4-4569-972b-ecc63bcd925f)
The text "Case study" is not center aligned (vertical)

![image](https://github.com/user-attachments/assets/2cdd4676-3284-405b-aa95-82eb98c2116c)
The logo and text here is not center aligned (vertical), or closer to the case study blocks as described in the figma file.

@ShravaniAK

**Comment by ShravaniAK** [comment]
thanks, @Leo6Leo for pointing out this bug, I will fix this and raise a pr asap!

**Comment by amiii123malviya** [comment]
Is this issue still active?

**Comment by amiii123malviya** [comment]
Hello @Leo6Leo ,
 
I hope you are doing well,

Yes i would like to contribute to other projects and i will check the meeting minutes.
Thankyou for your time .

Best Regards
