### ISSUE TITLE
Text size of the button is not consistent in the pre-released version of the website

### ISSUE THREAD

**Issue by Leo6Leo** [knative/docs#6067]
## Expected Behavior
![image](https://github.com/user-attachments/assets/0e102e31-0d6e-4b12-9fdf-31be4496b306)

## Actual Behavior
![image](https://github.com/user-attachments/assets/85559e3d-7d41-4d6d-8d6c-d4cd7cbc7101)

Same apply to some other buttons on the page.

https://www.figma.com/design/3arTeN4tR3byPKSkrzTibp/Knative-Website?node-id=911-56&t=Fju8Zi0eTYMbRaw4-0

@ShravaniAK

**Comment by bharateshwq** [comment]
i will take up this issue

**Comment by ShravaniAK** [comment]
I have fixed this in #6068
