### ISSUE TITLE
Inconsistent Text Color and Contrast in Knative Components Section

### ISSUE THREAD

**Issue by pranay911** [knative/docs#6071]
The text color and contrast in the "Knative Components" section are inconsistent between different instances. In the first instance, the heading is in green and the body text is in white, while in the second instance, both the heading and body text are in white. The green text might have lower contrast against the blue background, affecting readability and accessibility.

## Expected Behavior

![image](https://github.com/user-attachments/assets/bb0a7dce-72d7-44c6-b2eb-4fbac8addb04)

## Actual Behavior
![image](https://github.com/user-attachments/assets/d8cc6732-2c75-4500-a859-deb786b0fde4)

## Steps to Reproduce the Problem

1. Compare the two instances of the "Knative Components" section.

## Additional Info
Mention the importance of maintaining consistency and accessibility in the application.

**Comment by amiii123malviya** [comment]
Hello,

i hope you are doing well,

I would like to work on this issue, please let me work on this issue and on this project It will be a great opportunity.

Best Regards..

**Comment by ShravaniAK** [comment]
This has been fixed already, so we can close this issue!
