### ISSUE TITLE
nightly gcr images seem to be removed

### ISSUE THREAD

**Issue by jeremyrajan** [knative/docs#6100]
## Actual Behavior
Hi, we were using nightly builds and realized it was removed couple of days ago (https://console.cloud.google.com/artifacts/docker/knative-nightly/us/gcr.io/knative.dev%2Feventing) which started failing our deployments

## Steps to Reproduce the Problem
https://console.cloud.google.com/artifacts/docker/knative-nightly/us/gcr.io/knative.dev%2Feventing can't access.

**Install information:**
 - Platform (GKE, IKS, AKS, etc.): GKE
 - Knative Version: nightly

**Comment by pierDipi** [comment]
@jeremyrajan, thanks for reporting, I see for example, broker ingress here https://console.cloud.google.com/artifacts/docker/knative-nightly/us/gcr.io/knative.dev%2Feventing%2Fcmd%2Fbroker%2Fingress

which image is failing and how are you referencing them?
