### ISSUE TITLE
Remove next/previous text from blog footer

### ISSUE THREAD

**Issue by Cali0707** [knative/docs#6124]
**Describe the change you'd like to see**
Currently in the blog there is text on the footer above each link saying next/previous. As the blog posts are reverse chronological order this can be confusing, so it would be better to remove this altogether (but only for the blog, not the main docs)

**Additional context**
![Screenshot 2024-09-17 at 1 45 21 PM](https://github.com/user-attachments/assets/b99e9cf3-9d21-409e-8c85-2596eb2e561c)

**Comment by prushh** [comment]
Hi @Cali0707, I would like to work on this issue!

I have one question, should I remove all the `nav` selector or only the labels (_previous_ and _next_) above the links? Obviously just for the blog website.

**Outcome example**
<img width="1524" alt="image" src="https://github.com/user-attachments/assets/ba98059f-6a01-4103-9f8a-9f9f67607bcc">
