### ISSUE TITLE
Adding prettier to CI

### ISSUE THREAD

**Issue by gyliu513** [knative/docs#624]
As we have just merged the PR for `prettier` format at #620 in whole `knative/docs` repo, but as people will continue all markdown files in development, and will introduce format issue which will violate `prettier`, how about adding `prettier` check in CI?

/cc @samodell @RichieEscarez

**Comment by samodell** [comment]
Hi @gyliu513 , the PR in #620 was generated by a bot that is now run I believe nightly at 6am PT. So any un-pretty changes will eventually be caught and fixed.

Adding @mattmoor  to comment on if/when it will be added to the CI process for PRs.

**Comment by gyliu513** [comment]
Got it, I think we can continue use the bot. Thanks @samodell @mattmoor

**Comment by mattmoor** [comment]
There are a bunch of them here: https://github.com/mattmoor/knobots  They are based on the knative components themselves.  If you are interested I can do a little show and tell.

I hope to find a more permanent home as part of our productivity workgroup (cc @jessiezcc )

**Comment by gyliu513** [comment]
Ah, thanks @mattmoor , clear now, seems you are leveraging Knative `BuildTemplate ` at https://github.com/mattmoor/knobots/blob/master/config/prettier-template.yaml , this is awesome: Knative is a consumer for Knative ;-)

**Comment by jessiezcc** [comment]
@chaodaiG will look into this area. https://github.com/knative/test-infra/issues/294 tracks the work needed.
