### ISSUE TITLE
Builder can be mistaken as an API

### ISSUE THREAD

**Issue by ahmetb** [knative/docs#625]
/kind docs
/area build

See doc https://github.com/knative/docs/tree/41462c69e1879aba14ad91a6f2d10ffe6668051f/build 

This doc treats `Builder` as an API object by capitalizing it.

This made me think it's an API, so I tried to find the object spec or some examples, but I could not. If it's not an API but a concept (like "steps") we should not capitalize it (unless it's at the beginning of a sentence).

![image](https://user-images.githubusercontent.com/159209/49462781-c2889780-f7ab-11e8-92a8-2ebef7c596e3.png)

Kubernetes docs establish the convention here by reserving capitalizing to API types, I recommend following suit.

/cc @mattmoor

**Comment by ahmetb** [comment]
To provide more context: Think of Kubernetes documentation. If you're reading through it, and you see a concept word like "Foo" in the middle of the sentence, you can pretty much be sure that it's an API.

This is why you won't see "Container" capitalized in the middle of the sentence on Kubernetes, because it's not an API (just a concept) but "Pod" is always capitalized.

**Comment by samodell** [comment]
It was an early decision to capitalize each component of Knative: Serving, Build, Eventing, etc. This makes it clear that a Knative Build is its own distinct thing, separate from a generic build. We are not going to be able to follow every convention set by Kubernetes, even if it does create a bit of confusion from time to time.

**Comment by ahmetb** [comment]
I think when we have a website we should have a discussion on how to reorganize the information.
