### ISSUE TITLE
Source code for gcr.io/knative-samples/knative-route-demo not available

### ISSUE THREAD

**Issue by ahmetb** [knative/docs#628]
Used in this tutorial: https://github.com/knative/docs/blob/c64c63a160f5260de024aee0bc280d967972a62d/serving/samples/blue-green-deployment.md

The source code for image `gcr.io/knative-samples/knative-route-demo:{blue,green}` is not available on this repo.

I wanted to see the source code because if I specify env T_VERSION to something other than "blue" or "green", it defaults to "blue" which is unintuitive because I couldn't tell whether it's a routing issue (v1 serves blue) or simply app image has special code defaulting to blue (turns out this was the case).

We should put this tutorial into a folder, and add its dockerfile+.go file.

**Comment by ahmetb** [comment]
/cc @mchmarny 
any ideas?

**Comment by mchmarny** [comment]
https://github.com/mchmarny/knative-route-demo
