### ISSUE TITLE
Better not to automatically apply the anyuid addon to minishift during deployment

### ISSUE THREAD

**Issue by gbraad** [knative/docs#662]
In this docs you write the following:

https://github.com/knative/docs/blob/9530cae547f33a4c318d18624bbea89e2ba28e9e/install/Knative-with-Minishift.md#L52

You might not wanna do this as an enable of the add-on. This can lead to issues with the webconsole: https://github.com/minishift/minishift/issues/2809

It is better to do `minishift addon apply anyuid` after the deployment finished.

**Comment by RichieEscarez** [comment]
cc/ @kameshsampath
