### ISSUE TITLE
Can I delete namespace of full domain name

### ISSUE THREAD

**Issue by gongzili456** [knative/docs#680]
## Expected Behavior
 {route}.{default-domain}
## Actual Behavior
{route}.{namespace}.{default-domain}

## Steps to Reproduce the Problem
The fully qualified domain name for a route by default is {route}.{namespace}.{default-domain}, but I don't need the namespace part. How I do?

**Comment by tcnghia** [comment]
This is not currently possible.  Can you please open a feature request in https://github.com/knative/serving/issues ? Thanks

**Comment by samodell** [comment]
Closing as a non-docs related issue.
