### ISSUE TITLE
Resources not consistently formatted across the documentation

### ISSUE THREAD

**Issue by samodell** [knative/docs#707]
## Expected Behavior
The same resource is denoted identically in the documentation, using either `` or bold formatting or no formatting at all.

## Actual Behavior
The same resource is sometimes set off in code formatting, sometimes not, often using different styling on the same page.

## Steps to Reproduce the Problem
Related [PR](https://github.com/knative/docs/pull/703) and these pages:
https://github.com/knative/docs/blob/master/build/builds.md
https://github.com/knative/docs/blob/master/build/build-templates.md
https://github.com/knative/docs/blob/master/build/builder-contract.md

I don't think this problem is limited to just these pages, though. I think we need to have a larger discussion about formatting terminology across Knative, since we do have a lot of important terminology to explain. I think having multiple components exacerbates this problem for us, and it's important to make a decision early on so we can be consistent moving forward.

**Comment by RichieEscarez** [comment]
We need to define, agree, and publish some authoring guidelines before we can move forward. 

- When should a Knative resource include the code syntax formatting \` `?
- When is it okay to **bold** a resource name/object?

**Comment by RichieEscarez** [comment]
This can be closed. A while back we decided to use these guidelines: https://developers.google.com/style/text-formatting

re: https://knative.dev/community/contributing/docs/docs-contributing/#style-guide
