### ISSUE TITLE
Service with build is not functioning reliably 

### ISSUE THREAD

**Issue by hrishin** [knative/docs#709]
## Expected Behavior
- Github clone should work 
- Kaniko step should push docker image
- The application should be  accessible 

## Actual Behavior
- Github clone is failing intermittently as a second step of the build. Initially, I thought it could be GitHub issue or API rate limit is reached but it's not
- As [per example](https://github.com/knative/docs/blob/master/serving/samples/source-to-url-go/README.md), build template is using Kaniko to build and push the docker image. 
However, this step is too flecky. It is failing with 
`error building image: getting stage builder for stage 0: get https://index.docker.io/v2 : dial tcp look up index.docker.io on 10.96.0.10:53 : no such host`
I've cross checked the secrets, annotations but it is failing in 99%
- In one instance application got build and it got deployed. However, the application was not accessible from ingress as sidecar container was missing. I've crosschecked if `istio-injection: enabled` is enabled on namespace, it was there.

## Steps to Reproduce the Problem
follow https://github.com/knative/docs/blob/master/serving/samples/source-to-url-go/README.md

**Install information:**
 - Platform (GKE, IKS, AKS, etc.): minikube 
 - Knative Version: v0.2.2 - lite

**Comment by kameshsampath** [comment]
@hrishin  i guess the docker hub url is not right can  check adding the following annotation to your secret ` build.knative.dev/docker-0: https://index.docker.io/v1/`

**Comment by RichieEscarez** [comment]
Build to be deprecated
