### ISSUE TITLE
I'd like to translate docs into Japanese

### ISSUE THREAD

**Issue by toshi0607** [knative/docs#716]
## What is changing? (Please include as many details as possible.)

I'd like to translate docs into Japanese. Where should make a folder named like `ja` ?

## How will this impact our users?

It make Japanese users easier to catch up.

## When will the change take effect (to the best of your knowledge)?

When translation will have been completed.

## Context
Link to associated PRs or issues from other repos here.

nothing

## Additional info

nothing

**Comment by samodell** [comment]
Thanks for volunteering to help out with this! We don't have our docs set up for localization/translation yet. We will let you know when there's a structure in place for creating localized versions of the docs.

**Comment by samodell** [comment]
Closing as a duplicate of #1222 -- we'll use that issue to track the subject of translating the Knative docs in general.
