### ISSUE TITLE
Update all samples to reflect available install manifests

### ISSUE THREAD

**Issue by RichieEscarez** [knative/docs#719]
## Expected Behavior
Follow a [Knative Serving sample doc](https://github.com/knative/docs/tree/master/serving/samples) and install Knative.

## Actual Behavior
For 0.3, there are no longer ....release*.yaml install bundles for the Serving component.

The deleted manifest files are gone and need to be replaced with the corresponding available manifest file(s):

github /knative/serving/releases/download/v0.3.0??????/**serving.yaml**
github /knative/serving/releases/download/v0.3.0??????/**monitoring_.yaml**
github /knative/build/releases/download/v0.3.0??????/**build.yaml**

Note: actual version number/url is TBD

CONCERN:
Depending on the sample, validation is needed from the corresponding Host SME or previous author to determine which of the individual Knative components should be installed (for example, Serving only, or are the Build or monitoring plugins needed too?).

Immediate short-term fix might be to replicate the previously used install bundle (ie list/install all of the individual manifest files to duplicate what the removed ..release*.yaml included).

DELETED MANIFEST FILES:
Manifest files that have been deleted:

release.yaml
release-lite.yaml
release-no-mon.yaml

## Additional Info
PR that shows all the changes to the Knative Serving install: https://github.com/knative/serving/pull/2821

**Comment by samodell** [comment]
This was fixed in #775 and #777.
