### ISSUE TITLE
OpenShift docs missing service account to scc binding

### ISSUE THREAD

**Issue by etsauer** [knative/docs#742]
The `/install/Knative-with-OpenShift.md` doc is missing an scc assignment in the _Installing Istio_ section:

```
oc adm policy add-scc-to-user anyuid -z cluster-local-gateway-service-account -n istio-system
```

## Expected Behavior

Following instructions inder _Installing Istio_ should result in all pods coming up healthy

## Actual Behavior

Currently, the pod for the `cluster-local-gateway` pod fails to start with a `permission denied` error opening a .json file.

## Steps to Reproduce the Problem

1. Follow instructions for _Installing Istio_
1. See that the `cluster-local-gateway-*` pod fails
1. Run `oc adm policy add-scc-to-user anyuid -z cluster-local-gateway-service-account -n istio-system`
1. Delete the `cluster-local-gateway-*` pod.
1. Observe that a new pod starts up and becomes ready

## Additional Info
**Additional context**

**Install information:**
 - Platform (GKE, IKS, AKS, etc.):
 - Knative Version:

**Comment by bbrowning** [comment]
Just to clarify, did you hit this problem against Knative 0.3 or 0.2.x?

**Comment by bbrowning** [comment]
Nevermind - I see that this is a ServiceAccount that's new in 0.3. Once you added the missing SCC, did you run into any other new problems with Knative 0.3 and OpenShift?
