### ISSUE TITLE
Docs for graphana install need to be updated to work with current serving.

### ISSUE THREAD

**Issue by n3wscott** [knative/docs#755]
## Expected Behavior

 I can use the docs to install monitoring

## Actual Behavior

docs point to files that do not exist.

## Steps to Reproduce the Problem

1. go to [prometheus grafana setup](https://github.com/knative/docs/blob/master/serving/installing-logging-metrics-traces.md#elasticsearch-kibana-prometheus--grafana-setup)
1. follow instructions
1. fail to install.

## Additional Info
**Additional context**

Console output:

```
⦿ kubectl apply --recursive --filename config/monitoring/100-common \
>    --filename config/monitoring/150-elasticsearch \
>    --filename third_party/config/monitoring/common \
>    --filename third_party/config/monitoring/elasticsearch \
>    --filename config/monitoring/200-common \
>    --filename config/monitoring/200-common/100-istio.yaml
the path "config/monitoring/100-common" does not exist
the path "config/monitoring/150-elasticsearch" does not exist
the path "third_party/config/monitoring/common" does not exist
the path "third_party/config/monitoring/elasticsearch" does not exist
the path "config/monitoring/200-common" does not exist
the path "config/monitoring/200-common/100-istio.yaml" does not exist
```

**Install information:**
 - Platform (GKE, IKS, AKS, etc.): latest 1-14-2019
 - Knative Version: 0.3

**Comment by carieshmarie** [comment]
@n3wscott @mdemirhan Do we know if this issue still needs attention?

**Comment by mdemirhan** [comment]
This is no longer an issue. Documents are updated with correct instructions.
