### ISSUE TITLE
Ingress bug

### ISSUE THREAD

**Issue by white-cloud** [knative/docs#756]
Hello everyone,

1- I'm having actually a bug in the ingress, to get my ingress it always pending:

kubectl get svc knative-ingressgateway --namespace istio-system
NAME TYPE CLUSTER-IP EXTERNAL-IP PORT(S) AGE
knative-ingressgateway LoadBalancer 10.103.200.25 80:32380/TCP,443:32390/TCP,31400:32400/TCP,15011:31198/TCP,8060:32694/TCP,853:32359/TCP,15030:31316/TCP,15031:32161/TCP 1h

I used the following command to get the link of Hello so i can call it from outside the cluster, but i can;t get any host name to call
kubectl get ksvc helloworld-python --output=custom-columns=NAME:.metadata.name,DOMAIN:.status.domain
NAME DOMAIN
helloworld-python
In this case is there any solution or a configuration to do so i can use Nodeport instead of Loadbalancer.

Thank you.

**Comment by kmanicka** [comment]
Please provide details about the kubernetes environment are you trying to run this sample

**Comment by white-cloud** [comment]
@kmanicka Thank you for your answer, i already fixed that problem by installing a new version of Kubernetes .

**Comment by carieshmarie** [comment]
Looks resolved, so closing this issue.
