### ISSUE TITLE
knative-monitoring namespace is not installed by current instructions

### ISSUE THREAD

**Issue by vaikas-google** [knative/docs#757]
## Expected Behavior
As per the documents here:
https://github.com/knative/docs/blob/master/install/Knative-with-GKE.md

In the 'Installing Knative' section, after running the kubectl apply, it says to monitor Knative componets. The last item fails:
kubectl get pods --namespace knative-monitoring
No resources found.

vaikas@penguin:~/projects/go/src/github.com/vaikas-google/twitter$ kubectl get ns knative-monitoring
Error from server (NotFound): namespaces "knative-monitoring" not found

## Actual Behavior
That there are no failures with the instructions in a happy case, or that there's an error during the install saying something went wrong.

## Steps to Reproduce the Problem

1. Execute the instructions from here: https://github.com/knative/docs/blob/master/install/Knative-with-GKE.md

1. run "kubectl get pods --namespace knative-monitoring" after installing Knative 
1.namespace does not exist

## Additional Info
**Additional context**

**Install information:**
 - Platform (GKE, IKS, AKS, etc.):
 - Knative Version:

**Comment by justingrayston** [comment]
What K8S GKE version is your cluster running. I had a very similar issue which is still open #593

**Comment by jamesward** [comment]
Ditto for: https://github.com/knative/docs/blob/master/install/Knative-with-any-k8s.md

**Comment by samodell** [comment]
This was fixed in #786
