### ISSUE TITLE
Something without 8 Gi

### ISSUE THREAD

**Issue by sebgoa** [knative/docs#76]
We need to be able to do something basic with one component of `knative` without needing 8 Gi to run minikube.

As crazy as it sounds to some, a lot of people do not have 8 Gi to spare on their machine.

**Comment by bacongobbler** [comment]
+1, I was pleasantly surprised when I was evaluating knative and I couldn't get it to run on my 5-node AKS cluster.

A Googler kindly told me on twitter that the GKE docs mention requiring to bootstrap a cluster using `n1-standard-4` nodes, which have 4 vCPUs per node. This is noted in the AKS documentation as `Standard_DS3_v2` - which was my mistake - but I have not yet run into an app that required this much power to run a sample app!

So, perhaps there are 2 asks here:

1) a generic "Minimum Requirements" doc would be nice to have in the [main Install Guide](https://github.com/knative/docs/tree/master/install)
2) A way to run a slimmed-down version of knative, one that can run on simpler hardware.

For reference, here is how Openshift Enterprise lists its system requirements: https://docs.openshift.com/enterprise/3.0/install_config/install/prerequisites.html#system-requirements

And here's how Deis Workflow lists its system requirements: https://deis.com/docs/workflow/installing-workflow/system-requirements/
