### ISSUE TITLE
Link checker causing build failures

### ISSUE THREAD

**Issue by samodell** [knative/docs#772]
The link checker is occasionally failing when it shouldn't on some PRs.

#700 
Failing on demo links:
```
I0115 22:44:43.537] FILE: serving/samples/blue-green-deployment.md
I0115 22:44:43.914] [✖] http://blue-green-demo.default.YOUR_CUSTOM_DOMAIN.com
I0115 22:44:43.914] [✖] http://v2.blue-green-demo.default.YOUR_CUSTOM_DOMAIN.com
I0115 22:44:43.914] [✖] http://v1.blue-green-demo.default.YOUR_CUSTOM_DOMAIN.com
I0115 22:44:43.914] 
I0115 22:44:43.914] ERROR: dead links found!
```

#715 
Failing on a link with an underscore:
```
I0115 18:16:34.685] FILE: eventing/samples/writing-a-source/01-bootstrap.md
I0115 18:16:35.704] [✖] https://book.kubebuilder.io/quick
I0115 18:16:35.705] 
I0115 18:16:35.705] ERROR: dead links found!
I0115 18:16:35.966] 
I0115 18:16:35.966] FILE: eventing/samples/writing-a-source/02-define-source.md
I0115 18:16:37.941] [✖] https://book.kubebuilder.io/quick
I0115 18:16:37.941] 
I0115 18:16:37.941] ERROR: dead links found!
```

But the link is actually https://book.kubebuilder.io/quick_start.html , which is not dead.

**Comment by samodell** [comment]
Darn. A lot of the link-checking is really useful, and it's already found a good number of dead links. Is there a way to have the link checker run but not cause a build failure? Or a way to manually override the build tests in cases like this? I'd prefer either of those options to disabling it entirely.

**Comment by adrcunha** [comment]
If the link checker is not fatal, nobody will pay attention to it, I assure you. :P It seems that the best solution here is to have another check (non fatal) that will run the linter and the link checker. The author will decide whether to address any issues brought by them or not. Seems to be a fair compromise to me. However, this is not as simple as disabling the checks entirely (although not difficult as fixing the link checker tool), so probably disabling the link checker to unblock PR merging will be the first step.

**Comment by samodell** [comment]
Disabling it sounds good as a first step.

The majority of PRs in the docs repo are approved by a tech writer, so we can definitely make sure we ask folks to fix errors they see in the link checker (or linter) before approving their PRs. It's better than nothing, anyhow.
