### ISSUE TITLE
helloworld-csharp broken with dotnet sdk 2.2

### ISSUE THREAD

**Issue by ahmetb** [knative/docs#789]
If I go install dotnet SDK today, I'll get 2.2.

But the dotnet SDK provided in https://github.com/knative/docs/blob/b850378d5c17e5540d7bb0387133233485c3d662/serving/samples/helloworld-csharp/Dockerfile uses 2.1

The docs also say 2.1 but not sure how realistic it is to expect people will install/have the older version.

**Comment by ahmetb** [comment]
Install SDK link goes to https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial#install which downloads 2.2.

Microsoft doesn't provide links to download earlier versions as far as I can tell on this site.

So when you have 2.2 installed, the :2.1 tag on dockerfile causes `dotnet restore` to fail (because your project is 2.2).

And microsoft/dotnet doesn't have a simpler tag like `:2` either. https://hub.docker.com/r/microsoft/dotnet.

Either we're gonna chase the latest version of dotnet SDK every time, or we're gonna leave a note to have people update the version.

**Comment by ahmetb** [comment]
cc: @grayside

**Comment by steren** [comment]
I agree that the sample needs to be updated to the latest dotnet SDK version.
