### ISSUE TITLE
Docs don't explain how to configure GcpPubSub

### ISSUE THREAD

**Issue by meteatamel** [knative/docs#793]
In commit #777, we removed these lines from doc:

kubectl --namespace knative-sources create secret generic gcppubsub-source-key --from-literal=key.json=''
kubectl apply --filename https://github.com/knative/eventing-sources/releases/download/v0.3.0/release-gcppubsub.yaml

But we never show anywhere else how to apply gcppubsub.yaml. 

We should either show this in the main eventing installation page or in GCP Pub/Sub sample page.

**Comment by carieshmarie** [comment]
Looks like this was addressed in PR #829 , so closing this issue.
