### ISSUE TITLE
subsriber.yaml is missing "image" field

### ISSUE THREAD

**Issue by meteatamel** [knative/docs#794]
Subscriber currently has the following under container: 

        spec:
          container:
            gcr.io/knative-releases/github.com/knative/eventing-sources/cmd/message_dumper@sha256:8423232db7a7b4010c0cfbfaef95745efe962631af9b7456903825801a7893f7

But it should have the image field:

        spec:
          container:
            image: gcr.io/knative-releases/github.com/knative/eventing-sources/cmd/message_dumper@sha256:8423232db7a7b4010c0cfbfaef95745efe962631af9b7456903825801a7893f7

**Comment by sebgoa** [comment]
@meteatamel can you specify where this manifest is ?

**Comment by meteatamel** [comment]
I was probably referring to this but it looks like it's fixed now: https://github.com/knative/docs/blob/master/docs/eventing/samples/gcp-pubsub-source/subscriber.yaml
