### ISSUE TITLE
eventing cronjob does not work

### ISSUE THREAD

**Issue by gyliu513** [knative/docs#813]
When I follow steps at https://github.com/knative/docs/blob/master/eventing/samples/cronjob-source/README.md to run cronjob sample, found that the image `github.com/knative/eventing-sources/cmd/message_dumper:latest` cannot be found, am I missing anything?

https://github.com/knative/docs/blob/master/eventing/samples/cronjob-source/service.yaml#L13

FYI @zxDiscovery @whynowy

**Comment by whynowy** [comment]
@gyliu513 - sorry, my bad, it should be `ko apply -f service.yaml`, I'll fix it.

**Comment by whynowy** [comment]
Same issue for https://github.com/knative/docs/tree/master/eventing/samples/github-source, I'll check if there's anything else and fix them together.
