### ISSUE TITLE
Clearer instructions on using knative with a private container registry

### ISSUE THREAD

**Issue by beemarie** [knative/docs#819]
## Expected Behavior
I was trying to set up knative to use my private container registry (in this case IBM CR), and it was difficult to find instructions to do so. One possible solution would be to create a new page in the /serving folder with instructions for IBM Container Registry (& google container registry, & other private container registries).

Depending on how similar the instructions are, it may also make sense to create a generic private registry page.

## Actual Behavior
I couldn't find instructions for this. There are some instructions inside the [build-private-repo-go](https://github.com/knative/docs/blob/master/serving/samples/build-private-repo-go/README.md) sample, but the instructions are labeled as "Deploying to Knative from a Private GitHub Repo," so it wasn't clear to me that they were also using a private container registry. We ultimately did use the instructions found here to create the imagePullSecret as required, but it would be nice for there to be some clear documentation on private registries.

## Steps to Reproduce the Problem
1. Try to deploy to a private container registry

**Comment by beemarie** [comment]
I'm unable to assign myself, but I'm more than happy to write up docs for using IBM Container Registry from Knative. I was initially thinking that doc would live in the docs/serving folder.

**Comment by samodell** [comment]
Thanks for volunteering, @beemarie ! I assigned you to this. It sounds like a lot of the steps existed in a doc you already found, "Deploying to Knative from a Private GitHub Repo." What do you think about naming your new doc "Deploying to Knative using a Private Registry" to keep it more generic, and then in your walk-through you can use IBM Container Registry as an example?

**Comment by beemarie** [comment]
@samodell that sounds good to me, i'll get a PR started for this one.
