### ISSUE TITLE
Proposal: update helloworld-java with simpler code

### ISSUE THREAD

**Issue by steren** [knative/docs#832]
Our [simple Java hello world](https://github.com/knative/docs/tree/master/serving/samples/helloworld-java) uses Spring Boot. This adds a lot of complexity for this simple use case and Spring is not a framework that works great in serverless environment.

Proposal: 

* Replace `helloworld-java` with simpler code. For example, see this existing [minimal Java 11 sample](https://github.com/ludoch/samples/tree/master/java11/smallest-sample) or use a mote lightweight framework, like http://sparkjava.com/.

* Delete the existing sample or move it to `helloworld-java-spring` (I can understand trhat we would still want to showcase Spring Boot.

CC @ludoch @grayside

**Comment by hpandeycodeit** [comment]
@steren I can work on this one.

**Comment by saturnism** [comment]
I don't feel we should replace Spring. It would be useful to have a suite of Java examples for different frameworks. +1 to micronaut and spark. I feel we should add vert.x & ktor as well.

something like helloworld-java-spring, helloworld-java-micronaut, helloworld-kotlin-ktor can be useful.

**Comment by hpandeycodeit** [comment]
@saturnism @steren 

So shall I add examples on other frameworks as well as per comment by @saturnism?

**Comment by steren** [comment]
Yes, I think we should transform `helloworld-java` into `helloworld-java-spring`. And add other samples as @saturnism suggests
