### ISSUE TITLE
Dead link to install knative/build for minishift

### ISSUE THREAD

**Issue by navidshaikh** [knative/docs#844]
## Expected Behavior
In *Install knative-serving* section of [Knative-with-Minishift.md](https://github.com/knative/docs/blob/master/install/Knative-with-Minishift.md#install-knative-serving), `oc apply` command reads as follow

```
[..] \ 
oc apply -f https://github.com/knative/build/releases/download/v0.3.0/build.yaml
```
where link to expected YAML file should be (as per [Knative build v0.3.0 assets](https://github.com/knative/build/releases/tag/v0.3.0))
```
oc apply -f https://github.com/knative/build/releases/download/v0.3.0/release.yaml
```

| notice build.yaml vs release.yaml 

## Actual Behavior
The link referenced returns 404.
Related https://github.com/knative/docs/issues/719

**Comment by samodell** [comment]
Fixed by #877
