### ISSUE TITLE
[DOC] install/Knative-with-Minikube.md

### ISSUE THREAD

**Issue by alonsocamaro** [knative/docs#876]
## Additional Info

In the section "Installing Knative Serving", it is stated:

`` Because you have limited resources available, install only the Knative Serving component, omitting the other Knative components as well as the observability and monitoring plugins.``

Although many of us install minikube in a single VM that doesn't mean we have few resources. Could you please indicate how to do not have this limitation?

Many thanks

**Comment by moeyui1** [comment]
@alonsocamaro I think there is no any limitation in fact. According to [Knative Install on any Kubernetes](https://github.com/knative/docs/blob/master/install/Knative-with-any-k8s.md).
All you have to do to get the "Comprehensive installation" is applying the remaining `.yaml`.
```bash
kubectl apply \
--filename https://github.com/knative/build/releases/download/v0.3.0/release.yaml \
--filename https://github.com/knative/eventing/releases/download/v0.3.0/release.yaml \
--filename https://github.com/knative/eventing-sources/releases/download/v0.3.0/release.yaml \
--filename https://github.com/knative/serving/releases/download/v0.3.0/monitoring.yaml
```

**Comment by samodell** [comment]
Thanks @moeyui1 !
