### ISSUE TITLE
Broken link in gcp-pubsub-source/README.md

### ISSUE THREAD

**Issue by poy** [knative/docs#891]
Looking at the [Verify](https://github.com/knative/docs/blob/master/eventing/samples/gcp-pubsub-source/README.md#verify), it has a link to the Subscriber section. However, there is no "Subscriber" section, so the link is broken.

**Comment by moeyui1** [comment]
https://github.com/knative/docs/pull/559/files
It seems to be exits previously?

**Comment by sebgoa** [comment]
First the new URL of the GCP doc is: https://github.com/knative/docs/tree/master/docs/eventing/samples/gcp-pubsub-source
