### ISSUE TITLE
Create Developer Contract for Observability

### ISSUE THREAD

**Issue by dgerd** [knative/docs#902]
Knative Serving currently has a runtime contract ( https://github.com/knative/serving/blob/master/docs/runtime-contract.md ) to outline the experience a developer can expect from the runtime. An similar observability contract was drafted in https://github.com/knative/serving/pull/727, however, it was abandoned before merged. This issue is to track creating a document to define the developer experience for observability such as the metrics to expect, the hooks that are available, and any requirements of the developer in using the features.

Opening this issue in the docs repo as mentioned at the end of the related PR.

## Context
Link to associated PRs or issues from other repos here.

1. https://github.com/knative/serving/pull/727

**Comment by samodell** [comment]
@dgerd  Can you take a look and let us know if this is still relevant?

**Comment by dgerd** [comment]
A developer contract for observability still seems useful. I do not have an owner for this though. 

/cc @mdemirhan
