### ISSUE TITLE
Instructions for Google Cloud Source Repositories

### ISSUE THREAD

**Issue by jdwrink** [knative/docs#932]
## What is changing? (Please include as many details as possible.)
Add instructions for building from Google Cloud Source Repositories
## How will this impact our users?
This will provide another option for building from source beyond github and gitlab.
## When will the change take effect (to the best of your knowledge)?
N/A
## Context
N/A

## Additional info

I was asked by @mattmoor in #build-crd to contribute a code snippet for getting Build to work with CSR. Add this snippet in a build where you would put the github instructions:

source:
    custom:
      image: gcr.io/cloud-builders/gcloud:latest
      args: ["source", "repos", "clone", <YOUR REPO HERE>]

The user will need to set up an IAM account for their service account, with the role of "roles/source.reader". If the user is also pushing to Google Container Registry, then they should also give the account the role of "roles/storage.admin". This way the same service account secret can be used for both functions.

**Comment by carieshmarie** [comment]
Has this code snippet been added? If so, can you link it here so we have more context?

Feel free to open a PR with a draft of the instructions. :)

**Comment by RichieEscarez** [comment]
Build to be deprecated
