### ISSUE TITLE
Blue Green Deployment example incomplete doc

### ISSUE THREAD

**Issue by moficodes** [knative/docs#933]
## What is changing? (Please include as many details as possible.)
In the blue-green-deployment.md file the before you begin step mentions an optional step for a custom domain setup. But throughout the rest of the documentation assumes that a custom domain was set.
## How will this impact our users?
If someone does not setup a custom domain the route will look like
`blue-green-demo.default.example.com` (Atleast did look like that for me in IKS)
And that url can not be reached by our browser. 

We can still access it via steps shown in 
https://github.com/knative/docs/blob/master/install/getting-started-knative-app.md#interacting-with-your-app 

I think we should add that to this documentation as well or at least mention it. Otherwise making it optional will not make much sense.

## When will the change take effect (to the best of your knowledge)?
This does not look like it will be too big of a change.

**Comment by carieshmarie** [comment]
@moficodes - would you be up for making this change? If so, can I assign it to you? (Totally ok if you're not!)

**Comment by moficodes** [comment]
I will be glad if i can help.
I can get this in by later tonight. Or early tomorrow morning.

**Comment by moficodes** [comment]
I actually reread the doc. Looks like there is a comment mentioning this. Somehow missed it when I looked at it.
