### ISSUE TITLE
Knative Pluggability presentation access denied

### ISSUE THREAD

**Issue by nfishe** [knative/docs#957]
## Expected Behavior
To be able to view the Pluggability presentation

## Actual Behavior
Need permission to view Slides

## Steps to Reproduce the Problem
1. [https://docs.google.com/presentation/d/10KWynvAJYuOEWy69VBa6bHJVCqIsz1TNdEKosNvcpPY/edit](https://docs.google.com/presentation/u/0/d/10KWynvAJYuOEWy69VBa6bHJVCqIsz1TNdEKosNvcpPY/edit)

## Additional Info
**Additional context**

https://www.knative.dev/docs/reference/serving-api/

**Install information:**
 - Platform (GKE, IKS, AKS, etc.):
 - Knative Version:

**Comment by samodell** [comment]
Hi @nfishe , access to view this document is granted when you become a member of the knative-users Google Group: https://groups.google.com/forum/#!forum/knative-users
