### ISSUE TITLE
Proposal: Create labels for each Knative repo

### ISSUE THREAD

**Issue by rgregg** [knative/docs#969]
Today it's hard to find issues that are related to particular Knative projects. e.g. eventing vs. serving vs. build.

Based on a conversation in the TOC meeting today, I'm capturing a proposal to add new labels for each of the projects/repos to help enable potential doc writers/editors to find issues they're able to action on.

I'm adding this issue to track the ask, and make sure I've captured the proposal correctly and allow for public comment.

Proposed new labels:
- project/serving
- project/eventing
- project/eventing-sources
- project/build
- project/build-templates

I believe this was raised by @csantanapr in the TOC meeting.

**Comment by csantanapr** [comment]
Yes !

**Comment by samodell** [comment]
Done! See https://github.com/knative/docs/labels
